### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mkayen** [numixproject/numix-icon-theme-circle#100]
"sudo apt install numix-icon-theme-circle" Results in the following...

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 numix-icon-theme-circle : Depends: numix-icon-theme but it is not installable
E: Unable to correct problems, you have held broken packages.

I then try "sudo apt install numix-icon-theme" and get the following:

Package numix-icon-theme is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'numix-icon-theme' has no installation candidate

**Comment by jlu5** [comment]
What OS version are you using?

**Comment by palob** [comment]
Did you install the PPA?

**Comment by mkayen** [comment]
Yeah! I did, and updated. I'll try to update again and get back to you.

**Comment by Foggalong** [comment]
Closing pending further updates
