### ISSUE TITLE
Icon for Foobnix

### ISSUE THREAD

**Issue by leonardomilano** [numixproject/numix-icon-theme-circle#1003]
A numix-circle icon for Foobnix missing. 
![2014-07-23 13 48 56](https://cloud.githubusercontent.com/assets/8244743/3672124/f4a80ff2-1259-11e4-9acf-a2b1cb23c9a2.png)

**Comment by sojusnik** [comment]
+1!

**Comment by sojusnik** [comment]
icon=foobnix

found under:
/usr/share/pixmaps/foobnix.png
/usr/share/foobnix/images/foobnix.png

**Comment by palob** [comment]
Fixed.
