### ISSUE TITLE
Image Viewer icon (eog.svg) - drop shadow is wrong

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#1006]
Hi, the Image Viewer icon (eog.svg) looks somewhat blurred. I realised this is because the "inner" drop shadow appears to be wrong. The shadow colour is a very light, almost transparent colour (cf. screenshots).

On another note, the "inner" drop shadow is vertical and thus out of line with the overall diagonal "outer" drop shadow icon design of Numix-Circle. I will open a new, more general, issue for this aspect.

![eog1](https://cloud.githubusercontent.com/assets/7164227/3686352/1a8d20c8-1317-11e4-84a0-6eec32a51d21.png)

![eog2](https://cloud.githubusercontent.com/assets/7164227/3686357/28d9e62a-1317-11e4-9cff-ba9698a46742.png)

**Comment by palob** [comment]
Fixed meanwhile.

**Comment by dirtydancing** [comment]
@palob Thanks!
