### ISSUE TITLE
VLC systray icon

### ISSUE THREAD

**Issue by tumas04** [numixproject/numix-icon-theme-circle#1008]
With the newest github build, the VLC systray icon looks like this:
![bildschirmfoto](https://cloud.githubusercontent.com/assets/7829002/3708439/618c755a-1443-11e4-9113-400007bb1f54.png)

I do not have a screen, but it used to be just a greyish traffic cone. It did fit perfectly to the other greyish gnome icons on the top right.

I guess this new "look" is a bug, isn't it?

Thanks a lot

**Comment by Foggalong** [comment]
This should be fixed now
