### ISSUE TITLE
Icon for HardInfo

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#1010]
Hi, a Numix-Circle icon is missing for HardInfo - System Profiler and Benchmark.

Icon line: Icon=/usr/share/hardinfo/pixmaps/logo.png (hardcoded)

Original icon:
![hardinfo_original](https://cloud.githubusercontent.com/assets/7164227/3711787/e057ff2e-14ea-11e4-802b-8d4c388c69bd.png)

For clarification: there is an icon named "hardinfo.svg" in Numix-Circle, but this is apparently for I-Nex, cf. these former issues:

https://github.com/numixproject/numix-icon-theme-circle/issues/954
https://github.com/numixproject/numix-icon-theme-circle/issues/429

![hardinfo_circle](https://cloud.githubusercontent.com/assets/7164227/3711796/c8c4904c-14eb-11e4-8f31-ee685808e024.png)

So in addition, I would suggest to change the name of the current "hardinfo.svg" to "i-nex.svg". I am using both applications, so some kind of distinction would be useful.

**Comment by palob** [comment]
Found the I-Nex icon is hardcoded to the following path:
i-nex.desktop
Icon=/usr/share/pixmaps/i-nex-128.png
![i-nex-128](https://cloud.githubusercontent.com/assets/7050624/6426796/ab7d3572-bf6b-11e4-93c1-774edb6e6a33.png)
