### ISSUE TITLE
Icon for retroarch

### ISSUE THREAD

**Issue by JonnyPaulLarkin** [numixproject/numix-icon-theme-circle#1028]
RetroArch is an interface for Libretro that allows for emulation of classic game platforms using different emulator cores.
http://www.libretro.com/

Icon=/usr/share/pixmaps/retroarch.svg

Original icon:
![screenshot from 2014-07-31 11 55 52](https://cloud.githubusercontent.com/assets/5456548/3768187/a2cabb86-18d4-11e4-8177-0e0550c0faa8.png)

**Comment by hlechner** [comment]
I've taken a look into the developer's source code file (RetroArch-1.0.0.3-beta.tar.gz) and here is the original .desktop file:
```
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=RetroArch
Type=Application
GenericName=RetroArch
Comment=RetroArch Multi-Engine Platform
Icon=/usr/share/pixmaps/retroarch.svg
Exec=retroarch
Terminal=false
StartupNotify=false
Categories=Game
```
