### ISSUE TITLE
Update Version in Fedora Repos

### ISSUE THREAD

**Issue by OctoPenguin** [numixproject/numix-icon-theme-circle#103]
According to information from the dnfdragora utility, your Fedora package is at version 0.1.0. Since the current version of this repository is 1.8.0 (or thereabouts), I think an update is in order. 

OctoPenguin

**Comment by Foggalong** [comment]
The versioning across the two don't match; some packagers dislike that we use `YY.MM.DD` versioning so replace it with their own system. Nothing we can do about that, sorry!
