### ISSUE TITLE
Icon for diffpdf

### ISSUE THREAD

**Issue by MirkoCe** [numixproject/numix-icon-theme-circle#1030]
Hello,

I would like an icon for diffpdf

Icon name: diffpdf
Horrible original icon attached
![schermata da 2014-08-03 12 18 19](https://cloud.githubusercontent.com/assets/7479982/3790198/25b88106-1aef-11e4-803c-33bb66e613fe.png)

It is not a pdf reader :D

**Comment by hlechner** [comment]
Just to complement the request.

There is no .desktop file inside the developer's source code package.
Here the .desktop created by [ubuntu package](http://packages.ubuntu.com/search?keywords=diffpdf&searchon=names&suite=trusty&section=all):
```
[Desktop Entry]
Version=1.0
Name=DiffPDF
Comment=Compare two PDF files
Exec=diffpdf
Icon=diffpdf
Terminal=false
Type=Application
Categories=Utility;Qt;
```

However from [AUR side](https://aur.archlinux.org/packages/diffpdf/) it's hardcoded:
```
Icon=/usr/share/pixmaps/diffpdf.png
```

It should be reported to the AUR package's maintainer
