### ISSUE TITLE
Icon for Sunflower

### ISSUE THREAD

**Issue by brunces** [numixproject/numix-icon-theme-circle#1037]
Hey, guys.

Please, create an icon for the following application:

App: Sunflower
Icon=sunflower

![sunflower](https://cloud.githubusercontent.com/assets/7181488/3800489/0c980178-1bf9-11e4-836b-85173328b97f.png)
Thanks for your attention.

brunces

**Comment by hlechner** [comment]
Just adding some useful information to help the developers to create the icon.

**App Description**: Small, customizable twin-panel file manager
**App Website**: http://sunflower-fm.org/
**App Screenshot**:
![image](https://cloud.githubusercontent.com/assets/11244067/6623433/c5c85ad8-c8c1-11e4-849b-33dc86fb691d.png)
**App full desktop file**:
```
[Desktop Entry]
Type=Application
Icon=sunflower
Name=Sunflower
Comment=Browse the file system and manage the files
Categories=FileTools;FileManager;Utility;Core;GTK;
Exec=sunflower %U
StartupNotify=true
Terminal=false
MimeType=inode/directory;
```
