### ISSUE TITLE
Icon for SoftPerfect WiFi Guard

### ISSUE THREAD

**Issue by brunces** [numixproject/numix-icon-theme-circle#1038]
Hey, guys.

Please, create an icon for the following application:

App: SoftPerfect WiFi Guard
Icon=wifiguard.png

![guard](https://cloud.githubusercontent.com/assets/7181488/3800517/6a639c4a-1bf9-11e4-8074-fd075fa45dac.png)

Thanks for your attention.

brunces

**Comment by hlechner** [comment]
Adding some useful information for this app:

**App Description**: an essential tool for everyone running a small WiFi network and striving to keep it secure
**App Website**: https://www.softperfect.com/products/wifiguard/
**App Screenshot**:
![image](https://cloud.githubusercontent.com/assets/11244067/6623688/4084560e-c8c3-11e4-8221-795813292db1.png)
**App original desktop file**:
```
[Desktop Entry]
Encoding=UTF-8
Name=SoftPerfect WiFi Guard
Comment=Scans the network for new connected devices possible belonging to an intruder.
Exec=wifiguard
Terminal=false
Type=Application
Icon=wifiguard.png
Categories=Application;Network
```

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/7098644/d68f9e1c-dfb9-11e4-8fc7-617bfa279a0b.png)
Alt:
![image](https://cloud.githubusercontent.com/assets/11244067/7098706/f64a4274-dfba-11e4-8bd7-649b1e65c760.png)

**Comment by Foggalong** [comment]
The first is a nice idea! :D

**Comment by hlechner** [comment]
Just to remember, that it's a hardcoded icon due to **.png** in **Icon=** line

**Comment by brunces** [comment]
Hey, guys.

I have a doubt... This issue was closed on April 18, but until now I haven't found the icon you made (which, by the way, is very cool). Has it been added to the package yet? I've been using the Duolingo icon (which is not an owl, but at least it's a green bird) instead. lol

Thanks for you time. Your theme rocks! :)

**Comment by Foggalong** [comment]
[The file is there](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/wifiguard.svg) :)

**Comment by brunces** [comment]
Cool. Thanks a lot, Foggalong. :)
