### ISSUE TITLE
Request: Icon for Visual Studio Code

### ISSUE THREAD

**Issue by beruic** [numixproject/numix-icon-theme-circle#104]
Visual Studio Code gets the same icon as Gedit on my desktop, which, at times, is a bit a confusing.
A new icon would therefore be welcomed warmly.

**Comment by palob** [comment]
Currently our stance is not to fix this. See https://github.com/numixproject/numix-core/issues/2964 for the reasoning. In order to get the icon you can edit the launcher as laid out here #98 or use VSCodium or any other FLOSS vscode build.

**Comment by beruic** [comment]
Ah... I see... Bad Microsoft!
