### ISSUE TITLE
Icons for Calligra Suite [$31]

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1040]
Calligra Suite, the third free/open source Office Suite besides LibreOffice and Apache OpenOffice.
Part of the KDE Project.
https://www.calligra.org/

Component Icons:

**Calligra Words** (word processing)
Icon=calligrawords

![calligrawords](https://cloud.githubusercontent.com/assets/7050624/3804668/8f8f8ed6-1c29-11e4-9ac8-96c31c22537b.png)

**Calligra Sheets** (spreadsheets/calculation)
Icon=calligrasheets

![calligrasheets](https://cloud.githubusercontent.com/assets/7050624/3804691/e23ed164-1c29-11e4-9b99-a352eeb6844b.png)

**Calligra Stage** (presentations)
Icon=calligrastage

![calligrastage](https://cloud.githubusercontent.com/assets/7050624/3804708/16e8db08-1c2a-11e4-8cf9-de63ce64a1e8.png)

**Calligra Plan** (project management)
Icon=calligraplan

![calligraplan](https://cloud.githubusercontent.com/assets/7050624/3804735/88a6424e-1c2a-11e4-825a-4711ce3ba942.png)

**Calligra Kexi** (database creation)
Icon=calligrakexi

![calligrakexi](https://cloud.githubusercontent.com/assets/7050624/3804742/c07ce646-1c2a-11e4-999b-7dbaae37f163.png)

**Calligra Karbon** (drawing / vector graphics)
Icon=calligrakarbon

![calligrakarbon](https://cloud.githubusercontent.com/assets/7050624/3804771/fd41931a-1c2a-11e4-8116-94c64a93fc28.png)

**Calligra Flow** (flowcharts)
Icon=calligraflow

![calligraflow](https://cloud.githubusercontent.com/assets/7050624/3804785/2abaa3ae-1c2b-11e4-8068-3a4ebaa788a4.png)

**Calligra Braindump** (mindmap, sketches)
Icon=braindump

![braindump](https://cloud.githubusercontent.com/assets/7050624/3804818/9acba7d8-1c2b-11e4-9190-01d0734b7629.png)

**Calligra Author** (e-book authoring)
Icon=calligraauthor

![calligraauthor](https://cloud.githubusercontent.com/assets/7050624/3804852/51519846-1c2c-11e4-8235-fb605eb608cf.png)

A numix-circle icon for Krita (digital art) already exists.

**Comment by ChuckDaniels87** [comment]
@me4oslav, are you still interested in these icons? I got some ideas that could work.

**Comment by Foggalong** [comment]
I'm gonna save this one for Numix with the intent of forwarding the bounty to 6/7 other issues :)

**Comment by ChuckDaniels87** [comment]
Nice :+1:

**Comment by ChuckDaniels87** [comment]
My idea is the big C of Calligra and every icon inside, this is pretty simple but could keep the set of icons coherent.

Sketch:
![icons](https://cloud.githubusercontent.com/assets/8478202/6653280/582cc984-ca8b-11e4-9cd6-6d20fe7d8de6.png)

**Comment by Foggalong** [comment]
I'm not a massive fan of the C idea, but that note+bulb symbol is simply gorgeous. Asthetics aside, a big worry with the C is that it wouldn't scale very well to smaller sizes and would mean that the actual symbolmis limited to a minute size.

I'll tell you what though: rather than taking this for Numix as said above, if you'll throw in fixes for 2 outstanding bountyless issues of your choice (in separate pull requests but linked to here) I'll let you take this one. You've convinced me you have the ideas to make this work :)

**Comment by ChuckDaniels87** [comment]
Haha, deal. :wink:

About the big C, I'll try to do my best to make it scale well.
