### ISSUE TITLE
Pushbullet indicator icon

### ISSUE THREAD

**Issue by pamarsan** [numixproject/numix-icon-theme-circle#1049]
pushbullet-indicator is an app which sends and receives files, links etc. from and to any device which has pushbullet installed, such as android. I noticed you have a nice pushbullet icon for android which would suit pretty well for this app on the desktop :)

Icon = /opt/extras.ubuntu.com/pushbullet-indicator/share/pushbullet-indicator/icons/pushbullet-indicator.svg

![pushbullet](https://cloud.githubusercontent.com/assets/7572891/3813739/bcb0b2c8-1cb5-11e4-897b-b5fd651c5d21.png)

Does that icon line in /opt/ mean that you can't link the icon to the app? In that case could you release a pushbullet.svg and each user change the icon line of the app to Icon=pushbullet?

**Comment by Foggalong** [comment]
Moved to base :)

**Comment by bil-elmoussaoui** [comment]
@Foggalong i dont konw why this is moved to base? the indicator and the application icon are hardcoded. Maybe only adding the application icon and report that to the devs of Pushbullet indicator?
