### ISSUE TITLE
Icon for PokerTH

### ISSUE THREAD

**Issue by pamarsan** [numixproject/numix-icon-theme-circle#1056]
PokerTH is the classic Texas Hold'em Poker game:

![pokerth](https://cloud.githubusercontent.com/assets/7572891/3814466/6dc56b12-1cbb-11e4-96d2-fd9ceb157f9b.png)
![poker2](https://cloud.githubusercontent.com/assets/7572891/3814478/8c4e0058-1cbb-11e4-873e-d4bf65a026c6.png)

Icon=pokerth

**Comment by bil-elmoussaoui** [comment]
#1468
