### ISSUE TITLE
Icon For Fillydelphia Radio Desktop Player (Google Chrome Application)

### ISSUE THREAD

**Issue by mrtechtve** [numixproject/numix-icon-theme-circle#1061]
Requesting a Numix Circle Icon for The Fillydelphia Radio Desktop Player.
https://chrome.google.com/webstore/detail/fillydelphia-radio-deskto/fpljbkcbklinaahkojjlapfkbcoopgfg/details

**Comment by Foggalong** [comment]
The links dead, and I can't fine info on this anywhere :/
