### ISSUE TITLE
Icon for File Manager - new folder shape

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#1080]
Hi, quick question: are you planning to align the shape of the folder in the Numix-Circle icon for File Manager to the new folder icons in Numix base?

iirc, the design of the File Manager icon was changed with the new design for the folder icons in mind. Now that the folder icons have been redesigned differently, the shapes do not match anymore, like they did in the legacy versions.

I would suggest to align the shapes (and the colour in some way, was not an exact match before either). That would be consistent, and besides, personally, I really like the new folder icons :-) Screenshots:

legacy:
![file-manager_1](https://cloud.githubusercontent.com/assets/7164227/3902997/46b3fe06-22c6-11e4-86e4-f6dfd50d46cd.png)

current:
![file-manager_2](https://cloud.githubusercontent.com/assets/7164227/3903004/50f9baea-22c6-11e4-92bf-9e455982618c.png)

**Comment by palob** [comment]
Is fixed.

**Comment by dirtydancing** [comment]
@palob Thanks!
