### ISSUE TITLE
Slack Icon Request

### ISSUE THREAD

**Issue by SimpleAnecdote** [numixproject/numix-icon-theme-circle#1081]
Not strictly a Chrome App but more of a "Create application shortcut" type deal webapp. Still, the icon shows.

Website: https://slack.com/

They have a thing in the Chrome app store as well although it is not one by any means: https://chrome.google.com/webstore/detail/slack/jeogkiiogjbmhklcnbgkdcjoioegiknm

**Comment by te-gpm** [comment]
Has anyone managed to find a fitting, round icon for slack? Using the chrome app as well and it's basically the only icon left that is square :(
