### ISSUE TITLE
Icon request for Easystroke

### ISSUE THREAD

**Issue by allejok96** [numixproject/numix-icon-theme-circle#1082]
Easystroke is a mouse geusture recognition program

Icon=easystroke
![easystroke](https://cloud.githubusercontent.com/assets/7693838/3918988/6d233a30-23a1-11e4-92e6-36d3c43b3134.png)

The original svg icon can be found in this tar.gz (just 119kB)
http://sourceforge.net/projects/easystroke/files/easystroke/0.6.0/easystroke-0.6.0.tar.gz/download

**Comment by Foggalong** [comment]
Tried getting the gradient in too but it was a bit too fiddly to get the colours match up.
