### ISSUE TITLE
Icon request for Grafx2

### ISSUE THREAD

**Issue by Eiyeron** [numixproject/numix-icon-theme-circle#1085]
A  numix-square icon for Grafx2 is missing.
line=grafx2
image origin : /usr/share/icons/grafx2.svg
The original icon is attached : ![Grafx2 icon](http://images.software.com/mac.com.googlecode.grafx2/icon-128.png)
The SVG version, used with the program is attached [here](https://grafx2.googlecode.com/svn/branches/release/share/icons/grafx2.svg).

**Comment by hlechner** [comment]
@Foggalong I think he just tried to mention the path to icon on "image origin" reference. I've further investigate it from [ubuntu package](http://packages.ubuntu.com/trusty/grafx2) and [arch package](https://www.archlinux.org/packages/community/x86_64/grafx2/) and both are not hardcoded:

Ubuntu desktop file:
```
[Desktop Entry]
Name=GrafX2
Comment=Deluxe Paint Clone
Exec=grafx2
Terminal=false
Type=Application
Icon=grafx2
Categories=Application;Graphics;
```

Archlinux desktop file:
```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=GrafX2
GenericName=Drawing program
Comment=Pixelart-oriented painting program
Exec=grafx2 %U
Icon=grafx2
Terminal=false
StartupNotify=false
Categories=Graphics;2DGraphics;RasterGraphics;
MimeType=image/bmp;image/gif;image/png;image/x-tga;image/tiff;
```

And also into source code file as you can see on the following link:
http://pulkomandy.tk/projects/GrafX2/browser/trunk/misc/unix/grafx2.desktop
