### ISSUE TITLE
Icon for XCOM 2 (steam)

### ISSUE THREAD

**Issue by KRACK-BIT** [numixproject/numix-icon-theme-circle#109]
Game: XCOM 2
AppID: 268500
Icon: ![image](https://user-images.githubusercontent.com/46194176/56198182-51e36880-6032-11e9-9d41-9cbecdac2367.png)

Notes: the predecessor, XCOM: Enemy Unknown has a numix icon, so partially reutilizing that could be beneficial

**Comment by Foggalong** [comment]
This is the wrong repo for icon requests, please see the readme for more information.

**Comment by KRACK-BIT** [comment]
Sorry
