### ISSUE TITLE
Panel Indicator for Screencloud

### ISSUE THREAD

**Issue by bulu009** [numixproject/numix-icon-theme-circle#11]
There is no dedicated monochrome panel indicator for screencloud as there is one for Shutter. The app svg is shown as a panel indicator.

#!/usr/bin/env xdg-open

[Desktop Entry]
Name=ScreenCloud
GenericName=Screenshot sharing tool
Comment=Capture and share screenshots easily
Icon=screencloud
Type=Application
Exec=screencloud
Hidden=false
NoDisplay=false
Categories=Internet;RemoteAccess;Graphics;2DGraphics;TrayIcon;
Terminal=false

Panel Shows - 

![image](https://cloud.githubusercontent.com/assets/20025882/18596523/1eb9f868-7c67-11e6-8935-8d5d357383b1.png)

**Comment by Foggalong** [comment]
This is a base theme issue! Please report this in numix-icon-theme :)
