### ISSUE TITLE
Display Missing Icon (XFCE)

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [numixproject/numix-icon-theme-circle#111]
I'm using Xubuntu 19.04. Within the System Settings application the item for "Display" isn't showing the Numix Circle icon. 

![Screenshot_2019-05-18_02-14-05](https://user-images.githubusercontent.com/7698035/57962741-dddaff80-7912-11e9-9ae0-375cc49139b0.png)

**Comment by KUPOinyourWINDOW** [comment]
I just noticed another missing icon in the screenshot above. so I've gone into settings to check for all missing icons and there's three.

- Display (Screenshot 1, above)
- Removable Drivers and Media (Screenshot 1, above)
- MIME Type Editor (Screenshot 2, below)
![Screenshot_2019-05-18_14-44-09](https://user-images.githubusercontent.com/7698035/57970637-a2c0e680-797b-11e9-8f79-e6b688b2623c.png)

**Comment by KUPOinyourWINDOW** [comment]
I've done a further check in Numix Square and the issue is the exact same there, exactly the same missing icons. Hopefully I've provided all the info needed!

**Comment by Foggalong** [comment]
Those icons aren't missing, 
it's that those parts of the settings have been written to use an icon name which is used elsewhere (e.g. the drives setting uses the hard drive locations icon, rather than a "settings-harddrive" icon. This unfortunately isn't something we'd be able to solve on our end but if it's ever fixed upstream we'd be more than happy to cover them :)

**Comment by lujanfernaud** [comment]
In Xubuntu the icons in the Settings window can be replaced by using MenuLibre (Menu Editor).

![ksnip_20191221-074901](https://user-images.githubusercontent.com/18352529/71305062-67314380-23c6-11ea-81be-5d645f8b045c.png)

![ksnip_20191221-074723](https://user-images.githubusercontent.com/18352529/71305076-6ef0e800-23c6-11ea-8bdd-bd6a044e6b79.png)

![ksnip_20191221-074844](https://user-images.githubusercontent.com/18352529/71305082-731d0580-23c6-11ea-828a-636ce1a66a1d.png)

This only replaces the icons in the Settings window, but for me it's good enough.

These are the replacement icons that I used:

- Removable Drives and Media: multibootusb
- Color Profiles (new in XFCE 4.14): preferences-desktop-display-color
- Display: display
- MIME Type Editor: mediainfo
