### ISSUE TITLE
Icon for Tixati

### ISSUE THREAD

**Issue by andriykohut** [numixproject/numix-icon-theme-circle#1112]
Freeware bittorrent client with really ugly icon.
http://www.tixati.com/
`Icon=tixati`

![tixati](https://cloud.githubusercontent.com/assets/3106616/4081666/cc860df6-2ee9-11e4-8793-a03806515bd7.png)

Thanks for your terrific job!

**Comment by fa7ad** [comment]
I double this, i bet numix devs can come up with a much better icon than tixati's original.
It might not have to be related to the original at all :smile:
