### ISSUE TITLE
Icon for Remarkable

### ISSUE THREAD

**Issue by Neftas** [numixproject/numix-icon-theme-circle#1119]
There is currently no icon for Remarkable (which is a new Markdown editor).

The icon line says `/usr/share/remarkable/media/remarkable.svg` and the original icon is attached.

![screenshot from 2014-09-01 19 57 25](https://cloud.githubusercontent.com/assets/8035319/4111219/85106fb4-3201-11e4-879b-60caac9205f0.png)

I don't know if you guys do icons that are not available in the Ubuntu Software Center, and since this icon is already round it is definitely not a priority :)

**Comment by ChuckDaniels87** [comment]
Anyone could report hardcoded icon upstream?
