### ISSUE TITLE
Dead link for video tutorial

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#112]
In README.md the video tutorial link is a dead link that points to Google+, which does not exist any more.

**Comment by Foggalong** [comment]
@me4oslav I don't suppose you have a local copy of that tutorial saved anywhere? If not no worries and I'll rerecord the video :+1:

**Comment by TheGhostHybrid** [comment]
@Foggalong Greetings, fellow enby! Just chiming in to second the request for a new tutorial to replace the dead link.

**Comment by gregorydk** [comment]
Why was this closed? The dead video link to Google+ is still not removed.

**Comment by Foggalong** [comment]
@gregorydk Thanks for flagging, I did the copy-past fine for everything except the icon requests paragraph where it was really needed :facepalm:

**Comment by Foggalong** [comment]
Fixed now in [Circle](https://github.com/numixproject/numix-icon-theme-circle/commit/6969a1c6882a807238d805b04669c5d26805499a) and [Square](https://github.com/numixproject/numix-icon-theme-square/commit/000796658384593b0b344689ecbd630ef800b8b3), thanks @gregorydk!
