### ISSUE TITLE
icon for wifi guard by softperfect

### ISSUE THREAD

**Issue by cargie** [numixproject/numix-icon-theme-circle#1124]
Icon name is wifiguard
here's the reference url for the application http://www.softperfect.com/products/wifiguard/
the reference icon 
![wifiguard_logo](https://cloud.githubusercontent.com/assets/8433416/4187115/d29a805c-3766-11e4-8730-f40621cc79a6.gif)

thank you and i really liked your icons and themes. long live numix

**Comment by bil-elmoussaoui** [comment]
This was already reported in #1038; to close ;)
