### ISSUE TITLE
Icon for MEGASync

### ISSUE THREAD

**Issue by jirble2** [numixproject/numix-icon-theme-circle#1131]
MEGA Client for Linux recently released, and the icon is already pretty close to Numix style, merely lacking a drop shadow. Not the main issue though.
Icon=mega

![mega](https://cloud.githubusercontent.com/assets/8725013/4220256/44c56634-3900-11e4-8286-9c6f43fe6538.png)

The indicator icons for mega are coloured and appear blurred. Would be nice to see some monochrome icons for it.
![megai](https://cloud.githubusercontent.com/assets/8725013/4220269/4e7c903a-3900-11e4-9c46-a675dc54c9cb.png)

**Comment by alien2003** [comment]
MEGA icon is not hardcoded anymore
