### ISSUE TITLE
No Weather Icons: Weather Report Plasmoid KDE Plasma (Tumbleweed)

### ISSUE THREAD

**Issue by fleamour** [numixproject/numix-icon-theme-circle#114]
Hi

Lovely go to icons that fully rock the flat theme, but my Weather Report plasmoid no worky. Not sure if this a right pain or no to add?!? However Server Status plasmoid is better than default, as are the whole ambience...

Let me know if I can do anything.

Thx fo' yo' effortz!!!

**Comment by palob** [comment]
Could you please provide a screenshot with a theme that works and Numix so we can find out if it is about app icons (https://github.com/numixproject/numix-core) or an issue for our base theme (https://github.com/numixproject/numix-icon-theme)?

Next thing would be to get the icon names.

**Comment by fleamour** [comment]
![Screenshot_20190901_201932](https://user-images.githubusercontent.com/2966405/64081220-063a0e80-ccf6-11e9-877e-b3c585a30f31.png)
![Screenshot_20190901_201839](https://user-images.githubusercontent.com/2966405/64081223-089c6880-ccf6-11e9-9d25-3aa8bbce9baf.png)

**Comment by fleamour** [comment]
These are the icon names under Breeze;

![Screenshot_20190902_192900](https://user-images.githubusercontent.com/2966405/64130111-1ca89e80-cdb8-11e9-9656-6606c52d1666.png)

**Comment by palob** [comment]
Thank you! Could you please repost this in the base icon theme repo https://github.com/numixproject/numix-icon-theme ?

**Comment by fleamour** [comment]
Ah, soooooo...

I'm meana use base theme in conjunction with circle theme? Gotcha.

**Comment by Foggalong** [comment]
@fleamour All you have to do is install both the base theme and the circle theme, and then select the circle theme as you normally would from the theme chooser. Behind the scenes the base theme is then automatically brought into the circle theme without you having to do anything
