### ISSUE TITLE
numix circle light status icons seems blur

### ISSUE THREAD

**Issue by raknerak** [numixproject/numix-icon-theme-circle#1140]
After the last update numix circle light theme status icons is not sharp as seen:

![blur](https://cloud.githubusercontent.com/assets/7880734/4233054/998a9c66-39a5-11e4-8cc9-f65a0ba4025f.png)

I am also adding what can be possible which is alreadt in ubuntu-mono-light:

![sharp](https://cloud.githubusercontent.com/assets/7880734/4233065/d1557d78-39a5-11e4-9fcf-390c99c5f4cc.png)

**Comment by Foggalong** [comment]
We've removed the shadow from status icons so this should now be fixed :)
