### ISSUE TITLE
Icon for Waking mars (Steam) 

### ISSUE THREAD

**Issue by sergioad** [numixproject/numix-icon-theme-circle#1148]
A numix circle icon is needed for waking mars

AppID 227200
URL http://store.steampowered.com/app/227200/
icon steam_icon_227200

I have attached it's icon for you

![wakingmars](https://cloud.githubusercontent.com/assets/5375145/4252058/61bbbeb2-3a92-11e4-9ba8-491c68131a74.png)

**Comment by hlechner** [comment]
Hey @sergioad, would you mind to add a **(Steam)** at the final of the tittle? It help us for search purposes. Thanks!

**Comment by sergioad** [comment]
Ok, I will add it
