### ISSUE TITLE
Better Audacity icon?

### ISSUE THREAD

**Issue by pamarsan** [numixproject/numix-icon-theme-circle#1158]
I think Audacity icon could go under a redesign to bring it closer to the original design; the current one is too generic and doesn't follow the colours and the lines. What do you think? I made a mockup to see how it would look more or less
![audacity_logo_with_name](https://cloud.githubusercontent.com/assets/7572891/4317566/9ebade84-3f14-11e4-8147-f1babc8ca508.png)
![captura de pantalla de 2014-09-18 11 12 14](https://cloud.githubusercontent.com/assets/7572891/4317567/a537bde0-3f14-11e4-8f5d-d5af7a6049ec.png)
![audacity circle](https://cloud.githubusercontent.com/assets/7572891/4317570/a87143b4-3f14-11e4-816f-56ef4d2e92f8.png)
As you can see, it can look beautiful with the original colours on white background. I just flattened the shapes and used more vivid colours.

**Comment by dirtydancing** [comment]
A first step could be to simply change the colours in the current design. I have come up with this:

Current icon:
![audacity_current](https://cloud.githubusercontent.com/assets/7164227/7440973/0f94de46-f0d3-11e4-8524-35e27f1805f7.png)

Proposed icon:
![audacity_proposed](https://cloud.githubusercontent.com/assets/7164227/7440974/167f3a26-f0d3-11e4-9e14-debe842e46a1.png)

This is already much more vibrant within the current design. To me, the red and the yellow colour are the most relevant ones for the Audacity icon. They also are more energetic than e.g. blue and yellow. And finally, currently blue appears to be more present in Numix-Circle than red, so a red icon would fit in.

Screenshot of this proposed icon next to the original one:
![audacity_original](https://cloud.githubusercontent.com/assets/7164227/7441035/663e3b50-f0d5-11e4-9d0e-95d4baf5af23.png)

What do you make of this?

**Comment by wa4557** [comment]
Maybe different colors for the headphone but keep the yellow for the soundwave?

**Comment by Foggalong** [comment]
The blue is much more part of the audacity brand so it'd be nice to have it in there.

**Comment by dirtydancing** [comment]
Yeah, valid points. I like the design of the current Numix icon (also scales just fine), so I tried to keep this as simple as possible. Mixing more colours within this design is very tricky, so yeah, I guess a complete makeover is in order right away then :)

**Comment by Foggalong** [comment]
Yeah, the current Numix design is pretty nice just colours need updating.

**Comment by dirtydancing** [comment]
One more idea with the current design that actually works surprisingly well, and it adds some blue :)

![audacity_proposed_2](https://cloud.githubusercontent.com/assets/7164227/7441870/52622e64-f0fa-11e4-9337-d6c6abd0655b.png)

**Comment by Foggalong** [comment]
Nice idea, but a bit too trippy :P

**Comment by dirtydancing** [comment]
Trippy and tricky :), I rest my case then with the pure colour change of the current design. Curious to see where this will go...

Oh, I also tried a blue variant, and adding a red colour to the arch, but neither really convinced me:

![audacity_proposed_x](https://cloud.githubusercontent.com/assets/7164227/7442040/981a09c0-f101-11e4-8f5f-5bd063ce5ccf.png)

![audacity_proposed_y](https://cloud.githubusercontent.com/assets/7164227/7442042/a740de06-f101-11e4-8b6e-290cea449002.png)

**Comment by wa4557** [comment]
Why not something like this?
![audacity](https://cloud.githubusercontent.com/assets/6475757/7442149/dc8885fc-f104-11e4-93d7-b44f3bd7f3e5.png)

**Comment by dirtydancing** [comment]
Still not convinced :) Some more vibrancy maybe? I think vibrant blue on vibrant red and vice versa is difficult to achieve. And will the yellow show in regular icon size, maybe some more contrast is needed?

**Comment by dirtydancing** [comment]
How about this one (below in size 48x48)?

![audacity](https://cloud.githubusercontent.com/assets/7164227/7522754/9467a09a-f4f7-11e4-980c-5f275323faff.png)

![audacity](https://cloud.githubusercontent.com/assets/7164227/7522606/a659a1c8-f4f6-11e4-9b4c-47c52eeebc66.png)

![audacity_48x48](https://cloud.githubusercontent.com/assets/7164227/7522609/aa087ae2-f4f6-11e4-8a8c-de2fc9cd8c91.png)

**Comment by pamarsan** [comment]
Wow. I really like that one.

**Comment by sergioad** [comment]
@dirtydancing it looks amazing, I liked it :smile:

**Comment by dirtydancing** [comment]
@pamarsan @sergioad Thanks, I am glad you liked it :)

While I do like this icon, I am not sure if it is conforming to the design guidelines, https://github.com/numixproject/numix-wiki/wiki/Guidelines.

1) Size: the design guidelines specify that 24, 26 or 28 sized symbols should be used, and 30 or 32 sized if they are circles. The icon above uses a symbol size of 32x30, which might be ok as it is "circle" shaped, but those sizes might apply to plain circles only (?).

2) Colours: maybe too bright?

Anyways, I took these aspects into consideration for this alternative: symbol size is down to 28x26, and the symbol colours are slightly toned down. I think I prefer this version, and it seems to be more consistent with the other icons:

![audacity2_1](https://cloud.githubusercontent.com/assets/7164227/7533716/32b87efa-f574-11e4-9410-2a611b74026f.png)

![audacity2_2](https://cloud.githubusercontent.com/assets/7164227/7533717/3627e9cc-f574-11e4-853b-a6aaa70bd223.png)

**Comment by Foggalong** [comment]
Yeah, the symbol did need to be a bit smaller so it fitted in the guidelines. It's growing on me so if you submit it as a pull request once I'm back st a PC I'll check it over :)

**Comment by dirtydancing** [comment]
Done :), cf. https://github.com/numixproject/numix-icon-theme-circle/pull/2083
