### ISSUE TITLE
No Icon Folder

### ISSUE THREAD

**Issue by mugi789** [numixproject/numix-icon-theme-circle#116]
![image](https://user-images.githubusercontent.com/32443765/67066613-841a8200-f19d-11e9-8fc5-c9e35f125f81.png)

#UBUNTU 18.04

**Comment by Foggalong** [comment]
We're going to need much more information than that. It looks like maybe you're missing the base theme which Circle inherits? You can get that [from here](https://github.com/numixproject/numix-icon-theme)
