### ISSUE TITLE
Google Chrome icon becomes white

### ISSUE THREAD

**Issue by OSjerick** [numixproject/numix-icon-theme-circle#1160]
I'm not sure if this is an issue, but the Google Chrome icon becomes white inside Gnome 3 Dash bar when multiple applications are running.
![captura de pantalla de 2014-09-18 14 53 57](https://cloud.githubusercontent.com/assets/8047984/4325932/4a544758-3f6a-11e4-9a35-89e001175e1b.png)

**Comment by Foggalong** [comment]
Fixed now we've moved status icons to base :)
