### ISSUE TITLE
Two Evolution icons in use at the same time

### ISSUE THREAD

**Issue by Ferruck** [numixproject/numix-icon-theme-circle#1171]
At the moment, two icons for Evolution are in use at the same time – the older (blue background) and the newer one with the lighter background. The latter is used in the dock on the left side and in the top panel, the older one everywhere else as you can see in the screenshots.

![bildschirmfoto von 2014-09-20 10 18 56](https://cloud.githubusercontent.com/assets/5089996/4344680/ecd7579c-409e-11e4-8ace-20c1b6a77011.png)

![bildschirmfoto vom 2014-09-20 10 14 11](https://cloud.githubusercontent.com/assets/5089996/4344681/08534058-409f-11e4-84cc-cd32dbafde41.png)

**Comment by Foggalong** [comment]
Not sure why it didn't occur to me, this is just the icon cache not updating properly in some places. I have the same problem with docky :) A restart should fix problems like this if anyone else has it
