### ISSUE TITLE
Numix Circle update for PPA

### ISSUE THREAD

**Issue by mshmm** [numixproject/numix-icon-theme-circle#118]
Could Numix Circle be updated on the PPA please (particularly for the LTS Bionic)? Numix Square was updated last month, and includes lots of fixes that the version of Circle (2.0.3+21~201806080916 uploaded on 8th June last year) does not.

**Comment by Foggalong** [comment]
@numixproject/packaging Any idea why this has happened? Both Circle and Square were tagged but only Square got pushed to PPA

**Comment by mshmm** [comment]
Both numix-icon-theme and numix-icon-theme-square have been updated on the PPA in the last 24 hours, but numix-icon-theme-circle is still at the version uploaded on 8th June 2018.

**Comment by Foggalong** [comment]
I'm not sure why that's not updated too :confused:

**Comment by khurshid-alam** [comment]
PPA build are failing...will look into it.

**Comment by khurshid-alam** [comment]
Sorry for late reply. But this was fixed sometime ago.

**Comment by palob** [comment]
Thank you, there is now #126 though.
