### ISSUE TITLE
disk icon? and remote cloud

### ISSUE THREAD

**Issue by ferrvittorio** [numixproject/numix-icon-theme-circle#119]
Hi,
what about those two icons regarding disk and a cloud drive, which seemingly are not covered by Numix-Circle.
Is there anithyng I can do manually, I do not know how to get the svg names

https://imgur.com/a/tbNRm67

Thanks

**Comment by palob** [comment]
Well those two icons are device icons, we can't do Circle/Square icons because they would pop up in places they should  not then.

Those disk launchers are a Ubuntu thing. Could you please look if there's a corresponding ``.desktop`` launcher files in ``/usr/share/applications`` or ``$HOME/.local/share/applications``?

**Comment by ferrvittorio** [comment]
Thanks
I could find the second drive icon as `file:///usr/share/icons/Numix/48/devices/drive-harddisk-usb.svg`

But not the cloud account (it is my google drive which gets mounted in file roller), do not where it is inheriting from (looks like a multi-disk category)

**Comment by palob** [comment]
What we need to find is the ``.desktop`` file which determine which icon is selected. You can edit those in order to pick up different icons.

**Comment by ferrvittorio** [comment]
Hi. 
I was unable to locate correct `.desktop` files so following this tutorial https://www.linuxuprising.com/2019/11/how-to-hide-mounted-drives-from-dock-on.html 
I hid mounted drives from Ubuntu Dock (Dash to Dock). 

And I am happy for now.

Leaving thread open for your comments.

PS I noticed that some icon themes have customization for those drive types, I am not sure I really understand your 
> Well those two icons are device icons, we can't do Circle/Square icons because they would pop up in places they should not then.

above comment.

Thanks

**Comment by palob** [comment]
The icons in question are o app icons. So if we established Circle/Square icons there you would have pop them up in spots like your file manager, control center... places they shouldn't show up.
