### ISSUE TITLE
Gnome 3.14 some icons overscalled (some giant icons)

### ISSUE THREAD

**Issue by sergioad** [numixproject/numix-icon-theme-circle#1190]
Hello I have recently updated my Antergos to Gnome 3.14 and I got a really bad surprice, some icons are overscalled, for example the Cinnamon control center's categories icons or the Noise's settings icon

![captura de pantalla de 2014-10-03 13 45 34](https://cloud.githubusercontent.com/assets/5375145/4510861/a2cf329c-4b2e-11e4-9a48-c00f6c5d6f3c.png)

Normally CInnamon control center looks like this

![captura de pantalla de 2014-10-02 09 54 09](https://cloud.githubusercontent.com/assets/5375145/4510869/be9311ec-4b2e-11e4-9494-770232cc4572.png)

**Comment by Foggalong** [comment]
@sergioad is this still a problem?

**Comment by sergioad** [comment]
No, fortunelly it is not happening anymore :smile:
