### ISSUE TITLE
Nautilus icon not found

### ISSUE THREAD

**Issue by gcerretani** [numixproject/numix-icon-theme-circle#12]
Nautilus icon is not found after the update to the version 3.21.92. Now the icon is searched as **org.gnome.Nautilus**, that does not exists.

A new link should be added, from **org.gnome.Nautilus.svg** to **nautilus.svg**

```
$ cat /usr/share/applications/org.gnome.Nautilus.desktop 
[...]
Icon=org.gnome.Nautilus
[...]
```

**Comment by Foggalong** [comment]
This isn't an issue with the Linux packaging so needs to go in the new [circle-core](https://github.com/numixproject/circle-core) repo which houses the design assets.
