### ISSUE TITLE
Icon for Mandelbulber

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#1202]
Hi, a Numix-Circle icon is missing for Mandelbulber, an application for generating 3D fractals.

Icon line: `Icon=/usr/share/mandelbulber/icons/mandelbulber.png` (hardcoded)

Name of the .desktop file: mandelbulber.desktop

Original icon:

![mandelbulber](https://cloud.githubusercontent.com/assets/7164227/4581664/bd6100f6-4fe1-11e4-8bed-7c0efa7b34c6.png)

**Comment by wa4557** [comment]
Too subtle?
![fractal](https://cloud.githubusercontent.com/assets/6475757/7215461/8aba0164-e5d9-11e4-856c-de32901d5b44.png)

**Comment by Foggalong** [comment]
No, that's brilliant! I was completely stumped for this but I didn't think about using a different type of fractal. Symbol needs to come down 1 or 2px though to counteract the triangle illusion :)

**Comment by dirtydancing** [comment]
Very sweet symbol indeed, well done! One thing I noticed in size 48x48: possibly a little higher contrast?

**Comment by palob** [comment]
And it scales very well :+1:

**Comment by dirtydancing** [comment]
Cool, thanks! I have been wondering about this one as well :)

**Comment by dirtydancing** [comment]
Quick visual feedback of the Mandelbulber icon in the Ubuntu 14.10 app overview, very nice variation :)

![mandelbulber](https://cloud.githubusercontent.com/assets/7164227/7216031/3552c640-e5f0-11e4-91d4-7df012555c99.png)
