### ISSUE TITLE
new icon for baidunetdisk

### ISSUE THREAD

**Issue by vangoah20** [numixproject/numix-icon-theme-circle#122]
thanks for your great job.
could you please add a baidunetdisk icon?
![baidunetdisk](https://user-images.githubusercontent.com/2648547/79854581-415f8e00-83fc-11ea-9df7-4a5fe235e51a.png)

**Comment by palob** [comment]
Hi, please refile you request here and add the icon name to your report (tutorial linked).
https://github.com/numixproject/numix-core
