### ISSUE TITLE
Icon Request: OpenSpades

### ISSUE THREAD

**Issue by sonal-keshav** [numixproject/numix-icon-theme-circle#1221]
Openspades is a game (https://github.com/yvt/openspades)
Got the following from the openspades desktop file:
Icon=openspades.png

![screenshot from 2014-10-17 00 58 00](https://cloud.githubusercontent.com/assets/2701579/4674651/639d4300-5599-11e4-9eb7-1762907af37c.png)

**Comment by SM83** [comment]
+1, would love to have an icon for this.
