### ISSUE TITLE
Icon for (Unity) Privacy Indicator

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#1225]
Hi, a Numix-Circle icon is missing for (Unity) Privacy Indicator.

Icon line: `Icon=indicator-privacy`

Original Icon:

![indicator-privacy](https://cloud.githubusercontent.com/assets/7164227/4708129/74a0847a-5894-11e4-9c9a-2f3f9b7509d7.png)

(Unity) Privacy Indicator in addition comes with a panel icon in two variations for dark and light panels.

Panel icon name: `indicator-privacy-panel`

Original panel icon in two variations for dark and light panels:

![indicator-privacy-panel](https://cloud.githubusercontent.com/assets/7164227/4708168/b93540bc-5894-11e4-80c4-f4ec5762dfc7.png)

![indicator-privady-panel_2](https://cloud.githubusercontent.com/assets/7164227/4708170/bedc0b9a-5894-11e4-9dd5-466441ed9429.png)

**Comment by Foggalong** [comment]
Report the indicator part to Base :)
