### ISSUE TITLE
Software updater mistaken for crash report

### ISSUE THREAD

**Issue by serkandurusoy** [numixproject/numix-icon-theme-circle#1227]
The software updater icon used to be fine until after a couple of releases ago and now it is mistaken for the crash report icon:

![image](https://cloud.githubusercontent.com/assets/4649948/4736809/0be2bbd0-59f0-11e4-8ce4-a23a71c5355e.png)

**Comment by Foggalong** [comment]
Closing this, you should be used to it now ;)
