### ISSUE TITLE
Icon Request: Gnome Extensions

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [numixproject/numix-icon-theme-circle#123]
It's the only app I have that is missing a Numix Circle icon. As it's now required by Gnome (If I remove it Gnome Tweaks disappears), could we get an icon for this please?

![Screenshot from 2020-05-03 06-26-25](https://user-images.githubusercontent.com/7698035/80899343-141db480-8d07-11ea-9d26-f3218a1b1190.png)

**Comment by palob** [comment]
A fix has already been merged but not released yet
