### ISSUE TITLE
Icon for SmartGitHg

### ISSUE THREAD

**Issue by ghivert** [numixproject/numix-icon-theme-circle#1239]
Hey guys !

Just missing an icon for SmartGitHg !
Name=SmartGit/Hg 6
Icon=syntevo-smartgithg-6.png
Original icon : ![77d012c4c585e42b45b4cf8be385de74_400x400](https://cloud.githubusercontent.com/assets/7314118/4822638/a1832a5e-5f44-11e4-9b92-3dae837f5984.png)

**Comment by Foggalong** [comment]
Duplicate of #291
