### ISSUE TITLE
Potentially Broken Icon?

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [numixproject/numix-icon-theme-circle#124]
The icon in the far left of this looks really odd, is it broken? And if not, any chance we can improve it?

![Screenshot from 2020-05-04 06-56-03](https://user-images.githubusercontent.com/7698035/80939460-9a53fc80-8dd4-11ea-9801-0f7a644af483.png)

**Comment by palob** [comment]
What do you think is broken there?

**Comment by palob** [comment]
Labelling as *invalid* because this is an issue for our base theme https://github.com/numixproject/numix-icon-theme

**Comment by palob** [comment]
IIRC this icon stands for foggy conditions. Have you got screenshots to illustrate how it looks with other themes?

**Comment by KUPOinyourWINDOW** [comment]
I can't get one right now because there's not gonna be any foggy weather today or tomorrow so it won't show me it, but basically it looks a little stretched to me compared to the others, even in the photo I shared above.
(Sorry for posting here btw, I didn't know, want me to close and re-open the issue there?)

**Comment by palob** [comment]
Yeah, having this in the base reop will help to keep track.
