### ISSUE TITLE
Icon for Variety wallpaper changer

### ISSUE THREAD

**Issue by MageJohn** [numixproject/numix-icon-theme-circle#1245]
[Variety](http://peterlevi.com/variety/) is a lightweight wallpaper changer, which I rather like. It would be great to have an icon in Numix.  The icon is hardcoded, but I've opened issues on Variety itself and on hardcode-fixer.

Thank you!

**Comment by bil-elmoussaoui** [comment]
This should be closed ;) the variety indicator should be reported in the base theme rather than here 
https://github.com/numixproject/numix-icon-theme/issues/375
