### ISSUE TITLE
Icon for "DB Browser for SQLite"

### ISSUE THREAD

**Issue by bernimoses** [numixproject/numix-icon-theme-circle#1247]
A numix-circle icon for "DB Browser for SQLite" is missing.
The icon line says "sqlitebrowser" and the original icon is attached.
![screenshot from 2014-11-03 11 06 32](https://cloud.githubusercontent.com/assets/239049/4880907/e1d60260-6341-11e4-9842-64e8d38241b8.png)

**Comment by palob** [comment]
Fixed as of https://github.com/numixproject/numix-icon-theme-circle/commit/adabe01044760d90adb080dc5a42d27869a59565
