### ISSUE TITLE
Polari icon needed

### ISSUE THREAD

**Issue by sergioad** [numixproject/numix-icon-theme-circle#1249]
Hello friends I am here to request another icon Hitori - icon=hitori

Here is the icon, I hope see it soon :smile: 
![hitori](https://cloud.githubusercontent.com/assets/5375145/4893895/1c59b332-63c9-11e4-9fdd-8786d687faa3.png)

Cheers, greetings from Mexico friends :smile:

**Comment by palob** [comment]
Fixed?
