### ISSUE TITLE
Icon (and tray-icon) for Yarssr

### ISSUE THREAD

**Issue by zeronote** [numixproject/numix-icon-theme-circle#1259]
A numix-circle icon for Yarssr (not so popular but extremely lightweight rss reader for notification area) is missing.

Icon line says: "paper_green", the original icon is attached.

![selection_219](https://cloud.githubusercontent.com/assets/597692/4967809/39b33dd4-6826-11e4-8c8a-b94959bcd7c4.png)

**Comment by bil-elmoussaoui** [comment]
For the tray icon, could you provide more information? or report that to Numix base :)
