### ISSUE TITLE
Is there a ppa for 20.04?

### ISSUE THREAD

**Issue by derTobsch** [numixproject/numix-icon-theme-circle#126]
Hey,
thanks for your work!

When i add the ppa I get a

```
Err:6 http://ppa.launchpad.net/numix/ppa/ubuntu focal Release                  
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
```

**Comment by khurshid-alam** [comment]
Ideally you do not need the ppa since the circle theme is in the repo. Anyway I updated the ppa for focal and groovy. It should work now.

**Comment by Foggalong** [comment]
@khurshid-alam The official repo only carries the stable version, PPA should be building whenever a new build is pushed to this repo (not very often recently, lockdown issues on my end unfortunately).

**Comment by khurshid-alam** [comment]
@Foggalong Yes PPA only builds when a new code is pushed for existing series of Ubuntu.
