### ISSUE TITLE
Firefox Developer Editon

### ISSUE THREAD

**Issue by nekofar** [numixproject/numix-icon-theme-circle#1261]
![Firefox Developer Editon]
(https://mozorg.cdn.mozilla.net/media/img/firefox/developer/title.png)

**Comment by Ghokun** [comment]
Just tweaked some colors on firefox.svg. I can send a pull request if this is ok.

![firefox](https://cloud.githubusercontent.com/assets/3802058/6844496/9ed0b256-d3b4-11e4-9d9c-14cfb3b25e1f.png)

**Comment by Foggalong** [comment]
Fine with me, get that pull request setup :)
