### ISSUE TITLE
Icon for QEmu

### ISSUE THREAD

**Issue by Airblader** [numixproject/numix-icon-theme-circle#1262]
A `numix-circle` icon for [QEmu](http://wiki.qemu.org/Main_Page) is missing.

I'm not sure about the "icon name". Would it have to be added for all of qemu's executables, e.g., for `qemu-system-x86_64`?

There seem to be different icons. The icon for which it shows up with when launching a VM under Ubuntu, for me, can be seen [here](http://qemu.weilnetz.de/icon/benoit/black_and_orange_qemu_head-96x96.png).

**Comment by Foggalong** [comment]
Ah, I see what you mean now. Never mind!
