### ISSUE TITLE
Some icons renders incorrectly on Ubuntu 20.04

### ISSUE THREAD

**Issue by ingria** [numixproject/numix-icon-theme-circle#127]
For example, LibreOffice:

![Screenshot from 2020-06-07 23-45-12](https://user-images.githubusercontent.com/2178368/83979723-3368bc80-a919-11ea-883e-62491a4ab7eb.png)

I think this is caused by not-quite-correct compression.

**Comment by palob** [comment]
What do you think is wrong there and which compression are you referring to?
Can you show other examples?

**Comment by ingria** [comment]
Sorry, I was wrong. Now I see that is exactly what was intended.

I think I was confused because this icon doesn't look like libreoffice's logo, and also looks very different from the related ones:

![Screenshot from 2020-06-08 04-41-40](https://user-images.githubusercontent.com/2178368/83985637-a2a6d680-a942-11ea-84ef-5e04c23cf6ab.png)

Looked like a compression artifact to me (sometimes SVG compression goes wrong, and produces the similar image - random straight lines across geometric figures).

**Comment by palob** [comment]
It's the LibreOffice logo zoomed in but we possibly wouldn't design it that way nowadays.
May become a candidate for a redesign.
