### ISSUE TITLE
Numix circle icon request for FreeMiner [$5]

### ISSUE THREAD

**Issue by sergioad** [numixproject/numix-icon-theme-circle#1276]
A Numix circle icon is needed for FreeMiner icon=freeminer

![freeminer](https://cloud.githubusercontent.com/assets/5375145/5034738/439ef00e-6b37-11e4-883b-2f0c01b69f0d.png)

Because the icon file was a SVG I have needed a SVG to PNG converter but here it is attached

**Comment by ChuckDaniels87** [comment]
@sergioad There is a bounty now in this icon, are you still working on it?

**Comment by sergioad** [comment]
@ChuckDaniels87 many time has passed from the moment when I had it

**Comment by ChuckDaniels87** [comment]
There is an icon merged but it doesn't meet the style guidelines, are you still interested then?

**Comment by sergioad** [comment]
yes

**Comment by ChuckDaniels87** [comment]
Nice :wink:. As a suggestion, I was thinking on something like this in a circular base:

![3d-grass-icon](https://cloud.githubusercontent.com/assets/8478202/6595868/d68a0692-c7ee-11e4-9d54-b212278897f4.png)

**Comment by sergioad** [comment]
yes, the block can fit :smile:

**Comment by Ghokun** [comment]
@ChuckDaniels87 are you going to do that? If not I can also make one.

**Comment by ChuckDaniels87** [comment]
I wanted to do it but @sergioad said he was doing it.

**Comment by Foggalong** [comment]
Because the one @sergioad submitted ([link](https://github.com/sergioad/numix-icon-theme-circle/blob/3b135c1f643e88ab0878be27a62085c09eae05a3/Numix-Circle/48x48/apps/freeminer.svg) didn't fit the guidelines I'm gonna pass this onto @ChuckDaniels87. If he defers, then I'll pass to @Ghokun.

**Comment by ChuckDaniels87** [comment]
@Ghokun If you wanna make this icon is yours. I've already done several icons with bounties, I think it is important to share these bounties and motivate new collaborators. :wink:

**Comment by Foggalong** [comment]
@Ghokun the floor is yours then! :D

**Comment by Ghokun** [comment]
![freeminer](https://cloud.githubusercontent.com/assets/3802058/6886274/a4876b94-d63f-11e4-830b-1fee8a720825.png)

What do you think of this one?

**Comment by Ghokun** [comment]
How about a monochrome pickaxe ? 

![freeminer2](https://cloud.githubusercontent.com/assets/3802058/6886396/7344ae42-d645-11e4-9697-fb415278e847.png)

(By the way, is there a link for design guidelines ?)

**Comment by ChuckDaniels87** [comment]
Yes, [here](https://github.com/numixproject/numix-wiki/wiki/Guidelines).

**Comment by Foggalong** [comment]
Liking that a bit more. Make sure the picaxe is roughly between 24px and 26px in size, is all aligned to grid, and centered somewhere roughly in the middle of the icon.

**Comment by ChuckDaniels87** [comment]
One suggestion now that pickaxe is monochrome, could you reduce a bit pickaxe head width?

**Comment by Ghokun** [comment]
Some improvements

![freeminer3](https://cloud.githubusercontent.com/assets/3802058/6886770/bb5c4e54-d651-11e4-996f-564d0c3fd725.png)
![freeminer2](https://cloud.githubusercontent.com/assets/3802058/6886771/be636042-d651-11e4-99e3-ba1d50a7e97a.png)
![freeminer4](https://cloud.githubusercontent.com/assets/3802058/6886773/c31761ba-d651-11e4-8981-62af44bbcc0c.png)
![freeminer5](https://cloud.githubusercontent.com/assets/3802058/6886775/c599fcae-d651-11e4-8ba6-06051434f517.png)

**Comment by palob** [comment]
I think I prefer the dark axe + bright background one. Best contrast. Is there a gradient on the background?

**Comment by palob** [comment]
Or maybe a light grey head for the axe?

**Comment by Ghokun** [comment]
There is but hard to see by eye.

**Comment by Ghokun** [comment]
A simple one using same colors as "minecraft.svg"

![freeminer7](https://cloud.githubusercontent.com/assets/3802058/6886925/c15a2c84-d658-11e4-91e8-c775cfe053d3.png)

**Comment by Ghokun** [comment]
Here is another one:
![freeminer8](https://cloud.githubusercontent.com/assets/3802058/6888183/b05e2ba8-d67e-11e4-8ece-605356e66e8f.png)

**Comment by ChuckDaniels87** [comment]
Use a lighter background or another colour. It looks nice. :wink:

**Comment by Ghokun** [comment]
![freeminer9](https://cloud.githubusercontent.com/assets/3802058/6892372/1d6b1858-d6cc-11e4-85f3-e81ec664139e.png)
![freeminer10](https://cloud.githubusercontent.com/assets/3802058/6892380/244d34b2-d6cc-11e4-9008-35ca731e8995.png)
![freeminer11](https://cloud.githubusercontent.com/assets/3802058/6892384/28e47418-d6cc-11e4-8e81-987de54e6a3b.png)

**Comment by ChuckDaniels87** [comment]
I like 1º and 3º one, good job! :+1:

**Comment by Ghokun** [comment]
Thanks @ChuckDaniels87 

What should I do now ? Submit a pull request or wait for @Foggalong ?

**Comment by Foggalong** [comment]
How would the block look on a light blue background?

**Comment by ChuckDaniels87** [comment]
Always wait for @Foggalong, he is the icon sheriff here. :stuck_out_tongue_winking_eye:

**Comment by Ghokun** [comment]
A quick one:

![freeminer12](https://cloud.githubusercontent.com/assets/3802058/6895284/36c936b6-d6e7-11e4-8c91-7921074b24ca.png)

Nice catch there @Foggalong . ( It was 185 - 200 )

**Comment by Foggalong** [comment]
A bit more of a bluey blue, try #8bbaeb

**Comment by Ghokun** [comment]
![freeminer13](https://cloud.githubusercontent.com/assets/3802058/6895351/ed991c80-d6e7-11e4-8677-307e70fd939e.png)

**Comment by Foggalong** [comment]
O.o that's not 8bbaeb! too dark compared to the symbol

**Comment by Ghokun** [comment]
![screenshot from 2015-03-30 14 22 24](https://cloud.githubusercontent.com/assets/3802058/6895410/90b84e54-d6e8-11e4-872b-ef84010bad4d.png)

it looks like 8bbaeb :/

**Comment by Ghokun** [comment]
Using gradient of "alarm-clock.svg"

![freeminer14](https://cloud.githubusercontent.com/assets/3802058/6895458/1e5964be-d6e9-11e4-8c0d-297730393336.png)

**Comment by Foggalong** [comment]
Yeah, the two colours are different :P 
[1](https://cloud.githubusercontent.com/assets/3802058/6895574/66b44c1e-d6ea-11e4-9af5-9480f1deced6.png) & [2](https://cloud.githubusercontent.com/assets/3802058/6895351/ed991c80-d6e7-11e4-8677-307e70fd939e.png). Go with the last one you posted
