### ISSUE TITLE
Icon for Lutris - Open Gaming Platform [$5]

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1277]
"Lutris is an open source gaming platform for GNU/Linux"
https://lutris.net/about/

Icon=lutris
![lutris](https://cloud.githubusercontent.com/assets/7050624/5034977/adf22016-6b73-11e4-9bfe-a050e0945ddb.png)

**Comment by markubiak** [comment]
![Screenshot of Lutris icon in Inkscape](http://i.imgur.com/AhwWr7X.png)

This is my first go at it.  I'm by no means a professional, but the lack of an icon for Lutris was bugging me aswell and I had some time.

**Comment by markubiak** [comment]
![v2](http://i.imgur.com/On2eizK.png)

Wasn't happy with the first version, here's a more symmetrical Version 2

**Comment by palob** [comment]
I like the joystick design but it's definitely a bit big.
Could you get the symbol down to 26 px in height?
For ultimate sharpness it is best to have the sidelines of the joystick lines straight vertical and aligned to the pixel grid.

**Comment by markubiak** [comment]
I've been working on this quite a bit more since my comment.

[Here is a link with 10 versions of the icon.](

**Comment by markubiak** [comment]
I've been working on this quite a bit more since my comment.

[Here is a link with 10 versions of the icon.](https://www.dropbox.com/s/n678gktkri72xs3/lutris_v1-10.svg.tar.gz?dl=0)

The one I modified for your request is v10.  I used a 28px height instead of a 26px height, it looked much better.

**Comment by palob** [comment]
Well, apart from exceptions proving the rule 26x26 is the maximum symbol size according to the [guidelines](https://github.com/numixproject/numix-wiki/wiki/Guidelines)

Anyway I think No.10 is the best design :+1:  
I like the simplicity of the top down view design (6,7,8,9) but it doesn't scale too well to sub-48x48 symbol sizes.

However all icons look pretty dark. Could you play a bit with the colours (both baseplate and icon) and maybe simplify that "stick joint thingy"?

**Comment by sergioad** [comment]
Maybe a red button for the joystick? this could be awesome for get a more classic atari joystick look :smile:

**Comment by markubiak** [comment]
According to the guidelines, "User 24, 26 or 28 sized symbols and 30 or 32 sized symbols if they are circles."  To me, that sounds like a 26x28 icon is perfectly acceptable, but if it's still too high, I can absolutely shrink it.

For this version I played with the joystick colors to make it much lighter and changed the joint to be only 3 colors.  I'm trying to follow [the design of the Lutris website](http://www.lutris.net) but the accent color (#F90) isn't working too well as a base color.   I could make the button that color, but then what should the base be?  If I follow their site and use a dark grey, there will be way to much grey.  Hmm.

[Link to updated icon](https://www.dropbox.com/s/lb4t1wmzna308ly/lutris-v11.svg?dl=0)

**Comment by palob** [comment]
As I said, there are some exceptions to the rule, especially for game icons.

The changes did well and you're getting closer now :+1: 
Some remaining issues:
+ There is something wrong with your baseplate. The bevel on the lower right doesn't show for some reason.

+ The Numix Circle icons use a linear gradient for the baseplate colour instead of a solid one.
 10L lighter at the top than at the bottom. Just have a look on how it's done on the existing icons.

+ Currently the baseplate colour is 100% saturated (S255) which makes it look a bit brash.
   The colour combination still looks heavy to me.

+ The icon needs a symbol shadow. Basically a duplicate of the outlining symbol stuff, black with 10% opacity (A25).

+ Maybe it's just me or the icon looks slightly odd perpectively

+ Maybe move the red button a bit from the upper edge

Don't feel discouraged, seeing what you did so far I'm sure you'll manage it :)

**Comment by markubiak** [comment]
I didn't know about the background gradient, but the rest of those things were lost while working.  Thanks for sticking with me through this, it's a learning experiment.  I've added everything above, and changed the stick so that it's more upright and edited the base to match it.  I was thinking about the color scheme, and deided the Lutris accent color #f90 was an accent color for a reason and shouldn't be a background.  I changed the button on the joystick instead.  I am still struggling for a good background color, I'm trying a red but I think it's too deep.  I definitely need general color suggestions for the background now that the orange is out of the picture.

[Fixed with the light red gradient background](https://www.dropbox.com/s/q3gbisoj3hj14h7/lutris-v12.svg?dl=0)
[And with a turquoise background, just to see](https://www.dropbox.com/s/xswi2w7tjej8y09/lutris-v12-turquoise.svg?dl=0)

**Comment by palob** [comment]
There is nothing at all wrong with orange in general. Just use a less dominant one. You could check the symbol on existing orange baseplate like you find in for instance ``cairo-dock.svg``, ``Foto.svg``, ``google-musicmanager.svg``, ``gufw.svg``,``kuickshow.svg``, ``jockey.svg``, ``media-player-banshee.svg``.
When using a lighter orange for the baseplate you can go fora lighter grey on the joystick symbol without compromising the contrast.

**Comment by markubiak** [comment]
[Lighter joystick and better orange background](https://www.dropbox.com/s/8id4efdsy1c9xdf/lutris-v14.svg?dl=0)
It's very close now.  I'm happy with it, personally.

**Comment by palob** [comment]
Well done.

Now perhaps the stick could be a tad darker again + the button could be lighter so as to not to stand out that much.
Did you try to have the joystick base symmetric (that's what I meant by the odd perspective)?. 
Didn't turn out well?

About the 28px in height: I think the symbol looks close to the baseplate bottom so shortening the stick by 2px could help here.

The shadow paths has numerous unneeded nodes in it. How did you create the shadow?
Duplating all (or only the ones defining the outline) objects and a path union should do it.

Last but not least you can use Inkscape's "unneeded def cleaning" function to reduce the filesize (4th item from bottom up in the File menu). Just do it after finishing all your editing tasks.

I think it's ready for a pull request then.
Let's see what's @Foggalong's view.

**Comment by palob** [comment]
Do you now how to use git for a PR?

**Comment by palob** [comment]
I case you don't you can follow [this tutorial](https://github.com/ozonos/ozon-wiki/wiki/Code-Contribution).
By doing the PR you can pick up the 5$ bounty

**Comment by markubiak** [comment]
I'm sorry, yes I can do a pull request, that's no issue.  I addressed some concerns with perspective and color.  [Take your pick of the final 2 designs](https://www.dropbox.com/s/nq8tl3h62jhu2mm/lutris-final.tar.gz?dl=0) and I'll submit the request on the one that's better.

**Comment by palob** [comment]
Cool :+1: 
I think I prefer the symmetric one. What do you think @Foggalong ?


The button colour could be changed to for instance H0 ; L160 (top) and H0 ; L150 (sides) for better contrast.

The shadow is still messy, instead of a path union you've probably done a path combination.
What you're looking for is the 5th (from top) path menu item or ``Ctrl``+``+``.

**Comment by markubiak** [comment]
[Pull request submitted](https://github.com/numixproject/numix-icon-theme-circle/pull/2105)
