### ISSUE TITLE
redshift-status-off.svg missing in Numix-Circle-Light

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#1286]
An icon for `redshift-status-off.svg` is missing in Numix-Circle-Light. In contrast, Numix-Circle has both `redshift-status-on.svg` and `redshift-status-off.svg`, in `22x22/status`.

I am reporting this issue in Numix-Circle and not in Numix base, because currently those status icons are all in Numix-Circle and Numix-Circle-Light, cf. https://github.com/numixproject/numix-icon-theme/issues/190.

Screenshots of Numix-Circle (Ambiance GTK theme) and Numix-Circle-Light (Radiance GTK theme), with Redshift first on and then off, panel in Ubuntu 14.10/Unity:

![redshift1](https://cloud.githubusercontent.com/assets/7164227/5057081/04ddcf32-6cab-11e4-8afb-9afd6083d07d.png)
![redshift2](https://cloud.githubusercontent.com/assets/7164227/5057082/079d486a-6cab-11e4-8353-5133df5fdf27.png)
![redshift3](https://cloud.githubusercontent.com/assets/7164227/5057084/0947651a-6cab-11e4-8d1f-261c7b86ae34.png)
![redshift4](https://cloud.githubusercontent.com/assets/7164227/5057085/0a80a432-6cab-11e4-8f87-06e5b9cb3685.png)

For Redshift off in Numix-Circle-Light, the Redshift circle application icon is displayed, as `redshift-status-off.svg` is missing.

**Comment by Foggalong** [comment]
Moved to Numix base :)
