### ISSUE TITLE
Icon for Wakfu (Steam)

### ISSUE THREAD

**Issue by gzjjrp** [numixproject/numix-icon-theme-circle#1291]
Game: Wakfu
AppID: 215080
Icon: 
![steam_icon_215080](https://cloud.githubusercontent.com/assets/9773849/5059259/d16d8ec6-6d4f-11e4-9b26-2e974f8cee6c.png)

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by sergioad** [comment]
+1 but I have never played, the game has not worked on my PC several times

**Comment by Foggalong** [comment]
@sergioad Only +1 the icons you'll actually use, it kinda defeats the point otherwise :P

**Comment by sergioad** [comment]
@Foggalong Ok :smile:
