### ISSUE TITLE
Icon for megasync client missing

### ISSUE THREAD

**Issue by mateosss** [numixproject/numix-icon-theme-circle#13]
Currently there is no icon for Mega Sync desktop client.

from /usr/share/applications/megasync.desktop

```
Icon=mega
```

![mega](https://cloud.githubusercontent.com/assets/5622899/19021752/e098cb10-889e-11e6-9894-b48bef726d4d.png)

**Comment by Foggalong** [comment]
[We have one](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/mega.svg) so I'm not sure what's going on here. Are you running the latest version?

**Comment by mateosss** [comment]
Oh sorry I noticed that there is an icon. Which is pretty similar (of course it is :smile:) to the original.

But Mega as like as Dropbox have a status bar icon, which unlike Dropbox one, the mega status bar icon, isn't entirely white. Anyway, I don't know if this is on purpose. So thanks!

![captura de pantalla de 2016-10-03 21-14-22](https://cloud.githubusercontent.com/assets/5622899/19058520/62ca1fb6-89ae-11e6-8b38-96a619163c85.png)

**Comment by Foggalong** [comment]
Do you know what the name of the status bar icon is? If it's the same as the app icon name we can't fix it :(

**Comment by dschaehi** [comment]
Hi, I am also interested in having a less prominent status bar icon for Mega (I recently switched from Dropbox to Mega, as it provides 50GB cloud space and the same user experience as Dropbox).
How can I find the name of the status bar icon for Mega?

**Comment by Foggalong** [comment]
It'll usually be found inside the packaging for whatever you're installing. If you find it, please report it [here](https://github.com/numixproject/numix-icon-theme)
