### ISSUE TITLE
gtk2 open file dialog box - one missing icon

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme-circle#1309]
![numix-gtk2-open-file-dialog](https://cloud.githubusercontent.com/assets/7532854/5116205/ce5e3ef6-702e-11e4-82b9-a1f33af453fa.png)

This happens with applications using the old gtk2 open file dialog box. The highlighted icon is missing.

**Comment by palob** [comment]
Now discussed in Numix base issue 315
https://github.com/numixproject/numix-icon-theme/issues/315

**Comment by dirtydancing** [comment]
@palob Thanks for the heads-up. I figure that this issue can be closed then.
