### ISSUE TITLE
Ambiguous calculator icon

### ISSUE THREAD

**Issue by serek1024** [numixproject/numix-icon-theme-circle#131]
The calculator icon is ambigous. The previous version was more consistent, understandable and prettier

**Comment by Foggalong** [comment]
We're gonna need some more information from you to look at this, like screenshots of what the icon is now and (of you have it) what it was before. To my knowledge we haven't changed the calculator icon for a couple of years now.

**Comment by serek1024** [comment]
The screenshot attached with version comparizon for filr calc.svg 
![image](https://user-images.githubusercontent.com/9059060/93332198-c4f19f80-f821-11ea-9ad1-81ae9ecf7519.png)

**Comment by palob** [comment]
The left one isn't supposed to be the icon for calculator apps but for a pcb calculator.

Which of the icons above is shown where?

**Comment by mavlac** [comment]
As the serek's illustration indicates, the one on the right was the one I used to see as an icon of a calculator in Ubuntu Gnome app overview / panel. Now recently it switched to the left design.

By quickly checking /usr/share/icons/Numix-Circle/48/apps/ I am finding the left one under generic name calc.svg, which I second is not universally fitting.

**Comment by palob** [comment]
You're right, at least the latest release has the left one as ``calc``, master however correctly the left one.
@Foggalong So this looks to be an issue with ``data.json``.
