### ISSUE TITLE
icon for LinSSID [$5]

### ISSUE THREAD

**Issue by cargie** [numixproject/numix-icon-theme-circle#1313]
http://sourceforge.net/projects/linssid/

Icon=LinSSID

![image](https://cloud.githubusercontent.com/assets/8433416/5135768/b4f319d0-7157-11e4-82cc-7d980ceae212.png)

**Comment by hlechner** [comment]
Just for reference, here a screenshot of the LinSSID in execution:
![image](https://cloud.githubusercontent.com/assets/11244067/6588735/99ad75da-c774-11e4-912f-bee0cffd153c.png)

**Comment by ChuckDaniels87** [comment]
I don't like original icon, I'll see what I can do.

**Comment by hlechner** [comment]
Good job @ChuckDaniels87 !

**Comment by hlechner** [comment]
I've taken a look and it's hardcoded. installed by AUR community package, The icon isn't manually installed by the AUR script but by the own application.

Desktop file:
```
#!/usr/bin/env xdg-open

[Desktop Entry]
Encoding=UTF-8
Version=2.7
Name=LinSSID
GenericName=
Comment=Find local wireless attach points
Exec=linssid
Icon=/usr/share/pixmaps/linssid48.png
Terminal=false
Type=Application
Categories=Application;Network;Internet;
Name[en]=LinSSID
```

I'll raise an issue into hardcode-fix project

**Comment by ChuckDaniels87** [comment]
AUR packages can be easily fixed, hardcode-fix should be the last option. Report upstream here: https://aur.archlinux.org/packages/linssid/

_Note: Arch is cool_

**Comment by ChuckDaniels87** [comment]
Sorry, I've misunderstood your last message. Maybe we could report it even more upstream, [here](http://sourceforge.net/projects/linssid/).

**Comment by hlechner** [comment]
@ChuckDaniels87 Yea, I'll report to the LinSSID developer too, but it seems that it will take some time on their side, this project is not so active.

**Comment by hlechner** [comment]
Easier than I thought. I've reported:
https://sourceforge.net/p/linssid/discussion/bugs/thread/0d96d9f6/

The description of how to fix it is inside my report.

**Comment by ChuckDaniels87** [comment]
Nice @hlechner, the dev said that will fix it in the next release! Good job :wink:
