### ISSUE TITLE
Icon for MediaInfo

### ISSUE THREAD

**Issue by GLolol** [numixproject/numix-icon-theme-circle#1352]
https://mediaarea.net/en/MediaInfo
MediaInfo is a technical information and tag viewer for media formats.

mediainfo-gui.desktop file:
```
[Desktop Entry]
Type=Application
Version=1.0
Name=MediaInfo
Comment=Supplies technical and tag information about a video or audio file
Comment[fr]=fournit des informations techniques et les tags à propos de vos fichiers video et audio
Icon=mediainfo
Exec=mediainfo-gui %f 
Terminal=false
MimeType=
Categories=AudioVideo;AudioVideoEditing;
```

256x256 icon:
![mediainfo](https://cloud.githubusercontent.com/assets/4644601/5274982/ff18784a-7a51-11e4-8807-11ee434ce297.png)

**Comment by Ghokun** [comment]
How about this:
![mediainfo](https://cloud.githubusercontent.com/assets/3802058/6929918/717ef446-d807-11e4-8866-15ad4b825cf4.png)

**Comment by GLolol** [comment]
@Ghokun doesn't look bad to me! :)

**Comment by Foggalong** [comment]
Nice idea, though the main symbol would haveto be centred to avoid looking off kilt.

**Comment by palob** [comment]
The black looks a bit harsh to me.

**Comment by Foggalong** [comment]
@Ghokun @palob Yeah, 292929 is the official Numix black :)

**Comment by Ghokun** [comment]
I will have a look at this when I have time

**Comment by palob** [comment]
Another small suggestion: Currently all three colours are fully saturated (S 255). It's most noticeable on the blue part. Not a big deal here as the colours are alredy rather light but maybe a desaturation (+ increased L?) of the blue part could make it look more coherent.

**Comment by Ghokun** [comment]
Sorry that i could not finished this. So many things happening in real life, not that I have a newborn daughter :)

**Comment by Foggalong** [comment]
@Ghokun Not a problem, that's life! Congratulations on the daughter :D
