### ISSUE TITLE
Icon for Costume Quest (Steam)

### ISSUE THREAD

**Issue by cjcou** [numixproject/numix-icon-theme-circle#1372]
Game: Costume Quest
AppID: 115100
Icon: http://fc04.deviantart.net/fs70/f/2011/296/7/4/costume_quest_game_icon_by_wolfangraul-d4dp1gb.png
Notes: RPG Game about children at halloween.

**Comment by ChuckDaniels87** [comment]
Nice icon @Foggalong!! A lot of cool work recently. :wink:

**Comment by Foggalong** [comment]
Aha, thanks! I was determined to bring the Numix Circle issue list down from it's rather scary 200+ to a more manageable number. Gonna try and get it down to ~25 (and keep it there) before I switch focus to a different part of the theme (probably updating Square).

**Comment by ChuckDaniels87** [comment]
Nice idea indeed. :+1:
