### ISSUE TITLE
Icon for Empire: Total War (Steam)

### ISSUE THREAD

**Issue by cjcou** [numixproject/numix-icon-theme-circle#1374]
Game: Empire: Total War
AppID: 10500
Icon: http://ggstatic.com/productimages/empire-total-war_pac_m.jpg
Notes: Game about the American War of Independence.

**Comment by Foggalong** [comment]
@ChuckDaniels87 you still up for this? Think you'd do quite well for it :)

**Comment by ChuckDaniels87** [comment]
Yep, I still want to make it but I am a bit busy lately. I hope to be more relaxed in a couple of weeks and make some icons. :smile:

**Comment by Foggalong** [comment]
@ChuckDaniels87 No problem! Hope you're all good :)

**Comment by Foggalong** [comment]
The icon isn't perfect, but it does the job while not inciting controversy over the flag picked
