### ISSUE TITLE
Dropbox icon disappeared in Ubuntu 14.04 system tray

### ISSUE THREAD

**Issue by gsalvatori** [numixproject/numix-icon-theme-circle#1389]
Today, dropbox icon disappeared in my systray. Is it my fault or an issue with the icon pack?

![senzanome](https://cloud.githubusercontent.com/assets/1579930/5435273/278ca43e-8459-11e4-9797-8aedc48ab4bf.png)

**Comment by Foggalong** [comment]
Moved to base :)

**Comment by endikaml** [comment]
This link explains how to change the icons permanently.
http://www.aurumlinux.com/tutoriales/cambiar-iconos-en-dropbox/
To look transparent icons may be desirable to delay the start of dropbox few seconds.
