### ISSUE TITLE
[Bug] Simplenote icon is slightly smaller than the others

### ISSUE THREAD

**Issue by idontlikecaesar** [numixproject/numix-icon-theme-circle#139]

**Comment by idontlikecaesar** [comment]
![Screenshot from 2021-05-12 18-09-04](https://user-images.githubusercontent.com/83839684/117999093-2fc18f00-b34d-11eb-8ba9-74f21524a955.png)
It can be seen here

**Comment by palob** [comment]
That's probably not a Numix icon at all. Could you please look for the icon name (line that reads ``Icon=something``) from the respective ``.desktop`` file in ``/usrshare/applications`` or ``~/.local/share/applications``?

**Comment by idontlikecaesar** [comment]
You were right. Because it is flatpak, it was using its own icon instead of Numix. Sorry! :)

**Comment by palob** [comment]
Flatpak app icons are themeable, we just need the icon name.

**Comment by idontlikecaesar** [comment]
`com.simplenote.Simplenote`

**Comment by palob** [comment]
We've already got this very icon name which probably means you aren't using the latest Numix release.

**Comment by idontlikecaesar** [comment]
I installed Numix from Ubuntu repos

**Comment by palob** [comment]
PPA or distro repos?

**Comment by idontlikecaesar** [comment]
Distro repo

**Comment by palob** [comment]
Since Ubuntu isn't a rolling release distro packages won't be updated (apart from boring security updates).
You'll have to use the PPA or install the theme manually in order to get the latest and greatest of Numix. 

Don't hesitate to ask back if you are facing problems in doing so.
