### ISSUE TITLE
Chrome app - Videostream icon missing

### ISSUE THREAD

**Issue by zachprice** [numixproject/numix-icon-theme-circle#1391]
https://chrome.google.com/webstore/detail/videostream-for-google-ch/cnciopoikihiagdjbjpnocolokfelagl?hl=en

**Comment by Zubieta** [comment]
In OSX, I also can't find within Chrome itself the icon for launching it. However, if I write 'videostream' in Finder, it will open a native app briefly and then open a tab with the app.

**Comment by Foggalong** [comment]
@Zubieta I didn't know our icon theme worked with OSX? O.o
