### ISSUE TITLE
Icon for Trelby

### ISSUE THREAD

**Issue by Txarli** [numixproject/numix-icon-theme-circle#1410]
[Trelby](http://www.trelby.org/) is a free screenwriting software for Linux. It would be nice to have a Numix icon.

This is the actual icon:
![TrelbyIcon256](https://cloud.githubusercontent.com/assets/3373382/5530562/9f6443c2-8a21-11e4-8e5b-b8acf4bb8672.png)

Thank you!

**Comment by palob** [comment]
Hi, could you please add the information specified in the tutorial video (link on the frontpage)?

**Comment by palob** [comment]
Trelby 2.2 AUR package:

trelby.desktop
Icon=/opt/trelby/resources/icon256.png

**Comment by Txarli** [comment]
I'm sorry, I'll have it in mind in future requests. Thank you, and good job!

**Comment by palob** [comment]
You're welcome.:-) Is the icon line the same with your installation?
