### ISSUE TITLE
Icon request for gnujump/xjump

### ISSUE THREAD

**Issue by allejok96** [numixproject/numix-icon-theme-circle#1415]
The greatest game of them all. Lovin' those sound effects :laughing: 

Icon=gnujump
![gnujump](https://cloud.githubusercontent.com/assets/7693838/5548392/2d202ef2-8b70-11e4-8f75-abab527c14bc.png)

xjump is the older classical version of the game and it has exactly the same icon but it's a xpm file instead
Icon=xjump-icon.xpm

**Comment by palob** [comment]
Hi, is the filename of the xjump launcher *xjump.desktop* ?

**Comment by allejok96** [comment]
Yes, thats correct, at least in Ubuntu
