### ISSUE TITLE
Icon for Retext

### ISSUE THREAD

**Issue by Keops1984** [numixproject/numix-icon-theme-circle#1425]
A new icon for retext 

a powerfull markdown editor

![retext](https://cloud.githubusercontent.com/assets/2146560/5603365/7fc437c4-9382-11e4-8702-f6e36d2cc29a.png)

Thanks

**Comment by palob** [comment]
Hi, could you please add the information specified in the tutorial video (link on the numix-circle frontpage)?

**Comment by palob** [comment]
ReText 5.0.1:
Icon=retext
