### ISSUE TITLE
ms-office filetype icons using libreoffice filetype icons

### ISSUE THREAD

**Issue by orschiro** [numixproject/numix-icon-theme-circle#1426]
I noticed that the ms-office filetype icons, such as `.xlsx` or `docx`, are using the libreoffice filetype icons. 

Example:

![screenshot](https://cloud.githubusercontent.com/assets/170947/5613944/acf54106-94eb-11e4-9976-410745010e4f.png)

Can someone confirm that?

Thanks,

Robert

**Comment by Foggalong** [comment]
Thanks for reporting! This is related to [#110](https://github.com/numixproject/numix-icon-theme/issues/110) in the Numix Base theme - please add any information you have there :)
