### ISSUE TITLE
custom icon offer: network_config and wireless_config

### ISSUE THREAD

**Issue by meoso** [numixproject/numix-icon-theme-circle#1439]
I've edited together these icons for my personal use and now offer them to you if you like.
![my_network_config](https://cloud.githubusercontent.com/assets/1337447/5681673/1e162610-97e0-11e4-8221-ed802ed92780.png)
![my_wireless_config_2](https://cloud.githubusercontent.com/assets/1337447/5681676/2170f100-97e0-11e4-9f2c-d0c1256d2ec9.png)
![enterasys-icon-transparent_48](https://cloud.githubusercontent.com/assets/1337447/5681681/2d407e9c-97e0-11e4-9c35-c69f498efce3.png)

**Comment by Foggalong** [comment]
They don't really fit with the Numix design spec, sorry
