### ISSUE TITLE
Icon for budget 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1448]
Budget is a new (unstable version) for elementary os 
[Desktop Entry]
Name=Budget
Comment=Manage your budget
Keywords=budget;money;
GenericName=Personal budget manager
Exec=envelope
Icon=envelope
Terminal=false
StartupNotify=true
Type=Application
Categories=Utility;
X-GNOME-Gettext-Domain=envelope
X-GNOME-UsesNotifications=true;
Actions=AboutDialog;

[Desktop Action AboutDialog]
Exec=envelope --about
Name=About Budget

**Comment by Foggalong** [comment]
Can we have a picture of what the original icon looks like, gives us something to work with :)

**Comment by bil-elmoussaoui** [comment]
for the default icon ,there's nothing..the application was using  accessories-calculator as a default icon..
shall we wait till the officiel release ?

**Comment by Foggalong** [comment]
Nah, a screen shot of accessories calculator will be fine

**Comment by bil-elmoussaoui** [comment]
:s the icon is the same as a calculator... 

![capture du 2015-01-13 20 51 00](https://cloud.githubusercontent.com/assets/7660997/5727786/e8c3b750-9b65-11e4-86a8-9b2d8792414f.png)

**Comment by Foggalong** [comment]
Ah sorry, I see what you mean. I'll see what I can do as a temporary icon, but feel free to comment here again if the icon gets changed at official release :)
