### ISSUE TITLE
Please add some more icons

### ISSUE THREAD

**Issue by Shakhawat001** [numixproject/numix-icon-theme-circle#145]
Those icons are great. Maybe you can add some more.

* Figma
* workflow (icon: https://drive.google.com/file/d/1uew1USBUzMHnCsJB7sie06uWv4-1mMjb/view?usp=sharing)
* Notion
* Ticktick
* Shotcut
* OBS Studio

**Comment by Foggalong** [comment]
@Shakhawat001 Please read the readme for how to submit icon requests and please report them in the correct repo, this one is for packaging.

**Comment by palob** [comment]
@Shakhawat001 We've already designed icons for Figma, OBS and Shotcut so if we are missing something there it's a matter of mere symlinks. We need to know the icon names from your ``.desktop`` launcher files to help you.
