### ISSUE TITLE
Symlink gdebi application 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1452]
Hello, 
i think you have to add a symlink of gdebi application on Elementary os ; the icon line is 
[Desktop Entry]
Name=GDebi Package Installer
GenericName=Package Installer
Comment=Install and view software packages
Exec=gdebi-gtk %f
Icon=gnome-mime-application-x-deb
Terminal=false
Type=Application
Categories=System;
MimeType=application/x-deb;application/x-debian-package;
NotShowIn=KDE;
X-Ubuntu-Gettext-Domain=gdebi
StartupNotify=true
Keywords=package;apt;dpkg;install

**Comment by Foggalong** [comment]
This is a fault with the GDebi developers. They choose `gnome-mime-application-x-deb.svg` as their icon name, but this is also the same as they .deb [mime type](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/16x16/mimetypes/gnome-mime-application-x-deb.svg). This means that the program will have the wrong icon, and there's nothing we can do about it - sorry :( if you'd like this to change, you'll have to report the problem to them.

**Comment by palob** [comment]
Couldn't the hardcode fixer be of help here?
@bil-elmoussaoui you can edit the icon line to *Icon=gdebi* otherwise.
