### ISSUE TITLE
Screenshot and camera have the same icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1454]
Hello, 
The screenshot application and the camera app have the same icon 
the icon line of camera :Icon=accessories-camera
the icon line of screenshot : Icon=applets-screenshooter
both have this icon 
![capture du 2015-01-15 00 06 47](https://cloud.githubusercontent.com/assets/7660997/5749572/69389fba-9c4a-11e4-9fe2-bc5545d67506.png)

i don't know if you know about it , but it would be very cool if you made an other icon for the camera app? or the screenshot one ! 
Thank you for your great work

**Comment by Foggalong** [comment]
Just to clarify for @wa4557 and anyone else who might be keeping an eye on this, we're yet to discuss whether we want these to have distinct icons. I'll try to make sure we do asap, but we have some money stuff which is a bit more urgent atm :)

**Comment by palob** [comment]
In case of distinct icons a few symlinks would have to be changed as well for a screenshot <--> cam distinction.

**Comment by bil-elmoussaoui** [comment]
Well, if you use french as the default language in your system the icons camera is named "Appareil photo" and the screenshot app is named "Capture d'écran" and the icons are so close to each others and you can easily see that they are the same!

**Comment by Foggalong** [comment]
Just been speaking with @me4oslav about this issue. His original vision for these two icons was that the screenshot icons would look like this

![icon](http://i.imgur.com/uHUI87Z.jpg)

while the camera/webcam ones kept their current design.

**Comment by palob** [comment]
In case this is to be followed up on there are these two similar designs:

``hotshots.svg``(Darktable icon w/o inner circle)
![hotshots](https://cloud.githubusercontent.com/assets/7050624/8891013/39b4bd5a-3317-11e5-924e-783385b765d2.png)

and this one from the Android theme:
![com_android_camera_2](https://cloud.githubusercontent.com/assets/7050624/8891015/453de69c-3317-11e5-888b-6e8b13e12e3d.png)

**Comment by Foggalong** [comment]
Thanks @palob :+1:
