### ISSUE TITLE
icons themed in overview, not in favourite

### ISSUE THREAD

**Issue by rudrab** [numixproject/numix-icon-theme-circle#1475]
Hi,
first of all, thanks for the beautiful theme both in android and linux.
I am facing a problem in linux that for mendeley-desktop, the icon is themed in overview; but if I open it then in favourite, its not themed.

See this link: https://drive.google.com/file/d/0B02WblgE6NEvS2prZUJEbmpNR2c/view?usp=sharing 
for the screenshot for two mendeley desktop icon in two place.

I am using the current github version in fedora21

**Comment by Foggalong** [comment]
That's more than likely a problem with upstream Mendeley so there's nothing we can do to fix it, sorry :(
