### ISSUE TITLE
tomboy notes

### ISSUE THREAD

**Issue by Bishopst** [numixproject/numix-icon-theme-circle#1476]
Would really be cool if you can have an icon for the top panel for tomboy :)

**Comment by Foggalong** [comment]
That would be an issue for the base theme, please report there :)

**Comment by Bishopst** [comment]
Oh sorry, but what do you mean by base theme? I was referring to the numix-circle icon theme.

**Comment by ChuckDaniels87** [comment]
Open issue here: https://github.com/numixproject/numix-icon-theme
