### ISSUE TITLE
Replace JDownloader icon with the flareget icon from Numix Bevel

### ISSUE THREAD

**Issue by AndydeCleyre** [numixproject/numix-icon-theme-circle#1477]
Hi,

The old bevel flareget icon is both more attractive and more like the upstream JDownloader icon than the current Numix Circle JDownloader icon. Please just use that one instead.

https://github.com/numixproject/numix-icon-theme-bevel/blob/master/Numix-Bevel/48x48/apps/flareget.svg

**Comment by Foggalong** [comment]
I'll have a play around with both styles, see if we can't come up with a better icon :)

**Comment by ChuckDaniels87** [comment]
I want to take a look on this. :smile:
