### ISSUE TITLE
Icon for UberWriter

### ISSUE THREAD

**Issue by frozenxuan** [numixproject/numix-icon-theme-circle#1481]
Name=UberWriter
Icon=/opt/extras.ubuntu.com/uberwriter/share/uberwriter/media/uberwriter.svg
![screenshot from 2015-01-24 17 07 30](https://cloud.githubusercontent.com/assets/6898228/5886802/8a74f914-a3eb-11e4-88f3-0e43018122da.png)

**Comment by palob** [comment]
There is an Numix Circle icon, but the path is hardcoded. Could you report it as issue for the hardcode fixer script (link in the readme)?
