### ISSUE TITLE
REQUEST : Redshift

### ISSUE THREAD

**Issue by erikdubois** [numixproject/numix-icon-theme-circle#15]
Could you consider making an icon for redshift?
http://jonls.dk/redshift/

redshift.desktop 

[Desktop Entry]
Version=1.0
Name=Redshift
GenericName=Color temperature adjustment
Comment=Color temperature adjustment tool
Exec=redshift
Icon=redshift
Terminal=true
Type=Application
NoDisplay=true

**Comment by Foggalong** [comment]
[We have this icon](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/redshift.svg) - are you using the latest version?

**Comment by erikdubois** [comment]
I found the issue. The Arc theme makes it almost impossible to see it. Same applies to the Mint-Y theme. The trayicon is too dark. Application icon is fine.
Redshift disabled
![redshiftdisabled](https://cloud.githubusercontent.com/assets/10594806/19228633/6834111e-8ec7-11e6-8b8d-2c312a955a7c.jpg)
Redshift enabled
![redshift-enabled](https://cloud.githubusercontent.com/assets/10594806/19228638/737acd24-8ec7-11e6-941b-fa39758122b8.jpg)

**Comment by Foggalong** [comment]
There's something going wrong where the Redshift enabled icon isn't showing when you enable redshift. It should appear like this:
![screenshot_2016-10-10_09-25-15](https://cloud.githubusercontent.com/assets/5920259/19230250/789aa9ba-8ecb-11e6-9536-58760eac9259.png)

This will be an issue with numixproject/numix-icon-theme so please report it there :)
