### ISSUE TITLE
Whatsapp web (Chrome app)

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1507]
Hello,
the extension link : https://chrome.google.com/webstore/detail/whatsapp-web/gcjbnclfkeffmdfdhflnadahgmajfgcm?hl=fr

The icon line : 
Icon=chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default
the desktop file : 
chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default.desktop

Thanks

**Comment by kingcraig** [comment]
WhatsApp hack tool <a href="http://whatsapphacktool.wix.com/whatsapphacktool">Whats App Hack Tool 2015</a>
