### ISSUE TITLE
rss/feed reader icons broken

### ISSUE THREAD

**Issue by zensubz** [numixproject/numix-icon-theme-circle#151]
Hi,

Commit 118516c seems to have introduced some distortions in the following rss/feed reader icons:

blam.svg
quiterss.svg
internet-news-reader.svg
liferea.svg
raven-reader.svg
syndic.svg
urserver.svg

They look quite different now - please see the attached pic:

![Selection_001](https://user-images.githubusercontent.com/5127872/197380412-70f743bb-e2b3-4de8-b0a0-fcce54265269.jpg)

I would appreciate if these are fixed. Thanks.

**Comment by palob** [comment]
Hi, I can't repropuce this. Neithr with librsvg-based image viewers (using librsvg version ``2.55.1``, latest upstream relese) nor with QtSVG-based viewers.

Which image viewer are you using? Maybe it was a librsvg bug which has been fixed.
Does it look like this in your desktop or only in the image viewer?

**Comment by zensubz** [comment]
@palob thanks for the quick response. I am on CentOS 7.x with librsvg2 2.40.20, which is distro-provided. I have used MATE image viewer (eom) to view the image files (shown above), which is linked with librsvg2-2.40.20. They also look the same way in the Menu (launcher) - that's how I spotted the change in the icon-design. 

As far as I know, only the above-mentioned svg files seem to be affected, it would be great if you could fix them at your end.

**Comment by palob** [comment]
Looking at the SVG code I can't see what would cause this. The changes only affect ``path`` code, nothing globally SVG-related.

**Comment by zensubz** [comment]
You are right @palob - the problem is indeed due to (old) librsvg2 that is available in CentOS 7.x. I have checked with a relatively newer librsvg2 v2.42.9 and the problem seems to be resolved. Thanks.
