### ISSUE TITLE
Icon for Vega

### ISSUE THREAD

**Issue by xavihers** [numixproject/numix-icon-theme-circle#1517]
A numix circle icon for Vega is missing.

https://subgraph.com/img/slides/scene2/vega-transparent.png

**Comment by xavihers** [comment]
![vega](https://cloud.githubusercontent.com/assets/7763465/5970216/8b13fa60-a7f5-11e4-9db9-5643ef014afb.jpg)

Above the icon image

**Comment by dirtydancing** [comment]
@xavihers Please include the icon line (`Icon=...`) so that this icon request can be properly addressed.

The icon line is a part of the .desktop file, you will find this line when you open the file with a text editor.
