### ISSUE TITLE
Icon for HTTraQt

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1518]
Icon for HTTraQt, a GUI for HTTrack
http://httraqt.sourceforge.net/

Icon=httraqt.xpm

However, this file doesn't exist and the displayed icon is a PNG.
![httraqt](https://cloud.githubusercontent.com/assets/7050624/5977188/c307f5ac-a895-11e4-9dc2-298a5c50995d.png)

**Comment by bil-elmoussaoui** [comment]
The icon is hardcoded i guess? If not i believe someone have to symlink it to httrack icon 
![screenshot from 2015-03-05 19 29 13](https://cloud.githubusercontent.com/assets/7660997/6511563/0194940e-c36e-11e4-837e-4523bd5ab14d.png)

**Comment by palob** [comment]
Yep, the icon line *Icon=httraqt.xpm* is hardcoded. Is it the same with your installation?

**Comment by Foggalong** [comment]
Guess this is just a case of getting that upstream bug report filed then :)

**Comment by palob** [comment]
It's actually a different app. Will do a symlink + hardcode fixer entry

**Comment by Foggalong** [comment]
Ah right! Sorry, didn't realise :)
