### ISSUE TITLE
Icon for pycharm

### ISSUE THREAD

**Issue by kuravih** [numixproject/numix-icon-theme-circle#1519]
Icon for pycharm community edition, free Python IDE from jetbrains
https://www.jetbrains.com/pycharm/download/

Icon=/opt/pycharm-community-4.0.4/bin/pycharm.png

![pycharm](https://cloud.githubusercontent.com/assets/7969796/5978730/edde5daa-a86f-11e4-9c9f-e525f71dcf2e.png)

**Comment by Foggalong** [comment]
We have one, it's just hardcoded. See the readme for more info
