### ISSUE TITLE
Icon for Pure Data

### ISSUE THREAD

**Issue by gilbertohasnofb** [numixproject/numix-icon-theme-circle#1523]
I would like to request icons for Pure Data, both vanilla and extended versions. Here are their original icons:

https://guitarextended.files.wordpress.com/2011/12/puredata_icone1.jpg
http://i2.photobucket.com/albums/y43/johnwell/pd-extended.png

**Comment by Foggalong** [comment]
Do you have the icon name, we can't make one without it?

**Comment by gilbertohasnofb** [comment]
I believe the icon is simply named pd.gif (on my installation, it's located inside the program's folder in /usr/lib/pd-extended/tcl ).

**Comment by Foggalong** [comment]
Ah. That means the icons won't automatically apply, and you'll have to apply them manually

**Comment by gilbertohasnofb** [comment]
Sorry, my mistake, the icon for Pure Data extended is actually located at /usr/share/icons/hicolor/128x128/apps/pd-extended.png (I am using a custom icon myself, that being the source of the confusion here). As for Pure Data vanilla, on Linux it can be installed only by compiling it yourself, and the icon is named pd.ico but has to be dealt with manually (I had to create shortcuts for it manually anyway).

**Comment by Foggalong** [comment]
Ah, thanks for the correction!
