### ISSUE TITLE
Icon for PPSSPP Emulator

### ISSUE THREAD

**Issue by sandycorzeta** [numixproject/numix-icon-theme-circle#1536]
application.desktop file of PPSSPP emulator
```
[Desktop Entry]
Version=1.0
Type=Application
Name=PPSSPP
GenericName=PSP Emulator
Comment=PlayStation Portable Simulator Suitable for Playing Portably (PPSSPP)
Exec=ppsspp --fullscreen
Icon=ppsspp
Categories=Game
```
Icon of PPSSPP Emulator
http://www.ppsspp.org/img/ppsspp-icon.png

**Comment by freeniki** [comment]
![ppsspp](https://cloud.githubusercontent.com/assets/8083855/6059004/0d2304e0-ad3e-11e4-87e0-0ad5afcdad55.png)
SVG: http://www.datafilehost.com/d/e666d733

**Comment by Foggalong** [comment]
If you wish to contribute an icons please make a [pull request](https://help.github.com/articles/using-pull-requests/) it makes it easier for us to verify they meet the design guidelines and then merge them into the main theme

**Comment by palob** [comment]
@freeniki You can also have a look at this tutorial:
https://github.com/ozonos/ozon-icon-theme/wiki/Contributing

**Comment by hlechner** [comment]
Hey guys, Just for reference: There is other request for same app: #1159 (Sep 18, 2014)

**Comment by Foggalong** [comment]
Good catch
