### ISSUE TITLE
Icon for Ardour 3 Digital Workstation

### ISSUE THREAD

**Issue by sandycorzeta** [numixproject/numix-icon-theme-circle#1538]
the application.desktop file
```
[Desktop Entry]
Version=1.0
Name=Ardour Digital Audio Workstation 3
Comment=Record, mix and master multi-track audio
Exec=/usr/bin/ardour3
Terminal=false
Type=Application
Icon=/opt/ardour3/share/icons/ardour_icon_48px.png
Categories=AudioVideo;Audio;
MimeType=application/x-ardour;
```
The Icon
![ardour_icon_48px](https://cloud.githubusercontent.com/assets/4186454/6000204/88ae0960-ab1e-11e4-906a-1f6158a43f42.png)

**Comment by palob** [comment]
There is a Numix Circle icon but the default icon path is hardcoded. Could you report this as issue for the hardcode-fixer script please (link on thefrontpage)?

**Comment by ChuckDaniels87** [comment]
Or even better, report it to the upstream coders.

**Comment by sandycorzeta** [comment]
This is coming from KXStudio repos .... 
It maybe because the official repo on Ubuntu is still on version 2, while this one is on version 3
