### ISSUE TITLE
Icon for Euro Truck Simulator 2 game (Steam)

### ISSUE THREAD

**Issue by 19sickrun70** [numixproject/numix-icon-theme-circle#1540]
Game: Euro Truck Simulator 2
AppID: 227300
Icon: ![ets2](https://cloud.githubusercontent.com/assets/10813461/6003619/b85e47c4-ab05-11e4-9ff0-3625f0839329.png)

**Comment by Foggalong** [comment]
This game doesn't support Linux. I should know, I love it.

**Comment by hlechner** [comment]
@Foggalong Actually, it supports Linux. More details can be found inside the Steam Store: http://store.steampowered.com/app/227300/

**Comment by Foggalong** [comment]
Wha D: when did that happen!? I was running winento get this running not too long ago!
