### ISSUE TITLE
Natron Icon

### ISSUE THREAD

**Issue by ChuckDaniels87** [numixproject/numix-icon-theme-circle#1542]
__Natron__
Natron is a free open-source (MPLv2 license) video compositing software, similar in functionality to Adobe After Effects or Nuke by The Foundry.

Icon: natronIcon256_linux
Site: https://natron.inria.fr

![images duckduckgo com](https://cloud.githubusercontent.com/assets/8478202/6007688/5f52625c-ab1c-11e4-9866-a952870e9970.png)

**Comment by palob** [comment]
Just to be sure: Is it on purpose that the outer "N lines" aren't straight vertical?
