### ISSUE TITLE
Icon for bomi

### ISSUE THREAD

**Issue by varlesh** [numixproject/numix-icon-theme-circle#1549]
bomi (ex CMPlayer) is a graphical user interface(GUI) player based on mpv for Linux.

Home page:
http://bomi-player.github.io

Original icon:
https://github.com/xylosper/bomi/blob/master/icons/bomi.svg

Desktop Entry:
Name=bomi
GenericName=Media Player
Comment=Play your media
Icon=bomi

**Comment by freeniki** [comment]
![bomi](https://cloud.githubusercontent.com/assets/8083855/6059802/e2a83f1a-ad46-11e4-8025-5bb45492d469.png)

SVG: http://www.datafilehost.com/d/f643bb8f

**Comment by ChuckDaniels87** [comment]
If you're submitting an icon you'd better try a pull request. 
Fork the whole repository (numix-icon-theme-circle) add your icon in your local repository and then create a pull request to merge it. There are several tutorials in GitHub. +1

**Comment by palob** [comment]
Hi, @freeniki, I've had a look at your icon. :+1: 
Some suggestions:
+ Make sure that vertical and horizontal lines are aligned to the pixel grid (to be toggled with Ctrl+# in  Inkscape). This will make the icon look sharper.

+The symbol needs to be centered horizontically and vertically and the shadow moved 1px down and to the right relative to the symbol.

+Regarding the colour, it is preferred not to use the brightest plain white but something like L230 to L250 instead.

The icon should be ready to be merged then.
Right now the symbol is 24x24 in size but for circular icons 30x30 is allowed as well, so you can go for that if it looks good.
