### ISSUE TITLE
A Numix circle icon for AM2R is needed

### ISSUE THREAD

**Issue by sergioad** [numixproject/numix-icon-theme-circle#1562]
A Numix circle (and square) icon is needed for AM2R (Another Metroid 2 Remake) as it's name says the app is a remake of the GB title Metroid 2 return of Samus, the game is under development so it is not finished, it is currentlly in demo state and has not .desktop nor distribution package, it is distributed in a simple tar but I feel (and know) it is a good game what needs a good Numix icon

Original icon

![icon](https://cloud.githubusercontent.com/assets/5375145/6094966/1bbc1776-af0a-11e4-8796-3b36efd6cbb1.png)

Suggested icon name: am2r

Suggested design: the same icon but flat white on a green Numix icon, you can simply use the same green of the session properties icon (and the icon's background itself) and put on it the flat white AM2R icon over it, the design is simple so I think you will finish it so fast :smile:

**Comment by sergioad** [comment]
WOOOOOOOOOOOOOOOW the icon is really AMAZING, thank you so  much @Foggalong :smile:

**Comment by Foggalong** [comment]
Haha, not a problem! I'm a big metroid fan myself :)

**Comment by sergioad** [comment]
COOL, in this case you should try the AM2R demo, it is really amazing :smile:
