### ISSUE TITLE
Icon for Cura

### ISSUE THREAD

**Issue by Klikini** [numixproject/numix-icon-theme-circle#1564]
[Cura](https://ultimaker.com/en/products/software) slicer is used to convert 3D models into printer instructions, and it is the only program I have on my launcher without a matching icon (nice work there!)

Here is the current icon:
![image](https://cloud.githubusercontent.com/assets/1693960/6098449/bd85c83c-afa4-11e4-9af5-d4f7d837e0b9.png)

**Comment by Foggalong** [comment]
Do you have the icon name?

**Comment by Klikini** [comment]
No... How do I find that? Is it in the .desktop file?

**Comment by Foggalong** [comment]
Aye :) see [here](https://github.com/numixproject/numix-icon-theme-circle#icon-requests) for more info

**Comment by Klikini** [comment]
There isn't a real "icon name", but this is what the desktop entry looks like:

    Name=Cura
    Icon=/usr/share/cura/resources/images/c.png

**Comment by Foggalong** [comment]
Thanks!
