### ISSUE TITLE
Icon for Reditr

### ISSUE THREAD

**Issue by t3mux** [numixproject/numix-icon-theme-circle#1567]
Well a shiny numix circle icon for Reditr

http://reditr.com/

**Comment by Foggalong** [comment]
Shiny? Not sure what you mean, we have an icon for it in Circle though 
![screenshot - 100215 - 18 33 29](https://cloud.githubusercontent.com/assets/5920259/6133658/59fb0d9e-b153-11e4-81ba-e1dd658a42f1.png)

**Comment by t3mux** [comment]
Well, that's really odd. I am using Reditr on Elementary OS Luna (Ubuntu 12.04) and the Circle Theme. But it's the native Reditr Icon i am seeing. I installed Reditr via the .deb from the Website.

**Comment by Foggalong** [comment]
Do you have the icon line from the launcher? It'll be in ~/.local/share/applications or /usr/share/applications

**Comment by t3mux** [comment]
/usr/share/applications : Icon=/opt/reditr/128x128.png

**Comment by Foggalong** [comment]
Ahhh, that just means it's hardcoded. Change the line to `Icon=reditr` and you'll be fine :)
