### ISSUE TITLE
Icons for Nuvola Player 3 Web App Scripts

### ISSUE THREAD

**Issue by Atema** [numixproject/numix-icon-theme-circle#1576]
Numix icons are needed for the Nuvola Player 3 Web App Scripts. The current icons (for respectively Deezer, Google Play Music and Grooveshark) are as follows. SVG versions of those icons are available in the GitHub repositories mentioned here: https://github.com/tiliado/nuvolaplayer/wiki/Web-App-Scripts

![Deezer](https://cloud.githubusercontent.com/assets/774965/6200846/26505180-b48b-11e4-85b0-6f93dad21b3a.png) ![Google Play Music](https://cloud.githubusercontent.com/assets/774965/6200847/2f8042b0-b48b-11e4-8ace-5d69a5e99e0f.png) ![Grooveshark](https://cloud.githubusercontent.com/assets/774965/6200852/56fb4b82-b48b-11e4-8f86-8eaf445a0f63.png)

The icons are, unfortunately, hardcoded. Depending on the method of installation, the icons are to be found in:
```
/usr/share/nuvolaplayer3/web_apps/SERVICE_NAME/icon.png
```
or
```
~/.local/share/nuvolaplayer3/web_apps/SERVICE_NAME/icon.png
```

**Comment by Foggalong** [comment]
We can't fix icons with the name `icon.svg`, so please report to the developers to get them to change it :*

**Comment by rishadafc** [comment]
Is there any chance this issue can be re-opened? There is an update about the icons from a nuvolaplayer developer [here](https://github.com/tiliado/nuvolaplayer/issues/78#issuecomment-167314230).

**Comment by rickinbsb** [comment]
I'll send in a pull request this week fixing it
