### ISSUE TITLE
Icon for Enpass

### ISSUE THREAD

**Issue by MCommander** [numixproject/numix-icon-theme-circle#1585]
A numix icon for Enpass is missing.
The original icon is attached.
![enpass](https://cloud.githubusercontent.com/assets/6379282/6274887/fd156e2e-b87a-11e4-9f0e-68c3ba128acb.png)

**Comment by bil-elmoussaoui** [comment]
The application is hardcoded; the icon line is 
Icon=/opt/Enpass/enpass.png
But i want to see this on the numix icon pack ;)
You can report this to the devlopper so you can change the icon easily by changing the theme

**Comment by MCommander** [comment]
I contacted them, let you know the result.

**Comment by MCommander** [comment]
Enpass Support Team:

"Thanks for writing to us. We have noted down your suggestions and will definitely consider them for the future versions."

**Comment by t3mux** [comment]
Push :D

**Comment by eldragon87** [comment]
+1 :smiley:
