### ISSUE TITLE
Several (app) status icons are missing in size 24x24

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#1601]
Hi, I am filing this report against Numix-Circle and not against Numix base because of https://github.com/numixproject/numix-icon-theme/issues/190

Now that Xubuntu has a panel canvas size of 24x24 (and e.g. 24x24 is also the wingpanel canvas size in elementary OS Freya, currently in Beta 2), several of the Numix status icons look too big and a little blurred because they only come in size 22x22 and not in 24x24. If they are missing in 24x24 but are present in 22x22, the 22x22 icons have to get scaled to 24x24, and that causes a bit of "friction".

In contrast, the panel canvas size in Ubuntu is 22x22, so all looks fine on Ubuntu.

Examplary comparative screenshot of the panel in Ubuntu 14.10 ("bare metal") above and Xubuntu 14.10 (VM) below (affected status icons pointed to):

![xubuntu1410_canvas_24x24](https://cloud.githubusercontent.com/assets/7164227/6368524/d7bca626-bcdd-11e4-89a3-f55963664e62.png)

In this screenshot, the affected status icons are Shutter, Redshift, SysPeek and Y PPA Manager.

In Numix-Circle, there is a directory `22x22/status`, but not yet a directory `24x24/status`. So basically, the status icons in `22x22/status` would have to be added to `24x24/status`. Some of these icons in size 24x24 are already present in Numix base and just would have to be copied over to Numix-Circle, others are not.

This should be manageable by taking Numix-Circle's `22x22/status` directory as a guideline, so I filed this collective report. Please let me know if I should file a specific bug report for every specific status icon.

**Comment by bil-elmoussaoui** [comment]
I would just to mention (i hesitate to open a new issue only for this);some panel(status) icons are on the numix-circle theme; for ex: dropbox,caffeine... is it the right directory?

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Yes, Numix-Circle is the correct place for these app status icons to be in.

I am aware that this can be confusing, because one might think: Numix-Circle for the Circle app icons, and Numix base as the basis for the rest (non-circle icons that can be used as a base for Circle, Square, the upcoming non-uniformity icon theme, and so on). And the sytem status icons for the panel (such as battery, network, sound) are in Numix base as well, so why not the app status icons?

Well, unfortunately things are a little more complicated. It appears that the app status icons fall back to the app icon if no app status icon is detected. And in the icon theme inheritance line, Numix-Circle comes before Numix base (Numix-Circle inherits Numix base). E.g., if Redshift looks for the app status icon `redshift-status-on`, but does not find that in Numix-Circle, it will fall back to the app icon `redshift`, which is in Numix-Circle. So before Numix base with `redshift-status-on` can be inherited, the icon `redhshift` is already found in Numix-Circle and placed in the panel. The panel will then show the circle (and not-monochrome) Redshift app icon. This means that the app status icons have to be in the first icon theme of the icon theme inheritance line, or at least not behind the actual (circle) app icon.

This has also been discussed already in https://github.com/numixproject/numix-icon-theme/issues/190, when the app status icons changed to the Circle icons in the panel after the app status icons had been moved from Numix-Circle to Numix base.

So, for the time being, Numix-Circle is indeed the right place for these app status icons to be in.

I know this is somewhat confusing, and I hope that this has cleared things up a little bit for you.

**Comment by dirtydancing** [comment]
Update to my original report: When testing with Xubuntu 14.10, I noticed that placing 24x24 app status icons in a newly created folder `24x24/status` did not change the way that they are displayed in the Xubuntu 14.10 panel (which means that they were still coming from `22x22/status`).

But on the other hand, placing 24x24 app status icons in the already existing folder `24x24/apps` did work. So I figure that `24x24/apps` would be the relevant folder for the 24x24 app status icons.

Comparative screenshots with app status icons for Shutter, Redshift and SysPeek:

24x24 app status icons in `24x24/status` (no change to the current panel):
![xubuntu1410_current](https://cloud.githubusercontent.com/assets/7164227/6394610/eb738cfc-bdd2-11e4-9232-dcf57a06fc22.png)

24x24 app status icons in `24x24/apps` (now consistent size and sharpness):
![xubuntu1410_new](https://cloud.githubusercontent.com/assets/7164227/6394629/065b9960-bdd3-11e4-865d-ba4071759874.png)

**Comment by dirtydancing** [comment]
Just as a futher clarification: the actual app status icon size is the same, only the canvas is 24x24 instead of 22x22 (just like with the system status/indicator icons, such as audio, messages).

**Comment by wa4557** [comment]
@dirtydancing I want to fix that, but I need a few more infos:

1.Am I right, that there exists a 24x24/status folder in Numix-base that is correct, so nothing needs to be fixed there?

2. Wouldn't it be ok to just generate all the icons that in exist in 22x22/status in Numix-Circle in 24x24/status in Numix-Circle?

**Comment by dirtydancing** [comment]
Q1: Yes, correct, there is a `24x24/status` folder in Numix **base**, and nothing needs to be fixed there. But for the **app** status icons, the `24x24/status` folder in Numix **base** is irrelevant, because as it currently stands, the **app** status icons are taken exclusively from Numix-**Circle** :-)

Q2: Correct again. The canvas size of those icons would need to change from 22x22 to 24x24, but the actual icon size itself would need to remain the same. More detailed: there are the two folders `22x22/status` and `22x22/apps` in Numix-**Circle**, so arguably the new icons in `24x24/apps` in Numix-**Circle** (there are already some in there at present) should comprise the icons from both these folders in 22x22 (?).

**Comment by wa4557** [comment]
Ok, cool as soon as this notifications issues are sorted, I'll look into that...

**Comment by dirtydancing** [comment]
Great! This should be useful not only for users of Xubuntu, but also for users of elementary OS Freya.

**Comment by bil-elmoussaoui** [comment]
Yes!!! i would really love to see that, its one of the reasons i'm still using Elementary base theme; the same thing for https://github.com/numixproject/numix-icon-theme/issues/258

**Comment by wa4557** [comment]
@dirtydancing @bil-elmoussaoui Icons are finished, I'm just waiting for a pull request to be merged. One other thing: What's with the 16x16 size? Are they needed for sth?

**Comment by dirtydancing** [comment]
@wa4557 Fantastic news again! And now, on to your question:

I am not aware of a distribution that currently uses a 16x16 canvas for (fixed size) panel icons. This is what size 16x16 **app** status icons relevant here would be needed for. Another situation where size 16x16 might be of relevance is in cases of display scaling or when the default panel height is changed.

Maybe GNOME distributions come into play here, as GNOME Shell seems to draw upon size 16x16 icons. This would be up to an actual GNOME Shell user to determine/report/test.

Things are somewhat different for GNOME Shell: iirc, GNOME Shell by default does not display any **app** status icons at all, although there are extensions for this. And the **system** status icons are not "fixed size" ones, but rather "symbolic"-named ones from the "scalable" directory. And these "symbolic" **system** status icons follow somewhat different design guidelines than the "fixed size" **system** status icons.

This being said, in Numix base, the **system** status icons are present for the fixed size directories 16x16, 22x22 and 24x24. So it might make sense to include the size 16x16 **app** status icons for consistency.

@Foggalong?

**Comment by Foggalong** [comment]
This is now a base theme issue, see the above link for more details :)
