### ISSUE TITLE
Icon for iViewer

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1603]
I would like to ask for an icon : 
iViewer : https://github.com/Philip-Scott/iViewer
the icon is hardcoded; but i already reported this , the icon line will be fixed in the next update!
the original icon :
![icon48](https://cloud.githubusercontent.com/assets/7660997/6381301/6bfc3fd8-bd40-11e4-87d0-3a64f9fe84b3.png)
I will add the icon line as soon as i get the update!
Thank you

**Comment by Foggalong** [comment]
If you could ask the dev what then icon line will be changed to that would be ace :)

**Comment by Philip-Scott** [comment]
I'm not sure how themes work though, but on my end the .desktop file is reading the icon correctly form /usr/share/icons/hicolor(and elementary)/##x##/apps/iViewer.sgv
If you need the line number for any reason, here is the only line in the code that "reads" an icon :)
line 336: string icon = "iViewer"; 
I currently have sizes for 32, 48, 64 and 128

If you need anything else, please feel free to ask :)

**Comment by hlechner** [comment]
Hi @Philip-Scott,
Thanks for reporting us! I'm glad to know that it's fixed.

Just for you understand why we have asked for the line: the icons are case-sensitive and it needs to match exactly with the string inside the .desktop file.

Then now we know exactly which name we need to set it. If some day you need to change it just let us know so we can correct it on Numix side :)

Regards,

**Comment by ChuckDaniels87** [comment]
Let's celebrate it, a nice dev deserve a nice icon! :stuck_out_tongue_winking_eye:

**Comment by Philip-Scott** [comment]
Hey, may i ask you guys something? Apparently, i didn't realize that I've been reading the icon from /usr/share/iViewer/iViewer.svg all along. So were do i have to add the icons on the system so the .desktop files will read them with the icon name "iViewer"? I've been trying to prepare the app for a script installation, but adding the icons to /usr/share/icons/elementary/apps/-- doesn't seem to do the trick :P 

Do i have to "register" the app name somewhere?

**Comment by ChuckDaniels87** [comment]
If you put them in _/usr/share/icons/hicolor/?×?/apps/_ should work. Do not
use _/usr/share/icons/elementary/_ because it is not the standard one.
