### ISSUE TITLE
Missing status icons in mint mate 17.1

### ISSUE THREAD

**Issue by gregruth** [numixproject/numix-icon-theme-circle#1625]
For some reason a lot of the icons (maybe all) inside of the notification area widget are not displaying.

Mint Mate 17.1

![screenshot-1](https://cloud.githubusercontent.com/assets/6091509/6429419/68c4e362-bf8c-11e4-9598-cea01e3060b2.png)

**Comment by Foggalong** [comment]
This is an issue for base, not Circle
