### ISSUE TITLE
Icon for FlightGear

### ISSUE THREAD

**Issue by gilbertohasnofb** [numixproject/numix-icon-theme-circle#1630]
Request: icon for the opensource flight simulator FlightGear (www.flightgear.org). The current icon is:

https://lh6.googleusercontent.com/-A_Uf2fY5Dgs/AAAAAAAAAAI/AAAAAAAABY0/n0eNzwxlW9o/photo.jpg

**Comment by palob** [comment]
There already is a Numix Circle icon. So either your Numix Circle set isn't up to date or the icon is hardcoded. Could you please add the information pointed out in the readme on the front page, i. e. the icon line in the applications .desktop file?

**Comment by gilbertohasnofb** [comment]
I just found that I do have this icon, but it wasn't set automatically to the shortcut. It is probably hardcoded then. Also, FlightGear creates 2 shortcuts, one for the main profram `fgfs` and another for the launcher `fgrun` (the latter is the what most users use), both which show the same icon.

> Could you please add the information pointed out in the readme on the front page, i. e. the icon line in the applications .desktop file?

I don't understand which information is this and I can't find anything about a .desktop file in the front page. Could you please try to explain this to me so I can send it to you?

Thanks a  lot.

**Comment by Foggalong** [comment]
It's in the [section on how to submit icon request](https://github.com/numixproject/numix-icon-theme-circle#icon-requests)

**Comment by gilbertohasnofb** [comment]
`fgfs` icon line: `Icon=fgfs`
`fgrun` icon line: `Icon=/usr/share/pixmaps/flightgear.ico`

**Comment by palob** [comment]
Thanks. The first launcher just needs a symlink, the second one is hardcoded.
Do you know what's the difference between these two?

**Comment by palob** [comment]
Added a symlink for fgfs. You can fix fgrun manually by editing the icon line to ``Icon=flightgear``

**Comment by gilbertohasnofb** [comment]
Sure, I exchanged both fgfs and fgrun's icon line to `Icon=flightgear` and now all is well. Thanks for the help.
