### ISSUE TITLE
Request: Icon for pyRenamer

### ISSUE THREAD

**Issue by emariz** [numixproject/numix-icon-theme-circle#1658]
Hi there!

**pyRenamer** is a great mass file re-namer. I have been using it for a couple of years now, and it would be great if there were a Numix circle icon for this must-have application.
Thanks for the fantastic icon theme.

![pyrenamer](https://cloud.githubusercontent.com/assets/9307858/6538029/6fb11ff2-c43b-11e4-82f3-67deae87d447.png)
This is the default application icon.

https://packages.debian.org/sid/pyrenamer

**Comment by palob** [comment]
There is an icon. But it is hardcoded. You can download and run the hardcode-fixer script (link in the readme) or edit the icon line in the .desktop file manually to ``Icon=pyrenamer``.

**Comment by emariz** [comment]
@palob Thanks, mate. I edited the appropriate *.desktop* file and now the Numix pyRenamer icon is shown. Next time, I will check this before filing a report.
Cheers!
