### ISSUE TITLE
Icon request for Nuvola Player 3

### ISSUE THREAD

**Issue by jayseejc** [numixproject/numix-icon-theme-circle#1659]
A numix-circle icon for Nuvola player is missing. 
The icon line says nuvolaplayer3 and the original icon is attached.
![screenshot from 2015-03-07 01 05 29](https://cloud.githubusercontent.com/assets/1485633/6540332/11582f9c-c466-11e4-9894-d7087d0c127c.png)

**Comment by palob** [comment]
Hi, a symlink has been added recently. So it's probably just your local Numix Circle theme not up to the latest changes.
