### ISSUE TITLE
Icon for Amnesia: A Machine for Pigs (Steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1672]
Game: **Amnesia: A Machine for Pigs**
AppID: **[239200](https://steamdb.info/app/239200/)**
Website: **http://aamfp.com/**
Icon: ![image](https://cloud.githubusercontent.com/assets/11244067/6548816/494d527c-c5e4-11e4-9eee-cf833fa374b5.png)

Desktop file:
``Icon=steam_icon_239200``

**Comment by wa4557** [comment]
@Foggalong nice icon :) but you missed the shadow

**Comment by ChuckDaniels87** [comment]
Cool pig. :stuck_out_tongue_winking_eye:
