### ISSUE TITLE
[Numix Square] Missing icons

### ISSUE THREAD

**Issue by boukmi** [numixproject/numix-icon-theme-circle#1676]
Hi,

I've downloded the numix square icons form the numix store and extract the archive into the folder /user/share/icons.
There are some missing icons, I'm using Ubuntu 14.10.
I added a screenshot to this message.
Is there anything you can do?

Thank you.
![selection_001](https://cloud.githubusercontent.com/assets/2116866/6565226/dd0fa814-c6ae-11e4-8d72-97a065ef229c.png)

**Comment by Foggalong** [comment]
This is an issue for the [Numix Square](https://github.com/numixproject/numix-icon-theme-square) or [Store](https://github.com/numixproject/numix-store) issue trackers :)

**Comment by boukmi** [comment]
All right, I'll report the issue there
Thanks
