### ISSUE TITLE
Icon for Penumbra: Overture (Steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1683]
Game: **Penumbra: Overture**
AppID: [**22180**](https://steamdb.info/app/22180/)
Website: **http://www.penumbragame.com/**
Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/6589485/889b8290-c77f-11e4-932f-fb6df542b432.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6589496/b784c698-c77f-11e4-804c-3371458f63d8.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6589500/d10cc61a-c77f-11e4-946a-dc3e6391fd38.png)

Note: **Hardcoded (There is no game's icon, only reference to steam: Icon=steam)**
Note2: **The images above were taken from steam client.**
Note3: **[Amnesia](https://steamdb.info/app/57300/)-style game.**

Desktop file:
```
[Desktop Entry]
Name=Penumbra: Overture
Comment=Play this game on Steam
Exec=steam steam://rungameid/22180
Icon=steam
Terminal=false
Type=Application
Categories=Game;
```

Target desktop file:
``Icon=steam_icon_22180``

**Comment by ChuckDaniels87** [comment]
It's a difficult icon, here it is a sketch:

![icons](https://cloud.githubusercontent.com/assets/8478202/6766890/0c8709ca-d019-11e4-9109-a49d0c365493.png)

Any ideas? Can you give me more info about the gameplay?

**Comment by hlechner** [comment]
This games's serie is a really complicated one.

Basically story that you needs to discover about his dad, in a horror ambient scenarios. you need to go to find answer without gun or defense. need to be careful in a dangerous and unknown place.

The game is first person and is designed to scare the gamer.

here some gameplay screenshot of penumbra: overture:
![image](https://cloud.githubusercontent.com/assets/11244067/6766952/26e4b796-cffa-11e4-9bdc-fcb3a586acec.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6766953/2d032022-cffa-11e4-873d-734dbc46dda3.png)

This game as developed by the same studio that have developed the Amnesia: The dark descent

**Comment by hlechner** [comment]
I hope I could help you guys with design ideas but unfortunately, I'm a terrible designer.

But I think you're right: Due to the "unknown" and "scary" style, a man with a torch/light in the dark is take a lot of spirit of this game.

By the way: nice job on icon!

**Comment by ChuckDaniels87** [comment]
More sketches:
![icons_1](https://cloud.githubusercontent.com/assets/8478202/6767379/fb1b7fd6-d02c-11e4-9975-a658d164e482.png)
![icons_2](https://cloud.githubusercontent.com/assets/8478202/6767383/0d99d054-d02d-11e4-8361-1daa6b450a3d.png)

**Comment by Foggalong** [comment]
Like the flare idea! What are your thoughts @hlechner?

**Comment by hlechner** [comment]
I love the idea of a person with a torch (in the first one), I think the additional red light around torch was very nice!

Maybe like the first one with a close-up like the second would be the best in my opinion.

But the last one is very nice also. So anyone that you guys decide I agree :)

**Comment by ChuckDaniels87** [comment]
The problem is that there are three games and I want to make three different but related icons. @hlechner mix of 1º icon with close-up could be nice.

**Comment by ChuckDaniels87** [comment]
Another idea:

![icons](https://cloud.githubusercontent.com/assets/8478202/6767741/e3fb2a6a-d043-11e4-83bd-3de9e690514d.png)

**Comment by ChuckDaniels87** [comment]
Last idea could be used for the 3 games changin the glare colour. What do you think?

**Comment by hlechner** [comment]
The idea of glade color I think is very nice, because it can be identified as a "game group".

But I couldn't identified this one very well when small size like 32

**Comment by ChuckDaniels87** [comment]
Maybe with more color intensity?

__128x128__
![icons](https://cloud.githubusercontent.com/assets/8478202/6767757/ac61e146-d045-11e4-8ab2-de3e59d0142f.png)

__48x48__
![icons_1_48](https://cloud.githubusercontent.com/assets/8478202/6767758/b1e00bb6-d045-11e4-9117-ecf017423f4b.png)

**Comment by hlechner** [comment]
Nice! I think it could fit very well !!

I hope I'm not bothering you, but its possible maybe put a hand/torch in this one? Like just he's holding one. 

yea I love the idea of holding a torch like the first :P

**Comment by ChuckDaniels87** [comment]
To make it clearer my idea of the Penumbra Series:

__128x128__
![icons](https://cloud.githubusercontent.com/assets/8478202/6767777/67ec07d4-d046-11e4-94c6-950f4263b3bb.png) ![icons](https://cloud.githubusercontent.com/assets/8478202/6767806/014515c4-d047-11e4-95c0-fbebf0dd53e7.png) ![icons](https://cloud.githubusercontent.com/assets/8478202/6767817/547f93cc-d047-11e4-9dfe-55c5e5ad5b28.png)

__48x48__
![icons_1_48](https://cloud.githubusercontent.com/assets/8478202/6767778/70c09d2a-d046-11e4-927b-f065b3e6a188.png) ![icons_1_48](https://cloud.githubusercontent.com/assets/8478202/6767807/071498bc-d047-11e4-9eb1-cf7557b1c3e0.png) ![icons_1_48](https://cloud.githubusercontent.com/assets/8478202/6767816/5071354c-d047-11e4-9560-14016e7f4905.png)

**Comment by ChuckDaniels87** [comment]
@hlechner It would be difficult to me adding the torch to the siloutte without blurring the result. :confused:

**Comment by hlechner** [comment]
No problem, the last one is very cool, good job! it fit very well for penumbra games

**Comment by ChuckDaniels87** [comment]
I'm glad you like them as you created the issues. :wink:

Let's wait to hear what @Foggalong think about them and then I'll create the pull request if all is right.

**Comment by Foggalong** [comment]
That's all fine with me! Nice idea with the different colours for the different games :)
