### ISSUE TITLE
Icon for Anna - Extended Edition (Steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1685]
Game: **Anna - Extended Edition**
AppID: [**217690**](https://steamdb.info/app/217690/)
Website: **http://store.steampowered.com/app/217690/**
Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/6589695/bc95b630-c782-11e4-82c3-438c519979a4.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6589702/dbf8a898-c782-11e4-9b5b-387fb86d802d.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6589708/eda17980-c782-11e4-9c5a-6569783fba99.png)

Note: **Hardcoded (There is no game's icon, only reference to steam: Icon=steam)**
Note2: **The images above were taken from steam client.**
Note3: **Horror game style.**

Desktop file:
```
[Desktop Entry]
Name=Anna - Extended Edition
Comment=Play this game on Steam
Exec=steam steam://rungameid/217690
Icon=steam
Terminal=false
Type=Application
Categories=Game;
```

Target desktop file:
``Icon=steam_icon_217690``

**Comment by hlechner** [comment]
My first try in inkscape:
![image](https://cloud.githubusercontent.com/assets/11244067/6846994/9c591d00-d3a1-11e4-887f-1beca24b090c.png)

Any Suggestion?

**Comment by Foggalong** [comment]
Nice idea! To keep in with the icon guidelines the symbol needs to be about 24-26px. Maybe make the tendrils a bit smaller and center the A a bit more?

**Comment by hlechner** [comment]
Something like that?
![image](https://cloud.githubusercontent.com/assets/11244067/6849050/737d9e70-d3af-11e4-9511-eedc80498528.png)

I need to learn how to use inkscape

**Comment by Foggalong** [comment]
Aye, that's much better! Set it up in a pull request and I'll merge it in :)
