### ISSUE TITLE
Icon for Gone Home (Steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1686]
Game: **Gone Home**
AppID: [**232430**](https://steamdb.info/app/232430/)
Website: **http://www.gonehomegame.com/**
Icons:
![image](https://cloud.githubusercontent.com/assets/11244067/6589842/f1ba331a-c785-11e4-8e07-7e1b5f7b75f2.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6589847/02715076-c786-11e4-95a7-50b314a8a821.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6589854/0f0f434c-c786-11e4-956f-18b03eb47f0b.png)

Note: **Hardcoded (There is no game's icon, only reference to steam: Icon=steam)**
Note2: **The images above were taken from steam client.**
Note3: **Story Exploration game.**

Desktop file:
```
[Desktop Entry]
Name=Gone Home
Comment=Play this game on Steam
Exec=steam steam://rungameid/232430
Icon=steam
Terminal=false
Type=Application
Categories=Game;
```

Target desktop file:
``Icon=steam_icon_232430``

**Comment by ChuckDaniels87** [comment]
Could you report upstream this* hardcoded icon?

_*And the recent issues you opened?_

**Comment by hlechner** [comment]
@ChuckDaniels87 Do you mean the path for the hardcoded icon?

It seems the same logic of **dota2**, that only reference **steam** but there is no icon on it:

[Desktop Entry]
Name=Gone Home
Comment=Play this game on Steam
Exec=steam steam://rungameid/232430
Icon=steam
Terminal=false
Type=Application
Categories=Game;


The idea behind saying that it's hardcoded is to be easily to add to hardcode-fixer script as same as already happened to dota2. Should I change my approach ?

**Comment by ChuckDaniels87** [comment]
You did it quite well, a lot of info and that's good to make an icon and fixing the hardcoding. Nevertherless, it is nice to communicate this missing icon upstream and see if they can fix it.

**Comment by hlechner** [comment]
ooops, sorry for close the issue...

Thanks @ChuckDaniels87 I'll edit for better reflect it.

**Comment by hlechner** [comment]
nice icon!
