### ISSUE TITLE
Icon for Gjiten

### ISSUE THREAD

**Issue by wadaki** [numixproject/numix-icon-theme-circle#1699]
A Numix circle icon for Gjiten is missing.

Icon=jiten.png

![20150312_001_ubuntu software-center](https://cloud.githubusercontent.com/assets/8577568/6612189/de844656-c8ba-11e4-9812-65fd4109c515.png)

{code}
[Desktop Entry]
Encoding=UTF-8
Name=Gjiten
Comment=Japanese dictionary
Exec=gjiten
Icon=jiten.png
StartupNotify=true
Terminal=false
Type=Application
Categories=GNOME;Application;Utility;
X-Ubuntu-Gettext-Domain=gjiten
{code}

(http://gjiten.cvs.sourceforge.net/viewvc/gjiten/gjiten/pixmaps/jiten.png)
The written Kanji is "辞典".

**Comment by ChuckDaniels87** [comment]
Symbol shadow is missing here

**Comment by Foggalong** [comment]
Good spot. I got that fixated on aligning stuff that I plain forgot the shadow :P

**Comment by ChuckDaniels87** [comment]
It happens to me all the time, :stuck_out_tongue:

**Comment by wadaki** [comment]
Thanks a lot, looks very nice!
