### ISSUE TITLE
Add the application icon for Visual Studio

### ISSUE THREAD

**Issue by cawa-93** [numixproject/numix-icon-theme-circle#17]
Now the application icon for Visual Studio is no different from the usual icons editor. It is not comfortable.
![image](https://cloud.githubusercontent.com/assets/1662812/19418672/4df7485c-93d1-11e6-96d9-135735b793fb.png)

**Comment by palob** [comment]
It was decided that ``code`` is too generic for an icon name.
See discussions here https://github.com/numixproject/numix-core/issues/2964 and https://github.com/numixproject/numix-core/issues/3370.

The thing is that ``code`` is close to an action/status/mimetype icon name. We already face the issue of Numix Cirlce app icons showing up in place of action icons, for instance ``lighttable`` in Darktable and ``timeline`` in Kdenlive.
