### ISSUE TITLE
Icon for 7zip

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1716]
At this moment there are symlinks into Numix-Circles:
7z.svg > file-roller.svg
7zip.svg > file-roller.svg

But due to APP names they will be put so close in dash:
![image](https://cloud.githubusercontent.com/assets/11244067/6653651/2c0ff450-ca79-11e4-892c-442f1ae245bd.png)

Just an idea: use file-roller.svg icon and just change circle gradient.
![image](https://cloud.githubusercontent.com/assets/11244067/6653662/743010f8-ca79-11e4-984f-4612ac897de4.png)
 
Here it's the original logo from 7zip:
![image](https://cloud.githubusercontent.com/assets/11244067/6653670/b3cf985a-ca79-11e4-8eb4-a470db99b37a.png)

**Comment by hlechner** [comment]
This kind of request is useful or should I avoid it?

**Comment by ChuckDaniels87** [comment]
I think that could be a good idea document all file-roller symlinks. After that, it can be created for each compressed file type an icon based on the existing one (maybe with labels).

**Comment by Foggalong** [comment]
@hlechner  You can request enhancements to existing app icons if you so wish, but requests for new icons will take priority. Do you want to keep this open?

@ChuckDaniels87 these are different archive clients rather than file types, it just has a silly name.

**Comment by ChuckDaniels87** [comment]
@Foggalong you are right, I suppose that we need to work with the mimetypes to get my idea working.

**Comment by hlechner** [comment]
@Foggalong It doesn't need to be done now or even in this year :P

My idea is just to document useful stuffs for who is making the icons, so some day they can start to work based on issues reported. Just to make everything easier for the project.

But no priority is needed anyway. If you want to keep it open its ok, if you want to close it, its ok also.

**Comment by Foggalong** [comment]
By pure coincidence Georgi had been working on an enhancement for file roller so I thought I'd kill 2 birds with one stone :)
