### ISSUE TITLE
War thunder (Steam)

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1723]
I would like to request an icon for this awesome game <3

the icon line : Icon=steam_icon_236390
![warthunder_icon](https://cloud.githubusercontent.com/assets/7660997/6657939/fd0cfda6-cb59-11e4-9ec2-b293c796a0d0.png)

**Comment by Ghokun** [comment]
There is a nice svg here : http://erratic-fox.deviantart.com/art/War-Thunder-Vector-SVG-423283159

May be used as a template.
