### ISSUE TITLE
Icon for netbeans

### ISSUE THREAD

**Issue by wizath** [numixproject/numix-icon-theme-circle#1774]
Icon for netbeans is not set after the installation

[Desktop Entry]
Encoding=UTF-8
Name=NetBeans IDE 8.0.2
Comment=The Smarter Way to Code
Exec=/bin/sh "/usr/local/netbeans-8.0.2/bin/netbeans"
Icon=/usr/local/netbeans-8.0.2/nb/netbeans.png
Categories=Application;Development;Java;IDE
Version=1.0
Type=Application
Terminal=0

![zrzut ekranu z 2015-03-22 15 03 23](https://cloud.githubusercontent.com/assets/11598020/6769629/c9d77fa6-d0a4-11e4-8062-5ab93ce37824.png)

**Comment by Foggalong** [comment]
We [already have](https://github.com/numixproject/numix-icon-theme-circle/issues?q=is%3Aissue++netbeans+) one :) see the readme section on hardcoded icons for more info
