### ISSUE TITLE
Icons for Forged Alliance and Forged Alliance Forever

### ISSUE THREAD

**Issue by SM83** [numixproject/numix-icon-theme-circle#1776]
Numix is missing icons for Supreme Commander: Forged Alliance and Forged Alliance Forever - they're the only unthemed programs I run!

There are no default desktop files to my knowledge, as the programs run through wine. I'll post the custom ones I use if needed :).

SC: Forged Alliance
![forgedalliance](https://cloud.githubusercontent.com/assets/11599280/6770736/1301cede-d0a0-11e4-8c46-551bcb9be90b.png)

Forged Alliance Forever
![window_icon](https://cloud.githubusercontent.com/assets/11599280/6770716/7920e35e-d09f-11e4-9e21-fafb9c94cbad.png)

**Comment by Foggalong** [comment]
Same was with LoL [here](https://github.com/numixproject/numix-icon-theme-circle/issues/1086) we only do WINE stuff if it's a popular request. Get 5 "+1"s and we'll switch it to a request.

**Comment by EagleDelta2** [comment]
+1

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/7054795/59e59ff6-de15-11e4-8d9d-3defabd3e758.png)

**Comment by Foggalong** [comment]
Nice! If you fancy knocking something together for an FAF icon that'd be good for a pull request :)

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/7055284/c30fcdb4-de18-11e4-96be-c1d44092e813.png)

**Comment by hlechner** [comment]
SCForgedAlliance.svg and ForgedAllianceForever.svg ?

**Comment by Foggalong** [comment]
Yeah, that'd be great! :D

**Comment by Anaeijon** [comment]
Dear Joshua Fogg,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] Icons for Forged Alliance and Forged"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
