### ISSUE TITLE
Tray Icon for Clementine player

### ISSUE THREAD

**Issue by zeronote** [numixproject/numix-icon-theme-circle#1779]
It would be great if you could include a Clementine trayicon set, default one doesn't fit very well with others from numix-circle.
[Not sure that it can be useful] The icon line says: "application-x-clementine"
The original used by Ubuntu is attached.
![clementine-panel](https://cloud.githubusercontent.com/assets/597692/6792363/dc08cf5e-d1b7-11e4-8d2b-590d8f403ea6.png)
![clementine-panel-grey](https://cloud.githubusercontent.com/assets/597692/6792367/dee72676-d1b7-11e4-968f-4ba9c3a5f2a4.png)

**Comment by Foggalong** [comment]
This is an issue for the base theme rather than here :)
