### ISSUE TITLE
gtk-icons in Circles overwriting gtk-icons in Numix base theme

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1794]
Numix base icon theme:
![image](https://cloud.githubusercontent.com/assets/11244067/6882602/d371e280-d569-11e4-988a-c0ed19271430.png)

Numix icon Circle:
![image](https://cloud.githubusercontent.com/assets/11244067/6882605/f196ae44-d569-11e4-82e2-deca8ad9849b.png)

- gtk-about
- gtk-help
- gtk-preferences

It's a expected behavior or bug?

**Comment by bil-elmoussaoui** [comment]
This is related to the same bug #983
