### ISSUE TITLE
Icon for Builder

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-circle#1795]
Please make an icon for Gnome Builder; Builder is a new IDE for GNOME.
[Website](https://wiki.gnome.org/Apps/Builder)

Original icon:
![Builder](https://wiki.gnome.org/Apps/Builder?action=AttachFile&do=get&target=splash.png)

/usr/share/applications/org.gnome.Builder.desktop content:
Icon=builder

**Comment by handicraftsman** [comment]
#2677
