### ISSUE TITLE
Icon for DevAssistant

### ISSUE THREAD

**Issue by JulienRbt** [numixproject/numix-icon-theme-circle#1797]
Please for an icon for DevAssisant, it is an assisant for dev :smiley: 
[Website](http://devassistant.org/)

Original icon:
![DevAssisant](http://devassistant.org/landing_page/da-logo.png)

/usr/share/applications/devassistant.desktop content:
Icon=devassistant

**Comment by palob** [comment]
Already present in Numix-Circle master.

**Comment by Foggalong** [comment]
Duplicate of #1271. See [here](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/devassistant.svg) for the icon :)
