### ISSUE TITLE
Icon for Characters

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-circle#1798]
Hi, there are a new Gnome apps, Gnome Characters, I think that be cool if Numix add an icon for this :) (or use the same icon than for Gnome Characters Maps or Font Viewer :smile: )

So /usr/share/applications/org.gnome.Characters.desktop content:
Icon=gnome-characters

**Comment by palob** [comment]
Made these first drafts but they don't scale exceptionally well. Maybe just one symbol?
![characters1](https://cloud.githubusercontent.com/assets/7050624/7009720/8b85a6a2-dc9c-11e4-9441-9afb40b1485f.png)
![characters3](https://cloud.githubusercontent.com/assets/7050624/7009724/8f3252be-dc9c-11e4-9528-c5fcd79b9063.png)

**Comment by Foggalong** [comment]
What is the difference between GNOME Characters and GNOME Character map?

**Comment by palob** [comment]
As far as I can see the purpose is pretty musch the same. Just that Characters is the "official" GNOME app.
I think it's the same kind of redundance as with Shotwell / GNOME Photos, California / GNOME Calendar, Geary / Evolution ....

**Comment by Foggalong** [comment]
Oh right, I didn't realise GNOME Character map wasn't an official software thing. We'll probably keep the icon just as a symlink for this because we like to keep core settings icons standardised across different DEs.

**Comment by palob** [comment]
Speaking of which, *gnome-character-map.svg* should be pointing to *gucharmap.svg*. It's the same application.
+the icon would be different from the GNOME Font Viewer one.

**Comment by palob** [comment]
Just for reference, this is what the original icon looks like:
![gnome-characters](https://cloud.githubusercontent.com/assets/7050624/7074693/b61867ee-defc-11e4-86f6-b5b6ef64309c.png)

**Comment by Anaeijon** [comment]
Dear palob,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] Icon for Characters (#1798)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
