### ISSUE TITLE
Language indicator showing icon instead language

### ISSUE THREAD

**Issue by jacoborus** [numixproject/numix-icon-theme-circle#18]
I noticed numix icon theme shows the actual language code in the language indicator of the top panel, but numix circle just shows an icon with a keyboard.

Numix circle:
![selection_086](https://cloud.githubusercontent.com/assets/829859/19604409/6e02eca4-97b5-11e6-8d3e-36089ab2e4fb.png)

Numix:
![selection_087](https://cloud.githubusercontent.com/assets/829859/19604433/8853b2be-97b5-11e6-9f2e-833020d43bc4.png)

I don't know if that is a feature or a bug, but I rather see the actual language code in the panel

**Comment by Foggalong** [comment]
This is definitely a bug, but needs reporting [here](https://github.com/numixproject/numix-core). This repo is just for issues with the Linux packaging.

**Comment by jacoborus** [comment]
Done
