### ISSUE TITLE
Icon for Books

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-circle#1800]
Please make an icon for Gnome Books, it is an e-book manager application for GNOME
[Website](https://wiki.gnome.org/Apps/Books)

Original icon:
![Books](http://i.imgur.com/4UHlHDY.png)

/usr/share/applications/org.gnome.Books.desktop content:
#FIXME icon
Icon=gnome-books

**Comment by bil-elmoussaoui** [comment]
+1 for this ;)

**Comment by ChuckDaniels87** [comment]
I'd like to make new Gnome apps icons, I hope I find time to it soon.

**Comment by Foggalong** [comment]
For now just a symlink to our rather nice but underused kindle icon. Feel free to submit a unique on, @ChuckDaniels87 :)

**Comment by ChuckDaniels87** [comment]
I've seen that you symlinked Characters too, it is nice to have a temporal
icon. I'll do unique icons as soon as I can. :wink:

**Comment by Foggalong** [comment]
Yeah, there's no pressure time wise :)

**Comment by palob** [comment]
How about those (pretty much just slightly altered existing designs however)?
![gnome-books8b](https://cloud.githubusercontent.com/assets/7050624/7009102/3c217ec8-dc98-11e4-984d-a3e7546bb714.png)
![gnome-books7](https://cloud.githubusercontent.com/assets/7050624/7009112/450300e8-dc98-11e4-978e-af7534c6170f.png)
![gnome-books1](https://cloud.githubusercontent.com/assets/7050624/7009117/49485a9a-dc98-11e4-8107-13607246066d.png)
![gnome-books0c](https://cloud.githubusercontent.com/assets/7050624/7009122/4cd9bd8e-dc98-11e4-829a-e6e96db5edc0.png)

**Comment by ChuckDaniels87** [comment]
I like 1st and 2nd, 3rd one is nice with Gnome logo. Could you add that logo on the 1st or 2nd one someway?

**Comment by Foggalong** [comment]
Agree with @ChuckDaniels87, the 1st and 3rd are lovely but some way to combine them. Maybe the GNOME logo on the page as part of a "picture"?

**Comment by palob** [comment]
Like this?
![gnome-books8c](https://cloud.githubusercontent.com/assets/7050624/7009817/3e1bfece-dc9d-11e4-8198-33e24fcb87fb.png)
The GNOME foot isn't really distinguishable below like 96px.

**Comment by Foggalong** [comment]
Ah, yeah that was my idea but I imagine as you say it won't scale very well. Of the 4 though, I do like that the best and the GNOME logo can always be a little easter egg I guess

**Comment by palob** [comment]
Yeah it looks a bit more interesting with the image block anyway.
By the way, the 2nd design looks a bit busy with the logo imo:
![gnome-books7d](https://cloud.githubusercontent.com/assets/7050624/7009981/88713b46-dc9e-11e4-824d-e5e3b63fe00a.png)

**Comment by ChuckDaniels87** [comment]
I was thinking on something like the last one but the previous with a
little easter egg is really cool.

**Comment by palob** [comment]
Going with it?

**Comment by Foggalong** [comment]
Aye :)
