### ISSUE TITLE
Icon for Civilization: Beyond Earth (Steam)

### ISSUE THREAD

**Issue by Plasmodium1** [numixproject/numix-icon-theme-circle#1803]
Game: Sid Meier's Civilization: Beyond Earth
AppID: 65980
Icon:
![441-civbe-icon-1024](https://cloud.githubusercontent.com/assets/11717287/6894711/5d5532b0-d6d0-11e4-8a07-57a6e185661d.png)

Notes: Strategy game similar to Civ V but in space.

**Comment by ChuckDaniels87** [comment]
Try to download the image to your PC and upload it here. :wink:

**Comment by Plasmodium1** [comment]
D'oh, of course. :-) Changed.

**Comment by ChuckDaniels87** [comment]
Thanks!
