### ISSUE TITLE
Bug: VLC satus uses Numix-Circles instead of Numix

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1808]
In Gnome-shell the idea of status icon is different from most of you think from unity, gnome 2, xfce, kde, etc.

The status icon can be added in bottom bar. However the dimensions are pretty different of 22px.

So the VLC probably uses the *vlc.svg* in scalable to form a strange size icon (something like 22x48):
![image](https://cloud.githubusercontent.com/assets/11244067/6896185/0b4df382-d6bf-11e4-81a2-718ba58e1baa.png)

When Just uses the Numix instead of Numix-Circle:
![image](https://cloud.githubusercontent.com/assets/11244067/6896234/91178352-d6bf-11e4-9357-83ada9d28793.png)

Here Adwaita:
![image](https://cloud.githubusercontent.com/assets/11244067/6896272/fc459a2e-d6bf-11e4-9499-2eca1f129a72.png)

**Comment by hlechner** [comment]
Could someone who uses gnome-shell try it if face this bug too?

**Comment by Foggalong** [comment]
[See here](https://github.com/numixproject/numix-icon-theme/issues/190)
