### ISSUE TITLE
Icon for  ScudCloud

### ISSUE THREAD

**Issue by cdysthe** [numixproject/numix-icon-theme-circle#1810]
Hi, 

Please add icon for ScudCloud.

ScudCloud: Icon=/opt/scudcloud/resources/scudcloud.png

**Comment by Ghokun** [comment]
I will try my chance at vivaldi.

**Comment by palob** [comment]
Vivaldi was already done by @ChuckDaniels87 .

**Comment by cdysthe** [comment]
I do not see a Numix Vivaldi icon, but maybe it's not updated yet?

**Comment by Foggalong** [comment]
Always [check the git](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/vivaldi.svg) rather than the PPA. We've kept it from updating for now while we sort out some status icon problems :)

**Comment by cdysthe** [comment]
Thanks! I'm an ignorant user, but I think I can find my way around the git. :)

**Comment by Ghokun** [comment]
I am starting to enjoy inkscape

![scudcloud1](https://cloud.githubusercontent.com/assets/3802058/6905814/47f0e942-d733-11e4-9363-3295ddc2b73e.png)

**Comment by Foggalong** [comment]
Ooo, nice! :D

**Comment by bil-elmoussaoui** [comment]
@Ghokun great design!

**Comment by cdysthe** [comment]
Very nice indeed! Git and go! :)

**Comment by ChuckDaniels87** [comment]
Nice one @Ghokun!
