### ISSUE TITLE
Icon for Mint Installer

### ISSUE THREAD

**Issue by SkiFire13** [numixproject/numix-icon-theme-circle#1813]
A numix-circle icon for Mint Installer is missing.
The icon line says "/usr/lib/linuxmint/mintInstall/icon.svg" and the original icon is attached.
![screenshot at 31-03-15 15-36-49](https://cloud.githubusercontent.com/assets/9020423/6919982/c36e1260-d7bb-11e4-955e-b82e1b684a5d.png)

**Comment by Foggalong** [comment]
Because this is hardcoded and appears before installation it can't be fixed other than by the upstream Mint developers. Please report it to them!
