### ISSUE TITLE
Icon for Selektor please

### ISSUE THREAD

**Issue by maxdraki** [numixproject/numix-icon-theme-circle#1815]
Could we have an icon for Selektor please
Icon=/usr/share/icons/selektoricon.png

![image](https://cloud.githubusercontent.com/assets/3703338/6935923/3a868e4e-d844-11e4-8959-59419a02aa7e.png)
http://www.dazzleships.net/?page_id=71

**Comment by palob** [comment]
@maxdraki What is the launcher (.desktop) filename?

**Comment by maxdraki** [comment]
selekTOR.desktop
![image](https://cloud.githubusercontent.com/assets/3703338/6988036/396b7346-da45-11e4-8d10-7e1726aaed7a.png)

contents are:
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Categories=Network;Application;
Name=SelekTOR
Comment=Tor Exit Node Selection and Proxying
Exec=/usr/bin/selektor
Icon=/usr/share/icons/selektoricon.png
StartupNotify=true
Terminal=false
Type=Application

**Comment by palob** [comment]
Thanks, added it to the hardcode-fixer script

**Comment by maxdraki** [comment]
thank you! :)

max@illis.uk <max@illis.co.uk>
07803 009 004
