### ISSUE TITLE
Icon for SuperTuxKart

### ISSUE THREAD

**Issue by vidrafeed** [numixproject/numix-icon-theme-circle#1822]
Nimix missing icon for SuperTuxKart
Icon=/usr/share/pixmaps/supertuxkart_128.png
![supertuxkart](https://cloud.githubusercontent.com/assets/8080711/6948267/f3b9ad98-d8ac-11e4-8168-bd56628462cb.png)

**Comment by palob** [comment]
It's there, just run the hardcode fixer. You can find the link on the front page.

**Comment by vidrafeed** [comment]
https://github.com/Foggalong/hardcode-fixer
XD Thank you
