### ISSUE TITLE
Icon for Xfce drive removable media

### ISSUE THREAD

**Issue by vidrafeed** [numixproject/numix-icon-theme-circle#1823]
Numix missing icon for driver removable media in XFCE
Icon=drive-removable-media
![schermata del 2015-04-01 20 29 50](https://cloud.githubusercontent.com/assets/8080711/6948400/e3dba0ba-d8ad-11e4-9db6-1828d270cb68.png)
 Thank you :)

**Comment by palob** [comment]
This is an Numix icon actually. But from the base theme. It isn't an app, is it?

**Comment by Foggalong** [comment]
Yeah, this is a silly program which is using a system icon rather than an unique app icons. Can't fix :(
