### ISSUE TITLE
Icon for rdio.com chrome web shortcut

### ISSUE THREAD

**Issue by edgard** [numixproject/numix-icon-theme-circle#1824]
Please? :)

http://www.rdio.com/

The current Numix Android icon seems to be within the guidelines, so maybe it's just the matter of copying here?

https://github.com/numixproject/com.numix.icons_circle/blob/master/Icons/com_rdio_oi_android_ui.svg

**Comment by Foggalong** [comment]
@edgard what's the icon line for the Linux version?

**Comment by edgard** [comment]
Icon=chrome-http___www.rdio.com_

I'm currently replacing sucessfully with a icon named: chrome-http___www.rdio.com_.svg

**Comment by Foggalong** [comment]
Thanks!

**Comment by edgard** [comment]
Awesome! :+1:

**Comment by Foggalong** [comment]
Not a problem!
