### ISSUE TITLE
 Wrong LibreOffice icon in Xfce panel 

### ISSUE THREAD

**Issue by danjjl** [numixproject/numix-icon-theme-circle#1825]
The Numix LibreOffice icons are not used by the "Windows Buttons" item in the Xfce panel.

![lo-24px_panel](https://cloud.githubusercontent.com/assets/747240/6963455/f6a0882c-d93f-11e4-9e52-e04e5a4c7be3.png)

Using:
- Xubuntu 14.04
- Xfce 4.12
- numix-icon-theme-circle 1.0.2+3~201502071451~ubuntu14.04.1

*Might be related to https://github.com/numixproject/numix-icon-theme-circle/issues/722*

**Comment by bil-elmoussaoui** [comment]
I believe this is not related to Numix icon theme

**Comment by danjjl** [comment]
Closing because seems to affect all icon themes.
