### ISSUE TITLE
Oracle Sql Developer icon enhancement

### ISSUE THREAD

**Issue by Ghokun** [numixproject/numix-icon-theme-circle#1826]
Old icon does not look good when scaled down and the green arrow is not recognizable.

I used "sqlitebrowser.svg" for a little enhancement

(I use sql developer daily, wanted to change it)

Also as of version 4 they have changed icon in their website: http://www.oracle.com/technetwork/developer-tools/sql-developer/sqldev-101614-2340766.jpg

Old one:
![2_oracle-sqldeveloper](https://cloud.githubusercontent.com/assets/3802058/6964581/40c3aa02-d953-11e4-96f0-dd38a973169a.png)

Some tries:
![oracle-sqldeveloper2](https://cloud.githubusercontent.com/assets/3802058/6964569/27b6d520-d953-11e4-8bda-a5c14748aeab.png)
![oracle-sqldeveloper](https://cloud.githubusercontent.com/assets/3802058/6964570/2abd7c42-d953-11e4-9f1e-b10e02f9d627.png)

**Comment by Foggalong** [comment]
Feel free to submit the one with the black background as a pull request :)
