### ISSUE TITLE
Firefox launch application, icons are low resolution

### ISSUE THREAD

**Issue by raidermax** [numixproject/numix-icon-theme-circle#1827]
--Very Minor--

I am not entirely sure if this is Numix or Firefox's icons but I have the numix-icon-theme-circle being used and whenever I click on e-mail addresses the Firefox GUI comes up and it has two links for Gmail and Yahoo Mail, both of which have low resolution and blurry images. 

Reference Image: http://gyazo.com/808f968c5139183d5a7b4d404403005d

**Comment by Foggalong** [comment]
Yeah, that's a problem with Thunderbird rather than Numix Circle I think. If they can be themed though, the icons should go in Numix base too
