### ISSUE TITLE
Icon for ACE Player HD

### ISSUE THREAD

**Issue by matteosecli** [numixproject/numix-icon-theme-circle#1831]
Hello, I'm writing to report a missing icon for "[ACE Player HD](https://bitbucket.org/AceStream/acestreamplayer/)", a modified version of VLC.
The icon line says "Icon=acestreamplayer"; I've attached the original icon.
It would also be nice to have a replacement for the icon "acestreamplayer-xmas"; it looks the same as "acestreamplayer", so I'm not attaching that one also.
Thank you very much! :)
![acestreamplayer](https://cloud.githubusercontent.com/assets/4618521/6982609/3a4ce2da-da14-11e4-9eda-552caae09e0a.png)

**Comment by Foggalong** [comment]
Out of curiosity, what do they add to VLC?

**Comment by matteosecli** [comment]
They just add BitTorrent support, so that you can play torrents or torrent-based live streams via their "acestream" protocol.
Btw, thank you for the light-speed fix! :)

**Comment by Foggalong** [comment]
Not a problem!
