### ISSUE TITLE
Icon for OpenMW Content Editor

### ISSUE THREAD

**Issue by Taknamay** [numixproject/numix-icon-theme-circle#1833]
Note, that this request is not the same as OpenMW.

Name=OpenMW Content Editor
Icon=openmw-cs

![openmw-cs](https://cloud.githubusercontent.com/assets/6655349/6983688/d7488ae2-d9ee-11e4-9879-a88c8a5ec297.png)

**Comment by wa4557** [comment]
#957 Got fixed just now
