### ISSUE TITLE
Icon for OpenTyrian

### ISSUE THREAD

**Issue by Taknamay** [numixproject/numix-icon-theme-circle#1834]
Name=OpenTyrian
Icon=opentyrian

![tyrian-128](https://cloud.githubusercontent.com/assets/6655349/6983870/c0f3b148-d9f0-11e4-8d05-7d43ba86e475.png)

**Comment by Foggalong** [comment]
Fixed in ecdeec420fea480ee57b49b3721f6fc7f5b37fb2
