### ISSUE TITLE
KeepassX

### ISSUE THREAD

**Issue by sl-codenine** [numixproject/numix-icon-theme-circle#1852]
Icon for keepassx does not work in applications notification bar, it shows up the original one (in other places it works ok).

Fresh install: Ubuntu 14.10 / gnome 3.14 from gnome-team ppa

You can see what's the case on the screenshot.

![screenshot from 2015-04-04 23 00 10](https://cloud.githubusercontent.com/assets/6673789/6994593/79330734-db1f-11e4-91d5-553e331e4514.png)

**Comment by bil-elmoussaoui** [comment]
I dont think its a Numix bug, you might report this to keepassx devs

**Comment by sl-codenine** [comment]
Ok, thanks for quick reply. Closing this one.
