### ISSUE TITLE
Icon for BitBucket

### ISSUE THREAD

**Issue by sl-codenine** [numixproject/numix-icon-theme-circle#1853]
Icon=chrome-jbdlaalbpgnopkpnmoppmccbgkjhfmgh-Default

![master-logo-2562750429-5_avatar](https://cloud.githubusercontent.com/assets/5920259/6994894/b4eacb5c-db21-11e4-8e67-8db90b4bff87.png)

**Comment by bil-elmoussaoui** [comment]
The link of the application in the chrome store.

**Comment by sl-codenine** [comment]
Hmm, actually i've created it manually - using chrome settings button -> more tools - create application shortcut.

The one from chrome store opens just as a new tab in chrome, not as a standalone chrome instance.

Anyway here the link in any case, https://chrome.google.com/webstore/detail/bitbucket-shortcut/jbdlaalbpgnopkpnmoppmccbgkjhfmgh
