### ISSUE TITLE
Icon for Pushbullet indicator

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1854]
Hello, 
I would like to request a circle icon for pushbullet indicator.The icon is hardcoded and have been reported before here #1049 
the icon line is : Icon = /opt/extras.ubuntu.com/pushbullet-indicator/share/pushbullet-indicator/icons/pushbullet-indicator.svg
the desktop file is :  extras-pushbullet-indicator.desktop

![bcb0b2c8-1cb5-11e4-897b-b5fd651c5d21](https://cloud.githubusercontent.com/assets/7660997/6998307/8c4ef13a-dbdc-11e4-804b-30bdb51ee543.png)
(i took it from the old issue)
I hope this got be added!  And yes, this is not a tray icon but an application one.

**Comment by Foggalong** [comment]
I'll reopen the issue there :)
