### ISSUE TITLE
Icon for OCRFeeder

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1872]
Another character recognition GUI
https://wiki.gnome.org/Apps/OCRFeeder

Icon=ocrfeeder
![ocrfeeder](https://cloud.githubusercontent.com/assets/7050624/7033147/73851f38-dd78-11e4-935f-5ea57eaa0d87.png)

**Comment by hlechner** [comment]
BTW, nice job on gnome apps @palob
