### ISSUE TITLE
Icon for Doom 3

### ISSUE THREAD

**Issue by Eleuin** [numixproject/numix-icon-theme-circle#1880]
I know that chocolate doom has recently got some nice shiny new icons (which are in use on my system btw), but there is still one game in the doom series that i do run an awful lot and that is doom 3 which happens to be missing an icon (currently using steam_icon_4920), using the terminal command "doom3"

here is the current icon as supplied by id Software
![doom3](https://cloud.githubusercontent.com/assets/5553828/7039093/67bc42c8-dd8a-11e4-9a19-f5640df72210.png)

**Comment by Foggalong** [comment]
[4920](https://steamdb.info/app/4920/) is Natural Selection 2, Doom3 is [9050](https://steamdb.info/app/9050/
