### ISSUE TITLE
Icon for Quake 4

### ISSUE THREAD

**Issue by Eleuin** [numixproject/numix-icon-theme-circle#1889]
4th installment of the popular id Software series
icon = /usr/local/games/quake4/q4icon.bmp (even though i use the Quake 3 Arena one for now just for visual consistency, that is what is used by default)

icon as supplied by id Software (of note, the pink background is not actually used and is just removed anyways)
![q4icon](https://cloud.githubusercontent.com/assets/5553828/7046111/88932a4c-ddd1-11e4-8275-5015981b2e79.png)

**Comment by Foggalong** [comment]
Can you add the icon line as stated in the readme :)

**Comment by Eleuin** [comment]
updated :D
