### ISSUE TITLE
Icon for NVIDIA Visual Profiler [$5]

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1901]
Application: **NVIDIA Visual Profiler**
Category: **Nvidia Application for optimizing CUDA apps**
Icon: 
![image](https://cloud.githubusercontent.com/assets/11244067/6578559/a175a8f6-c723-11e4-8154-1fda40539c6c.png)
Note: **hardcoded fixed by hardcode-fixer:** https://github.com/Foggalong/hardcode-fixer/issues/69
Desktop File:
```
Icon=/opt/cuda/libnvvp/icon.xpm
```

Target icon:
```
Icon=nvvp
```

**Comment by ChuckDaniels87** [comment]
I was about to open this issue and the others. :yum: CUDA C++ programming +1

**Comment by Foggalong** [comment]
@ChuckDaniels87 you fancy taking a crack at this?

**Comment by ChuckDaniels87** [comment]
I'm a bit busy these days but I'll see what I can do. :wink:

**Comment by Foggalong** [comment]
I was a bit stumed as to what to do that's all, but that's fair enough :)

**Comment by RadicalRaccoon** [comment]
So what you want is a Numix Circle style icon for Nvidia Visual Profiler, right?
Here's what I have so far.
![selection_034](https://cloud.githubusercontent.com/assets/9145396/7673519/87ec1338-fcda-11e4-8eb8-2fe45310d094.png)

I wasn't sure what sort of direction I wanted to go with it, so I just adapted a few notable features of the original icon. I had originally added a grid, but I found it to be a little too busy. 
If you have any suggestions or anything, feel free to let me know.

In the meantime, I'll be working on another design; one that more closely resembles the original.

**Comment by ChuckDaniels87** [comment]
Nice idea, :+1:

**Comment by plumpudding** [comment]
@RadicalRaccoon can we get svgs for this?
looks quite nice
better than that original icon compared to all the other great numix icons

**Comment by Foggalong** [comment]
As a note, it's not close enough to the Numix design guidelines to be merged into the icon set

**Comment by MrTimscampi** [comment]
Trying to correct this one, here's my version of it, based off of @RadicalRaccoon's PNGs:
![nvpp](https://cloud.githubusercontent.com/assets/1087450/11133806/8738834a-8998-11e5-8724-9672f91037ab.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/nvvp.svg

**Comment by Foggalong** [comment]
If you want to submit it as a pull request for review feel free!
