### ISSUE TITLE
Icon for PrBoom+

### ISSUE THREAD

**Issue by Taknamay** [numixproject/numix-icon-theme-circle#1905]
Name=PrBoom+
Icon=prboom-plus

![prboom-plus](https://cloud.githubusercontent.com/assets/6655349/7057717/a2d89cac-de26-11e4-8433-5639d4c54e60.png)

**Comment by Anaeijon** [comment]
Dear Taknamay,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for PrBoom+ (#1905)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
