### ISSUE TITLE
Icon for Quake 2

### ISSUE THREAD

**Issue by Eleuin** [numixproject/numix-icon-theme-circle#1908]
yet another classic FPS from id Software
icon = quake2

icon as supplied by id Software, converted into PNG
![quake2](https://cloud.githubusercontent.com/assets/5553828/7058514/d2eb6fa0-de30-11e4-92d4-cdd2ea0b26b7.png)

**Comment by Anaeijon** [comment]
Dear Eleuin,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for Quake 2 (#1908)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
