### ISSUE TITLE
Icon for FreeRCT

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1909]
Game: **FreeRCT**
Webpage: https://github.com/FreeRCT/FreeRCT
Description: **FreeRCT aims to be a free and open source game which captures the look, feel and gameplay of the popular games RollerCoaster Tycoon 1 and 2**
Icon:
![image](https://cloud.githubusercontent.com/assets/11244067/7060650/9d8b703c-de5b-11e4-919b-b6f747e65a06.png)

freerct.desktop:
```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=FreeRCT
Name[es]=FreeRCT
Comment=FreeRCT aims to be a free and open source game which captures the look, feel and gameplay of the popular games RollerCoaster Tycoon 1 and 2.
Comment[es]=FreeRCT es el juego libre y open source que aptura la estética y la jugabilidad de los famosos juegos RollerCoaster Tycoon 1 y 2.
Exec=/opt/freerct/bin/freerct
Icon=freerct
Categories=StrategyGame;
Terminal=false
```

**Comment by Anaeijon** [comment]
Dear Henrique Lechner,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for FreeRCT (#1909)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
