### ISSUE TITLE
Icon for Machinarium

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1910]
Game: **Machinarium**
Website: http://machinarium.net/
Description: **A point-and-click logic adventure game by the creators of Samorost**
Icon:
![image](https://cloud.githubusercontent.com/assets/11244067/7060906/0800b504-de60-11e4-993c-d282ab6c4146.png)

machinarium.desktop:
```
[Desktop Entry]
Name=Machinarium
GenericName=A point-and-click adventure game by the creators of Samorost
Type=Application
Categories=Game;
Icon=machinarium
Exec=machinarium
Terminal=false
```

**Comment by Anaeijon** [comment]
Dear Henrique Lechner,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for Machinarium (#1910)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
