### ISSUE TITLE
Icon for Zen Bound 2 (Steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1911]
Game: **Zen Bound® 2**
Game App ID: [61600](https://steamdb.info/app/61600/)
Description: **Zen Bound 2 is a meditative puzzle game of wrapping rope around wooden sculptures.**
Icon:
![image](https://cloud.githubusercontent.com/assets/11244067/7061427/26a3273c-de68-11e4-87e6-07666a592f8a.png)

Zen Bound 2.desktop:
```
[Desktop Entry]
Name=Zen Bound® 2
Comment=Play this game on Steam
Exec=steam steam://rungameid/61600
Icon=steam_icon_61600
Terminal=false
Type=Application
Categories=Game;
```

**Comment by Anaeijon** [comment]
Dear Henrique Lechner,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for Zen Bound 2 (Steam) (#1911)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by Foggalong** [comment]
Wasn't fixed, got the number wrong :P
