### ISSUE TITLE
Icon for Cogs (Steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1913]
Game: **Cogs**
Game ID: [26500](https://steamdb.info/app/26500/)
Description: **A Steampunk Puzzle Game from Lazy 8 Studios**
Icon:
![image](https://cloud.githubusercontent.com/assets/11244067/7061654/32852cc8-de6b-11e4-8e6c-07ff8b12c3f0.png)

Cogs.desktop:
```
[Desktop Entry]
Name=Cogs
Comment=Play this game on Steam
Exec=steam steam://rungameid/26500
Icon=steam_icon_26500
Terminal=false
Type=Application
Categories=Game;
```

**Comment by Anaeijon** [comment]
Dear Henrique Lechner,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for Cogs (Steam) (#1913)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
