### ISSUE TITLE
Icon for Avadon: The Black Fortress (Steam)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme-circle#1914]
Game: **Avadon: The Black Fortress**
Game ID: [112100](https://steamdb.info/app/112100/)
Description: **Epic, Indie fantasy role-playing saga.**
Icon:
![image](https://cloud.githubusercontent.com/assets/11244067/7061788/84b30834-de6c-11e4-9674-f73f53e46fa5.png)

Avadon The Black Fortress.desktop:
```
[Desktop Entry]
Name=Avadon: The Black Fortress
Comment=Play this game on Steam
Exec=steam steam://rungameid/112100
Icon=steam_icon_112100
Terminal=false
Type=Application
Categories=Game;
```

**Comment by Anaeijon** [comment]
Dear Henrique Lechner,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for Avadon: The Black Fortress (Steam)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
