### ISSUE TITLE
Icon for atlas maps

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#1915]
Hello! 
Atlas maps is a new application designed for elementary..
the icon line is Icon=atlas
the original icon is : 
![infobulle_001](https://cloud.githubusercontent.com/assets/7660997/7064629/89f56b18-deb0-11e4-96b8-e97de4c4fd18.png)
the icon might be symlinked to maps or gnome-maps.

Thank you!

**Comment by Anaeijon** [comment]
Dear Bilal Elmoussaoui,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for atlas maps (#1915)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by bil-elmoussaoui** [comment]
Just stop spamming all the issues here please!

**Comment by Anaeijon** [comment]
Dear Bilal Elmoussaoui,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] Icon for atlas maps (#1915)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by Foggalong** [comment]
@bil-elmoussaoui I've reported @Anaeijon to the GitHub team to hopefull they can deal with this :)

**Comment by Anaeijon** [comment]
Dear Joshua Fogg,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] Icon for atlas maps (#1915)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by hlechner** [comment]
Until it take some effect, I suggest you @Foggalong to block this user:
https://help.github.com/articles/blocking-a-user/

```
In repositories you own, blocked users cannot:

  Open issues
  Fork the repository
  Send pull requests
  Comment on issues and pull requests
  Add or edit wiki pages
```

So it should solve this problem with this spammer

**Comment by Anaeijon** [comment]
Dear Henrique Lechner,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] Icon for atlas maps (#1915)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by Foggalong** [comment]
Nobody owns the Numix Project repositories though, they're part of an 
organisation. And afaik organisations can't block people :(
