### ISSUE TITLE
Icon for Alleyoop

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1916]
A Valgrind(memory error detector) GUI
http://alleyoop.sourceforge.net/

Icon=alleyoop
![alleyoop](https://cloud.githubusercontent.com/assets/7050624/7074337/f9c73c16-def9-11e4-8a79-2ac436687903.png)

**Comment by Anaeijon** [comment]
Dear Joshua Fogg,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] Icon for Alleyoop (#1916)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by Anaeijon** [comment]
Dear palob,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon for Alleyoop (#1916)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
