### ISSUE TITLE
A few KDE app icons

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1918]
+ Kajongg - game
https://www.kde.org/applications/games/kajongg/

Icon=kajongg
![kajongg](https://cloud.githubusercontent.com/assets/7050624/7074501/4db793c4-defb-11e4-911c-99c39b521f57.png)

+ KNemo - network monitor
https://www.kde.org/applications/internet/knemo/

Icon=knemo
![knemo_48](https://cloud.githubusercontent.com/assets/7050624/7074405/83a66470-defa-11e4-85e4-45fda3dca9fa.png)

+ KJots - notes
https://www.kde.org/applications/utilities/kjots/

Icon=kjots
![kjots](https://cloud.githubusercontent.com/assets/7050624/7074447/d269fbe4-defa-11e4-9186-13be39cd8b8e.png)

+ KDbg - GDB debugging GUI
http://www.kdbg.org/

Icon=kdbg
![kdbg](https://cloud.githubusercontent.com/assets/7050624/7074473/0886516e-defb-11e4-8865-7fc9218203e8.png)

**Comment by Anaeijon** [comment]
Dear Joshua Fogg,

The email sent to david@d-doering.tk with subject
"Re: [numix-icon-theme-circle] A few KDE app icons (#1918)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by Anaeijon** [comment]
Dear palob,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] A few KDE app icons (#1918)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
