### ISSUE TITLE
Icon request: Devdocs

### ISSUE THREAD

**Issue by varemenos** [numixproject/numix-icon-theme-circle#1920]
It's a chrome extension: https://chrome.google.com/webstore/detail/devdocs/mnfehgbmkapmjnhcnbodoamcioleeooe

Thanks in advance

**Comment by Anaeijon** [comment]
Dear Adonis K.,

The email sent to david@d-doering.tk with subject
"[numix-icon-theme-circle] Icon request: Devdocs (#1920)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to david@d-doering.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
