### ISSUE TITLE
Icon for QQ International

### ISSUE THREAD

**Issue by Kat1031** [numixproject/numix-icon-theme-circle#1925]
**QQ International** is a chat application

Icon=qqintl

![selection_001](https://cloud.githubusercontent.com/assets/8394389/7089796/f176ccde-dfd0-11e4-863f-3608bd4769f5.png)

**Comment by Foggalong** [comment]
We won't fix the Mint icon because it's hardcoded, and being part of the installer there's no easy way to fix it on our end. Please contact the mint devs about this :)

**Comment by Kat1031** [comment]
Okay, just the first one :)
