### ISSUE TITLE
xmgrace icons

### ISSUE THREAD

**Issue by rudrab** [numixproject/numix-icon-theme-circle#1929]
Grace (or xmgrace) is a very popular software among scientific communities, it will be nice if you theme the icon.

```
[Desktop Entry]
Encoding=UTF-8
Name=Grace
Comment=Numerical Data Processing and Visualization Tool
Exec=xmgrace
Icon=grace
Terminal=false
Type=Application
Categories=Graphics;
X-Desktop-File-Install-Version=0.22
```

[This](http://plasma-gate.weizmann.ac.il/Grace/) is the website.
From the default adwaita icon, I tried [this](https://drive.google.com/file/d/0B02WblgE6NEvamhtbDRsckZXRFU/view?usp=sharing)

**Comment by palob** [comment]
Hi, could you please add the information outlined in the video tutorial (icon line of the launcher file)?

Your draft doesn't fit the [guidelines](https://github.com/numixproject/numix-wiki/wiki/Guidelines) unfortunately.

**Comment by rudrab** [comment]
[Desktop Entry]
Encoding=UTF-8
Name=Grace
Comment=Numerical Data Processing and Visualization Tool
Exec=xmgrace
Icon=grace
Terminal=false
Type=Application
Categories=Graphics;
X-Desktop-File-Install-Version=0.22

is the Desktop entry.

**Comment by rudrab** [comment]
Hi, Thanks for the update. I have updated my git. The grace icon is in the application view, but once opened, not on the app-switcher/favourites view, as shown in the screenshot:
https://drive.google.com/file/d/0B02WblgE6NEvbGdxUE1QSlg2QjA/view?usp=sharing

**Comment by Foggalong** [comment]
Does that happen with any other themes or without a theme?
