### ISSUE TITLE
MintInstall missing icons.

### ISSUE THREAD

**Issue by spelufo** [numixproject/numix-icon-theme-circle#1930]
![mintinstall-numix-circle](https://cloud.githubusercontent.com/assets/1312203/7101511/3d7c0218-e033-11e4-82dc-23f3f1934fe2.png)

I don't know why, but mintinstall is not taking some of numix-circle icons. I think this might be fixed with some symlinking, since most of the categories can be replaced with existing icons. The needed icons are named `applications-*`, as can be seen [here](https://github.com/linuxmint/mintinstall/blob/6ffef49e98ca8aa27f8227b14a492476ea700bbe/usr/lib/linuxmint/mintInstall/mintinstall.py#L1117-L1183). I tried [this](https://github.com/numixproject/numix-icon-theme-circle/pull/1678) but it didn't work. I guess they have to be in "categories" subdirectories. Regular Numix has most of them: try `find /usr/share/icons/Numix/ -name 'applications-*.svg' | cut -d '/' -f 6-`.

Also, how can I clone the repo and install my local version of it with apt, do I have to package it? How do you do it?

**Comment by Kat1031** [comment]
What's your window borders and desktop theme? Looks good.

**Comment by Foggalong** [comment]
Are you running the latest version of the theme from git?

**Comment by bil-elmoussaoui** [comment]
If you want to update the icons to the last update you can use this : 

  ```bash
git clone https://github.com/numixproject/numix-icon-theme.git
git clone https://github.com/numixproject/numix-icon-theme-circle.git

cp -r ~/numix-icon-theme/Numix /usr/share/icons/
cp -r ~/numix-icon-theme/Numix-Light /usr/share/icons/
cp -r ~/numix-icon-theme-circle/Numix-Circle /usr/share/icons/
cp -r ~/numix-icon-theme-circle/Numix-Circle-Light /usr/share/icons/

gtk-update-icon-cache /usr/share/icons/Numix-Circle/
gtk-update-icon-cache /usr/share/icons/Numix-Circle-Light/
  ```
To avoid issues , as the monochrome icons are moved to the base theme. You better remove the old version you use using this 
  ```bash
rm -rf /usr/share/icons/Numix-Circle/
rm -rf /usr/share/icons/Numix-Circle-Light/
rm -rf /usr/share/icons/Numix/
rm -rf /usr/share/icons/Numix-Light/
  ```
You need to to this using the root permissions.

**Comment by palob** [comment]
It is at least a revision where #1678 is already applied.

**Comment by spelufo** [comment]
@Kat1031 It's all Numix.

![theme](https://cloud.githubusercontent.com/assets/1312203/7108289/1797548c-e158-11e4-8249-2705202f1b8f.png)

**Comment by Kat1031** [comment]
@spelufo Thanks.

**Comment by palob** [comment]
@Foggalong Just in case you closed this because you mistook my comment as duplicate report:
I didn't link to a duplicate issue :)

**Comment by Foggalong** [comment]
My bad :P

**Comment by dkotel** [comment]
bil-elmoussaoui Your method does not work for me. When I run the 2 commands to update the gtk icon cache I get the following errors:

`gtk-update-icon-cache: Failed to open file /usr/share/icons/Numix-Circle/.icon-theme.cache : File exists`
`gtk-update-icon-cache: Failed to open file /usr/share/icons/Numix-Circle-Light/.icon-theme.cache : File exists`

**Comment by Foggalong** [comment]
@dkotel If you're trying to do it onto an existing Numix installation rather than removing as suggested you need to use `gtk-update-icon-cache -f $YOURTHEME` to force the cache to be updated

**Comment by dkotel** [comment]
@Foggalong Sorry I was looking at the directions in the order they were listed. I didn't run the rm commands because I was thinking "why would I want to remove what I just created?". Thanks for setting me straight, though it doesn't solve the missing icons issue.

**Comment by Foggalong** [comment]
Not a problem! Even though it didn't work, st least we know to look elsewhere for an answer :)

Have you used any other icin themes that don't have this problem?

**Comment by dkotel** [comment]
Honestly I don't even remember having this problem with numix prior to today. Then again I haven't booted in to Mint in awhile either. I'm can say with 90% certainty that this was not a problem with ubuntu, which I ran for a long time.

**Comment by bil-elmoussaoui** [comment]
@dkotel i would like to take a look at this. Can you please tell me which version of Mint you're using?

**Comment by dkotel** [comment]
I am using Mint 17.1 Rebecca running Cinnamon 2.4.8

**Comment by bil-elmoussaoui** [comment]
Thos are the icons used in Mintinstall 
```
applications-internet
applications-multimedia
applications-graphics
applications-office
applications-games
applications-utilities
applications-system
applications-fonts
applications-science
applications-development
applications-other
``` 
Some of the icons are in Numix-Circle and those are missed 
```
applications-games
applications-utilities
```
All the icons do exists in Numix-Base/categories. Can you try using an other icon theme or using Numix base instead of Numix-Circle?

**Comment by wa4557** [comment]
So here once again, removing those icons from circle would solve this issue :)

**Comment by bil-elmoussaoui** [comment]
@wa4557 did those icons exists in Base? if so, i will create a PR and waits if @Foggalong  will merge it or not

**Comment by wa4557** [comment]
Yeah all of them exist in base, go ahead I think this is the proper approach to this problem
