### ISSUE TITLE
Icon for PopcornTime

### ISSUE THREAD

**Issue by lucagto** [numixproject/numix-icon-theme-circle#1952]
A numix-circle icon for PopcornTime is missing.

**Comment by bil-elmoussaoui** [comment]
Please watch this and update your last requests : https://plus.google.com/+NumixProjectOrg/posts/DkRmhFZuWez

**Comment by Foggalong** [comment]
We also do have an icon, so unless it's a symlinking that's needed we're all good :) ![screenshot_2015-04-12_19-58-28](https://cloud.githubusercontent.com/assets/5920259/7107037/4c25f0aa-e14e-11e4-83d8-c0836becd2dd.png)
