### ISSUE TITLE
Icon for Koala

### ISSUE THREAD

**Issue by Fwagra** [numixproject/numix-icon-theme-circle#1956]
Hi! Could you make an icon for Koala, a gui application for less, sass and compass?
Here is the icon line : 
*Icon=koala*
The original icon
![nw](https://cloud.githubusercontent.com/assets/3933375/7135067/5f916740-e2a3-11e4-83ec-74a9e4095812.png)

Thank you!

**Comment by bil-elmoussaoui** [comment]
Duplicate of #1492 #1565 and already fixed! You can use the github version if you want to use it

**Comment by Fwagra** [comment]
Indeed, sorry!
