### ISSUE TITLE
Icon for GTK3 icon browser

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1971]
"An application that shows themed icons"
https://blogs.gnome.org/mclasen/2014/06/24/whats-that-icon/

Icon=gtk3-icon-browser

Comes without icon (at least I can't find one)

Any design ideas?

**Comment by Foggalong** [comment]
An icons for icons :/ @me4oslav?

**Comment by wa4557** [comment]
Why not the numix Logo? Seems appropriate
