### ISSUE TITLE
Icon for Gallery app

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#1989]
New Unity8 photo management app

Icon=gallery-app
![gallery-app](https://cloud.githubusercontent.com/assets/7050624/7207902/128748b0-e53d-11e4-8ecf-bbf20b3ff53a.png)

**Comment by palob** [comment]
Which icon to symlink to?
``accessories-image-viewer.svg``(``eog.svg``), ``fotowall.svg``, ``gnome-photos.svg``, ``gpicview.svg``, ``gthumb.svg``,  ``kuickshow.svg`` or ``ristretto.svg`` ?

**Comment by Foggalong** [comment]
`accessories-image-viewer.svg` :)
