### ISSUE TITLE
KDE breakage

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2016]
Despite having done a few KDE icons lately I have never actually used KDE as my DE.

Yesterday I tried Numix Circle on *Kubuntu 15.04* and *Fedora 21 KDE* live isos and in addition to a few missing icons in the base theme a lot of Numix Circle icons appear broken all over the place (Menu, Dolphin, Gwenview, Muon Discover...).

It's not the breakage encountered on Github or in web browsers but looks like this:
![breakage](https://cloud.githubusercontent.com/assets/7050624/7252079/bc7cfe86-e831-11e4-94b7-28e66aea420b.png)

So the issue is about paths exceeding the baseplate, recoloured objects showing the colour set previously and recoloured baseplates being transparent. The latter two might be somehow related two our dreaded Inkscape gradient bug.

It looks the same with other Qt-based viewers (like Nomacs).
The issue is due to KDE/Qt using a different SVG rendering backend system (Qt SVG instead of librsvg).

[According to this](https://forum.kde.org/viewtopic.php?f=19&t=121637) the KDE bugtrackers are full of related reports but the problem is with Qt and not likely to be fixed anytime soon.

Some more reports of Qt's mediocre SVG support:
http://www.qtcentre.org/threads/57772-How-to-replace-Qt-svg-render-engine
https://bugreports.qt.io/browse/QTBUG-12588
https://bugs.kde.org/show_bug.cgi?id=333497
https://bugreports.qt.io/browse/QTBUG-1865
https://bugreports.qt.io/browse/QTBUG-28636
http://matplotlib.1069221.n5.nabble.com/Qt-SVG-clipping-bug-it-s-NOT-a-matplotlib-bug-Qt-won-t-fix-td37980.html

Not sure if anything can/should be done on the Numix side, just writing this so as to anticipate similar bug reports.

**Comment by palob** [comment]
If need be a script rendering the SVGs to PNGs for all sizes (using a tool capable of doing this reliably) could be a workaround.

**Comment by Foggalong** [comment]
I think PNGing stuff is out of the question - you loose out on a lot of the quality in scaling it. It'd make sense for the theme that has different icons for different sizes (like Moka) but not for Numix.

It's possibly a case of going through all the icons and making sure they use intersections rather than path clipping. I'm not sure how to deal with the gradient & vanishing baseplate objects though :(

**Comment by palob** [comment]
PCManFM-Qt doesn't seem to support SVG preview at all but Dolphin reveals the breakage.
Or you can use the file browser of Gwenview or Nomacs as well to see all broken icons in one place.

**Comment by Foggalong** [comment]
Thanks for the info. It'll probably be a while until I have time to sit down and fix this, but I'll bare that in mind for when I do :)

**Comment by palob** [comment]
Yeah it'd be a good chunk of work. After converting to intersections you get outlines again :)

**Comment by Foggalong** [comment]
Outlines?

**Comment by palob** [comment]
Those occuring when having differently coloured paths on top of each other.

**Comment by Foggalong** [comment]
I'd not thought about that; there are ways around it but it's a lot of work on top of an already long and tedious task.

Basically the KDE community are gonna have to bounty the shit out of this bug for it to be fixed anytime soon. Because the issue will go across Circle and Square we're talking days (if not weeks) of work just on this one thing, and honestly right now I'd sooner just spend that time fulfilling requests.

**Comment by palob** [comment]
Two more small issues:
+ Shadow elements o top of each other add up their opacities. So the elements should be merged to a single path. (Pretty much fixed with #2240)

+ "Special objects" (I don't actually know how they're called or created) don't show up correctly:
![issue](https://cloud.githubusercontent.com/assets/7050624/7957385/448da36c-09e7-11e5-90c6-f75173c0e0f1.png)

**Comment by palob** [comment]
@Foggalong In the matter of bounties I found [this](http://www.qtcentre.org/archive/index.php/t-62215.html). Looks like someone offers funding for SVG clipping support in Qt.

**Comment by palob** [comment]
In the file browser of the Nomacs image viewer some icons are displayed tiny. 
When I was looking for remaining Numix Circle icons with those recently discussed "broken baseplates" (misshaped grey objects below the coloured baseplate) using a quite inefficient "Monte Carlo method" it turned out that the tiny icons are those with broken baseplate.

So that'll be my next task.

**Comment by Foggalong** [comment]
That's really weird. I really hope that someone at Qt pulls their finger out on this. Linux support in general for SVG is pretty poor, but Qt is a new low

**Comment by palob** [comment]
Linux support is poor? On other platforms there's close to no support at all :)

**Comment by Foggalong** [comment]
librsvg (what Linux uses) has very shaky implementation of the SVG spec. Features missing, others buggy, and generally a bit of a mess. It's definitely better than some places, but still far from great

**Comment by palob** [comment]
Icons containing those ["special objects"](https://github.com/numixproject/numix-icon-theme-circle/issues/2016#issuecomment-108281705) all have longer code and contain something this:
```SVG
  <image id="image10" width="48" height="48" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAAfklEQVRoge3PsQmAMBRF0SjWHyxtxQEcwV1cSRAcxSHSBNzAXiFYW9kHJD6Ee+oP/13nAAAA8FtF6uFmVg8x7jnHPFazpj+OM+W2zD0mNwLUCFAjQI0ANQLUCFAjQI0ANQLUCFAjQK1KPZy6Ls4hjDnHPJa2vZz3X7wCAACv3ArrEBTB61tZAAAAAElFTkSuQmCC"/>
```

This would actually mean there's some raster graphics element included. Does any body know what this is?

**Comment by Foggalong** [comment]
That's really weird. Any ideas what it is @me4oslav?

**Comment by palob** [comment]
Anyway, I've restoredd all of them as paths/rectangles/circles.

**Comment by Foggalong** [comment]
@palob just wanted to say that you've done amazingly in tackling this mammoth of an issue.

**Comment by palob** [comment]
So the remaining issue is about clipped paths.

Assuming the feature got implemented by means of funding and merged to upstream Qt 5.5.x finally I think the earliest non-rolling-release distros to receive it could be Ubuntu 16.04/Fedora 24/Debian Stretch....

So it probably makes sense to do the conversion to intersections (while avoiding hairlines/outlines).

I could do this but I could use some more feedback of actual KDE users as to whether it's really needed. 
I don't know of a way to make Qt applications use librsvg but someone set *librsvg* as dependency for the [Nitrux KDE icon theme AUR build](https://aur.archlinux.org/packages/nitrux-icon-theme-kde/).

So is anybody out there able to get Numix Circle showing up flawlessly on a Qt desktop environment?

**Comment by wa4557** [comment]
I have a VM running Kubuntu 14.04 and I can reproduce that a lot of icons (including the ones you posted above) look weird in dolphin...

**Comment by palob** [comment]
Alright, I've just started working on this.
