### ISSUE TITLE
Icon for Don't Starve Together (Steam)

### ISSUE THREAD

**Issue by Jacajack** [numixproject/numix-icon-theme-circle#2018]
Numix-Circle icon for Don't Starve Together is missing. "Icon" line in launcher says "steam_icon_322330".
Original icon looks like this: 

![screenshot from 2015-04-23 15 00 33](https://cloud.githubusercontent.com/assets/6173262/7297552/f29bb25c-e9c9-11e4-8237-2956a6fa7294.png)

I'd be really happy If you could add it :)

**Comment by Foggalong** [comment]
Ooo, is this a needs game, or just a multiplayer addon? Regardless, it should be pretty easy to modify the existing icon to have a multiplayer feel :)
