### ISSUE TITLE
Dynamic Calendar Icons

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme-circle#2019]
Request made by [Hua Gong](gonghuabupt@gmail.com) via email:

> *Hi, I am using numix for my linux. Great job. Does numix have calendar icons for every date? It's kinda odd to see 19 on my calendar, even though it's not.*

This is something users have requested in the past and one user even made the script and icons which did it. I can't find them now, but they were for the old calendar icon I think so we'd have to do them again anyway.

**Comment by wa4557** [comment]
Well that shoudn't be too hard to do, but I wonder of what use this is? Are there distributions that change the icon based on the date? Whcih names should the icon have?

**Comment by Foggalong** [comment]
No, the request is to make a program which makes the dates switch (along with the icons) :)

**Comment by wa4557** [comment]
Ah ok. Well that should be doable as well :)

**Comment by bil-elmoussaoui** [comment]
I really want to do this but im so busy preparing my finals. You might use Cron and make it update daily, and modify the icon name of the calendar application( default one) to the current day icon.

**Comment by wa4557** [comment]
Cron is not necessary I think. You could do it as a startup application

**Comment by Foggalong** [comment]
Fixed! :D
