### ISSUE TITLE
Clion icon isn't working after editing .desktop file

### ISSUE THREAD

**Issue by sargunster** [numixproject/numix-icon-theme-circle#2026]
I noticed that the Clion IDE has a hardcoded icon, so I edited the .desktop file to fix the icon, but this didn't work. I was able to do this successfully for Intellij IDEA and for Android Studio which are similiarly hardcoded, but I can't get the Numix icon to show for Clion. Here's my Clion desktop file: 

```
[Desktop Entry]
Version=1.0
Type=Application
Name=CLion
#Icon=/opt/clion/bin/clion.svg
Icon=clion
Exec="/opt/clion/bin/clion.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-clion
```

I just get the default "page" icon when I try to use the numix clion icon. I'm using the latest version of Numix from `ppa:numix/ppa`. Has that not been updated with the Clion icon yet? And if that's the case, how can I manually add it?

**Comment by Ghokun** [comment]
Download the icon from github, put it under "/usr/share/icons/Numix-Circle/48x48"

**Comment by Foggalong** [comment]
Updates for the PPA are on hold until we've sorted a few things out, but if you download the version from GitHub it'll be there :)
