### ISSUE TITLE
Oracle SQL Developer icon for Linux is missing

### ISSUE THREAD

**Issue by Emanz93** [numixproject/numix-icon-theme-circle#2027]
Hello,
these icon is missing in Fedora 21 and other distroes. 

Thank you for your work!
![icon](https://cloud.githubusercontent.com/assets/10403746/7344691/2c6488cc-ecce-11e4-823a-720511525680.png)

**Comment by Ghokun** [comment]
It actually exists. https://github.com/numixproject/numix-icon-theme-circle/blob/a610a8d25fdcd981563d4c83c808e68999fcb9de/Numix-Circle/48x48/apps/oracle-sqldeveloper.svg

It is hardcoded so you have to create a .desktop file yourself.

**Comment by palob** [comment]
Could you please add the information outlines in the(video tutorial)[https://plus.google.com/+NumixProjectOrg/posts/DkRmhFZuWez]?
