### ISSUE TITLE
Icon for Visual Studio Code

### ISSUE THREAD

**Issue by jags9415** [numixproject/numix-icon-theme-circle#2041]
Hi, a Numix Circle Icon for Visual Studio Code for Linux is missing.
Link: https://code.visualstudio.com/

Original Icon:

![vso](https://cloud.githubusercontent.com/assets/3059433/7404129/ff3439b8-ee9b-11e4-8a46-e71cd8a71464.png "width:50px")

**Comment by Foggalong** [comment]
Can you add the information given in the readme

**Comment by jags9415** [comment]
The application doesn't come with a .desktop file so you have to create it. The icon is hardcoded.
