### ISSUE TITLE
Icon for Balsamiq Mockups (Chrome)

### ISSUE THREAD

**Issue by Algram** [numixproject/numix-icon-theme-circle#2042]
Hello, I'd like to request an icon for the mockup-tool "Balsamiq".

Icon1: chrome-bfpgdckfbpnmoopkbfbelihlnfncbkag-Default
Icon2: balsamiq

![](http://www.google.de/url?source=imglanding&ct=img&q=https://media.balsamiq.com/files/mockups-app-icon.png&sa=X&ei=7llCVZW5MMbharrGgLAE&ved=0CAkQ8wc4Hg&usg=AFQjCNFaGHLPfe_jCdHCoFPnyFtjWMcNiw)

Thank you very much!

**Comment by Algram** [comment]
maybe you could at the smiley to the icon?

**Comment by Foggalong** [comment]
@ahhmarr would you prefer the smile to the lines? I only went with those because they'll be less blurry than the smile

**Comment by Algram** [comment]
I think they smile fits balsamiq better, so yeah.

**Comment by Foggalong** [comment]
Fair enough! :)
