### ISSUE TITLE
Icon for KGoldrunner

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2048]
KDE game
https://games.kde.org/game.php?game=kgoldrunner

Icon=kgoldrunner
![icon](https://cloud.githubusercontent.com/assets/7050624/7429326/d0d24988-efff-11e4-818e-533e28f022b9.png)
![kgoldrunner](https://cloud.githubusercontent.com/assets/7050624/7429327/d4302fd2-efff-11e4-8986-cf567d48c9ad.png)

**Comment by palob** [comment]
Not sure about this one. A few drafts:
![kgoldrunner0](https://cloud.githubusercontent.com/assets/7050624/7429330/e9c870c0-efff-11e4-95a5-5d57e4fb84bb.png)
![kgoldrunner0b](https://cloud.githubusercontent.com/assets/7050624/7429331/e9c87994-efff-11e4-9856-c8ebde8d3b64.png)
![kgoldrunner1](https://cloud.githubusercontent.com/assets/7050624/7429333/e9cb786a-efff-11e4-84e5-030efe297cd2.png)
![kgoldrunner1a](https://cloud.githubusercontent.com/assets/7050624/7429332/e9c943b0-efff-11e4-9672-753840ed3f34.png)
![kgoldrunner1b](https://cloud.githubusercontent.com/assets/7050624/7429334/e9cbac04-efff-11e4-9c08-e308648d371c.png)
![kgoldrunner2](https://cloud.githubusercontent.com/assets/7050624/7429335/e9cc2300-efff-11e4-88d3-51b52ac21258.png)
![kgoldrunner3](https://cloud.githubusercontent.com/assets/7050624/7429336/e9de8eb4-efff-11e4-9048-0ed4431c55b3.png)

**Comment by Foggalong** [comment]
I quite like the 5th one :)

**Comment by palob** [comment]
Pushed it :+1:
