### ISSUE TITLE
Icon for ECWolf

### ISSUE THREAD

**Issue by Eleuin** [numixproject/numix-icon-theme-circle#2050]
classic FPS from id Software
![ecwolf](https://cloud.githubusercontent.com/assets/5553828/7431258/e2064c78-efea-11e4-8a26-222b40c04e52.png)
icon=ecwolf

**Comment by Foggalong** [comment]
@Eleuin does this have an alternate icon similar to the others in style that could be used instead?

**Comment by Eleuin** [comment]
what we could do, is create an issue for wolf4sdl and share the icon from wolf4sdl between these two (because it uses part of the Wolfenstein 3D graphics anyways). Keeps the theme free of all the nasties :D
