### ISSUE TITLE
Icons for Bomber and KSirK

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2051]
Next 2 KDE games
https://www.kde.org/applications/games/

Icon=bomber
![bomber](https://cloud.githubusercontent.com/assets/7050624/7432475/b3e9f310-f028-11e4-86ac-1c79a1d1739d.png)

Icon=ksirk
![ksirk_48](https://cloud.githubusercontent.com/assets/7050624/7432478/bd2974b4-f028-11e4-84da-86986f67b518.png)

**Comment by palob** [comment]
Which colour's the best for Bomber?
![bomber](https://cloud.githubusercontent.com/assets/7050624/7432488/d51622ac-f028-11e4-95d4-da7f05e04b2b.png)
![bomber6b](https://cloud.githubusercontent.com/assets/7050624/7432489/d51908fa-f028-11e4-9d99-6fd97a61dd3f.png)
![bomber7b](https://cloud.githubusercontent.com/assets/7050624/7432490/d51b9228-f028-11e4-8ef0-c025cc92ea87.png)

**Comment by Eleuin** [comment]
i say blue, just because its sorta KDE's colour

**Comment by Foggalong** [comment]
I'd go red since we have less icons using those, and it works well with either :)

**Comment by palob** [comment]
And what's the best design for KSirK?
![ksirk0aa](https://cloud.githubusercontent.com/assets/7050624/7435339/4998fb1c-f043-11e4-942c-e567073ac451.png)
![ksirk0c](https://cloud.githubusercontent.com/assets/7050624/7435340/499c6810-f043-11e4-8f26-5141e7420b23.png)
![ksirk3b](https://cloud.githubusercontent.com/assets/7050624/7435341/499da36a-f043-11e4-833f-d1cb46a77047.png)

**Comment by Foggalong** [comment]
Go with the first :)

**Comment by palob** [comment]
PR ready :+1:

**Comment by Foggalong** [comment]
Woop!
