### ISSUE TITLE
Icon for Yandex Browser

### ISSUE THREAD

**Issue by Yankees3028** [numixproject/numix-icon-theme-circle#2057]
Hi, a Numix-Circle icon is missing for Yandex Browser.

Icon line: Icon=yandex-browser-beta

![selection_006](https://cloud.githubusercontent.com/assets/12204992/7439392/d28add0c-f046-11e4-9e12-d0dc2be05175.png)

Thank you, I hope you can help!

**Comment by Foggalong** [comment]
You don't have to put please in the title of every issue.

**Comment by Yankees3028** [comment]
Sorry. I just wanted to be as polite as possible to get the issues solved.

**Comment by Foggalong** [comment]
That's quite alright, the politeness really is appreciated :) I just like to keep the issue titles as clean as possible

**Comment by Yankees3028** [comment]
@Foggalong Understood :)
