### ISSUE TITLE
Icon for Ubuntu's Webbrowser-App please

### ISSUE THREAD

**Issue by Yankees3028** [numixproject/numix-icon-theme-circle#2058]
Hi, a Numix-Circle icon is missing for Webbrowser-App. Right now the current icon looks horrid.

Icon line: Icon=/usr/share/webbrowser-app/webbrowser-app.png

![webbrowser-app-icon-numix-circle](https://cloud.githubusercontent.com/assets/12204992/7439427/ccb67baa-f048-11e4-801b-79f0b41d53a2.png)

Thank you, I hope you can help!

**Comment by wa4557** [comment]
There is an icon but it's hardcoded. In order to get it you have to use the hardcode fixer as outlined in the readme
