### ISSUE TITLE
Icon for xdiagnose please

### ISSUE THREAD

**Issue by Yankees3028** [numixproject/numix-icon-theme-circle#2060]
Hi, a Numix-Circle icon is missing for xdiagnose.

Icon line: Icon=/usr/share/xdiagnose/icons/microscope.svg

![selection_009](https://cloud.githubusercontent.com/assets/12204992/7439509/f53ec9ee-f04b-11e4-9dce-04e06c70660e.png)

Thank you, I hope you can help!

**Comment by wa4557** [comment]
There is an icon but it's hardcoded. In order to get it you have to use the hardcode fixer as outlined in the readme
