### ISSUE TITLE
Enhancements for usb Icon please

### ISSUE THREAD

**Issue by Yankees3028** [numixproject/numix-icon-theme-circle#2061]
Hi, a this Numix-Circle icon doesn't look quite as converged with the other icons. In fact (in my opinion, right now the current icon looks horrid.

Icon line: Icon=drive-removable-media

![selection_010](https://cloud.githubusercontent.com/assets/12204992/7439533/fcfc6d98-f04c-11e4-8799-175038da925f.png)

Thank you, I hope you can help!

**Comment by dirtydancing** [comment]
This icon is not part of Numix-Circle, but rather of Numix base, which incidentally is also why it does not have a Numix-Circle design :). Please file this issue over at Numix base: https://github.com/numixproject/numix-icon-theme/issues

Please also note the related open issue https://github.com/numixproject/numix-icon-theme/issues/101 and specifically this comment https://github.com/numixproject/numix-icon-theme/issues/101#issuecomment-58883307

Screenshot from current `48x48/devices` in Numix base:
![base_drives](https://cloud.githubusercontent.com/assets/7164227/7440303/e367de3e-f0ac-11e4-92d5-f8d4c2fabdb5.png)
