### ISSUE TITLE
Ppa release asap for Vivaldi Icon please

### ISSUE THREAD

**Issue by Yankees3028** [numixproject/numix-icon-theme-circle#2062]
I've noticed you've created a icon for it, but have not released it.

**Comment by wa4557** [comment]
The ppa is obviously on hold right now, so you have to wait or download the icon from git instead

**Comment by Foggalong** [comment]
Yeah, PPA is on hold till we fix a status icon issue. Either use the bit version or just download the specific icons you need :)
