### ISSUE TITLE
the ppa updates almost daily

### ISSUE THREAD

**Issue by hopf** [numixproject/numix-icon-theme-circle#2077]
Hey!

I don't know if this is the right place to ask but I'll give it a shot at least.

I am using your circle icons on Ubuntu via the ppa. The issue I am having is that it seems to update very very frequently. Sometimes almost daily. The update size is usually around 3MB so I suspect it is really updating all logos, kind of.
I was just wondering if there is any reason behind that behaviour?

Regards

//an otherwise very happy user

**Comment by Foggalong** [comment]
The PPAs pull any changes from GitHub once a day so you're pretty much always running the most up to date version. Take a look at the [commit history](https://github.com/numixproject/numix-icon-theme/commits/master) and you'll see that we add new stuff to the theme or make changes to older stuff pretty much every single day :)
