### ISSUE TITLE
Icon for Tor Browser

### ISSUE THREAD

**Issue by fau** [numixproject/numix-icon-theme-circle#2078]
Would be nice to have a numix icon for the Tor Browser.

Here's the default one:
![tor-browser-en](https://cloud.githubusercontent.com/assets/4341723/7467242/55dff496-f2b1-11e4-8616-7eef6c235baa.png)

**Comment by Foggalong** [comment]
We have one - this is a duplicate of #867. When making an icon request please give us all the information asked for in the readme :)
![screenshot_2015-05-05_09-21-53](https://cloud.githubusercontent.com/assets/5920259/7469168/4ed1f850-f308-11e4-8d3c-0a639a5b2854.png)

**Comment by roscoe8000** [comment]
and why is it not applying?

**Comment by Foggalong** [comment]
Read the linked issue

**Comment by roscoe8000** [comment]
solved
thanks :)

**Comment by Foggalong** [comment]
NP :)
