### ISSUE TITLE
Icon for Borderlands: The Pre-Sequel (Steam)

### ISSUE THREAD

**Issue by mralext20** [numixproject/numix-icon-theme-circle#2079]
Game: Borderlands: The Pre-Sequel
AppID: 261640
Icon: [HERE](http://i0.wp.com/www.controlcommandescape.com/wp-content/uploads/2014/10/AppIcon.png?fit=150%2C150)

Notes: same series as [this icon](https://github.com/numixproject/numix-icon-theme-circle/blob/7679495e3bea19e72bbcfcad77fd5c93d6426d85/Numix-Circle/48x48/apps/steam_icon_49520.svg), probably something similar. game takes place on a moon.

**Comment by Eleuin** [comment]
@Foggalong the quality good enough on this? if you give me the ok, ill submit a PR for it
![borderlands](https://cloud.githubusercontent.com/assets/5553828/7995860/1886b806-0ae8-11e5-949c-15c360e14657.png)
