### ISSUE TITLE
Icon for Time Tracker (Project Hamster)

### ISSUE THREAD

**Issue by piraces** [numixproject/numix-icon-theme-circle#2082]
Missing icon for Gnome TIme Tracker, included by default in Debian 8 (“jessie”). 
Project page: https://github.com/projecthamster/hamster

Icon line: Icon=hamster-time-tracker
![timetracker](https://cloud.githubusercontent.com/assets/11027628/7534519/81647106-f57b-11e4-9e48-6eb2c1070e8d.png)

Thanks! Hope you include it!

**Comment by palob** [comment]
Actually this icon is in the repository:
https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/hamster-time-tracker.svg

It's a symlink to ``hamster.svg``

**Comment by piraces** [comment]
10 hours ago I did last update. I realized the problem is what you said, github fails to render hamster.svg. Symlink and other are working fine. I will wait under a good rendererd .svg. Thanks! :)

**Comment by palob** [comment]
What I wanted to point out is that you won't see the icon when clicking on the above link.
Nonetheless it should be very well in place locally.
You don't happen to use KDE or LXQt?

**Comment by piraces** [comment]
Sorry for my bad english :confounded: . I don't see the icon when clicking on the above link but neither in the place installed but it was my fault. It's working fine now, i failed to install the theme in some way. I have now re-installed it and now works fine every single icon for me. The issue can be closed, and sorry for the confusion. Thanks for all!

**Comment by palob** [comment]
That's good to hear! :)
