### ISSUE TITLE
Icon for Task Coach

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2089]
Another todo manager
http://taskcoach.org/

Icon=taskcoach
![taskcoach-ori](https://cloud.githubusercontent.com/assets/7050624/7551786/fa793e62-f695-11e4-81f2-c4c2dd5b18ee.png)

**Comment by palob** [comment]
Some drafts:
![taskcoach4b](https://cloud.githubusercontent.com/assets/7050624/7551791/120bbdfc-f696-11e4-821e-211ae28307e6.png)
![taskcoach6c](https://cloud.githubusercontent.com/assets/7050624/7551792/120c3296-f696-11e4-9fb4-e9e26c6d61fa.png)
![taskcoach6d](https://cloud.githubusercontent.com/assets/7050624/7551793/120fba38-f696-11e4-8afb-7653d81dea71.png)

![taskcoach7c](https://cloud.githubusercontent.com/assets/7050624/7551794/1210e2e6-f696-11e4-94c3-0deaf201e8c6.png)

Which one's the best?

**Comment by dirtydancing** [comment]
I think I prefer the first one. It is closest to the original and to me it is easier to place than the others.

But the icon above might be somewhat close to `zanshin.svg`, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/1966.

Zanshin current icon:
![zanshin_current](https://cloud.githubusercontent.com/assets/7164227/7555804/9d114676-f757-11e4-9905-02989dab34a5.png)

Zanshin original icon:
![zanshin_original](https://cloud.githubusercontent.com/assets/7164227/7555802/8949c1ae-f757-11e4-9c9e-af10b8df97d0.png)

Why not take the current Zanshin icon (or the first one from above) for taskcoach, and take e.g. the icon below for Zanshin? Zanshin sees itself about "getting your mind like water", https://zanshin.kde.org/.

I would be happy to submit a pull request for that icon. What do you think?

Zanshin proposed icon:
![zanshin_proposed](https://cloud.githubusercontent.com/assets/7164227/7555809/daa37982-f757-11e4-9646-d4a970eaddab.png)

**Comment by palob** [comment]
Alright, if your Zanshin draft is tolerably recognisable at lower sizes feel free to do a PR :+1:

**Comment by dirtydancing** [comment]
Done :) Included a screenshot of size 48x48. Just seeing your additional comment about the baseplate. I will take a look.

**Comment by palob** [comment]
Just for the record, by lower sizes I meant sizes below 48px :)
(Relevant for instance for Xfce/Cinnamon/MATE menus and panels)

**Comment by dirtydancing** [comment]
I see :-) Will include a screenshot of size 24x24 in the PR, just checking a brighter baseplate.

**Comment by palob** [comment]
@Foggalong What do you think is the one to go for (old Zahnshin one included)?

**Comment by Foggalong** [comment]
@palob I'd go with swapping task-coach and zahnshin as @dirtydancing suggested. Possibly good to make sure for icons linking to zahnshin before you do though

**Comment by palob** [comment]
There shouldn't be any links. I've only recently done the zanshin one and it's basically the GTG icon recoloured.

**Comment by Foggalong** [comment]
Ah, okay :)
