### ISSUE TITLE
Icon for PhpStorm

### ISSUE THREAD

**Issue by sakren** [numixproject/numix-icon-theme-circle#2097]
Please add missing icon for [PhpStorm](https://www.jetbrains.com/phpstorm/).

Icon configuration in .desktop file does not use icon name but absolute path to webide.png image.

I found icon in similar style as yours:
![phpstorm](https://d13yacurqjgara.cloudfront.net/users/269651/screenshots/1755483/phpstorm_yosemite_icon.jpg)

**current icon:**
![vyber_001](https://cloud.githubusercontent.com/assets/1174072/7560772/629e721a-f7c6-11e4-8c6c-533a94364820.png)

Thank you

**Comment by Ghokun** [comment]
There is one actually

https://github.com/numixproject/numix-icon-theme-circle/blob/87d443378dc31b6f4b811b9260c77f79cc69e5f3/Numix-Circle/48x48/apps/phpstorm.svg

**Comment by palob** [comment]
Could you please add the *path to webide.png image*?
Seems hardcoded.

**Comment by sakren** [comment]
@Ghokun I should look there myself.... Unfortenately it looks like this:

![plocha 1_003](https://cloud.githubusercontent.com/assets/1174072/7561148/1a4bed4a-f7ca-11e4-8d36-510db9e11c10.png)

@palob I did not try that script, but I changed the hardcoded path to icon name `phpstorm` (I'm using MenuLibre for that).

**Comment by palob** [comment]
You're probably using the PPA. It's outdated but an update is on hold until some problems are sorted out.

**Comment by sakren** [comment]
You're right.. Sorry guys to bother you, I now see the [old](https://github.com/numixproject/numix-icon-theme-circle/issues/967) issue.

And I really [searched](https://github.com/numixproject/numix-icon-theme-circle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+php) for "php" in closed issues before I posted this one.

So again sorry and thanks for great icon theme
