### ISSUE TITLE
Icon for Quaternion

### ISSUE THREAD

**Issue by PureTryOut** [numixproject/numix-icon-theme-circle#21]
I would love to see an icon for [Quaternion](https://github.com/fxrh/quaternion). It's a Qt-based client for [Matrix](https://matrix.org), which is an upcoming, decentralized, FOSS, encrypted chat/voip protocol. It's current logo is available [here](https://github.com/Fxrh/Quaternion/blob/master/icons/quaternion/sources/quaternion.svg).

**Comment by Foggalong** [comment]
Please see the README section on [requests](https://github.com/numixproject/numix-icon-theme-circle#issues--requests)
