### ISSUE TITLE
Icon for Whatsapp

### ISSUE THREAD

**Issue by KeizerDev** [numixproject/numix-icon-theme-circle#2148]
Hi, 

I made a shortcut to `web.whatsapp.com` in my dock, now I want to have a icon for it.

If you are interested in how, just make a file in `~/.local/share/applications/` called `whatsapp.desktop` and paste this is. Then search for Whatsapp in your dash(you may have to set a filter to see applications).
```
[Desktop Entry]
Name=Whatsapp
Comment=
Exec=firefox http://web.whatsapp.com
Icon=whatsapp
Terminal=false
Type=Application
StartupNotify=true
```

**Comment by bil-elmoussaoui** [comment]
This is a duplicate of this #1507 You can use the same icon or create a symlink to it ;) 
The ppa has not been updated in a while due to an issue. You can download the icon or use the github version

**Comment by KeizerDev** [comment]
Thanks!
