### ISSUE TITLE
Gnome Pie icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2165]
A gnome pie icon is needed 
the icon line is 
``` 
Icon=gnome-pie
```
the default icon : 
![3](https://cloud.githubusercontent.com/assets/7660997/7786223/5c96283e-01be-11e5-819d-d8cff017bf84.png)

**Comment by palob** [comment]
Two simple drafts:
![gnome-pie](https://cloud.githubusercontent.com/assets/7050624/7847518/4b3e6b74-04c4-11e5-91b2-2797d9cc359d.png)

![gnome-pie0](https://cloud.githubusercontent.com/assets/7050624/7847519/4b40dd96-04c4-11e5-9b51-36fff39310e9.png)

**Comment by bil-elmoussaoui** [comment]
I do prefer the first one :+1:

**Comment by Foggalong** [comment]
Agreed +1
