### ISSUE TITLE
Icon for pushbullet-indicator

### ISSUE THREAD

**Issue by ricwtk** [numixproject/numix-icon-theme-circle#2167]
A numix circle icon for pushbullet-indicator is missing.
The icon line refers to a hard-coded location for icon with the name of 'pushbullet-indicator'. 
The original icon is attached. 
![pushbullet](https://cloud.githubusercontent.com/assets/3527220/7787672/ad950c2c-020f-11e5-873a-3cc74f8635a2.png)

**Comment by bil-elmoussaoui** [comment]
Duplicate of #1854 #1049 , the icon already exists in the github repo
