### ISSUE TITLE
Icon for xfdashboard

### ISSUE THREAD

**Issue by ricwtk** [numixproject/numix-icon-theme-circle#2168]
The numix circle icon for xfdashboard is missing.
The icon line says "xfdashboard" and the original icon is attached.
![xfdashboard](https://cloud.githubusercontent.com/assets/3527220/7787691/90e3597a-0210-11e5-9444-b87951876b45.png)

**Comment by bil-elmoussaoui** [comment]
Duplicate of this #1821 , you can download the icon from the github repo
