### ISSUE TITLE
Elements dissapear in elementary Freya

### ISSUE THREAD

**Issue by Gabriel-p** [numixproject/numix-icon-theme-circle#2169]
Freya's default icon set shows two elements in the Files manager that disappear when using this icon set:

1- Ticks in top left corner of icon files to select them one by one by clicking on said tick mark.

![captura de pantalla de 2015-05-24 12 30 02](https://cloud.githubusercontent.com/assets/6054951/7788485/8326ea8e-0212-11e5-9658-9fb6ccff5bcd.png)

2- Arrows in right click menu to access sub-menus.

![captura de pantalla de 2015-05-24 12 29 02](https://cloud.githubusercontent.com/assets/6054951/7788489/d05c7558-0212-11e5-9991-fd5d68635221.png)

Also the "Previous, Next" in the top left of the Files manager look rather horrible and out of proportion.

**Comment by bil-elmoussaoui** [comment]
Those icons must be reported in Numix icon theme. I've already reported all the missing icons there, and i didn't find the icon names of those two. If you find them, you can add that there
