### ISSUE TITLE
Non circular icons in Numix-Circle

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2171]
This a list of those icons , i don't know it it's the right place or we should move them to numix base?

- [ ] yahoo.svg
- [x] xscreenaver.svg
- [x] xwfm4.svg
- [x] xfce4-ui.svg
- [ ] twitter.svg
- [x] screensaver.svg
- [x] preferences-theme.svg
- [x] preferences-system-windows.svg
- [x] preferences-desktop-screensaver.svg
- [x] preferences-desktop-theme.svg
- [x] preferences-calendar-and-tasks.svg
- [ ] people-nearby.svg
- [ ] live.svg
- [ ] jabber.svg
- [ ] google.svg
- [ ] goa-account-yahoo.svg
- [ ] goa-account-twitter.svg
- [ ] goa-account-pocket.svg
- [ ] goa-account-owncloud.svg
- [ ] goa-account-microsoft.svg
- [ ] goa-account-live.svg
- [ ] goa-account-kerberos.svg
- [ ] goa-account-google.svg
- [ ] goa-account-flickr.svg
- [ ] goa-account-facebook.svg
- [x] gnome-settings-theme.svg
- [x] calendar.svg
- [ ] aim.svg
- [ ] facebook.svg - symlink to goa-account-facebook.svg
- [ ] salut.svg

**Comment by wa4557** [comment]
you can remove 
```
xscreenaver.svg
xwfm4.svg
xfce4-ui.svg
screensaver.svg
preferences-theme.svg
preferences-system-windows.svg
preferences-desktop-screensaver.svg
preferences-desktop-theme.svg
preferences-calendar-and-tasks.svg
gnome-settings-theme.svg
calendar.svg
```
from your list. Those icons are already circular. Do you want to turn that into a tick-list ?

**Comment by bil-elmoussaoui** [comment]
Done, i was using a very old version when i did this

**Comment by bil-elmoussaoui** [comment]
The rest of the icons are the ones used in Gnome online accounts/Ubuntu online accounts

**Comment by wa4557** [comment]
I think they should be moved to base (`48x48/apps`?)

**Comment by bil-elmoussaoui** [comment]
I do think too, i can do this if @Foggalong agrees?

**Comment by palob** [comment]
Some more?
[aim.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/aim.svg)
[facebook.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/facebook.svg) - symlink to ``goa-account-facebook.svg``
[salut.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/salut.svg)

**Comment by bil-elmoussaoui** [comment]
@Foggalong those icons should not be cercle, i propose to move them to base if you want to? i can create a PR for that

**Comment by Foggalong** [comment]
@bil-elmoussaoui sorry, only just seen this! yeah feel free to move these to base :)

**Comment by bil-elmoussaoui** [comment]
I will do tonight, should i put them in `Numix/sizexsize/apps/`?

**Comment by Foggalong** [comment]
Yeah. I think they're all 48px so all in there :)

**Comment by wa4557** [comment]
Shouldn't they be designed for other sizes as well? (In `22` there are for example a few pngs that are basically exactly those icons...)

**Comment by Foggalong** [comment]
Ooo, that would be great! Crossing a few PNGs off the list too

**Comment by wa4557** [comment]
Ah that reminds me, I have a few png icons almost ready :)

**Comment by Foggalong** [comment]
:D

**Comment by wa4557** [comment]
@bil-elmoussaoui Just a heads so that we are not working on the same thing. I'm going to add those icons to Numix, so don't worry about different sizes :)
