### ISSUE TITLE
Icon for Tintii Photo FIlter

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2179]
A selective colouring application
http://sourceforge.net/projects/tint/

Icon=tintii
![tintii-ori](https://cloud.githubusercontent.com/assets/7050624/7840461/bb2a9cfa-0497-11e5-9c4a-f9cf13815547.png)

**Comment by palob** [comment]
Not sure about this one. Two drafts:
![tintii](https://cloud.githubusercontent.com/assets/7050624/7840504/f5be83b8-0497-11e5-8310-6f52b4748224.png)
![tintii0b](https://cloud.githubusercontent.com/assets/7050624/7840505/f5c10a70-0497-11e5-852f-489a0d300e47.png)

**Comment by Foggalong** [comment]
Like the first one! :D
