### ISSUE TITLE
Icon for mkvmerge GUI

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2187]
Icon=mkvtoolnix-gui

Instead of making yet another symlink, I suggest to simply rename mkv-gui.svg to mkvtoolnix-gui.svg. Unless that name is still used somewhere, then make a symlink :-)

**Comment by Foggalong** [comment]
We already have an icon with that name :) [link](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/mkvtoolnix-gui.svg)

**Comment by gregorydk** [comment]
OK, never mind. Didn't see it. Time to update:-)
