### ISSUE TITLE
Icon for Viber

### ISSUE THREAD

**Issue by gtomas41** [numixproject/numix-icon-theme-circle#22]
A numix-icon-circle icon for Viber desktop application for Linux.
The icon line says viber, but it's linux, not numix.

[Desktop Entry]
Name=Viber
Comment=Viber VoIP and messenger
Exec=/opt/viber/Viber
Icon=/usr/share/pixmaps/viber.png
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Network;Application;
Path=

![image](https://cloud.githubusercontent.com/assets/22322105/20173041/d587a978-a737-11e6-81e1-46b2e5ceb71d.png)

**Comment by Foggalong** [comment]
This is the wrong repo. Please report missing icons [here](https://github.com/numixproject/numix-core) and follow the instructions in the README.
