### ISSUE TITLE
Icon for GNOME Video Arcade

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2214]
Icon=gnome-video-arcade

![gnome-video-arcade](https://cloud.githubusercontent.com/assets/7804464/7882181/4207ac4e-060b-11e5-878c-80ca3301060d.png)

**Comment by Eleuin** [comment]
this actually looks like a fun one

**Comment by Eleuin** [comment]
![gnome-video-arcade2](https://cloud.githubusercontent.com/assets/5553828/8064391/670cb7fa-0ea8-11e5-8370-d323c4792a9c.png)
![gnome-video-arcade](https://cloud.githubusercontent.com/assets/5553828/8064395/6a0d05fe-0ea8-11e5-823f-c5f62560ed50.png)

**Comment by sergioad** [comment]
Add a white gnome logo at the visible side of the arcade and ready :smile:

**Comment by Eleuin** [comment]
i actually flipped the direction of the machine because the lighting was falling in the same direction as the shadow

**Comment by Eleuin** [comment]
![gnome-video-arcade](https://cloud.githubusercontent.com/assets/5553828/8065945/c21190b2-0eb2-11e5-909c-3aac294281c8.png)
![gnome-video-arcade2](https://cloud.githubusercontent.com/assets/5553828/8065946/c547281e-0eb2-11e5-8f2b-f5a2302d755a.png)

**Comment by Foggalong** [comment]
I love it <3

**Comment by Eleuin** [comment]
just need to remove some commits from that branch, and ill send a pull request that way. really don't want dup commits :)
