### ISSUE TITLE
Icon for Access Remote Desktops

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2216]
Made an icon for `virt-viewer` a supporting tool for `virt-manager`.

![virt-viewer](https://cloud.githubusercontent.com/assets/7804464/7883343/0a8cd70c-0616-11e5-9330-79fc163dc80d.png)

**Comment by palob** [comment]
Fixed in https://github.com/gregorydk/numix-icon-theme-circle/commit/66842f6b78b110e64f0a18a6dbb0a04dd809c3df
