### ISSUE TITLE
Icon for LiteIDE

### ISSUE THREAD

**Issue by nekofar** [numixproject/numix-icon-theme-circle#2217]
```
[Desktop Entry]
Version=1.0
Name=LiteIDE
Comment=LiteIDE is a simple, open source, cross-platform Go IDE. 
Exec=sh -c 'eval `ssh-agent -s`;/opt/liteide/bin/liteide'
Icon=/opt/go/doc/gopher/gophercolor.png
Type=Application
Actions=golang;http;gopath;

[Desktop Action golang]
Name=golang.org
Exec=xdg-open http://golang.org/pkg

[Desktop Action http]
Name=HTTP server (localhost:8080)
Exec=xdg-open http://localhost:8080

[Desktop Action gopath]
Name=GOPATH
Exec=xdg-open go-programs/src
```

![gophercolor](https://cloud.githubusercontent.com/assets/147401/7886195/a4634c4a-063d-11e5-973a-901df40f93bc.png)

**Comment by palob** [comment]
It seems the icon line isn't set [upstream](https://github.com/visualfc/liteide/blob/193e8510a84a5d7b7fce76f4f81fdfabca69d29c/liteidex/liteide.desktop).

The AUR package provides ``Icon=liteide`` and the following icon (which is acreenshot actually):
![liteide](https://cloud.githubusercontent.com/assets/7050624/7890296/7fc04476-0645-11e5-967a-decf14df4524.png)

Their [GitHub page](https://github.com/visualfc/liteide) shows this logo:
![liteide-logo](https://cloud.githubusercontent.com/assets/7050624/7890321/a5f4362a-0645-11e5-8860-dc911ae07197.png)

**Comment by palob** [comment]
How about these simple designs based on the logo?
![liteide0](https://cloud.githubusercontent.com/assets/7050624/7890373/f32f9dda-0645-11e5-8b13-6503721032ab.png)
![liteide00](https://cloud.githubusercontent.com/assets/7050624/7890374/f32ffb5e-0645-11e5-9860-19b414c3be07.png)
![liteide0b](https://cloud.githubusercontent.com/assets/7050624/7890376/f33281b2-0645-11e5-9127-da37089a9850.png)
![liteide1](https://cloud.githubusercontent.com/assets/7050624/7890375/f3328d7e-0645-11e5-9837-e3302fa067a2.png)

**Comment by bil-elmoussaoui** [comment]
The second +1

**Comment by Eleuin** [comment]
3rd keeps the bold + italics, and still maintains a nice ratio between the brackets and logo. I would say its more faithful to the original

**Comment by Foggalong** [comment]
I kinda like the 3rd too :)

**Comment by palob** [comment]
Alright, 2:1 for the 3rd :)
