### ISSUE TITLE
Icon for Urban Lightscape

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2224]
Lightning photo filters application 
http://www.indii.org/software/urbanlightscape/

Icon=urbanlightscape
![urbanlightscape](https://cloud.githubusercontent.com/assets/7050624/7896839/e440e622-06c6-11e5-91d6-cda1ebc3ff04.png)

**Comment by palob** [comment]
How about this one?
![urbanlightscape-work3b](https://cloud.githubusercontent.com/assets/7050624/7896841/fb8f0b2e-06c6-11e5-90e1-83162a2a1675.png)
![urbanlightscape-work3b-32](https://cloud.githubusercontent.com/assets/7050624/7896843/fb944fda-06c6-11e5-8076-f228273f8ea5.png)
![urbanlightscape-work3b-256](https://cloud.githubusercontent.com/assets/7050624/7896842/fb91b52c-06c6-11e5-8437-a149174b6d88.png)

Brighter light post?
![urbanlightscape-work4-128](https://cloud.githubusercontent.com/assets/7050624/7896844/0671741e-06c7-11e5-8b1a-e696df4ba979.png)

**Comment by Foggalong** [comment]
Can't use glow because librsvg doesn't support it unless it's done using gradients. Same reason Hexagon was never ported to desktop :(

**Comment by palob** [comment]
It does show up correctly here - it is a radial gradient.
What about the design in general?

**Comment by Foggalong** [comment]
Yeah, design is fine with me :)

**Comment by palob** [comment]
So now glow, dark post?

**Comment by Foggalong** [comment]
Yeah :)
