### ISSUE TITLE
Icon for Zandronum

### ISSUE THREAD

**Issue by Eleuin** [numixproject/numix-icon-theme-circle#2231]
Online Doom source port
![zandronum](https://cloud.githubusercontent.com/assets/5553828/7899978/09ffcb88-070a-11e5-99e8-0d96412ff42b.png)
icon = /usr/share/pixmaps/zandronum.png

**Comment by Eleuin** [comment]
![zandronum](https://cloud.githubusercontent.com/assets/5553828/7900081/86b65442-0711-11e5-8c7f-07992508a91a.png)
hows this so far?

**Comment by palob** [comment]
The contrast looks a bit harsh to me so maybe a tad brighter black?

**Comment by Eleuin** [comment]
how about this instead?
![test](https://cloud.githubusercontent.com/assets/5553828/7927322/636e84a4-08ac-11e5-81fd-0e6108da3028.png)

**Comment by palob** [comment]
Try a lower S value for the baseplate again (it's S255).

Maybe a different colour for the baseplate altogether? Does it represent the game's atmosphere? 
Idon't know what exactly the game is about but looking at the website I can't see where you got that colour. Doesn't maybe look it to "joyful" :)

**Comment by Eleuin** [comment]
you know, your right. it was a little too bright and i probably should have gone for a little bit of a darker green to fit into their branding a bit better.
![test](https://cloud.githubusercontent.com/assets/5553828/7934416/208bffba-08f5-11e5-9019-9b04e013fe13.png)

**Comment by palob** [comment]
I think I'd prefer your very first baseplate draft (maybe a tad darker / desaturated).

**Comment by Eleuin** [comment]
so like this? yeah, ill remember in the future to make things less saturated and bright
![test](https://cloud.githubusercontent.com/assets/5553828/7934584/f16f7174-08f6-11e5-9745-97f8d6f3abfe.png)

**Comment by Eleuin** [comment]
![zandronum48](https://cloud.githubusercontent.com/assets/5553828/7965495/ddcf8898-09eb-11e5-9855-39cb995cf520.png)
the final draft, talked about it on irc, and it seems a lot better now. sent off a pull request for it
