### ISSUE TITLE
Viber Indicator icon

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-icon-theme-circle#2235]
As you might be aware there is a nice viber-wrapper indicator as mentioned here:
http://www.webupd8.org/2014/11/viber-wrapper-indicator-hides-floating.html

It seems it simply uses the viber app icon so I've simply changed the colors in the existing Numix-Circle icon to monochrome and copied it to the sub-folder for size 22x22 to get a matching monochrome icon in my systray.

Maybe this can be in included in the official set as well?

**Comment by bil-elmoussaoui** [comment]
It has been added in Numix Base [Adds status icons for viberwrapper commit](https://github.com/numixproject/numix-icon-theme/commit/5db54f6a88b0230ed2dea3bac2209cb86d1a15e7)

**Comment by Sadi58** [comment]
Hmmm,  yes, I can see it now - thanks for letting me know. But it seems this viber-wrapper-indicator insists on using the viber.svg in the apps sub-folder - strange :\)

**Comment by bil-elmoussaoui** [comment]
I've reported this to viberwrapper dev and this has been fixed in the latest ppa version [Make viberwrapper themable](https://github.com/karas84/viberwrapper-indicator/issues/4) 
Hope you can close this :)

**Comment by Sadi58** [comment]
I'm afraid I'm having another Numix and Numix-Circle combination issue here and that's why I saw the App icon (Numix-Circle) in the my SysTray although I had those two Status icons (Numix).

I could see them as I should only after I created symlinks in Numix-Circle (and Numix-Circle-Light) as well.
(This had happened with the Redshift icons as well)

**Comment by wa4557** [comment]
@Sadi58 It's not you, its the github version that produces this bug see [#190] (https://github.com/numixproject/numix-icon-theme/issues/190). It's basically the gtk lookup that takes the wrong icon

@Foggalong I really think this bug should be tackled, otherwise these issue reports will come up again and again. I'd gladly put some work in that...

**Comment by bil-elmoussaoui** [comment]
@wa4557 i don't think it's the same issue as the viberwrapper doesn't use the same icon name as the viber application
@Sadi58 are you using the ppa or the github version , for Numix and Viberwrapper indicator too?

**Comment by wa4557** [comment]
@bil-elmoussaoui It's exactly the same issue. If you read through this issue you'll see that the wrong icon is used, even if the name of the icon is actually different. That's why @dirtydancing and I were suggesting to symlink these icons to `numix-circle`

**Comment by Sadi58** [comment]
I use both Numix and Viver-Wrapper PPAs.
Redshift  issue disappeared after I switched from github to PPA though...

**Comment by Sadi58** [comment]
If you can still hear me, I've encountered this problem again today after a new update from PPA, and I've figured out that I can avoid this by adding 22x22/status to the list of directories together with a corresponding section below.

**Comment by Foggalong** [comment]
I'm not sure what you're saying? You mean the index file?

**Comment by Sadi58** [comment]
Yes, yes, sorry for the ambiguity.

**Comment by Foggalong** [comment]
[We don't have 22/status in Numix Circle anymore?](https://github.com/numixproject/numix-icon-theme-circle/tree/master/Numix-Circle/22x22)

**Comment by Sadi58** [comment]
Hmm, interesting. I'm using PPA now and I think it was there before, and I even added a couple of icons and/or symlinks, and upgrades keep that "legacy" sub-folder.

**Comment by Foggalong** [comment]
Yeah, we've removed that folder. All status icons are now handled in base. There's a symlink which links some troublesome icons back to Circle (the panel folder) and we've also dropped support for any programs which used the same name for the app and status icons. They were causing way too many problems so it just wasn't worth it anymore

**Comment by Sadi58** [comment]
So we're back at the same old point: Numix Circle (Light) somehow fails to inherit Numix (Light) icons -- at least as well as status icons in Unity top panel are concerned.

**Comment by Foggalong** [comment]
What exactly is the problem you're having?

**Comment by Sadi58** [comment]
When I start Viber, apparently it cannot find the (monochrome) indicator status icons in 22x22/status sub-directory, and so it simply displays the standard (color) app icon.

**Comment by Foggalong** [comment]
What's the icon name?

**Comment by dirtydancing** [comment]
Is it the monochrome icon `viber-normal.svg` that we are talking about here? This is currently located in `Numix-Light/22x22/status`.

@Sadi58 Could you try to move that icon to `Numix-Light/22x22/panel` and see if it is displayed in the panel then?

**Comment by Sadi58** [comment]
app icon: viber.svg
status icons: viber-normal.svg, viber-notification.svg

**Comment by dirtydancing** [comment]
Well, these Viber status icons are named differently from the app icon (so these are not "toxic"), and they are still located in the `status` folders.

This indicates that so far, Viber has not been identified as an app that has the "status icon issue". So moving these status icons to the `panel` folders in Numix and Numix-Light should be fine.

**Comment by Foggalong** [comment]
@dirtydancing well that needs to be tested first :P

**Comment by dirtydancing** [comment]
Yep, that is why I asked @Sadi58 to check whether this works :)

**Comment by Sadi58** [comment]
I've just tested, but no, it seems the indicator-app looks for the status sub-director as it now displayed a viber-normal status icon that is probably from hicolor status :-(

**Comment by Foggalong** [comment]
Do you have both Numix base and Numix Circle installed into the same directory?

**Comment by dirtydancing** [comment]
Just in case that these icons are moved from `status` to `panel`: both `viber-normal.svg` and `viber-notification.svg` would then need to be in Numix and in Numix-Light.

Currently, `viber-notification.svg` is located only in Numix, not in Numix-Light. This is fine for the base icon themes, as Numix-Light inherits from Numix. But for the purposes of the `panel` folders and their counterpart symlinks in Circle, all the icons need to be in Numix-Light as well, because Numix-Circle-Light does not inherit from Numix (only from Numix-Light).

**Comment by Sadi58** [comment]
I have all of them in different directories under /usr/share/icons: Numix, Numix-Light, Numix-Circle, Numix-Circle-Light, Numix-Square, Numix-Square-Light

**Comment by Foggalong** [comment]
That's fine - they just both have to be in /usr/share/icons or some intertheme links break

**Comment by dirtydancing** [comment]
@Sadi58 Which icon is relevant in your case, `viber-normal.svg` or `viber-notification.svg`?

**Comment by Sadi58** [comment]
I should be seeing viber-normal.svg, but that's not the case.

**Comment by dirtydancing** [comment]
OK, could you update the icon cache (forced) of Numix-Light with `sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Light` and see if that changes anything

**Comment by Sadi58** [comment]
That's it! I should have done this ;-)

**Comment by Foggalong** [comment]
Wait, that does it with the move to /panel or with the standard setup?

**Comment by dirtydancing** [comment]
:+1:

**Comment by Sadi58** [comment]
So the solution is: moving viber indicator icons from status to panel sub-directory :-)

**Comment by Foggalong** [comment]
:+1:

**Comment by dirtydancing** [comment]
@foggalong Should I create a PR for this (happy to do so) or do you want to do this?

**Comment by Foggalong** [comment]
Feel free!

**Comment by dirtydancing** [comment]
Done, cf. https://github.com/numixproject/numix-icon-theme/pull/649.

**Comment by Sadi58** [comment]
Updated PPA tested. Perfect! Thanks...

**Comment by Foggalong** [comment]
The solution hasn't even been merged yet :/ so it's now working without it?

**Comment by wa4557** [comment]
A ppa update does not remove icons that were added manually, so I guess @Sadi58 updated the PPA and thought that this solved the problem, but in reality the manual movement he did yesterday solved it :)

**Comment by Sadi58** [comment]
Same mistake again ;-)
