### ISSUE TITLE
Symlink Fbmessenger to messengerfordesktop

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2237]
MessengerForDesktop is a nice messenger client for facebook [more info](https://github.com/Aluxian/Facebook-Messenger-Desktop)

the icon line is 
``` 
messengerfordesktop
```

**Comment by Foggalong** [comment]
Does it still work? Facebook recently killed support via XMPP which means a lot of clients no longer work :/

**Comment by bil-elmoussaoui** [comment]
It's using the new facebook messenger website & nodejs to implement that in desktop :P

**Comment by Foggalong** [comment]
I see!

**Comment by bil-elmoussaoui** [comment]
I was going to do this, but thanks that was fast

**Comment by Foggalong** [comment]
Ah, sorry! I had the terminal already open in the right place so thought I'd just quickly do it
