### ISSUE TITLE
Update fedy-based installation instructions

### ISSUE THREAD

**Issue by evfool** [numixproject/numix-icon-theme-circle#2241]
The README says `sudo fedy -e numix_themes` should install the themes, but the latest version of fedy just opens, and does not install anything. There's an error in the console: `(gjs:4671): GLib-GIO-CRITICAL **: This application can not open files.` which might be the real cause, or simply the fact that fedy does not show the numix packages anymore in the latest version.

The fedy-based installation instructions should either be removed or updated.

**Comment by Foggalong** [comment]
@satya164 Is command line Fedy installation still supported?

**Comment by satya164** [comment]
Fedy has Numix themes, but it doesn't have a CLI anymore. I already told ahmar to update the instructions.

**Comment by satya164** [comment]
@Foggalong We should remove the OBS instructions since we won't maintaining the OBS repo anymore.

**Comment by Foggalong** [comment]
@satya164 I thought that's why we needed the package maintainers?

**Comment by satya164** [comment]
@Foggalong No, to set up automatic build process for copr (we have copr, so who needs obs) and maintain packages for our premium stuff.

**Comment by Foggalong** [comment]
@satya164 Oh right! Does copr work with openSUSE too?

**Comment by satya164** [comment]
@Foggalong It doesn't. Only for Fedora and RHEL. The main reason of not using OBS is, all the downtime it gives. Many times repos don't work.

Also copr is very much like a PPA for Fedora, so, it's kinda easier.

**Comment by Foggalong** [comment]
Ah okay, I'd not realised it had problems :( I'll trip it out of the readmes then :)

**Comment by satya164** [comment]
@Foggalong :+1:
