### ISSUE TITLE
Icon for TigerVNC

### ISSUE THREAD

**Issue by nejsan** [numixproject/numix-icon-theme-circle#2246]
The icon name is simply `tigervnc` and the default icon is this:
![tigervnc_48](https://cloud.githubusercontent.com/assets/2885412/7994424/f10b5f1c-0ad2-11e5-8ef9-b8b854277283.png)

I could try my hand at creating the icon, but I don't know how the package maintainers feel about that.

**Comment by Foggalong** [comment]
We whole heartedly welcome contributions from 3rd parties :) [Just look at our long history of merged pull requests!](https://github.com/numixproject/numix-icon-theme-circle/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+)

**Comment by nejsan** [comment]
Ok, I'll take a shot at it!

**Comment by Foggalong** [comment]
Issue can stay open until a suitable merge is pulled :)

**Comment by Foggalong** [comment]
Fixed in  #2248
