### ISSUE TITLE
InSync icon syncing status

### ISSUE THREAD

**Issue by mwolfindale** [numixproject/numix-icon-theme-circle#2253]
Hi,

The Numix Circle InSync icon is great - just wondered if we could show the syncing status as with the original icon?

When syncing it shows this (see top right) - blue sync icon:
http://www.webupd8.org/2013/03/unofficial-google-drive-client-insync.html

When finished syncing it shows this - a green tick:
https://www.liberiangeek.net/wp-content/uploads/2012/08/insync_precise_thumb.png

On error, it has a red cross - (sorry this is Mac not Ubuntu, but couldn't find a screenshot for that!):
https://support.insynchq.com/uploads/default/422/b0a9b33f215eb0fe.png

**Comment by bil-elmoussaoui** [comment]
Well, if you talk about the application icon, that won't be possible as you've to ask Insync devs to implement this feature. And if you talk about status/panel icon, the indicator icon and emblem icons are supported in the latest version of Numix base, all you've to do is to upgrade or to use the github repo.

**Comment by wa4557** [comment]
well this might be [#190] (https://github.com/numixproject/numix-icon-theme/issues/190) striking again. @mwolfindale Is a circular icon displayed in the tray?

**Comment by mwolfindale** [comment]
Sorry I may have misunderstood - the original InSync icon does change depending on the status, but when applying the Numix circle theme, it's just a circular icon with no tick/cross etc. depending on the status.

Does that make sense? Happy to provide more info.

**Comment by wa4557** [comment]
Yeah this is a known bug, which will be hopefully fixed sometimes... But you can add those icons manually for now. 

I suppose your themes are installed in `/usr/share/icons/Numix` and `/usr/share/icons/Numix-Circle`, if not change the paths in the following command accordingly

```
cd  /usr/share/icons/Numix
find . -iname *insync* -exec cp -a --parents {} /usr/share/icons/Numix-Circle \;
```

that should fix that if you want to know why this happens read [#190] (https://github.com/numixproject/numix-icon-theme/issues/190)
