### ISSUE TITLE
accessories-text-editor

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2260]
Hello, i wanted to know where this icon is used in Numix Circle as this must be in base..
``` accessories-text-editor.svg ``` 
As you can see in the official doc for geary [Symbolic icons](https://wiki.gnome.org/Apps/Geary/SymbolicIcons)
 
![capture du 2015-06-10 12 41 48](https://cloud.githubusercontent.com/assets/7660997/8080591/1029317c-0f6e-11e5-8f4a-b0b81c914c9a.png)

Is it okay to remove it from Circle?

**Comment by wa4557** [comment]
Is used as application icon for `gedit`, so it cannot be removed, I'm afraid

**Comment by bil-elmoussaoui** [comment]
I really don't understand why some dev use ```action``` icons as default icons

**Comment by palob** [comment]
I think it is an application icon. The mistake is on Geary's side here.

**Comment by bil-elmoussaoui** [comment]
The same icon is used in Thunderbird too..(i guess)

**Comment by Foggalong** [comment]
I use Thunderbird and iive nevernseen it. Definitely a bug on Geary's part.
