### ISSUE TITLE
Icon for Unreal Engine 4 editor

### ISSUE THREAD

**Issue by dslul** [numixproject/numix-icon-theme-circle#2276]
Here is the original:

![icon76](https://cloud.githubusercontent.com/assets/6121202/8132352/6ec3b540-1121-11e5-8c1e-043bed134f3e.png)

icon=ue4editor

**Comment by Eleuin** [comment]
Oh god yes, loving this issue, i so want to do this

**Comment by bil-elmoussaoui** [comment]
@dslul you forgot the icon name

**Comment by Eleuin** [comment]
Get on the icon name, and ill do this. Mostly because seeing this kind of excited me...

**Comment by dslul** [comment]
I updated the icon name, however when compiling one has to create the .desktop file manually
