### ISSUE TITLE
file-manager.svg needs fixing

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2278]
There's multiple layers and grey objects under the baseplate and the gradient is wrong (it's not L10).

**Comment by wa4557** [comment]
@gregorydk This should also be fixed in the `numix-folder` repository. Because each time a user selects a custom folder style the error will be restored

**Comment by palob** [comment]
There's probably more with the grey objects, it's only apparent together with light colours. I've already fixed a few with https://github.com/numixproject/numix-icon-theme-circle/commit/7cb73cd4ce356dc7a6ca10ca4809eb51e7147cb3.

**Comment by palob** [comment]
Fixed meanwhile here and in the ``numix-folders`` repo.
