### ISSUE TITLE
nm-device-wireless.svg needs a circular version

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2285]
This one can probably not be fixed but in Notifications in GNOME Control Center the 'Network' icon isn't circular. So `nm-device-wireless.svg` which is in numix-icon-theme should be circular if possible.

**Comment by dirtydancing** [comment]
Thank you for reporting! Could you please provide a screenshot of this issue and report which distro/GNOME version you are running.

I am running Arch/GNOME 3.16, and in the GNOME system settings the `Network` setting is a Circle icon, as well as the `Network` icon in the Notifications settings, cf. this screenshot:

![network](https://cloud.githubusercontent.com/assets/7164227/8182542/997ff9c6-1430-11e5-9bf5-98d685a71854.png)

And you are right: arguably this issue is a won't fix. `nm-device-wireless.svg` has been removed from Numix-Circle earlier on purpose, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/1361.

**Comment by gregorydk** [comment]
Your screenshot looks good, mine doesn't. I'm using Debian with GNOME 3.16 with latest Numix.

![screenshot-notifications](https://cloud.githubusercontent.com/assets/7804464/8183304/54dc6104-1437-11e5-84a6-86cb0082b11b.png)

**Comment by dirtydancing** [comment]
Well, this is strange, and it reminds me of an earlier version of Lubuntu that also used `nm-device-wireless.svg` for the system settings, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/154.

`nm-device-wireless.svg` does not really fit into Numix-Circle, as it is neither an app icon nor a system preferences icon, but rather a device icon or a status icon. The borders between Numix-Circle and Numix base in this area are somewhat blurry, though.

Moreover, including `nm-device-wireless.svg` in Numix-Circle again would probably break consistency in several notification systems (e.g. in Ubuntu/Xubuntu).

It would be interesting to see how other distros with GNOME are handling this.

**Comment by dirtydancing** [comment]
@palob Would you fancy to have a look at how the `Network` icon is displayed in the GNOME Notification settings in Fedora (Numix-Circle icon or Numix base icon)?

@wa4557 Do you happen to be aware if `nm-device-wireless.svg` is used somewhere else in Ubuntu, where adding this icon to Numix-Circle would break consistency within Ubuntu?

**Comment by wa4557** [comment]
@dirtydancing Yes. It is used as the notification icon when establishing a wireless network connection. Therefore we added `nm-device-wireless` to `48x48/notifications`...

**Comment by palob** [comment]
Circle icon in Fedora 21, no Network plug present by default in Fedora 22.

**Comment by gregorydk** [comment]
Other computer has 2 network entries, one with circular icon and another with non-circular icon. Not sure what package is responsible.

**Comment by dirtydancing** [comment]
@wa4557 @palob Thanks!

@wa4557 Yeah, I was actually thinking about somewhere else besides the Ubuntu notification bubble. Anyways, one of the base icons that you contributed has now made its way quite unexpectedly into the settings in Debian/GNOME :)

@gregorydk After all this, to me this looks like a bug in a Debian package. You could always work around it in Numix-Circle by manually adding a symlink `nm-device-wireless.svg` e.g. with the target `network-workgroup.svg`.

@Foggalong I would recommend to NOT add `nm-device-wireless.svg` to Numix-Circle. As far as I can tell, this issue report is the only instance in which this icon is used (inconsistently) for the preferences.

**Comment by Foggalong** [comment]
@gregorydk are you running the latest versions of Circle and Square?

**Comment by dirtydancing** [comment]
@gregorydk Is this Debian testing? iirc Debian 8 is shipping with GNOME 3.14. Maybe this explains it.

**Comment by gregorydk** [comment]
I'm running latest everything.

**Comment by Foggalong** [comment]
This is really weird. Does Debian modify the GNOME sources before packaging? Possibly uses a different network settings manager?

**Comment by wa4557** [comment]
In Ubuntu there is a `.desktop` file named `nm-applet.desktop` that has `Icon=nm-device-wireless`. However it has an entry `NoDisplay=true` hence it is not shown in the dash. @gregorydk Can you check if that is the corresponding `.desktop` file?

**Comment by gregorydk** [comment]
It is.

Icon=nm-device-wireless
Exec=nm-applet
Terminal=false
Type=Application
NoDisplay=true
NotShowIn=KDE;GNOME;

**Comment by Foggalong** [comment]
This is weird as hell

**Comment by wa4557** [comment]
`NotShownIN=KDE;**GNOME**` oO
Can you run `grep -r "Icon=nm-device-wireless" /usr/share/applications/", to see if there's another desktop file?

**Comment by gregorydk** [comment]
No, nm-applet.desktop is the only desktop file.

**Comment by palob** [comment]
What happens after deleting the file (take a backup :) ) or editing it to ``NoDisplay=false`` and deleting the ``NotShownIn`` line?

**Comment by wa4557** [comment]
Well the `NoDisplay=true` [should prevent it from being shown] (https://linuxcritic.wordpress.com/2010/04/07/anatomy-of-a-desktop-file/), so setting it to false won't change a lot. I strongly doubt that this is the corresponding desktop file as there are two entries that should be enough to keep it hidden. @gregorydk Are you sure that there's no other desktop file that has the `Icon=nm-device-wireless` entry? If not try to delete it and check if it is really this desktop file.

**Comment by Foggalong** [comment]
(cut and paste it to a backup location rather than deleting in case you need it back)

**Comment by gregorydk** [comment]
If I remove nm-applet.desktop, the entry in the Notifications window for Network is gone.

**Comment by dirtydancing** [comment]
What is the icon for Network that is showing in your Control Center overview (not in the Notification settings)? In Arch/GNOME, this is also the Numix-Circle icon, the same one as in the Notification settings. Screenshot:

![settings](https://cloud.githubusercontent.com/assets/7164227/8249948/77347cca-166f-11e5-8f1f-6dbec5ca4f3d.png)

**Comment by gregorydk** [comment]
That one is the correct one.

**Comment by dirtydancing** [comment]
When the nm-device-wireless.svg icon is showing in the Notification settings of GNOME Control Center, is it also showing as an app in the activities icon overview of GNOME Shell?

**Comment by dirtydancing** [comment]
And what is displayed when you click on the `Network` icon in the Notification settings. Does it look like this in Arch/GNOME?:

![notifications-network](https://cloud.githubusercontent.com/assets/7164227/8250767/1e1444d8-1677-11e5-83ee-608a481aa96f.png)

**Comment by palob** [comment]
@gregorydk Are you using plain Unstable or did you install GNOME 3.16 manually on Stable/Testing?

**Comment by dirtydancing** [comment]
Just as a point of reference: In my Arch/GNOME (3.16) setup, there is no .desktop file with the icon line `Icon=nm-device-wireless`

The relevant .desktop file appears to be `gnome-network-panel.desktop`, and the icon line for that one is `Icon=network-workgroup`

**Comment by dirtydancing** [comment]
Or possibly `nm-connection-editor.desktop`, with the icon line `Icon=preferences-system-network`

**Comment by gregorydk** [comment]
@palob Unstable.

**Comment by Foggalong** [comment]
@gregorydk @dirtydancing @PaoloRotolo @wa4557 can anyone replicate this on any other system, or even Debian Unstable itself?

**Comment by dirtydancing** [comment]
No (Arch/GNOME 3.16)

**Comment by wa4557** [comment]
No (Ubuntu 15.04)

**Comment by bil-elmoussaoui** [comment]
The same thing in ubuntu 14.04

**Comment by Foggalong** [comment]
GNOME versions too please since I'm guessing that's an integral
 part of this

**Comment by wa4557** [comment]
@dirtydancing tested this already for gnome I guess. I really think this whole thing is really an issue (no offense @gregorydk) I suppose this has something to do with debian unstable, but is probably nothing Numix should care about

**Comment by Foggalong** [comment]
Yeah, I'm thinking thst we're gonna have to close this too. If it's working with the latest versions of GNOME on Ubuntu, Arch, and Fedora then it must be something the Debian packager for the gnome-wcid has accidentally introduced.

Closing, but we'll keep an eye on whether it sticks around or spreads to other systems
