### ISSUE TITLE
Linux mint icons

### ISSUE THREAD

**Issue by erikdubois** [numixproject/numix-icon-theme-circle#2287]
mintNanny.desktop file points to Icon=mintnanny
But there is only a mintNanny.svg link.
Change to Icon=mintNanny

Will post this in hardcore-fixer at foggalong. I believe it can be changed there

mintupload.desktop files point to Icon=mintupload
But there is only a mintUpload.svg
Change to Icon=mintUpload

Will post this in hardcore-fixer at foggalong. I believe it can be changed there

**Comment by Foggalong** [comment]
Replied over there
