### ISSUE TITLE
Icon for lollypop

### ISSUE THREAD

**Issue by sevachka** [numixproject/numix-icon-theme-circle#2288]
Hi, a Numix-Circle icon is missing for Lollypop Music-Player

Icon line: Icon=lollypop

original Icon attached.
Thank you!
![lollypop](https://cloud.githubusercontent.com/assets/11356897/8193266/1b44e5fa-1474-11e5-9d41-71db21f9314a.png)

**Comment by palob** [comment]
There has been [one](https://github.com/numixproject/numix-icon-theme-circle/commits/master/Numix-Circle/48x48/apps/lollypop.svg) for about six months.

You might be using an outdated version of Numix Circle.

**Comment by Foggalong** [comment]
@sevachka I'm so confused, how are you running a version that out of date? O.o

**Comment by sevachka** [comment]
sorry! I mixed it up with numix-square! I realized that mistake now.... is there a chance to get it for numic-square? I am using Antergos.

**Comment by Foggalong** [comment]
Square is in the slow process of being updated :) it'll get there eventually
