### ISSUE TITLE
vlmc.svg baseplate is too big

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2289]
baseplate is 47px instead of 46px in height.
@Foggalong Any chance you remember which icon you took the baseplate from (in case this issue is present for more icons)?

**Comment by Foggalong** [comment]
That was from `mkv-extractor-gui.svg`. From what I can see it's not the baseplate being missized, it's that the whole icon is 1px too high? Regardless I've pushed a fix :)
