### ISSUE TITLE
Icon for Google Photos

### ISSUE THREAD

**Issue by barcia** [numixproject/numix-icon-theme-circle#2296]
Icon for Google Photos web app.

This is the default icon:
![](https://www.considerednormal.com/wp-content/uploads/2014/02/Google-Photos-icon-logo.png)

**Comment by Foggalong** [comment]
What's the name of the chrome app icon? We need that to make ours :)

**Comment by palob** [comment]
There is [this] and I presume the resemblance isn't accidental :)

**Comment by Foggalong** [comment]
Yeah, that's the icon. Because this is missing information we can't fix it :(
