### ISSUE TITLE
Pypar2 has no icon for numix-circle

### ISSUE THREAD

**Issue by erikdubois** [numixproject/numix-icon-theme-circle#2300]
http://pypar2.silent-blade.org/

**Comment by dirtydancing** [comment]
Thanks for reporting!

When reporting missing icons, please always include the icon line of the .desktop file and the original icon, cf. guidelines for icon requests in the readme pointing to this tutorial:

https://plus.google.com/+NumixProjectOrg/posts/DkRmhFZuWez

Also additional info can be useful, cf. e.g. this issue report: https://github.com/numixproject/numix-icon-theme-circle/issues/2036

**Comment by erikdubois** [comment]
strange i had copy/paste the complete .desktop code... ofcourse ...
so once again

[Desktop Entry]
Name=PyPar2
Comment=A graphical frontend for the par2 utility
Encoding=UTF-8
Exec=pypar2
MimeType=application/x-executable
Terminal=false
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Application
Icon=pypar2
