### ISSUE TITLE
Openoffice 4

### ISSUE THREAD

**Issue by erikdubois** [numixproject/numix-icon-theme-circle#2301]
Just installed openoffice and added these links to have the icons

ln -s ooo-base.svg openoffice4-base.svg
ln -s ooo-calc.svg openoffice4-calc.svg
ln -s ooo-draw.svg openoffice4-draw.svg
ln -s ooo-impress.svg openoffice4-impress.svg
ln -s ooo-math.svg openoffice4-math.svg
ln -s ooo-printeradmin.svg openoffice4-printeradmin.svg
ln -s ooo-writer.svg openoffice4-writer.svg

**Comment by palob** [comment]
How about the "main icon / startcenter icon" (which launches the startcenter from where you can choose which kind of document to work on)?
Did it show up without further ado?

**Comment by erikdubois** [comment]
oh no sorry
i made a special icon for Icon=openoffice4-startcenter (Not a numix-circle look)
https://github.com/erikdubois/themes-icons-pack/tree/master/Ardis-Sardi%20Icon%20Theme
When visiting this link
http://www.openoffice.org/product/index.html
I do not see anything about web... Is it something you can install extra?
ooo-web.svg and ooo-template.svg do not show up in the menu
