### ISSUE TITLE
icon request for glogg

### ISSUE THREAD

**Issue by rahul8290238014** [numixproject/numix-icon-theme-circle#2302]
icon for apache log viewer like glogg (http://glogg.bonnefon.org/index.html) is missing.

**Comment by Foggalong** [comment]
@rahul8290238014 we need the information set out in the readme to fix icon requests :(

**Comment by palob** [comment]
The official repo has got [Icon=glogg](https://github.com/nickbnf/glogg/blob/master/glogg.desktop) and [this icon](https://raw.githubusercontent.com/nickbnf/glogg/master/glogg48.ico)

Still @rahul8290238014, please add the information. Sometimes distro packagers change something.
