### ISSUE TITLE
Icon for Aria Maestosa

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2312]
"Aria Maestosa is an open-source (GPL) midi sequencer/editor"
http://ariamaestosa.sourceforge.net/

Icon=ariamaestosa
![ariamaestosa-ori](https://cloud.githubusercontent.com/assets/7050624/8273559/d980b19a-1873-11e5-9a60-7bf92d9b67d3.png)

**Comment by palob** [comment]
Any chance for this to be merged?
![ariamaestosa-work-clip2-16](https://cloud.githubusercontent.com/assets/7050624/8273571/2af4d736-1874-11e5-9cc4-d925b19eb878.png)
![ariamaestosa-work-clip2-16](https://cloud.githubusercontent.com/assets/7050624/8273568/1ed6849a-1874-11e5-8d91-8a15578f7de0.png)
![ariamaestosa-work-clip2-256](https://cloud.githubusercontent.com/assets/7050624/8273570/257f392c-1874-11e5-9c02-c9dbe6a15209.png)

**Comment by Foggalong** [comment]
1st itteration fine by me :)

**Comment by palob** [comment]
Btw @Foggalong, is it easier fo you to do the Square icons if I use clipping? I've used intersections n some icons in the past.

**Comment by ChuckDaniels87** [comment]
Really nice icon. :smiley:

**Comment by Foggalong** [comment]
@palob Intersections are just fine :)
