### ISSUE TITLE
Icon for Jamulus

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2341]
Internet Jam Session Software
http://llcon.sourceforge.net/

Icon=jamulus
![jamulus](https://cloud.githubusercontent.com/assets/7050624/8293766/02e5b066-1938-11e5-82e1-365606710a65.png)

**Comment by palob** [comment]
One of these?
![jamulus1](https://cloud.githubusercontent.com/assets/7050624/8293772/0d21d47e-1938-11e5-8450-c2995d6667fe.png)
![jamulus1b](https://cloud.githubusercontent.com/assets/7050624/8293771/0d2130c8-1938-11e5-9442-e4eba3068d61.png)
![jamulus4](https://cloud.githubusercontent.com/assets/7050624/8293770/0d20b12a-1938-11e5-97ac-8023f8aaf8b9.png)
![jamulus4b](https://cloud.githubusercontent.com/assets/7050624/8293773/0d44a3aa-1938-11e5-8579-a847ff81f9ad.png)

**Comment by Foggalong** [comment]
No2 please :)
