### ISSUE TITLE
Icon for WhatsAppForDesktop

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-icon-theme-circle#2348]
http://whatsapp-desktop.com/

[Desktop Entry]
Version=1.0
Type=Application
Name=Unofficial WhatsApp
Icon=whatsappfordesktop
Exec=/opt/WhatsAppForDesktop/UnofficialWhatsApp
Comment=Unofficial WhatsApp for Desktop
Categories=Network;Chat;
Terminal=false
X-Desktop-File-Install-Version=0.22

![whatsapp](https://cloud.githubusercontent.com/assets/11137173/8305368/9fca4bf0-19ae-11e5-94cd-493a3d086ea0.png)

Thanks for your effort.

**Comment by palob** [comment]
Symlink to [chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default.svg)?
