### ISSUE TITLE
KDE IM Contacts > Online status icon

### ISSUE THREAD

**Issue by codemedic** [numixproject/numix-icon-theme-circle#2351]
The below two icons seem missing the make-over.

- [ ] Available status icon in KDE IM Contact list
- [ ] Online status icon in the Notification Area

Thanks very much for the great effort guys!

![kde-im-contact-list](https://cloud.githubusercontent.com/assets/691011/8327816/3841613e-1a63-11e5-8751-de50fc0141ad.png)

![kde-im-online](https://cloud.githubusercontent.com/assets/691011/8327813/2f17e7ea-1a63-11e5-9e6f-ae7800b61f80.png)

**Comment by palob** [comment]
Hi, that's an issue for the [base theme](https://github.com/numixproject/numix-icon-theme).

Do you know the icon name? Possibly it's one of [those](https://github.com/numixproject/numix-icon-theme/issues/580)

From your screenshot's it looks like you're using Numix Circle on KDE.
Aren't you encountering the issue reported in #2016 ?
