### ISSUE TITLE
Icon for Tesseract

### ISSUE THREAD

**Issue by Eleuin** [numixproject/numix-icon-theme-circle#2354]
FPS based on the Cube 2: Sauerbraten engine
![tesseract](https://cloud.githubusercontent.com/assets/5553828/8354106/4727a31a-1b13-11e5-86e6-4273044b44c6.png)
icon=tesseract

**Comment by Eleuin** [comment]
![tesseract_icon](https://cloud.githubusercontent.com/assets/5553828/8354944/10d15c96-1b1a-11e5-8b0b-a769e78f9475.png)
came up with this

**Comment by Foggalong** [comment]
Yeah, definitely too squashed

**Comment by Eleuin** [comment]
slightly less squashed, and the inner cube lighter
![tesseract_icon](https://cloud.githubusercontent.com/assets/5553828/8355140/69e10542-1b1b-11e5-83d9-4f0df4115529.png)
i still feel that inner cube needs tweaking, but maybe its just OCD

**Comment by Foggalong** [comment]
It still looks a little bit distorted  :(

**Comment by Eleuin** [comment]
haha, its insanely tough doing isometric stuff with cube proportions and trying to actually align nodes to the pixel grid xD

**Comment by palob** [comment]
You don't necessarily need to align all nodes to the grid. Just horizontal and vertical lines :)

**Comment by Eleuin** [comment]
haha, good to know
