### ISSUE TITLE
missed circle light icon

### ISSUE THREAD

**Issue by amojtaba** [numixproject/numix-icon-theme-circle#2357]
An icon for goldendict.svg is missing in Numix-Circle-Light.

**Comment by Foggalong** [comment]
Like a panel icon?

**Comment by Foggalong** [comment]
Please add some more information :(

**Comment by amojtaba** [comment]
![missg goldendic icon](https://cloud.githubusercontent.com/assets/12130796/8392339/b77ed38c-1cfc-11e5-9eac-d0b81f954b92.png)
I have Ubuntu OS and the picture is clear.

**Comment by Foggalong** [comment]
That's an issue for the base theme, not for Circle. Might be a problem to fix it too because it has the same name as the app icon :/
