### ISSUE TITLE
Icon for GTKWave

### ISSUE THREAD

**Issue by OSjerick** [numixproject/numix-icon-theme-circle#2358]
Numix-Circle icon for GTKWave is not inside the package.
The icon line says "gtkwave", I'm using the icons package on OpenSUSE. The original icon is attached.

![gtkwave_256x256x32](https://cloud.githubusercontent.com/assets/8047984/8380213/62ab3cb0-1bee-11e5-83bc-47391bd7fc06.png)

**Comment by palob** [comment]
There [is one](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gtkwave.svg).
Seems the package you're using is outdated. So you'd have to ask the packager for an update
Alternatively you can clone the git repo and install the latest theme manually.
Do you know how to?

**Comment by OSjerick** [comment]
Thanks palob, I'm using the [OpenSUSE repo](https://build.opensuse.org/project/show/home:paolorotolo:numix) for numix-icon-theme-circle, I can wait for the packager. I don't know how to use git to clone the repo and manually install it.

**Comment by palob** [comment]
On the [frontpage](https://github.com/numixproject/numix-icon-theme-circle) click **Download ZIP**.
Unzip it and move the folders ``Numix-Circle`` and ``Numix-Circle-Light`` you'll find inside to either ``$HOME/.icons``, ``$HOME/.local/share/icons`` (both local installation) or ``/usr/share/icons``(global installation=for all users).

**Comment by OSjerick** [comment]
Thank you palob.

Cloning the git repo is better? I get updates automatically?

**Comment by palob** [comment]
You'll have the latest and greatest but you'll have to update manually doing the same procedure.

**Comment by OSjerick** [comment]
Ok, great! Thanks again.

**Comment by Foggalong** [comment]
We've dropped support for openSUSE via official packaging. You should have received notification, so sorry if you didn't :(

**Comment by palob** [comment]
Before you do the manual installation you should uninstall the package version prefereably.

**Comment by OSjerick** [comment]
I didn't. Well, I have to install manually. Thanks. Great work!

**Comment by Eleuin** [comment]
```
git clone https://github.com/numixproject/numix-icon-theme-circle.git
cd nu*
sudo cp -r Nu* /usr/share/icons
```
for future reference :smile:

**Comment by palob** [comment]
But before doing the above you maybe need to install ``git`` :)

**Comment by Eleuin** [comment]
:3
