### ISSUE TITLE
some icons are missing on the tray/panel

### ISSUE THREAD

**Issue by esn89** [numixproject/numix-icon-theme-circle#2361]
Everything seems to work system wide.  At the moment, the programs causing me the problems are Chromium and the termite terminal.

In the system and xfce4 application launcher, I can see termite and chromium icons no problem:  http://i.imgur.com/IP0ZKB1.png

However, once we get to the panel it does this: http://i.imgur.com/XpjZX1u.png as you can see, the taskbar icons of my browser and termite are little white squares.

anyone know a fix for this?

**Comment by Foggalong** [comment]
This is a problem with the XFCE panel and can't be fixed on our end :( as a fellow XFCE user though I just use the [DockBarX XFCE panel plugin](http://www.webupd8.org/2013/03/dockbarx-available-as-xfce-panel-plugin.html) to get around it

**Comment by esn89** [comment]
still no luck:  http://i.imgur.com/8zXeZLy.png

i'm using xfce my self as well. how did you configure yours?

**Comment by Foggalong** [comment]
I don't have it installed on this PC, but if you go to system settings you should see some options to modify appearance. I know some of them at least make the icons show properly :)

**Comment by esn89** [comment]
where in systems setting do you mean?  dockbarx only has preferences

**Comment by Foggalong** [comment]
Yeah, in the preferences!

**Comment by esn89** [comment]
Thanks. I'll give it a shot tonight

**Comment by esn89** [comment]
when I go into dockbarx preferences, this is all I see:

http://i.imgur.com/Bn4kJeq.png

is yours any different?  still nothing indicating that I can modify the icons to make them sho wproperly :/

**Comment by Foggalong** [comment]
You need to go to the main preferences in the XFCE settings.

**Comment by esn89** [comment]
If you mean Settings -> Appearance  then that has already been done.  I've set my theme to Numix and the icon theme to Numix-Circle-Light.  But still no dice.

**Comment by Foggalong** [comment]
NOOOOOOO. If you bring up the main XFCE Settings Manager there's a new option called DockBarX Preferences

**Comment by esn89** [comment]
oooooooh.   haha...wow.   thank you, even though that took a very, very, long time to do

**Comment by Foggalong** [comment]
Not a problem :) It's not a specific option to display the icons, but just some of the styles available are make the icons show and some don't so it's just a case of playing around until you find one that suits you

**Comment by esn89** [comment]
Sorry to turn this into a dockbarx tech-suppor forum, this is the last message I will send.  Ever.   hahaha

Is there a way to make dockbarx display the icons AND the window title/name?
