### ISSUE TITLE
Gdebi has no circular icon

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2367]
In gdebi.desktop: Icon=gnome-mime-application-x-deb

Can this be fixed?

**Comment by bil-elmoussaoui** [comment]
Duplicate of #1452

**Comment by palob** [comment]
The current icon line points to a mimetype icon name.

To fix it you have to change the icon line to ``Icon=gdebi`` manually or run the [hardcode fixer script](https://github.com/Foggalong/hardcode-fixer).
