### ISSUE TITLE
Need Volume Normal icons ;-)

### ISSUE THREAD

**Issue by xiangzhai** [numixproject/numix-icon-theme-circle#2368]
Hi Numix designers,

Thanks for your great icons, it is so beautiful! but the Volume Normal icons are too transparent, show as below:

![numis-circle-screenshot1](https://cloud.githubusercontent.com/assets/851100/8468237/3dd2c7de-209c-11e5-88a7-f69e19dad618.png)

I am developing the volume control applet for Elsa Shell https://github.com/AOSC-Dev/elsa-shell there are symbolic (svg) icons available, could you design the Volume Normal icons? thanks a lot!

Regards,
Leslie Zhai

**Comment by xiangzhai** [comment]
Also network wifi icon is too transparent ;-)

![numix-circle-screenshot2](https://cloud.githubusercontent.com/assets/851100/8470256/d6b9c8c6-20ba-11e5-8a1e-123243d7f9da.png)

**Comment by palob** [comment]
It's an issue for the [base theme](https://github.com/numixproject/numix-icon-theme).

That said, I don't think it's possible to change the colour as the icons are mostly shown on dark panels such that a certain contrast is needed. Maybe it's possible to have an additional dark version or to change the colour on your side. Isn't it a shell theme thing?

In your screenshot the *volume-low* icon actually does show up dark in the panel. Is this a Numix icon?

**Comment by dirtydancing** [comment]
@xiangzhai Which distribution is this? Esp. which DE/Shell?

To me, in the panel in the lower right, it looks like the volume icon is a "symbolic"-named Numix icon (these can be colour-themed by the respective GTK theme), whereas the volume icons in center screen are not "symbolic"-named. On the other hand, the network icons in the lower right appear not to be "symbolic"-named, which makes for a somewhat odd mix.

Basically, in Numix base there are two different sets of "system" icons (volume/network/battery etc.), one set for the fixed size directories (16x16, 22x22 and 24x24, used e.g. by Unity, Xfce) and another one for the scalable directory (used by GNOME Shell). All of these icons are .svg icons.

And as @palob already said, the colour of these icons is like this on purpose, in **Numix** light icons for dark panels, and in **Numix-Light** dark icons for light panels.
