### ISSUE TITLE
Icon for KRDC

### ISSUE THREAD

**Issue by Telmur** [numixproject/numix-icon-theme-circle#2369]
A numix-circle icon for KRDC is missing.
The Icon line says "krdc" an the original Icon is attached.
![krdc](https://cloud.githubusercontent.com/assets/13147931/8473261/66a98588-20a8-11e5-9bb8-6ba752489f2a.jpg)

**Comment by palob** [comment]
The icon [exists](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/krdc.svg).
You must be using an outdated version of Numix Circle, the PPA version I suppose?
