### ISSUE TITLE
Icon for Soap UI

### ISSUE THREAD

**Issue by Ghokun** [numixproject/numix-icon-theme-circle#2382]
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=SoapUI-5.1.3
Exec=/bin/sh "/opt/SmartBear/SoapUI-5.1.3/bin/SoapUI-5.1.3"
Icon=/opt/SmartBear/SoapUI-5.1.3/.install4j/SoapUI-5.1.3.png
Categories=Application;

seems to be hardcoded

![soapui-5 1 3](https://cloud.githubusercontent.com/assets/3802058/8522198/24748a74-23f4-11e5-8fca-e7507a84dd05.png)

**Comment by palob** [comment]
There is one: [soapUI.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/SoapUI.svg) or the symlink ``soapui.svg``.

**Comment by Ghokun** [comment]
I searched the repo with the keyword "soap" but could not find the icon you linked.

Desktop file is: SoapUI-5.1.3.desktop
