### ISSUE TITLE
Icon for Plague Inc. Evolved (Steam & Android)

### ISSUE THREAD

**Issue by Uberfap** [numixproject/numix-icon-theme-circle#2385]
Game: Plague Inc. Evolved
AppID: 246620
Icon: 
![unityplayer](https://cloud.githubusercontent.com/assets/10727423/8544409/0a5975c4-249d-11e5-918d-bced4969dd26.png)
Notes: This is a game about the player controlling a plague to destroy the world, and the rating is in form of Biohazards like on the provided icon

**Comment by bil-elmoussaoui** [comment]
This icon can be added to Numix Circle for android too

**Comment by Uberfap** [comment]
Yes indeed
