### ISSUE TITLE
Icon for netbeans

### ISSUE THREAD

**Issue by ameya1** [numixproject/numix-icon-theme-circle#2388]
Request for icon for netbeans.

Netbeans run through a shell script.
The location for the netbeans icon is given in the shell script(location: Netbeans/bin/netbeans.sh) as
-J-Xdock:icon=$basedir/nb/netbeans.icns.
where $basedir is the location of the netbeans folder.

![netbeans](https://cloud.githubusercontent.com/assets/8477095/8555413/a97d09d4-250d-11e5-922a-1a39a1e2dcf9.png)

Thanks

**Comment by palob** [comment]
Huh? What's your distro and how did you install it?

Anyway, there is a [Netbeans icon](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/netbeans.svg).

You have to change the path in the script to ``.../Numix-Circle/48x48/apps/netbeans.svg`` where ``...`` is the path to your Numix Circle installation.

**Comment by ameya1** [comment]
My distro is Mint and i found the icon i also specified its location in the shell file but i am still getting the old icon.

The way i installed it was i ran the sh file of installation and specified my home directory. If its wrong can you tell me the right way for installation.

Thanks

**Comment by palob** [comment]
Well, you need to find out where your ``Numix Circle`` directory is.
