### ISSUE TITLE
Qbittorrent icon not being applied in xfce panel

### ISSUE THREAD

**Issue by fa54a5s5s5s5** [numixproject/numix-icon-theme-circle#2392]
Hey folks,

On Xubuntu 15.04 with Xfce 4.12 it seems that the Qbittorrent icon is not themed at all. Using the latest stuff from the numix repos. Using it with Numix GTK3 theme too. It is themed properly in the whisker menu but just not in panel. Can someone help me figure out how to fix this?

Thanks

![screenshot_2015-07-08_19-48-53](https://cloud.githubusercontent.com/assets/13235129/8567637/60c6ea8c-25aa-11e5-907e-83acdd53f0b8.png)

**Comment by Foggalong** [comment]
See #2361 for more information

**Comment by fa54a5s5s5s5** [comment]
Thanks for letting me know. Keep up the good work. I still love you Xfce ;-)

**Comment by Foggalong** [comment]
XFCE is my DE of choice too :)

**Comment by fa54a5s5s5s5** [comment]
Nice! For future reference is there any way to manually edit a file or config within qbittorrent to *force* it use a specific icon? Qbittorrent must have to find it's stock icon from somewhere right? Appreciate the help.

**Comment by Foggalong** [comment]
There will be, but it will differ for every single app and I wouldn't even know where to start looking.
