### ISSUE TITLE
No Update icon In KDE Plasma Statusbar

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [numixproject/numix-icon-theme-circle#24]
In KDE Plasma 5.8, the numix circle icon theme doesn't have an icon for the icon that appears when updates are available.

**Comment by palob** [comment]
Is it this issue? https://github.com/numixproject/numix-icon-theme/issues/1141

**Comment by KUPOinyourWINDOW** [comment]
It is, my apologies.
