### ISSUE TITLE
Icon android sdk

### ISSUE THREAD

**Issue by ikibits** [numixproject/numix-icon-theme-circle#2400]
Please add icon for android-sdk, I like the project, thanks

**Comment by palob** [comment]
Could you please add the needed information specified in the [video tutorial](https://plus.google.com/+NumixProjectOrg/posts/DkRmhFZuWez)?

**Comment by ikibits** [comment]
App : Android-sdk
Icon: ![android-sdk](https://cloud.githubusercontent.com/assets/3784449/8631119/623c7a08-2735-11e5-8020-7ab020e3460a.png)
Notes: This icon is similar to android-studio
![search-gnome](https://cloud.githubusercontent.com/assets/3784449/8631307/d9189e92-2738-11e5-8aac-39d84cdcbd1a.png)

**Comment by Foggalong** [comment]
We need the actual icon name too :)

**Comment by ikibits** [comment]
I hope this helps:
[Desktop Entry]                                                                                                                                  
Encoding=UTF-8
Name=Android SDK 
Comment=Android Sofware Development Kit 
Exec=android
Icon=android-sdk
Terminal=false
Type=Application
Categories=IDE;Development;

**Comment by ikibits** [comment]
Icons android-studio and android-sdk are similar, I would recommend this could change:
![sdk_manager](https://cloud.githubusercontent.com/assets/3784449/8631429/534aa8f2-273b-11e5-9161-476a377d210b.png)

Because android-sdk is a package manager, and when the application is running the icon changes like this:
![iconandroid-sdk](https://cloud.githubusercontent.com/assets/3784449/8631451/036c3426-273c-11e5-9436-a4f6a1adfa99.png)

**Comment by palob** [comment]
So Android SDK and Android SDK manager are exactly the same?

**Comment by ikibits** [comment]
It is true, I do not understand because you switch icon
