### ISSUE TITLE
Icon for GpsPrune

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2402]
Website: http://activityworkshop.net/software/gpsprune/

Icon=/usr/share/pixmaps/gpsprune.xpm

![gpsprune](https://cloud.githubusercontent.com/assets/7804464/8637730/8347954e-28a1-11e5-8f9b-cdc9d65c34b8.png)

**Comment by Foggalong** [comment]
Hardcoded duplicate of #1977. Report this to tye hardcode fixer or manually change the icon line :)

**Comment by gregorydk** [comment]
Sorry, need to learn to check for duplicates.
