### ISSUE TITLE
ClipIt Tray Icon issue

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-icon-theme-circle#2408]
I'm not sure if this is the correct place for this:
With today's PPA update I've got my good old monochrome ClipIt Tray Icon (```clipit-trayicon.svg``` symlinked to ```clipman.svg``` under ```/22x22/status```)  replaced with a regular App icon in a red circle.
I wonder which new change caused this so that I know how to go back to the previous state.

**Comment by Foggalong** [comment]
This is a problem with the clipit app. You need to file an issue with the developers to get them to rename their app icon from `clipit-trayicon.svg` to just `clipit.svg`. See #190 and #192 for more information.

**Comment by Sadi58** [comment]
OK, thanks...

**Comment by Foggalong** [comment]
We've basically just stopped supporting apps which use non-standard naming schemes in their icons. Specifically, ones which use the same name for both the general app icon and the tray icon.
