### ISSUE TITLE
Are info.svg and help.svg app icons?

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2412]
Or does any application use it for its launcher icon?
You've probably seen something like this where the Circle icons ``help.svg`` and ``info.svg`` show up where they shouldn't.

![help](https://cloud.githubusercontent.com/assets/7050624/8757563/8b3697da-2cdb-11e5-96ad-df5ad108676d.png)
![info](https://cloud.githubusercontent.com/assets/7050624/8757562/8b366de6-2cdb-11e5-98fc-3c05b554fa09.png)

We haven't got action icons named ``help`` and ``info`` yet.

Just to show it's really ``help.svg`` and ``info.svg`` this is how it looks after removing ``info.svg`` and renaming ``2048.svg`` to ``help.svg``:
![help2](https://cloud.githubusercontent.com/assets/7050624/8759388/203e0e6e-2cf3-11e5-985b-7efbeeb25ed8.png)
![info2](https://cloud.githubusercontent.com/assets/7050624/8759401/53726fc8-2cf3-11e5-9b5f-11982d4c18f8.png)

@bil-elmoussaoui Was this what caused the issue you reported [here](https://github.com/numixproject/numix-icon-theme/issues/190#issuecomment-89869828)?

**Comment by bil-elmoussaoui** [comment]
Yeah, if you do merge Circle & Base, base icons will show instead of circle ones. I have no idea if there used by any application

**Comment by palob** [comment]
In this case deleting them from Circle (while watching out for symlinks) and adding a symlink for ``info.svg`` to base should do the trick.

**Comment by palob** [comment]
Same goes for ``snap.svg`` which shows up in Inkscape. Is any application using it?

**Comment by Foggalong** [comment]
The stock_thing icons are really weird. As far as I can tell they all come from really old apps but are still used here and there both as app icons and action icons.

**Comment by Foggalong** [comment]
`info.svg` was added during a [big commit](https://github.com/numixproject/numix-icon-theme-circle/blob/adc6a87dd152f02a931e80d39836a1f474aa9de1/Numix-Circle/48x48/apps/info.svg) which brought us on par with Faenza. I think we can probably remove it and replace it with a symlink to one of the appropriate status icons.

`help.svg` is much older - it's been in Numix since it's [initial commit](https://github.com/cldx/numix/blob/ba7eab1e512031f879f50e25c7bcc00ffa76cac2/apps/48/help.svg) 2.5 years ago, always as an app icon. Not 100% sure how we go about tracing which app is using it though :(

**Comment by Foggalong** [comment]
@palob I've just realised that we do actually have an info.svg in base already :/

**Comment by wa4557** [comment]
I would be less careful about that. In my opinion those are not app icons and therefore do not belong to circle. Iirc we already removed a few icons from circle that used to be there for a very long time (`mail.svg`, `weather-clear.svg` etc..).
The thing is: if I'd open a issue report asking to add for example `error.svg` because I found an app that uses this as an app icon, you'd probably mark it as a wontfix because it would induce breakage in base.

**Comment by Foggalong** [comment]
tru dat

**Comment by palob** [comment]
So should we venture removing all from Circle?

**Comment by Foggalong** [comment]
I'm not sure - when you were testing did you find that removing `info.svg` broke the icon rather than it picking up the status icon from base?

**Comment by palob** [comment]
Hmm, removing breaks the icon. Even copying the base ``info.svg`` from ``status`` to ``actions`` doesn't seen to fix it.

**Comment by wa4557** [comment]
icon-cache thing?

**Comment by Foggalong** [comment]
O.o

**Comment by palob** [comment]
No, took care of the cache. What this shows is that it wasn't ``info.svg`` but an icon which symlinks to it.

**Comment by Foggalong** [comment]
Ah, that would explain it!

**Comment by palob** [comment]
Adwaita hasn't got any ``info.svg`` but shows a 4-point star. Looking for it.

**Comment by palob** [comment]
It was ``help-about.svg`` from the list above.

**Comment by palob** [comment]
But why the icon wasn't inherited from ``gnome`` and broken instead?

**Comment by palob** [comment]
Strangely enough I'm not able to get rid of the Circle icon (which broke before) in one particular place by removing ``help-about.svg`` and ``stock_about.svg``. 

Btw, the app I'm currently testing with is Linphone.

Maybe this is the kind of "mystery" like Nemo displaying ``nemo.svg`` when Circle is in use but ``nemo-eject.svg`` with only Numix base used for the drive eject button.

**Comment by palob** [comment]
Maybe it's possible for GTK applications to define different icon names and choose what's found in the icon theme (+depending on some kind of priority).

**Comment by palob** [comment]
The ``nemo.svg`` issue possibly is due to a ``GTK_ICON_LOOKUP_GENERIC_FALLBACK`` flag used.
Cf. [here](https://developer.gnome.org/gtk3/stable/GtkIconTheme.html#GtkIconLookupFlags)

**Comment by wa4557** [comment]
Interesting. That's most probably also the reason for #190. Who needs this; this is complete useless?

**Comment by palob** [comment]
Ouch, the Circle icon just didn't cease to show up since Linphone remains up an running after clicking the ``X`` (as indicated by the tray icon).
The icon shown was ``help_about.svg``.

@Foggalong Now to correctly respond to your [question](https://github.com/numixproject/numix-icon-theme-circle/issues/2412#issuecomment-124173077): it does pick up ``help-about`` from base.

**Comment by palob** [comment]
Is there any evidence the icons are needed in Numix Circle so far?

**Comment by Foggalong** [comment]
I don't think so thus far :)
