### ISSUE TITLE
Spotify changed colors on their default icon

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-icon-theme-circle#2414]
Spotify has upstream changed their default green color to a more 'lime green' color, side by side can be seen here:

http://cdn2.trymodern.com/wp-content/uploads/2015/06/spotify-new-color-800x450.jpg

Perhaps we should adjust ours to match

**Comment by Ghokun** [comment]
https://github.com/numixproject/numix-icon-theme-circle/pull/2242

**Comment by wa4557** [comment]
Why did they do this? The new colour is awful imo :(

**Comment by Foggalong** [comment]
Yeah, its not great

**Comment by Ghokun** [comment]
Made the waves a little larger (32x21 as rectangle) and changed color

![spotify-client_2](https://cloud.githubusercontent.com/assets/3802058/8820169/b96f78b4-305b-11e5-86e9-cad57c912be8.png)

**Comment by Foggalong** [comment]
Why the size increase? Remember our guidelines for non-circular symbols is 24px² to 26px²

**Comment by palob** [comment]
The black looks a bit harsh in contrast to the background.

**Comment by Ghokun** [comment]
I made it to see how the original icon fits the theme. To be honest I don't like the current spotify icon design in numix circle. If this is not appropriate I will not send any pr.

**Comment by Foggalong** [comment]
You don't like the symbol size?

**Comment by Ghokun** [comment]
I think the current symbol size is too small.

**Comment by palob** [comment]
Well, you're probably coming from the original icon. 
Then again there are Numix Circle icons which aren't remotely similar to the original design.

I second @Foggalong that 32px width definitely looks big on the baseplate.

**Comment by Foggalong** [comment]
Yeah, I'm not really sure where you're coming from in making it more similar to the other icons in design. This is further from the circle guidelines not closer - a recolor of the current icon is all that's needed.

**Comment by Ghokun** [comment]
Well that was just a suggestion ...

**Comment by Corsseir** [comment]
When are you going to recolor current icon?

**Comment by brittyazel** [comment]
They already did, albeit the new color isn't exactly the right hue

**Comment by Corsseir** [comment]
I got update for numix circle icons today but i dont have new Spotify icon...

**Comment by Foggalong** [comment]
[It's in the latest version](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/spotify-client.svg)
