### ISSUE TITLE
Icon for ckb

### ISSUE THREAD

**Issue by AdamNiederer** [numixproject/numix-icon-theme-circle#2416]
CKB is a driver and profile editor for the Corsair K65, K70, and K95 and their RGB equivalents. It also utilizes an indicator icon of similar description to the primary one.

Desktop file: 
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=ckb
Comment=Corsair keyboard driver user interface
Exec=ckb
Icon=/usr/share/icons/hicolor/512x512/apps/ckb.png

Icon:
![ckb](https://cloud.githubusercontent.com/assets/4571394/8784454/3a065cf8-2ef0-11e5-90a6-5f576cf28916.png)

**Comment by palob** [comment]
So is this a program to change the colour of keyboard illumination?

**Comment by AdamNiederer** [comment]
Yes, it's used for changing keyboard illumination color, animations, and intensity on RGB models, and is also used to rebind keys and update keyboard firmware. https://github.com/ccMSC/ckb

**Comment by palob** [comment]
![ckb](https://cloud.githubusercontent.com/assets/7050624/8788360/20ca1096-2f3a-11e5-8b8d-54302c07152d.png)
How about this one? Too garish?

**Comment by dirtydancing** [comment]
Nice one! :+1:

**Comment by AdamNiederer** [comment]
That's awesome! Thanks so much!

**Comment by Foggalong** [comment]
That's great :D
