### ISSUE TITLE
Gedit shows up as white circle in top bar.

### ISSUE THREAD

**Issue by rockon999** [numixproject/numix-icon-theme-circle#2429]
I'm not positive if this is Numix's fault, but this has been a consistent problem for a while. In the Gnome Shell top bar Gedit shows up as a white circle while other  apps show the correct icons. I've included relevant screenshots.

![13](https://cloud.githubusercontent.com/assets/2943271/8890635/2a551552-32cd-11e5-91db-bd2a00ea0a4f.png)
![12](https://cloud.githubusercontent.com/assets/2943271/8890636/2a60bc7c-32cd-11e5-94fb-660de212da52.png)
![11](https://cloud.githubusercontent.com/assets/2943271/8890637/2a6f6b50-32cd-11e5-9c4a-4a4f1fa76a61.png)

**Comment by palob** [comment]
It's related to [this issue](https://github.com/numixproject/numix-icon-theme/issues/485) of the base theme.

The white circle is the monochromated Numix Circle icon.
It's strange however. Actually you should be seeing a ``...-symbolic icon``.

Do you use Numix Circle only or the Numix base theme as well?
Could you add ``Adwaita`` to the ``Inherits`` line of the ``index.theme`` of you Numix base installation and see what is shown then?

Anyway, the only way to get consistency (i.e. no symbolic-polychrome icon mixture) is to disable the AppMenu icons altogether using the Gnome Shell extension [Hide App Icon](https://extensions.gnome.org/extension/810/hide-app-icon/)

**Comment by rockon999** [comment]
I've tried adding Adwaita as an inheritable and removing Numix and relying solely on Adwaita. Neither changed Gedit's icon.

**Comment by palob** [comment]
So it's still the circle after changing back to Adwaita as icon theme?
How did you install Numix Circle?

**Comment by rockon999** [comment]
No sorry. In index.theme I tried the following...
Inherits=Adwaita
Inherits=Numix,Adwaita

Installed it using AUR's git package. (https://aur.archlinux.org/packages/numix-circle-icon-theme-git/)

I double checked and reinstalled using the latest from github and the bug persists.

**Comment by rockon999** [comment]
If it helps... the bug doesn't affect Numix base when it is set as the icon theme.

**Comment by palob** [comment]
I can confirm this. Just didn't notice it because I never turn off the extension.

Found the reason for the bug: It's ``accessories-text-editor-symbolic.svg`` in Numix Circle.
After removing it you'll get the symbolic icon from Adwaita.

**Comment by rockon999** [comment]
Okay. I've got a fix. In your current Gnome Shell theme replace the following code (if you have it):

#panel .panel-button .app-menu-icon {
    -st-icon-style: symbolic;
}

with...

#panel .panel-button .app-menu-icon {
    -st-icon-style: regular;
}

(restart shell)

Normal icons again! No monochromatic craziness!

**Comment by rockon999** [comment]
@palob Try this out. It's an extension that changes the style without messing with themes. https://github.com/rockon999/appmenu-regular-icons

**Comment by palob** [comment]
@rockon999 Editing the Adwaita Shell stylesheet never did and still doesn't have any effect for me but your extension works! Thanks a lot :+1:

**Comment by dirtydancing** [comment]
I can confirm the circle monochromatic icon as the active app icon in the top bar of GNOME Shell 3.16 with Arch/GNOME. This happens because a Numix-Circle icon is used, and as in this case a "symbolic"-named icon exists in Numix-Circle, this icon is then "coloured" by the GTK theme (which is possible because the icons is "symbolic"-named), so it turns into a completely white circle.

The question for me is: why is there a symbolic icon in Numix-Circle at all, in this case `accessories-text-editor-symbolic.svg`? imo this icon should be removed from Numix-Circle.

Apparently, currently there is only one other symbolic icon in Numix-Circle, `gnome-do-symbolic.svg`.

**Comment by Foggalong** [comment]
I've done some looking through the git history and both can be safely removed I think. Gonna do that now :)

**Comment by dirtydancing** [comment]
Great! :+1:
