### ISSUE TITLE
Gnome contact icon should be removed

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2440]
Hello,
The Gnome Contact icon is using a mimetype icon name instead of a normal icon name and there's a symlink/icon to that on Numix-Circle. It's the same case as #2367 
The icon line :  `Icon=x-office-address-book` , this should be fixed using hardcode-fixer ;)

**Comment by bil-elmoussaoui** [comment]
There's already a mimetype icon with the same name in Numix Base

**Comment by Foggalong** [comment]
Do you know which app it is that uses this?

**Comment by bil-elmoussaoui** [comment]
It's Gnome Contacts, the desktop file name is  ` org.gnome.Contacts.desktop`

**Comment by palob** [comment]
On the other hand what's the mimetype icon used for? I've never seen a Numix Circle icon show up in place of a mimetype one.

**Comment by Foggalong** [comment]
Yeah, mimetypes seem to be pretty good at showing up where they should, it's the app icons that are a PITA.

**Comment by palob** [comment]
I mean as long as the app icon ``x-office-address-book`` doesn't cause too bad an issue I'd rather keep it than point users to the hardcode-fixer for a Gnome core app.

**Comment by bil-elmoussaoui** [comment]
It's the same case as for Gdebi, the mimetype does not look circle neither; we should remove the symlink to `x-office-address-book` or add the one for Gdebi

**Comment by palob** [comment]
But GDebi isn't a GNOME app + the "GDebi mimetype" is used for DEB packages.

**Comment by bil-elmoussaoui** [comment]
Well, in the official gnome theme, the mimetype look like an application icon :/ I reported this here after using Ozon icon theme and the mimetype icon  was shown instead of the application icon (if they have one)

**Comment by Foggalong** [comment]
@palob @bil-elmoussaoui If we add a gdebi icon with the same name as the mimetype, will that show up in the place of the mimetypes?

**Comment by bil-elmoussaoui** [comment]
I just tried that; and it's not ;) everything works fine like for gnome contacts

**Comment by palob** [comment]
Yeah, looks like DEB packages still show up correctly with ``gnome-mime-application-x-deb.svg`` in Numix Circle.
