### ISSUE TITLE
Google Calendar Icon

### ISSUE THREAD

**Issue by snydox** [numixproject/numix-icon-theme-circle#2442]
Google updated it's calendar icon in favour of Material Design. I feel the Numix Icon needs an update as well.

Chrome App: https://chrome.google.com/webstore/detail/google-calendar/ejjicmeblgpmajnghnpcppodonldlgfn

![selection_007](https://cloud.githubusercontent.com/assets/13590875/9045401/8336e21e-39e8-11e5-9518-09d425e62794.png)
![selection_008](https://cloud.githubusercontent.com/assets/13590875/9045418/9e7f6af0-39e8-11e5-8c38-f95c15ac0708.png)

**Comment by Foggalong** [comment]
The calendar icon is based on a blue version of our standard calendar icon rather than the Google icon. There are a lot of icons attached to this too so for now it's a wontfix.
