### ISSUE TITLE
Icon for LINE chrome webapp

### ISSUE THREAD

**Issue by nathaneltitane** [numixproject/numix-icon-theme-circle#2444]
New icon request for chrome webapp LINE messenger.

![line_logo_128x128](https://cloud.githubusercontent.com/assets/5674757/9085783/e4cad5e2-3b4d-11e5-8668-d5e89f5ce89f.png)

**Comment by Foggalong** [comment]
Please include the icon line or the link to the chrome page so we know wat to call the icon

**Comment by wa4557** [comment]
https://chrome.google.com/webstore/detail/line/menkifleemblimdogmoihpfopnplikde

**Comment by bil-elmoussaoui** [comment]
we might use this https://github.com/numixproject/com.numix.icons_circle/blob/master/Icons/jp_naver_line_android.svg
