### ISSUE TITLE
Chrome status icon still not themed to monochrome scheme

### ISSUE THREAD

**Issue by nathaneltitane** [numixproject/numix-icon-theme-circle#2445]
![screenshot from 2015-08-05 08-43-55](https://cloud.githubusercontent.com/assets/5674757/9085809/21861c26-3b4e-11e5-9d79-4344f588f966.png)

**Comment by nathaneltitane** [comment]
And also still using unthemed version of the icon... any fix?

**Comment by bil-elmoussaoui** [comment]
First, this is not a Numix circle issue but a Numix base one. The google chrome indicator have a hardcoded icon and those kind of icons are dealt with Hardcode--Tray. Please report thay there so this issue can be fixed, the link is on Numix base readme

**Comment by wa4557** [comment]
Checkout hardcode-tray by @bil-elmoussaoui
