### ISSUE TITLE
Icon for Pokémon online

### ISSUE THREAD

**Issue by Eeveel** [numixproject/numix-icon-theme-circle#2448]
Name=Pokémon Online
Terminal=true
Type=Application

![icon](https://cloud.githubusercontent.com/assets/13693421/9134382/d843d5c8-3d03-11e5-824c-3e5b8ddb2742.png)

Thanks for your beautiful project!

**Comment by Foggalong** [comment]
We need the actual icon name too :)

**Comment by Eeveel** [comment]
The icon name is the one in the icon when I launch it I hope.
Is Pokemon Online.
I compil it from source code and I create a launcher so its a little bit complicate for me. Because the actual version in depo is too old.

**Comment by Foggalong** [comment]
Yeah, we need that icon name (preferably the one from the repo) otherwise we can't make the icon.
