### ISSUE TITLE
Icon for viber

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2450]
This icon is missing.
The icon is in /usr/share/pixmaps/viber.png
![viber](https://cloud.githubusercontent.com/assets/1277920/9149235/2c2edf34-3d77-11e5-8179-f6bb98cda8e9.png)

**Comment by wa4557** [comment]
Duplicate: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/viber.svg
