### ISSUE TITLE
Icon request for i-nex

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2452]
Missing a icons for 2 .desktop files

./i-nex.desktop
./i-nex-library.desktop

Icon=/usr/share/pixmaps/i-nex-128.png

![inex](https://cloud.githubusercontent.com/assets/1277920/9149346/907cadea-3d7c-11e5-8d85-9cab412822be.png)

**Comment by wa4557** [comment]
Already there: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/i-nex.svg

**Comment by leoheck** [comment]
Ok, What I need to do? Update the Icon= in .desktop file?

**Comment by wa4557** [comment]
Yes. Or use https://github.com/Foggalong/hardcode-fixer

**Comment by Eleuin** [comment]
yes, please use the hardcode fixer first, then submit issues :smile:

**Comment by leoheck** [comment]
Awesome! I will give a try.

**Comment by leoheck** [comment]
Missing the i-nex-library.desktop fix. I need to post the issue on the fix project?

**Comment by wa4557** [comment]
Yes
