### ISSUE TITLE
Icon request for GNU octave

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2453]
Missing icon for www.octave.org-octave.desktop 
Icon=/usr/share/octave/3.8.1/imagelib/octave-logo.svg

![octave](https://cloud.githubusercontent.com/assets/1277920/9149349/ca42e0bc-3d7c-11e5-9137-6def09c89150.png)

**Comment by wa4557** [comment]
Duplicate: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/octave.svg
