### ISSUE TITLE
Icon request for FreeCAD

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2454]
Missing icon for FreeCAD: freecad.desktop 
Icon=/usr/share/freecad/freecad.xpm
![freecad](https://cloud.githubusercontent.com/assets/1277920/9149361/fb9c5832-3d7c-11e5-9818-0b4cb93f053a.png)

**Comment by wa4557** [comment]
Also already there: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/freecad.svg

**Comment by leoheck** [comment]
The hardcode-fixer does not apply this one.

**Comment by wa4557** [comment]
Report it or even better create a pull request :)

**Comment by leoheck** [comment]
Ok, nice! I will try a pull request.
