### ISSUE TITLE
Icon request for intel graphics installer

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2455]
Icon for intel-linux-graphics-installer.desktop 
Icon=/usr/share/intel-linux-graphics-installer/images/logo.png
![intel](https://cloud.githubusercontent.com/assets/1277920/9149382/a21902f0-3d7d-11e5-9e4d-8e55a53f2e26.png)

**Comment by wa4557** [comment]
Already theere but hardcoded https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/intel-installer.svg

Use https://github.com/Foggalong/hardcode-fixer to deal with hardcoded icons
