### ISSUE TITLE
Icon request for pencil

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2456]
Missing icon for pencil.desktop
Icon=/usr/share/pencil/skin/classic/icon.svg
![pencil](https://cloud.githubusercontent.com/assets/1277920/9149390/dd3b5388-3d7d-11e5-99e3-3e1bac6a0a12.png)
http://pencil.evolus.vn/

**Comment by wa4557** [comment]
lready there: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/pencil.svg
