### ISSUE TITLE
Icon request for Visual Studio

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2457]
Icon=/home/lheck/tools/web/visual-studio-code/resources/app/vso.png
![visual](https://cloud.githubusercontent.com/assets/1277920/9149397/375c0d6c-3d7e-11e5-82d3-57e23652ee8d.png)

**Comment by wa4557** [comment]
https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/visualstudiocode.svg

**Comment by palob** [comment]
Could you add this to your hardcode-fixer PR please?
