### ISSUE TITLE
Icon request for YoutTube Donwloader

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2462]
```
cat youtube-dlg.desktop 

[Desktop Entry]
Version=1.0
Type=Application
Name=YouTube DL GUI
Exec=python2 /usr/share/pyshared/youtube_dl_gui/__main__.py
Icon=/usr/share/pixmaps/youtube-dlg.png
Categories=Network;
Comment=GUI for YouTube-DL
```
![you](https://cloud.githubusercontent.com/assets/1277920/9149448/c81094de-3d80-11e5-85cf-9b8b8d62951e.png)

**Comment by wa4557** [comment]
Already there: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/youtube-dl.svg
