### ISSUE TITLE
Icon request for GSTM

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2463]
SSH Tunnel Manager
```
cat gstm.desktop 
[Desktop Entry]
Name=gSTM
GenericName=gSTM
Comment=Manage SSH tunnel connections
Exec=gstm
Icon=gSTM.png
Terminal=false
Type=Application
Categories=Application;GTK;GNOME;Network;
```

![stm](https://cloud.githubusercontent.com/assets/1277920/9149453/0fedf6b6-3d81-11e5-8a2c-b5185145663f.png)

**Comment by Veske** [comment]
Is the icon added now?

**Comment by Foggalong** [comment]
@Veske Yeah, [it was added](https://github.com/numixproject/numix-icon-theme-circle/blob/64eb2f1f9b5658507953a1196967f9ad7deb0f01/Numix-Circle/48x48/apps/gSTM.svg) a while ago :P

**Comment by Veske** [comment]
Ah found it now, it's named 'lock' for some reason

**Comment by Foggalong** [comment]
No, the icon is called `gSTM.svg`. You can find it through the link above. I think you might be using an outdated version of the theme

**Comment by Veske** [comment]
That's weird. I see that I have the version: 1.0.2+4~201507161646~ubuntu15.04.1 installed. Installed it from your PPA. Should be the latest right now.

**Comment by bil-elmoussaoui** [comment]
@Veske check this #2430, you can update to the latest version by downloading the git version

**Comment by Veske** [comment]
Ah...   I wondered why I suddenly don't see my daily Numix updates anymore :D

**Comment by Foggalong** [comment]
We're working on possible solutions, hopefully we can get them back soon enough

**Comment by Veske** [comment]
I hope so too :) Looked into the problem @bil-elmoussaoui linked here and it seems pretty complicated.
