### ISSUE TITLE
Icon request for Copy

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2465]
https://www.copy.com

```
cat copy.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=Copy
Exec=/opt/copy-client/CopyAgent
Comment=Sync, Protect and Share. Everywhere.
Icon=/usr/share/icons/hicolor/scalable/apps/copyagent.svg
Categories=GNOME;GTK;Utility;

```
![copy](https://cloud.githubusercontent.com/assets/1277920/9149476/fbc8c3fe-3d81-11e5-9f76-e6eeed237b8c.png)

**Comment by wa4557** [comment]
That ones also already there: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/copy.svg

**Comment by leoheck** [comment]
Added on hardcode-fixer
