### ISSUE TITLE
Big arduino icon

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2469]
I only find this: ```/usr/share/icons/Numix-Circle/48x48/apps/arduino.svg```
But it gives me a big icon in launcher.

![big](https://cloud.githubusercontent.com/assets/1277920/9151509/ea44a626-3dda-11e5-901c-b6e243621e13.png)

**Comment by dirtydancing** [comment]
Please cf. this thread: https://github.com/numixproject/numix-icon-theme-circle/issues/1192. Is the path to the icon "hardcoded"? That might be the reason for the big icon in Ubuntu/Unity. If so, this is not a Numix-Circle issue, but rather a Unity issue.

**Comment by bil-elmoussaoui** [comment]
Well, i had already this issue, you should not write the path to the icon; but only the icon name in the desktop file.

**Comment by leoheck** [comment]
Yes, you are right!
You need to do ```Icon=arduino``` instead of ```Icon=[PATH]/arduino.svg```
