### ISSUE TITLE
Non Numix icon used when launcher icon size > 38

### ISSUE THREAD

**Issue by keunes** [numixproject/numix-icon-theme-circle#2476]
Testing things for another bug with the launcher icons, I discovered that when I set the icon size 40 or higher, on my external monitor the icon for my windows partition is not the icon that I'm used to. I think it's a non-Numix icon, but that should be confirmed by someone else.

Weird thing (so maybe this, too, is not a Numix bug): the icon changes back to the expected one as soon as I A) decrease the icon size to 38 or smaller or B) de-connect my external screen (making use of my laptop screen).

Expected (38 & under) and unexpected (40 and up) icon:
![screenshot from 2015-08-12 22 14 37](https://cloud.githubusercontent.com/assets/11229646/9235595/eb420b14-413f-11e5-8022-8220e57455cf.png) ![screenshot from 2015-08-12 22 13 29](https://cloud.githubusercontent.com/assets/11229646/9235594/eb25c2ec-413f-11e5-9ee7-c6ff4c2924fa.png)

**Comment by wa4557** [comment]
Well that's probably correct the way it is. Both icons are atually numix icons, ,but for larger sizes the `devices` icons turn monochrome (why? No idea, that's just the way it is). So altohough this is pretty inconsistent it's probably not a "bug"

**Comment by keunes** [comment]
Ah, well. In that case I'd like to open the discussion on whether or not this behaviour should be kept :P
It seems, apart from inconsistent, rather illogical to me. Curious to hear back from the developers on the rational behind it :)

**Comment by wa4557** [comment]
It is illogical for sure and should probably be changed, but I guess it would mean a shitload of work :)

**Comment by bil-elmoussaoui** [comment]
I have the same issue in Ubuntu Gnome 15.04 with Gnome 3.16.3 (i guess). The icons in Nautilus look a little bit bigger and so the mounted disks in the desktop
![screenshot from 2015-08-12 22-30-51](https://cloud.githubusercontent.com/assets/7660997/9235883/ce953868-4141-11e5-8ceb-59aa8c6fbd14.png)

**Comment by keunes** [comment]
Maybe I'm totally wrong, but this seems like it should have actively be put in place, no? (just curious here)
In my launcher it's not that big of an issue (as it doesn't catch the eye too much), but on @bil-elmoussaoui 's desktop it really looks out of place

**Comment by wa4557** [comment]
Those are not the symbolic icons. Just the rgular `devices` icons for larger sizes

**Comment by keunes** [comment]
So then who (or rather 'what') decides when the devices icons for larger or for smaller sizes should be used? (sorry, I'm a noob here. If you don't feel like explaining, that's fine, too)

**Comment by bil-elmoussaoui** [comment]
@wa4557 those aren't fixed yet? as they should not look like that, didn't they? :/

**Comment by bil-elmoussaoui** [comment]
Anyway, @keunes  this a Numix Base issue and not a Numix circle one. You can a open a new issue there if needed ;)

**Comment by wa4557** [comment]
There are several sizes in the icon theme `16` `22` `24` `32` `48` `64` `128` and `256`. If you now for example increase the icon size in the dash first e.g. th `32` icons are used (normal icons) but if you increase the size at some point the larger icons are used. The values at what point the larger icons are used are defined  in the `index.theme` file.

**Comment by wa4557** [comment]
@bil-elmoussaoui Not fixed yet, not even started I guess :)

**Comment by keunes** [comment]
Ah, I see :+1: 
I guess I'll do another bug report, then
