### ISSUE TITLE
Icon for SuperCollider IDE

### ISSUE THREAD

**Issue by jags9415** [numixproject/numix-icon-theme-circle#2492]
Name = [SuperCollider IDE](https://supercollider.github.io/)
Icon = sc_ide

![icon supercollider](https://cloud.githubusercontent.com/assets/3059433/9400309/47a22540-477d-11e5-8893-346b210d8911.gif)

**Comment by palob** [comment]
I' short of ideas for this one. Or do you think those are any good?
![sc_ide2](https://cloud.githubusercontent.com/assets/7050624/10559118/ce264bee-74e8-11e5-900c-355dc5c44c7a.png)
![sc_ide3b](https://cloud.githubusercontent.com/assets/7050624/10559119/ce2719d4-74e8-11e5-9dd5-fd6af3c7a409.png)

**Comment by Foggalong** [comment]
1st is an interesting take, I like that :)

**Comment by palob** [comment]
Closer to the original yet duller colour variants:
![sc_ide2b](https://cloud.githubusercontent.com/assets/7050624/10559194/1de774e4-74eb-11e5-8fca-2e4d2528e415.png)
![sc_ide2b2](https://cloud.githubusercontent.com/assets/7050624/10559195/1debaffa-74eb-11e5-8971-51a371f5e140.png)
