### ISSUE TITLE
Missing icon kpat

### ISSUE THREAD

**Issue by region51** [numixproject/numix-icon-theme-circle#2493]
*A numix-circle icon for kpatience is missing.*
*Name=KPatience*
*Type=Application*
*Icon=kpat*
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417169/c8703f10-4852-11e5-8b92-17927b2d3b77.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417172/cf63b432-4852-11e5-9275-f928933947b7.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417194/d5eb3b40-4852-11e5-81b9-239fc2d740e2.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417201/e2bc8af4-4852-11e5-9035-4ede9ef05fb3.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417208/ee543600-4852-11e5-8668-702f6357c0ff.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417211/f3ec1f7e-4852-11e5-9ba3-27ac34da34b8.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417213/fe60d3fa-4852-11e5-9e0f-51dac4111a72.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417218/06e5e88a-4853-11e5-8b03-cf481df2bbb0.png)

**Comment by Foggalong** [comment]
Please add the information set out in the readme otherwise we cant fix this

**Comment by region51** [comment]
*@Foggalong what information? No icons for KPatience.*

**Comment by bil-elmoussaoui** [comment]
@region51 please follow this tutorial https://plus.google.com/+NumixProjectOrg/posts/DkRmhFZuWez

**Comment by region51** [comment]
*A numix-circle icon for kpatience is missing.*
*Name=KPatience*
*Icon=kpat*
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417169/c8703f10-4852-11e5-8b92-17927b2d3b77.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417172/cf63b432-4852-11e5-9275-f928933947b7.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417194/d5eb3b40-4852-11e5-81b9-239fc2d740e2.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417201/e2bc8af4-4852-11e5-9035-4ede9ef05fb3.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417208/ee543600-4852-11e5-8668-702f6357c0ff.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417211/f3ec1f7e-4852-11e5-9ba3-27ac34da34b8.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417213/fe60d3fa-4852-11e5-9e0f-51dac4111a72.png)
![kpat](https://cloud.githubusercontent.com/assets/13280183/9417218/06e5e88a-4853-11e5-8b03-cf481df2bbb0.png)

**Comment by Foggalong** [comment]
We actually [already have this icon](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/kpat.svg). Are you sure it's not showing?

**Comment by region51** [comment]
*@Foggalong sorry, this is problem in org.kde.kpat.desktop.
it was necessary to add to .desktop StartupWMClass=kpat*
![2015-08-21 23-11-15](https://cloud.githubusercontent.com/assets/13280183/9418073/f7ba80da-4859-11e5-93a2-aa3f92230f94.png)

**Comment by Foggalong** [comment]
No problem! :)
