### ISSUE TITLE
Icon for Gnome Internet Radio Locator

### ISSUE THREAD

**Issue by region51** [numixproject/numix-icon-theme-circle#2501]
*Missing icon for girl https://wiki.gnome.org/Apps/Girl
Name=Internet Radio Locator
Icon=girl*
![girl](https://cloud.githubusercontent.com/assets/13280183/9471340/819e1c02-4b58-11e5-83ae-f8e8505375a3.png)
![girl](https://cloud.githubusercontent.com/assets/13280183/9471351/8ea1ff90-4b58-11e5-8b2b-f9473da8c568.png)

**Comment by Eleuin** [comment]
![girl](https://cloud.githubusercontent.com/assets/5553828/9476048/8c19f7e8-4b38-11e5-86d9-b8a35b514aa3.png)

**Comment by palob** [comment]
Maybe a bit busy and hardly recognisable at smaller sizes?

**Comment by Foggalong** [comment]
I don't mind the design that much. What exactly does the app do - what are internet radios?

If that is the design you're going with though use the colours from the original icon, plain black and white can get a bit dull.

**Comment by Eleuin** [comment]
@Foggalong tldr: GIRL (loving the naming btw) is an app for GNOME that allows a user to listen to radio broadcasts done over the web instead of over the air

if the colours are too monochrome, i could go for a lighter grey and a cream colour

**Comment by Foggalong** [comment]
Got it :)

**Comment by Eleuin** [comment]
![girl_24](https://cloud.githubusercontent.com/assets/5553828/9528948/88b9ef2a-4cc5-11e5-9bf8-44f060e99f8f.png)
![girl](https://cloud.githubusercontent.com/assets/5553828/9528918/53934670-4cc5-11e5-9c6a-bea40d97a138.png)

**Comment by Foggalong** [comment]
I'd be happy to merge that :)

**Comment by region51** [comment]
*@Foggalong @Eleuin*
*Missing new color icon for girl https://wiki.gnome.org/Apps/Girl*
*Name=Internet Radio Locator*
*Icon=girl*
![girl](https://cloud.githubusercontent.com/assets/13280183/10870859/05d23422-80e7-11e5-85ed-15f3dd051bec.png)

**Comment by Foggalong** [comment]
Please file a new issue for that since it'd be an enhancement not a request

**Comment by region51** [comment]
@Foggalong ok.
