### ISSUE TITLE
Wrong network-manager icon

### ISSUE THREAD

**Issue by Zeluboba** [numixproject/numix-icon-theme-circle#2502]
Hello,

today I ran apt-get update command and got wrong wired network-manager icon.
I found few similar issues, where it's said that it's fixed in 2014, but today is 2015 :)
I tried to reinstall as well.

![guszhhd](https://cloud.githubusercontent.com/assets/1494347/9478483/e009b206-4b80-11e5-8ddd-c4534e57721b.png)

**Comment by bil-elmoussaoui** [comment]
How do you installed Numix? are you using the ppa or you've just downloaded the zip from the repo?

**Comment by Zeluboba** [comment]
@bil-elmoussaoui As I said, I used 'apt-get update' command, so, I got it from ppa.

**Comment by Foggalong** [comment]
This is a problem with [numix base](https://github.com/numixproject/numix-icon-theme) not Circle :)
