### ISSUE TITLE
Icon for Psi+

### ISSUE THREAD

**Issue by region51** [numixproject/numix-icon-theme-circle#2507]
*Missing icon for psi-plus 
Name=Psi+
Icon=psi-plus*
![psi-plus](https://cloud.githubusercontent.com/assets/13280183/9520119/0a72d58e-4ccd-11e5-90fe-5a85020de27f.png)
![psi-plus](https://cloud.githubusercontent.com/assets/13280183/9520123/119959aa-4ccd-11e5-8d51-179cbd99718d.png)

**Comment by palob** [comment]
A simplish draft:
![work0c](https://cloud.githubusercontent.com/assets/7050624/9534166/dcbe07fe-4d16-11e5-9b59-b5a996c5f5e6.png)

**Comment by Foggalong** [comment]
:+1:
