### ISSUE TITLE
Two icons for same application

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme-circle#2525]
I just discovered, that `mathematica` and `wolfram-mathematica` do have different icons altough they are definitely made for the same app. Maybe one should be a symlink to the other one (I guess `wolfram-mathematica` is the better one

**Comment by palob** [comment]
If in doubt the other one could be archived with ``-alt`` or ``-old`` name to let the user choose. Anyway, ``wolfram-mathematica`` is the design the mimetype should be symplified with.

**Comment by wa4557** [comment]
Agreed
