### ISSUE TITLE
icon for TOR-browser

### ISSUE THREAD

**Issue by indrabinridwan** [numixproject/numix-icon-theme-circle#2535]
<br>
<b> A Tor Browser and StarUML is missing (Request)<b>
<br>
![screenshot 2015-09-07 08 25 48](https://cloud.githubusercontent.com/assets/7960066/9707721/7f17ee68-553a-11e5-8b25-36476805fb5b.png)

**Comment by palob** [comment]
Hi, could you please add the information set out in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests)?

**Comment by leoheck** [comment]
Yes, it is. I added it but it not there anymore. I will do it again.

**Comment by leoheck** [comment]
Add the following line in hardcoded-fixer csv file. My fork needs a lot of work to synchronize it now.
```Tor Browser,tor-browser-en,/usr/share/pixmaps/tor-browser-en.png,tor-browser-en```

**Comment by palob** [comment]
@leoheck [No need](https://github.com/Foggalong/hardcode-fixer/blob/master/tofix.csv#L288) to add it :)

**Comment by indrabinridwan** [comment]
okay

**Comment by leoheck** [comment]
@palob why not? The csv is missing the  ```/usr/share/...``` (which is the standard path). There is an optional path in ```/opt/...```.  My tor-browser isan't fixed by the hardcoder right now.

**Comment by palob** [comment]
@leoheck The line in your comment above is exactly the one present in ``totfix.csv``. Did you mean to paste the ``opt`` paste in. 
Btw, git *branches* is what you're looking for in order to carry out different things at once in your fork.
