### ISSUE TITLE
Icon for TickTick Chrome App

### ISSUE THREAD

**Issue by itsamoreh** [numixproject/numix-icon-theme-circle#2540]
It's so close to Numix Circle already but it would be awesome to have a real icon!

https://chrome.google.com/webstore/detail/ticktick-todo-task-list/eempgbpnkjnacmilmobpbhbfpdjdcpgd?hl=en

**Comment by palob** [comment]
I've made [one](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/chrome-eempgbpnkjnacmilmobpbhbfpdjdcpgd-Default.svg) a few days ago.

**Comment by itsamoreh** [comment]
Thank you! I run Arch but for some reason Numix wasn't updating with yaourt. I had to install Numix Circle again to update.
<pre>yaourt -S numix-circle-icon-theme-git</pre>

Sorry about that and thanks again!

**Comment by ChuckDaniels87** [comment]
Yaourt manages git/svn/hg/cvg packages different from normal AUR packages.
 
Try this: `yaourt -Syua --devel`

You will update your system including AUR packages and AUR git/svn/hg/cvg packages. :wink:
