### ISSUE TITLE
Thumbnail Previews Not Working

### ISSUE THREAD

**Issue by indrabinridwan** [numixproject/numix-icon-theme-circle#2541]
this theme change preview image (jpg/png/svg) in my nautilus file. how to preview image looks like default theme ubuntu?

![screenshot from 2015-09-12 16 09 48](https://cloud.githubusercontent.com/assets/7960066/9830855/bf4d9348-5968-11e5-98ff-f490e929703d.png)

**Comment by palob** [comment]
Did you check your Nautilus preview preferences?

**Comment by Foggalong** [comment]
@indrabinridwan ^^

**Comment by indrabinridwan** [comment]
![screenshot from 2015-09-13 20 40 27](https://cloud.githubusercontent.com/assets/7960066/9836952/b7b4137e-5a57-11e5-9369-d1341334539c.png)

yeah, its nautilus preview reference and
i have clean ~/.cache/thumnails/fails/*

**Comment by Foggalong** [comment]
Do you have the same problem with any other icon themes? Might help us narrow down the problem :)

**Comment by palob** [comment]
Maybe it's another gtk-icon-cache thing.
Did you try removing everything inside ``~/.cache/thumbnails`` and ``~/.thumbnails``?

**Comment by indrabinridwan** [comment]
i have checked!

thumnails only work normal in sudo mode with```sudo nautilus```

![screenshot from 2015-09-14 11 51 01](https://cloud.githubusercontent.com/assets/7960066/9842355/3a9cfb64-5ad7-11e5-9d61-eef62841673b.png)


but not work for user.
there may be something wrong with permission...

i not have idea.

sory bad english.

**Comment by Foggalong** [comment]
@indrabinridwan Can you test with other icon themes?

**Comment by indrabinridwan** [comment]
@Foggalong it turns out.
moka icon theme have same problem.

**Comment by Foggalong** [comment]
Huh. Any icon themes which don't have this problem?

**Comment by indrabinridwan** [comment]
[Solved] 
@Foggalong  yes. and just do this
```
sudo chown -R $USER:$USER ~/.thumbnails
```

```
sudo rm -rf ~/.thumbnails/* ~/.cache/thumbnails/*
```

**Comment by palob** [comment]
That's what I suggested above. Why the ``chown`` thing?

**Comment by Foggalong** [comment]
Glad your problem got solved!
