### ISSUE TITLE
Icon for Slack

### ISSUE THREAD

**Issue by azat-io** [numixproject/numix-icon-theme-circle#2542]
Hello!

Currently, Slack for Linux application is in test (https://docs.google.com/forms/d/1uOlDiuT9XMEGijhXicsOasJv3Nxvt5Azvd9OIIS61Sk/viewform).
This app need an icon.

[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/share/slack/slack %U
Icon=slack
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=text/plain;
 
Maybe it will be something like this?

![slackicon](https://cloud.githubusercontent.com/assets/5698350/9831848/c65fe850-596f-11e5-861e-a70f3b39933c.png)

**Comment by azat-io** [comment]
Oh, sorry. It's not working after Numix circle icon them update.

**Comment by Foggalong** [comment]
The Circle PPA isn't currently updating because of #2430 :(
