### ISSUE TITLE
Icon for ColorHug Backlight

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2548]
Icon=colorhug-backlight

![colorhug-backlight](https://cloud.githubusercontent.com/assets/7804464/9874398/1786650a-5ba6-11e5-957b-8521da6c448d.png)

**Comment by palob** [comment]
A draft in accordance with the existing ``colorhug-flash.svg``:
![colorhug-backlight1](https://cloud.githubusercontent.com/assets/7050624/10123447/231d4bca-653a-11e5-93a8-f79c322779a5.png)

**Comment by palob** [comment]
Fixed.
