### ISSUE TITLE
Icon for ColorHug Display Analysis

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2549]
Icon=colorhug-refresh

![colorhug-refresh](https://cloud.githubusercontent.com/assets/7804464/9874435/45666e34-5ba6-11e5-8592-307317630f2c.png)

**Comment by palob** [comment]
Can you tell what exactly it does?
Name is *analysis*, icon name is *refresh* and the icon shows a *check*, can't make sense of that.

**Comment by Foggalong** [comment]
We do have a colorhug icon already so it's possible this is just a symlink, but yeah more details would be nice.

**Comment by gregorydk** [comment]
Use the existing ColorHug icon and add a check mark.

**Comment by palob** [comment]
Alright :) but the icon name really is **-refresh**?

**Comment by indrabinridwan** [comment]
bad
