### ISSUE TITLE
default shutdown icon (top panel) looks more suitable for this icon theme

### ISSUE THREAD

**Issue by indrabinridwan** [numixproject/numix-icon-theme-circle#2552]
In my opinion default shutdown icon (top panel) looks more suitable for numix-icon-theme-circle

![default](https://cloud.githubusercontent.com/assets/7960066/9896052/23ae569c-5c61-11e5-8637-24ee07b4efab.png)

![circle](https://cloud.githubusercontent.com/assets/7960066/9896053/2660ce60-5c61-11e5-8269-a4faf9915f16.png)

**Comment by Foggalong** [comment]
I'm not sure what you're saying? Shutdown icons are action or status icons but not app icons :/
