### ISSUE TITLE
Icon Request for Layout Editor

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2553]
http://www.layouteditor.net/

```
/usr/share/applications » cat layout.desktop 
[Desktop Entry]
Value=1.0
Type=Application
Name=LayoutEditor
GenericName=LayoutEditor for IC/MEMS design
Icon=layout.png
Exec=/usr/bin/layout %F
MimeType=application/gds;application/dxf;application/oasis;application/cif
Categories=Graphics;VectorGraphics;Science;Electronics;Electricity;Engineering
```
![screenshot from 2015-09-17 19 32 52](https://cloud.githubusercontent.com/assets/1277920/9947748/f9967016-5d72-11e5-91e5-7fcfe09cc525.png)

Hardcode-fixer [issue](https://github.com/Foggalong/hardcode-fixer/issues/172) was asked.

**Comment by leoheck** [comment]
Hi, my quick fix is [here](https://www.dropbox.com/s/o1gnhjqnjo2q0ri/LayoutEditor.svg?dl=0)

**Comment by leoheck** [comment]
I also create some new mimetypes for [.cif](https://www.dropbox.com/s/bm7rtkkcmlvzyrp/ciffile.svg?dl=0) and [.gds](https://www.dropbox.com/s/xapha49t18qhe1c/gdsfile.svg?dl=0) (follow links to donwload the svg). They don't use the same font as in other files. It can be improved, it is just my quick fix.

![screenshot from 2016-03-28 22-14-53](https://cloud.githubusercontent.com/assets/1277920/14095057/81e780d4-f532-11e5-9d59-30be29e3212b.png)

How can I integrate the images with these mimetypes? Can you help me with that? And It will be nice to see this files in Numix theme.

**Comment by Foggalong** [comment]
@leoheck Please submit requests about mimetypes [here](https://github.com/numixproject/numix-icon-theme), the theme they're contained in is not Circle but the base theme. I've merged a modified version of your layout icon into Circle though :)

**Comment by Foggalong** [comment]
Anyone have any idea why this didn't automatically close?

**Comment by palob** [comment]
When I open the commit the tab label shows some strange characters:
![signs](https://cloud.githubusercontent.com/assets/7050624/14111911/f5907230-f5cc-11e5-8e79-ddfa9e64d2ee.png)

**Comment by Foggalong** [comment]
Damn. This is what I get for trying to do development on Windows. I'll just use my Linux vm in future.
