### ISSUE TITLE
Docky don't display circle icon for LibreOffice

### ISSUE THREAD

**Issue by jeffesongouveia** [numixproject/numix-icon-theme-circle#2554]
Hello great team, i use Elementary OS Freya 0.3.1 and my menu slingshot display correct circle theme for libreoffice but it's don't happen on docky, his display the normal icon.

Note: the plank menu show normally :<
Note 2: sorry about my english

![print](https://cloud.githubusercontent.com/assets/12664845/9961294/b8e2c1e8-5ded-11e5-9860-c694fdd2d8f1.png)

**Comment by palob** [comment]
Did you install LibreOffice from a ``.deb`` or a PPA?
Could you please add the information set out in the readme?
(Name of the ``.desktop`` file and ``Icon=...`` line inside the file?)

**Comment by jeffesongouveia** [comment]
From PPA.

Like you request:
/usr/share/applications/libreoffice-writer.desktop

[Desktop Entry]
Version=1.0
Terminal=false
Icon=libreoffice-writer
Type=Application
Categories=Office;WordProcessor;X-Red-Hat-Base;X-MandrivaLinux-Office-Wordprocessors;
Exec=libreoffice --writer %U
MimeType=application/vnd.oasis.opendocument.text;application/vnd.oasis.opendocument.text-template;application/vnd.oasis.opendocument.text-web;application/vnd.oasis.opendocument.text-master;application/vnd.oasis.opendocument.text-master-template;application/vnd.sun.xml.writer;application/vnd.sun.xml.writer.template;application/vnd.sun.xml.writer.global;application/msword;application/vnd.ms-word;application/x-doc;application/x-hwp;application/rtf;text/rtf;application/vnd.wordperfect;application/wordperfect;application/vnd.lotus-wordpro;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.ms-word.document.macroenabled.12;application/vnd.openxmlformats-officedocument.wordprocessingml.template;application/vnd.ms-word.template.macroenabled.12;application/vnd.ms-works;application/vnd.stardivision.writer-global;application/x-extension-txt;application/x-t602;text/plain;application/vnd.oasis.opendocument.text-flat-xml;application/x-fictionbook+xml;application/macwriteii;application/x-aportisdoc;application/prs.plucker;application/vnd.palm;application/clarisworks;application/x-sony-bbeb;application/x-abiword;application/x-iwork-pages-sffpages;
Name=LibreOffice Writer
....
Some generic names in a thousand languages
...
StartupNotify=true
X-GIO-NoFuse=true
Keywords=Text;Letter;Fax;Document;OpenDocument Text;Microsoft Word;Microsoft Works;Lotus WordPro;OpenOffice Writer;CV;odt;doc;docx;rtf;
InitialPreference=5
StartupWMClass=libreoffice-writer
X-KDE-Protocols=file,http,ftp,webdav

Actions=NewDocument;
[Desktop Action NewDocument]
Name=New Document
Exec=libreoffice --writer

**Comment by Foggalong** [comment]
That's weird, we [definitely have the icon for it](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/libreoffice-writer.svg)

**Comment by jeffesongouveia** [comment]
I using docky version 2.2.1.1 the latest stable version installed by PPA

**Comment by bil-elmoussaoui** [comment]
It's Docky issue i guess, as Numix-Circle icons are shown using Plank in elementary OS Freya 0.3.1 ;)

**Comment by karzinom** [comment]
Hey there!

Just installed LibreOffice 5 via the .deb files from the Libreoffice Webpage. I have the same Problem, every Icon is there except the ones for libreoffice. I didnt change the dock, so it's the standard dock that comes with freya 0.3.1.

what can I do to obtain the circle icons back?

**Comment by palob** [comment]
@karzinom Can you look for the icon line in the ``.desktop`` file when you install from the .deb.

It probably needs some symlinks.

**Comment by karzinom** [comment]
never mind! after reinstalling it through the software center, the icons are there! something went wrong installing it via the .deb files from the official page :)

**Comment by Foggalong** [comment]
:+1:
