### ISSUE TITLE
Icon Request for Google Drive - Grive Tool

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2555]
![screenshot from 2015-09-18 11 22 01](https://cloud.githubusercontent.com/assets/1277920/9961687/40e3053a-5df8-11e5-9434-6bf113389e92.png)

I already posted the hardcode-fixer issue [\#173](https://github.com/Foggalong/hardcode-fixer/issues/173)

```
Launcher=/usr/share/applications/grive.desktop 
Name=Grive Setup
Icon=/opt/thefanclub/grive-tools/grive.png
```
```
Launcher=/usr/share/applications/grive-setup.desktop 
Name=Google Drive
Icon=/opt/thefanclub/grive-tools/GoogleDrive.png
```
```
Launcher=/usr/share/applications/grive-indicator.desktop 
Name=Google Drive Indicator
Icon=/opt/thefanclub/grive-tools/GoogleDrive.png
```

**Comment by bil-elmoussaoui** [comment]
There's already a Google drive icon ;) maybe adding those to hardcode-fixer?

**Comment by leoheck** [comment]
What is the name of the icon?

**Comment by bil-elmoussaoui** [comment]
I don't know, i guess GoogleDrive or something like that; )

**Comment by leoheck** [comment]
I found it, it is google-drive.svg
