### ISSUE TITLE
BOINC icon resists changing

### ISSUE THREAD

**Issue by CaptainCaffeine** [numixproject/numix-icon-theme-circle#2556]
Even though numix circle provides an icon for BOINC, whenever the program boincmgr is started it continues to use the old icon in my dock and in the background applications.

Here's the icon you guys provide:
![boinc_icon](https://cloud.githubusercontent.com/assets/4934864/9979301/cb210fe4-5f1a-11e5-9ce1-27ff7b7fc4a0.png)

When I add boincmgr to my dock, it shows up with the numix icon, but when I start the program the old icon shows up at the bottom of my dock, and in my background apps tray.
![boinc_icon_dock](https://cloud.githubusercontent.com/assets/4934864/9979305/e09256a8-5f1a-11e5-9b65-10142c71d3f6.png)
![boinc_icon_tray](https://cloud.githubusercontent.com/assets/4934864/9979307/ea7a3578-5f1a-11e5-9ae5-fb88ec2b1640.png)

I've used Foggalong's hardcode-fixer script, and it didn't help. I'm running Debian Testing with Gnome 3.16.2.

**Comment by palob** [comment]
Does copying the ``.desktop`` file to ``~/.local/share/applications`` help?

**Comment by bil-elmoussaoui** [comment]
"The fact that the icon is not the same in the ALT-Tab switcher is due to `StartupWMClass` in the desktop file of the application. try adding this to your desktop file `StartupWMClass=copy` if not just open your system monitor (gnome system monitor if you're using ubuntu) and change the name from "copy" to the processus name. " Or copy the desktop file from /usr/share/applications to .local/share/applications and change the desktop file name to the processus name

**Comment by dirtydancing** [comment]
Not sure if this is applicable here, but the situation reminds me of this former issue, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/865#issuecomment-64084167.

**Comment by Foggalong** [comment]
Gonna close this til more info added

**Comment by CaptainCaffeine** [comment]
Sorry for such a late reply, I've been swamped lately. But these suggestions did help figure it out!

Copying the desktop file to `~/.local/share/applications`, adding the line `StartupWMClass=boincmgr`, and changing the file name to the process name (which is boincmgr) did change the duplicate icon in the dock to the numix icon. But the duplicate was still there, I had to add `StartupWMClass=boincmgr` to the desktop file in `/usr/share/applications` as well, which made the duplication stop. Thanks for your help!

**Comment by bil-elmoussaoui** [comment]
You're welcome @CaptainCaffeine!

**Comment by dirtydancing** [comment]
:+1:
