### ISSUE TITLE
Hourglass icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2557]
Hello, 
There's a missing icon for Hourglass, Hourglass is a clock/alarm application designed for elementary OS

The icon name 
Icon=hourglass

The default icon 
![screenshot 20-09-2015 22 17 25](https://cloud.githubusercontent.com/assets/7660997/9982726/64baaee2-5fe5-11e5-9cc7-c68bd91de755.png)

**Comment by palob** [comment]
How about a hourglass design, literally?
![hourglass1b](https://cloud.githubusercontent.com/assets/7050624/10119437/0ca6bf56-6496-11e5-8e61-f57379ee90ed.png)
![hourglass2](https://cloud.githubusercontent.com/assets/7050624/10119438/0caa5a9e-6496-11e5-8448-052bc56baed6.png)
![hourglass2b](https://cloud.githubusercontent.com/assets/7050624/10119439/0cae395c-6496-11e5-991b-a4bfa190f127.png)
![hourglass3b](https://cloud.githubusercontent.com/assets/7050624/10119440/0cb172ca-6496-11e5-9088-1c587c2f2efd.png)

**Comment by Foggalong** [comment]
Love it! no 4 looks like a winner to me
