### ISSUE TITLE
feedreader icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2558]
Feedreader icon is missing
The icon name 
Icon = feedreader
The icon can be symlinked into any RSS feed application icon
https://bugs.launchpad.net/feedreader

**Comment by palob** [comment]
While I was looking into this I reworked ``liferea.svg``, the symlink target for several feedreader icons.

Before:
![liferea-old](https://cloud.githubusercontent.com/assets/7050624/10119779/2ef4e032-64a1-11e5-8be3-7329a9e7d83b.png)
After:
![liferea](https://cloud.githubusercontent.com/assets/7050624/10119780/3492c6e4-64a1-11e5-9533-ddb6aa846c7c.png)

Now I wonder whether to do ``feedreader.svg`` simply as symlink or as recoloured design in accordance with the original icon's colours:
![feedreader](https://cloud.githubusercontent.com/assets/7050624/10119784/681dc70c-64a1-11e5-84e8-11842050a46b.png)

By the same token I could change the symlink base and recolour ``liferea.svg`` following the somewhat blueish original icon:
![feedreader2](https://cloud.githubusercontent.com/assets/7050624/10119799/b2bd0dfe-64a1-11e5-9abf-026d357562ce.png)

**Comment by bil-elmoussaoui** [comment]
I prefer the recolored icon :D

**Comment by palob** [comment]
@Foggalong

**Comment by Foggalong** [comment]
Like the reworking, and the recolour for `liferea` is cool too! I like that idea :)
