### ISSUE TITLE
Icon for Gtick

### ISSUE THREAD

**Issue by smalltimer** [numixproject/numix-icon-theme-circle#2559]
Numix circle icon for Gtick is missing. Icon line says:

" Icon=/usr/share/icons/hicolor/64x64/apps/gtick.xpm "

The current (not very nice) icon is attached. 

![screenshot from 2015-09-20 22 27 39](https://cloud.githubusercontent.com/assets/14436654/9982992/d644ee6e-5fe6-11e5-97c4-61c87859597e.png)

Thanks in advance, and cheers guys!

**Comment by bil-elmoussaoui** [comment]
The icon is hardcoded, can you share the launcher/desktop file name too. So we can add this to hardcode-fixer database too?

**Comment by smalltimer** [comment]
Hi! 

Woooops. I just looked into the fix.sh and that sorted it out (and the GDebi icon, which I have gone and made another silly issue-report about). Sorry for being such an over eager issues-reporter. Will do a thorough check before reporting anything further.

That said, do appreciate the super quick response! Many thanks for that.

**Comment by bil-elmoussaoui** [comment]
You're welcome :)
