### ISSUE TITLE
Jabref and R-studio

### ISSUE THREAD

**Issue by smalltimer** [numixproject/numix-icon-theme-circle#2560]
Hi guys! 

I use the programs JabRef and R-Studio a lot. The numix-circle icons for both the programs are lovely but similar 'R's in blue backgrounds of different shades. Since they are both science related, they are in the same menu and it is quite confusing! If you have the time, please do consider doing a different icon for one of the two. I know you guys have loads of requests, so just get to it whenever, it is not a very high priority issue :)

Cheers!

**Comment by palob** [comment]
Maybe something more close to [Jabref's original "JR" logo](https://en.wikipedia.org/wiki/JabRef#/media/File:JabRef_Icon.svg)?

**Comment by smalltimer** [comment]
That looks ace!
