### ISSUE TITLE
Icon for Slack

### ISSUE THREAD

**Issue by philiplarsson** [numixproject/numix-icon-theme-circle#2566]
A numix-circle icon for [slack](https://slack.com/apps) is missing.

Icon=slack

Original icon is attached.
![icon256](https://cloud.githubusercontent.com/assets/3718865/10073094/d8cd7038-62c6-11e5-923c-67a1961c3692.png)

**Comment by Foggalong** [comment]
[Dude.](https://github.com/numixproject/numix-icon-theme-circle/issues/2542).

**Comment by philiplarsson** [comment]
@Foggalong opps, my fault. Sorry about that.

**Comment by Foggalong** [comment]
np! :)
