### ISSUE TITLE
Icon Request for DJV View

### ISSUE THREAD

**Issue by aditiapratama** [numixproject/numix-icon-theme-circle#2567]
[DJV](http://djv.sourceforge.net/)
```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Icon=djv_view
Exec=/usr/local/djv-1.1.0-Linux-64/bin/djv_view.sh %U
Name=djv_view
Comment=Professional movie playback software for film production, VFX, and computer animation
Categories=Graphics
Terminal=false
MimeType=image/jpeg;image/png;image/tiff;image/x-cin;image/x-dpx;image/x-iff;image/x-ifl;image/x-jpeg;image/x-lut;image/x-1dl;image/x-exr;image/x-pic;image/x-png;image/x-pbm;image/x-rla;image/x-sgi;image/x-tga;image/x-tiff;video/quicktime;video/mp4;
```
![screenshot_2015-09-26_05-56-09](https://cloud.githubusercontent.com/assets/982553/10113872/5ce9e5ca-6413-11e5-9513-9225d5f4179b.png)

**Comment by palob** [comment]
Just as inspiration (way too busy / detailed imo), this is what I've come up so far:
![djv_view2](https://cloud.githubusercontent.com/assets/7050624/10119450/65114404-6496-11e5-80c7-6f36e18809c5.png)

**Comment by Foggalong** [comment]
:+1: looks great!

**Comment by ChuckDaniels87** [comment]
Nice one. :+1:

**Comment by bil-elmoussaoui** [comment]
@aditiapratama take a look at this https://github.com/numixproject/numix-icon-theme-circle/pull/2580 ;)

**Comment by aditiapratama** [comment]
@bil-elmoussaoui thanks for pointing that out, hope it'll be merge soon :)
