### ISSUE TITLE
MATLAB icon

### ISSUE THREAD

**Issue by smalltimer** [numixproject/numix-icon-theme-circle#2573]
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=matlab -desktop -glnx86
Name=MATLAB
Icon=/usr/share/icons/hicolor/48x48/apps/matlab.png
Categories=Development;Math;Science
Comment=Scientific computing environment
StartupNotify=true

The current icon is attached. 
![matlab](https://cloud.githubusercontent.com/assets/14436654/10122456/3d4b9a46-6513-11e5-9a62-5227a8f1ea70.png)

Perhaps basing the background of the circle on the background of the splash screen (attached below) might be a good idea? 
![matlabsplashscreen](https://cloud.githubusercontent.com/assets/14436654/10122476/cd1ef974-6513-11e5-8005-88e1a0dcf5f6.PNG)

And thanks for all the hardwork you guys are putting in. I am sitting in my office (on a Sunday), working away on a paper, and it feels good to know there's other people working away on a Sunday too, just because we WANT to XD 

Cheers!

**Comment by Foggalong** [comment]
[We have one](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/matlab.svg), it's just hardcoded :) Check out the information in the readme for what to do next

**Comment by Foggalong** [comment]
And good luck with your paper!

**Comment by smalltimer** [comment]
Ahh, thanks. Which readme should I look at? Is it the fix.sh script? If so, I already ran it and the Matlab icon is still the same. 

And thanks! XD

**Comment by Foggalong** [comment]
Ah, in that case open a [new issue](https://github.com/Foggalong/hardcode-fixer/issues/new) along with:

* this icon line `Icon=/usr/share/icons/hicolor/48x48/apps/matlab.png`
* the filename for the .desktop file
