### ISSUE TITLE
Network icon broken when connected using mobile broadband

### ISSUE THREAD

**Issue by akhyarrh** [numixproject/numix-icon-theme-circle#2575]
Not connected:
![2015-09-27_21 40 12](https://cloud.githubusercontent.com/assets/10618799/10123092/1befd94a-6561-11e5-8417-dd0ba8aa9901.png)

Connected:
![2015-09-27_21 41 05](https://cloud.githubusercontent.com/assets/10618799/10123094/3444fa48-6561-11e5-97e0-3732ee8f01c5.png)

Lubuntu 14.04
numix-gtk-theme 2.4
numix-icon-theme-circle 1.0.2+4~201507161646~ubuntu14.04.1

**Comment by wa4557** [comment]
The icon is empty in Numix :( A new one needs to be designed

**Comment by bil-elmoussaoui** [comment]
It's a Numix base issue, see this [Issue](https://github.com/numixproject/numix-icon-theme/issues/743) ?

**Comment by akhyarrh** [comment]
From default Lubuntu icon theme:
- nm-mb-roam
- nm-tech-3g
- nm-tech-cdma-1x
- nm-tech-edge
- nm-tech-evdo
- nm-tech-gprs
- nm-tech-hspa
- nm-tech-lte
- nm-tech-umts
- nm-vpn-active-lock
- nm-wwan-tower

**Comment by akhyarrh** [comment]
As @bil-elmoussaoui said, it's Numix base issue. Closing...
