### ISSUE TITLE
Update agenda icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2578]
Agenda is a Task application created for elementary see [this](https://quassy.github.io/elementary-apps/Agenda/)

the current icon is the same as calendar icon, the icon should be modified/changed to something else
Icon=agenda
I don't know if this icon name is used by an other application, if it's the case just close this already ;)

**Comment by bil-elmoussaoui** [comment]
@Foggalong This should be en enhancement i guess ;)

**Comment by Foggalong** [comment]
My bad :)
