### ISSUE TITLE
Icon for FoxitReader

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme-circle#2581]
![foxitreader-64x64](https://cloud.githubusercontent.com/assets/6475757/10218574/1ffd92c8-6838-11e5-92ef-2ddb27c8b77d.png)
Finally one of the best (though proprietary) pdf viewers was ported to Linux. 
http://www.webupd8.org/2015/09/foxit-pdf-reader-sees-new-linux-release.html
Icon line says:
`Icon=/home/root/.local/share/icons/hicolor/64x64/apps/FoxitReader.png`

**Comment by bil-elmoussaoui** [comment]
Can you add the desktop file name too so i can add FoixtReader to the hardcode-fixer once this got fixed?

**Comment by wa4557** [comment]
Depends on the installation method, it's either in `/usr/share/applications/FoxitReader.desktop` or at `~/.local/share/applications/FoxitReader.desktop`

**Comment by bil-elmoussaoui** [comment]
Thanks :D
