### ISSUE TITLE
Repositories in Fedora Copr not updating

### ISSUE THREAD

**Issue by aengelke** [numixproject/numix-icon-theme-circle#2582]
The last update was 4 months ago.

https://copr.fedoraproject.org/coprs/satya164/numix/

**Comment by Foggalong** [comment]
Yeah, the copr builds aren't daily builds like the PPA, AUR, and git. It's unfortunate but I'm not sure what we do about it.

**Comment by bil-elmoussaoui** [comment]
@Foggalong I just moved to Fedora, i might help you by building a new version every weekend!

**Comment by urbenlegend** [comment]
Also we need some Fedora 23 copr builds as well. The repository only has 22 and 21

**Comment by mastaiza** [comment]
I have not received the answer to the question . why not updated https://copr.fedoraproject.org/coprs/numix/numix/

**Comment by aengelke** [comment]
I guess the update needs to be triggered manually (e.g. by @sspreitzer).

**Comment by mastaiza** [comment]
I can't understand you what do you lead

**Comment by sspreitzer** [comment]
Hi guys, the travis automation was linked to fedora:rawhide docker image which had problems pushing coprs builds. Changed that to fedora:latest which pushes coprs builds again.
Build happens now every Sunday 11 am UTC.

Btw. run
> $ dnf update -y numix-\\*

**Comment by sspreitzer** [comment]
See also: https://travis-ci.org/sspreitzer/numix-specs/builds/104298018
