### ISSUE TITLE
Icon request for Unity

### ISSUE THREAD

**Issue by marez** [numixproject/numix-icon-theme-circle#2584]
Hi!
Unity *finally* got ported to linux, would be great to have a nice icon for it.

Icon name:
`Icon=unity-editor-icon`

Original icon:
![image](https://cloud.githubusercontent.com/assets/2983901/10234609/1292705a-6896-11e5-8bb5-ff4f73e4a3d6.png)

Cheers!

**Comment by wa4557** [comment]
This exact icon is already present in numix-icon-theme-circle :
https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/unity-editor-icon.svg
