### ISSUE TITLE
Guidelines?

### ISSUE THREAD

**Issue by crutchcorn** [numixproject/numix-icon-theme-circle#2594]
Hey there! I am looking to HOPEFULLY make one or 5 new icons for Numix Circle and was wondering if there were any guidelines I needed to follow aside from making it a circle. I haven't found any other issues regarding this (but I could always be wrong!) so hopefully I'm not TOO bothersome.

**Comment by ChuckDaniels87** [comment]
[Here](https://github.com/numixproject/numix-wiki/wiki/Guidelines). I must admit that is a little bit hidden. We could put a link in Numix Circle _README.md_, what do you think @Foggalong ?

**Comment by crutchcorn** [comment]
I am SOOOOOO sorry for missing that! I should have checked the wiki first before asking here!

**Comment by crutchcorn** [comment]
Hey, I figure I'll ask here - since I don't think that I did anything right and want to check up on that before creating an embarrassing pull request: https://drive.google.com/file/d/0ByMswsRUqQ7QNHRGdjRHYzlOaUE/view?usp=sharing

Was this icon made correctly? I know that AI sucks with SVGs but I'm not smart enough to know Inkscape yet

**Comment by Foggalong** [comment]
I've not downloaded the icon to check it yet (afk atm) but we do [already have](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/smartgit.svg) a `smartgit.svg` icon :)

**Comment by crutchcorn** [comment]
Oh! Interesting... It didn't apply for me... At any rate - I would still love for the SVG to be evaluated and given tips on for future possibilities of contributing if that's alright with you guys! ^-^

**Comment by Foggalong** [comment]
The icon is probably hardcoded - see the README for more information. I'll still evaluate your icon though when I'm back at keyboard :)

**Comment by crutchcorn** [comment]
It's strange. On one of them it's hardcoded but on the other it's not... At any rate - I'll be sure to check out the readme about that when I wake up again. Heading to bed now. Thank you so much for your assistance thus far - I was super afraid with proceeding with any of this because of your prowess over the community. Haha

**Comment by Foggalong** [comment]
Don't sweat it, always happy to help out new contributors :)

**Comment by Foggalong** [comment]
Okay, had chance to download and take a look:

* we use 48px as standard for Linux desktop icons
* the circle baseplate should have a gradient of 10L difference, darkest being on bottom
* I'm not entirely sure how you made shadow but on ungrouping it goes all weird - it's simply a copy of the symbol set to `#000000` and then 10% transparency
* The shadow should be located exactly 1px right and 1px down of the symbol

**Comment by crutchcorn** [comment]
I actually used two different svgs downloaded from this repo to compare the shadows and such. I thought it was weird how the shadow was made but didn't want to question it. Haha. I also thought it was weird that the icon was 100px when I I opened it. AI is so weird. At any rate - what should the shadow dimmentions be aside from 1px down and 1 px to the right? Black and 10%? 

What do you mean by "10L"? I appologize but I'm unaware of this measurement. 

Lastly, what should the glyph size be? I saw 26,28, etc. Which should it be? Sorry if that's an obvious question. 

Thanks again for the help. I earnestly appreciate it. :)

**Comment by crutchcorn** [comment]
BTW, for reference; the SVG I downloaded to compare with was 2048.

**Comment by Foggalong** [comment]
* As a general point, I'd recommend using Inkscape over AI especially when contributing to Numix. I (and as far as I know all of the other devs) use Inkscape so we won't be able to give you help for using AI. It's free, easy to use, powerful, and centred around SVG. 
* Some shadows in the repo are messed up from an error in a previously used automation script. The preferred method is to simply clone all of the shapes in the symbol, union the whole thing, set the colour to `#000000`, transparency to 10%, and then transform 1px down+right.
* [HSL](https://en.wikipedia.org/wiki/HSL_and_HSV) is just another color model like RGB. For the baseplate gradients we use the same color but with a 10L difference between top and bottom. HSL is available as an option in the "Fill and Stoke" Inkscape menu.
* Symbol size standard is 24px for square, 30px for circle. Some shapes fall between these so it's helpful to use a size in between like 26 or 28.

And no problem :)

**Comment by palob** [comment]
@crutchcorn Regarding the weirdnesses of ``2048.svg`` that must be AI which from what I know doesn't fully support the SVG specs.

What is weird indeed is that the shadow shows up as ``#000000`` with A255 and 100% opacity (meaning it would be just black) in Inkscape's *Fill and Stroke* panel for this and other older icons.

**Comment by crutchcorn** [comment]
Thanks for the info guys. I'll try to keep all this in mind for future work that I hope to do for Numix Circle! :)

**Comment by Foggalong** [comment]
No problem, glad we could help! :)
