### ISSUE TITLE
Copr repo for Fedora 23

### ISSUE THREAD

**Issue by hhlp** [numixproject/numix-icon-theme-circle#2595]
please do a copr repo for Fedora 23

regards.,

**Comment by Foggalong** [comment]
Does the current version not work?

**Comment by hhlp** [comment]
sudo dnf copr enable satya164/numix

what i get :  

Failed to synchronize cache for repo 'satya164-numix' from 'https://copr-be.cloud.fedoraproject.org/results/satya164/numix/fedora-23-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 1:21:02 ago on Sat Oct 10 19:15:50 2015.
Dependencies resolved.
Nothing to do.

**Comment by Foggalong** [comment]
@satya164 ?

**Comment by CyanBlob** [comment]
You can solve this pretty easily yourself. Edit the copr repo (numix_copr.repo for me) in /etc/yum.repos.d (sudo gedit etc/yum.repos.d/numix_copr.repo) and change the all references to $releasever to say "22" (without quotes).
This is my repo after making the change, which works fine:
```
[satya164-numix]
name=Copr repo for numix owned by satya164
baseurl=https://copr-be.cloud.fedoraproject.org/results/satya164/numix/fedora-22-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/satya164/numix/pubkey.gpg
enabled=1
enabled_metadata=1
```

**Comment by handicraftsman** [comment]
@CyanBlob Thanks) Such problem)

**Comment by Foggalong** [comment]
[We have someone working on this now :) ](https://github.com/numixproject/numix-copr/issues/1)

**Comment by jsquaredz** [comment]
had this same issue today.  Changed it to 22 manually and its fine.  Maybe just need to add a sym link so make 23 point to 22.  This way the repo script can continue to work as intended?

**Comment by igitur** [comment]
Now https://copr-be.cloud.fedoraproject.org/results/satya164/ is completely empty ?!

**Comment by satya164** [comment]
It's changed to this - https://copr-be.cloud.fedoraproject.org/results/numix

Satyajit Sahoo
UX Designer
Behance Profile <https://www.behance.net/satyajitha28c7>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.
