### ISSUE TITLE
Numix Circle doesn't cover Gnome apps in Fedora 25

### ISSUE THREAD

**Issue by joedborg** [numixproject/numix-icon-theme-circle#26]
Even if I reinstall, all the Gnome apps are showing their default icons.

**Comment by bil-elmoussaoui** [comment]
The issue should be reported here instead https://github.com/numixproject/numix-core
And also we need the application name and the icon name too. Check the readme to get to know how to get those informations

**Comment by palob** [comment]
@joedborg Are you maybe talking about Flatpak apps? Otherwise your Numix Circle theme might be outdated.

**Comment by joedborg** [comment]
@palob, i'm using the copr repo for the installation, maybe this out of date?

The apps are Files, Builder, Power Statistics, Videos

**Comment by palob** [comment]
I was referring to your apps because afaik as yet Flatpak apps aren't themeable botj in terms of icons and GTK.
