### ISSUE TITLE
Last update broke Caffeine Indicator icon

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-icon-theme-circle#2602]
![screenshot from 2015-10-14 14 16 44](https://cloud.githubusercontent.com/assets/11137173/10483223/796cf628-727e-11e5-88c0-de6ae0f9bbeb.png)

**Comment by wa4557** [comment]
I guess you're using the version from PPA? That's because the versio needs an upgrade but doesn't upgrade automatically #2430

**Comment by Corsseir** [comment]
Nop. Everything was ok, but this morning I have got the update of numix-icon-theme on Ubuntu 14.04 and this update brake caffeine indicator icon.

**Comment by Foggalong** [comment]
This is indeed that problem. As soon as @PaoloRotolo triggers a Circle build we'll be good

**Comment by Corsseir** [comment]
Ok, thanks a lot for your effort :)

**Comment by rauldipeas** [comment]
I have the same issue with Copy, Diodon, Deluge and bluetooth indicators on Ubuntu 15.04 and 14.04.

**Comment by wa4557** [comment]
A way to fix this manually for now, is to change the symlink in `/usr/share/icons/Numix-Circle/{22x22}{16x16}{24x24}/panel` from `../../Numix/{22x22}{16x16}{24x24}/panel` to `../../Numix/{22}{16}{24}/panel`

**Comment by rauldipeas** [comment]
I try to fix manually like You suggest, but after re-login icons still the same.

**Comment by wa4557** [comment]
Did you run `ln -sf ../../Numix/22/panel` in this folder `/usr/share/icons/Numix-Circle/22x22`?
(The same for `16x16` and `24x24`) This should definitely work....

**Comment by rauldipeas** [comment]
I run ln -s in all mentioned folders, I'll try with -sf option.

**Comment by rauldipeas** [comment]
I run "sudo ln -sf /usr/share/icons/Numix/22/panel /usr/share/icons/Numix-Circle/22x22/panel" and the same for other folders but indicators still the same.

**Comment by rauldipeas** [comment]
I'll do the same on Numix-Circle-Light and works correctly, but on regular Numix-Circle don't.

**Comment by wa4557** [comment]
what does `ls -l` say?

**Comment by rauldipeas** [comment]
total 0
lrwxrwxrwx 1 root root 31 Out 14 18:11 panel -> /usr/share/icons/Numix/22/panel

**Comment by wa4557** [comment]
can you `cd` into `panel`?

**Comment by rauldipeas** [comment]
Yes, cd runs correctly into panel folder.

**Comment by wa4557** [comment]
Try: `sudo gtk-update-icon-cache /usr/share/icons/Numix-Circle` and `sudo gtk-update-icon-cache /usr/share/icons/Numix`

**Comment by rauldipeas** [comment]
I try this, nothing change after restart Unity... :/

**Comment by wa4557** [comment]
Hmm, strange... Let me think about it

**Comment by rauldipeas** [comment]
I try all You recommend, but no success, I'm running Ubuntu 14.04 now, don't try on Ubuntu 15.04 yet.

**Comment by jsherer** [comment]
The difference is that /usr/share/icons/Numix has folders named 16, 22, 24, etc. And Numix-Circle and Numix-Circle-Light are looking for the folder to be named 22x22. A simple fix:

    cd /usr/share/icons/Numix
    sudo ln -s 22 22x22

My caffeine indicator changed back to the original icon in a few seconds. If it doesn't happen automatically, try logging out and/or purging the icon cache.

**Comment by rauldipeas** [comment]
I try this now, indicators still de same... x_x

I don't know what to do.

**Comment by rauldipeas** [comment]
Now I fix it!
I run sudo ln -s 22 22x22; sudo ln -s 16 16x16;sudo ln -s 24 24x24 on Numix folder AND Numix-Light, all indicators has fixed.

Thanks for help guys!

**Comment by keunes** [comment]
Heya,

I just discovered this issue yesterday evening. @wa4557 with your [comment about the PPA](https://github.com/numixproject/numix-icon-theme-circle/issues/2602#issuecomment-148031756), did you suggest that the issue as such has been resolved (here on github), but that the fix hasn't been uploaded to launchpad yet?

I feel more like waiting for the PPA upgrade than to start fiddling in my system :P

**Comment by bil-elmoussaoui** [comment]
@Foggalong This can be closed :)

**Comment by Foggalong** [comment]
:+1:
