### ISSUE TITLE
Icon Request: Monochromatic Spotify icon for top panel

### ISSUE THREAD

**Issue by pwittchen** [numixproject/numix-icon-theme-circle#2605]
Hi,

Is it possible to set monochromatic good looking icon for Spotify via Numix icon theme?
By default there's big green and cut icon in top panel.

I've done it myself, but my way is quite hacky and maybe it could be done better through Numix theme without my workarounds?

Here are my steps:
- step 1: `sudo apt-get install gksu`
- step 2: `gksu xdg-open /opt/spotify/spotify-client/Data/resources.zip`
- step 3: go to `_linux` subdirectory and replace existing icon (`spotify-linux-512.png`) with new one

I found appropriate icon somewhere on the web and modified it in Gimp to make it fit into top panel.
I'm not a graphic designer, so I know it could be done better, but I'm leaving it here for the reference.

![spotify-linux-512](https://cloud.githubusercontent.com/assets/695319/10510286/60ce5c4c-7332-11e5-8ddd-096acd07a0f6.png)

Regards,
Piotr

**Comment by bil-elmoussaoui** [comment]
You can use [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray), follow the instructions and every ugly tray icon will look better with Numix :D if not, don't hesitate to report an issue there ;)

**Comment by Foggalong** [comment]
Basically that :)
