### ISSUE TITLE
Icon for Gambas IDE

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2607]
http://gambas.sourceforge.net/en/main.html

**Original icon:**
gambas3.desktop
Icon=gambas3.png
![logo](https://cloud.githubusercontent.com/assets/7050624/10529164/ce83ba34-739b-11e5-87d3-ddd7d401d921.png)

**Proposed Numix Circle icon:**
![gambas](https://cloud.githubusercontent.com/assets/7050624/10529174/dcb7152e-739b-11e5-9def-e8f54e61846e.png)

PR is on hold so as not to collide with the HiDPI PR.

**Comment by Foggalong** [comment]
:+1:
