### ISSUE TITLE
Spec Ops: The Line (Steam)

### ISSUE THREAD

**Issue by MrTimscampi** [numixproject/numix-icon-theme-circle#2611]
Name: Spec Ops: The Line
AppID: 50300
Icon: ![spec_ops__the_line_icon_by_jonywallker-d5n731m](https://cloud.githubusercontent.com/assets/1087450/10543189/4312bf36-741d-11e5-8a7e-e50f670ae8b6.png)
Notes: Game about war and its atrocities, set in the middle-east.

**Comment by MrTimscampi** [comment]
This one is hardcoded, by the way (Didn't notice that before submitting).

**Comment by MrTimscampi** [comment]
I tried a design for a fullscreen symbol icon.

Design is based on the desert theme of the game with some sort of soldier wandering in it.

![steam_icon_50300](https://cloud.githubusercontent.com/assets/1087450/11049731/d54b8172-8740-11e5-8b61-4e35470702a9.png)

Any criticism welcome. (I'm very new to this)

If the icon is okay, I'll commit it to my fork and make a pull request (Or include it in my pending pull request if it's still there).

**Comment by ChuckDaniels87** [comment]
Could you link SVG icon?

**Comment by MrTimscampi** [comment]
Sure, [here you go](https://dl.dropboxusercontent.com/u/40932393/steam_icon_50300.svg) :)

I didn't know how to keep the new path to the circle path of the icon, so I basically duplicated the circle and modified the top of the path, which explains the kind of weird look of the front layer of sand.  
I'd like to change the sand a bit, make it a bit lower and flatter, and maybe make the sand dune in the back less tall and round, but I don't really know what to look for as far as tutorials go (Like cutting a path from another path to keep the round shape of the icon correct)

**Comment by ChuckDaniels87** [comment]
The icon you made is really cool but I am not sure if you went to far from the guidelines. Let's wait and see what @Foggalong thinks about it.

About the sand stuff. I usually copy the circle and I intersect it with the shape I want. This results in a new shape that perfectly fit baseplate circle.



![example](https://cloud.githubusercontent.com/assets/8478202/11086287/b6fc9250-884f-11e5-8255-f056fedd4790.png)

**Comment by MrTimscampi** [comment]
Oh, right, you can do that :p 
I cleaned up the overlaps in the previous icon using intersect and difference, and corrected the sand to make it less "I copied the circle and moved a few points around".

Here's the PNG:
![steam_icon_50300](https://cloud.githubusercontent.com/assets/1087450/11090336/5813c318-8871-11e5-95ba-ca256987a0ac.png)

And here's the SVG:
https://dl.dropboxusercontent.com/u/40932393/steam_icon_50300.svg

I am of course open to modifying the design if it doesn't fit the guidelines :)
If you guys would rather have a regular symbol icon instead of a fullscreen one, I just had an idea for one, too. I'll work on it and post it here as well.

**Comment by ChuckDaniels87** [comment]
If you can post both ideas to compare them it would be nice. :wink:

**Comment by MrTimscampi** [comment]
Here's my other idea:
![steam_icon_50300-b](https://cloud.githubusercontent.com/assets/1087450/11094038/c96674f4-888d-11e5-9295-0dbe5ddb5d29.png)

And here's the SVG:
https://dl.dropboxusercontent.com/u/40932393/steam_icon_50300-symbol.svg

The upside-down torn flag was used in quite a few promotional materials, is on the title screen of the game and represents the game quite well, I think (You are an american soldier fighting a group of american soldiers that rebelled, to over-summarize the plot)

**Comment by wa4557** [comment]
Second one is perfect imo :) (Maybe make the flag a tad smaller)

**Comment by MrTimscampi** [comment]
Thanks, that flag was really hard to make :D (I never used Inkscape or worked with SVGs before my few contributions here)
But it made me learn quite a lot about boolean operations and aligning stuff :p 

The symbol is currently 28px wide.

Here's a version with 26px wide:
![steam_icon_50300-symbol-26px](https://cloud.githubusercontent.com/assets/1087450/11095394/0b95bcd4-8895-11e5-9a6c-fffdb84435f6.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_50300-symbol-26px.svg

and here it is with 24px wide:
![steam_icon_50300-symbol-24px](https://cloud.githubusercontent.com/assets/1087450/11095410/1b400efa-8895-11e5-8c53-cdb3d2a14545.png)
**SVG:** https://dl.dropboxusercontent.com/u/40932393/steam_icon_50300-symbol-24px.svg

**Comment by wa4557** [comment]
:+1: I'd go with the 26px one

**Comment by MrTimscampi** [comment]
That's what I thought as well :)

I'll wait for @ChuckDaniels87 and/or @Foggalong to comment on it, then I'll push to my currently open pull request :)

**Comment by ChuckDaniels87** [comment]
Both icons are really cool, good job. However, I think second one is closer to guidelines. I would choose 28px for that type of symbol.

**Comment by MrTimscampi** [comment]
Thanks, will commit to my fork to update my current pull request with it :)

**Comment by palob** [comment]
Ah, that's what that icon is for. Actually I prefer the idea of the first one, I think it's more descriptive.
