### ISSUE TITLE
Two new icons

### ISSUE THREAD

**Issue by Nebrit** [numixproject/numix-icon-theme-circle#2614]
There are some icons of programs that do not have Numix, I created in SVG along the lines of design circle as I can send Numix

**Comment by ChuckDaniels87** [comment]
You can create a new **Pull Request** in GitHub. If you got problems with that, you can upload *SVGs* to external hosting service (p.e. Dropbox) and post links here.

**Comment by Nebrit** [comment]
I cant create Pull Request, i put links here.

Turpial New Icon, not exist -> https://www.dropbox.com/s/9u96beie78wtlnz/turpial.svg?dl=0

New Evolution proposal Item -> https://www.dropbox.com/s/a2y1eyfv0jkp8k1/evolution.svg?dl=0

I can inform, 

If added. On the other hand, I can continue designing some, such as the VLC can be improved.

Thanks.
