### ISSUE TITLE
Evolution preferences dialog

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2615]
There's 2 circle icons in the preferences shown in Evolution. The icons are called `preferences_mail.svg` and `preferences-calendar-and-tasks.svg` both already have a base icon available. I guess they just need to be deleted in circle.

**Comment by dirtydancing** [comment]
To clarify, here are two screenshots of the Evolution preferences with circle and with base:

Numix-Circle
![numix-circle](https://cloud.githubusercontent.com/assets/7164227/10588889/bd8395b4-76a8-11e5-9610-2cdd889c8e01.png)

Numix base
![numix](https://cloud.githubusercontent.com/assets/7164227/10588896/c5f3e8b6-76a8-11e5-91bd-178e6876b2dd.png)

Assuming these are `preferences-mail.svg` and `preferences-calendar-and-tasks.svg`: these two icons can arguably only be removed from Numix-Circle if their removal does not cause breakage elsewhere. Do we know if these two icons are used somewhere else, e.g. in the control center?

With Arch/GNOME (3.18), so far I have not come across these two icons elsewhere. GNOME control center does not include them. Screenshot:

![control-center](https://cloud.githubusercontent.com/assets/7164227/10589279/92f79df2-76aa-11e5-9a96-f13251c34e13.png)

**Comment by Foggalong** [comment]
Yeah, they're used in some control centres :/

**Comment by wa4557** [comment]
I think we cannot remove any `preferencs-*` icons from circle since they are used in various control centers :(

**Comment by palob** [comment]
Nope, these 2 icons are actually mimetype? icons, the ``x-something`` ones.
We can't remove them from Circle as they're used as app icons by two GNOME core apps, Contacts and Calendar.

Evolution uses quite a few bollocks icons (which do look somewhat fitting in Adwaita).
Just have a look at the icon for *Kontakte* in the screenshot above. It's an autocompletion action icon.

**Comment by Foggalong** [comment]
The last few weeks have taught me that Evolution doesn't really do anything (apart from not hardcoding the shit out of everything) right regarding icons.

**Comment by dirtydancing** [comment]
Agreed that Evolution is kind of a troublemaker when it comes to icon consistency, cf. the main window:

![evolution_main-window](https://cloud.githubusercontent.com/assets/7164227/10593180/bb45da64-76c1-11e5-9255-512701baae42.png)

**Comment by bil-elmoussaoui** [comment]
@dirtydancing for drafts icons, it's the same as in Gedit. Tried to report that on Launchpad but my issue was closed i don't know why..

**Comment by wa4557** [comment]
Evolution is generally one of the worst programs on Linux imo. Extremely bloated

**Comment by gregorydk** [comment]
IMHO, preferences icons should be in base and non-circle.

**Comment by palob** [comment]
As I pointed out above alas we can't simply remove the ``x-office-`` icons from Circle since this would raise another issue.

Anyway, I stand corrected. Only the icons in @dirtydancing's last screenshot are ``x-office-*`` mimetype icons.

The ones in your first screenshot I think are ``preferences-calendar-and-tasks`` and ``preferences-mail`` indeed. We have to look around whether those are shown somewhere else.

**Comment by gregorydk** [comment]
Possible but controversial solution: make all x-office-* and preferences-* icons in circle not circle but base style.

**Comment by dirtydancing** [comment]
Well, I for one do like the `preferences-*` Numix-Circle icons e.g. for the control center, and I would suggest to leave those as circle icons. For circle preferences icons cf. e.g. also https://github.com/numixproject/numix-icon-theme-circle/issues/927, https://github.com/numixproject/numix-icon-theme-circle/issues/1820.

The tendency so far has been to go for circle icons e.g. also for the `applications-*` icons for the main menues e.g. in Xfce/Cinnamon, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/2164, so circle icons also for `preferences-*` are consistent here.

Moreover, iirc in Numix-Circle there are currently consistently no non-circle icons anymore on purpose.

**Comment by palob** [comment]
If we did that we wouldn't need to have them in Circle.
We would have to redesign them as the current ones from base are category icons which look bland in contrast to all other Numix icons.

That aside I don't know whether ``preferences-calender-and-tasks`` and ``preferences-mail`` are needed in Circle. Maybe it's safe to remove them.

**Comment by Foggalong** [comment]
The two I believe are used in control centres

**Comment by Foggalong** [comment]
Don't think of this as a wontfix, but a cantfix. I'd suggest telling the upstream Evolution devs to use standard icon names but it was established long ago I think that that path is a lost cause.
