### ISSUE TITLE
Icons borders looking ugly when highlighted

### ISSUE THREAD

**Issue by hiperion85** [numixproject/numix-icon-theme-circle#2616]
I have noticed that the icons borders look bad when they are highlighted (the border becomes very dark and with a jagged look, what makes the icon have an awful effect).

I attach some images to show the contrast:

![save_normal](https://cloud.githubusercontent.com/assets/1215405/10593737/7344c2e8-76c6-11e5-870a-7d971f3b9886.png)
![save_highlight](https://cloud.githubusercontent.com/assets/1215405/10593738/73481ee8-76c6-11e5-9fc5-dc97060f9f07.png)
![search_normal](https://cloud.githubusercontent.com/assets/1215405/10593739/7348c884-76c6-11e5-9662-68c12057ae6f.png)
![search_highlight](https://cloud.githubusercontent.com/assets/1215405/10593740/734b62f6-76c6-11e5-96a6-0b4204ae6398.png)
![sound_normal](https://cloud.githubusercontent.com/assets/1215405/10593741/734d1dda-76c6-11e5-8adf-d36daceaa6fb.png)
![sound_highlight](https://cloud.githubusercontent.com/assets/1215405/10593742/73518da2-76c6-11e5-918c-6a95a8f22f46.png)

Apart from that, the icon set is wonderful. Thanks for your awesome work :)

**Comment by dirtydancing** [comment]
Which distribution is this? This might be GTK-related.

iirc, I ran into this kind of issue e.g. with GNOME control center 3.16/GTK 3.16. Currently, with Arch/GNOME 3.18/GTK 3.18, this is no problem when highlighting/hovering over the icon.

Screenshot of Arch/GNOME control center 3.18/GTK 3.18:

![gnome_318_control_center](https://cloud.githubusercontent.com/assets/7164227/10601358/4ed9da42-7711-11e5-8699-5b313ed6102b.png)

Actually, this might be Numix GTK theme related: in the screenshot above, I am using the default Adwaita GTK theme, but this issue is present with Numix GTK theme:

![numix-gtk](https://cloud.githubusercontent.com/assets/7164227/10601485/681fb318-7712-11e5-9b18-c99b343f76cd.png)

This would mean that this is not a Numix-Circle issue.

**Comment by palob** [comment]
I encounter this with some Numix Circle action icons (Adwaita/GTK+ 3.18.1). No problems with Circle.

**Comment by hiperion85** [comment]
The screenshots are taken under Ubuntu 14.04 with Gnome 3.10 (Adwaita gtk theme), but I've tested it with Ubuntu 15.10 Beta (that ships with Gnome 3.14) and the issue is still present.

**Comment by palob** [comment]
Doesn't 15.10 ship 3.16?

**Comment by hiperion85** [comment]
@palob 15.10 ships with 3.14 on most appplications (as far as I have seen).

I have tested with some other icon themes. Some of them (modern icon sets with similar looks) have the same effect (on rounded corners, which is where the problem resides). The sets with monochorome icons on toolbars look good (I think they have the same problem but being monochrome hides the effect).

**Comment by dirtydancing** [comment]
I have checked the control center with Arch/GNOME 3.18/GTK 3.18 with a couple of GTK themes: all is fine with default Adwaita, Arc and Paper GTK themes, but the issue (on rounded corners when hovering over, which is why this is particularly visible with Numix-Circle) is present with Numix, Ozon and Evopop GTK themes.

I have checked with a couple of icon themes, and this issue has appeared/not appeared consistently depending on the GTK theme and independent of the icon theme. This leads me to the conclusion that this is a GTK theme issue and should arguably be reported against Numix GTK theme over at https://github.com/shimmerproject/Numix/issues.

**Comment by dirtydancing** [comment]
@hiperion85 As to this issue showing with Adwaita GTK theme (and also with other GTK themes) for pre-3.18 GTK versions, this might be a pre-3.18 GTK issue.

**Comment by hiperion85** [comment]
Thank @dirtydancing , I'll try with Gnome 3.18

Have you tried also with the buttons on the menus (for example, Gedit). Because on control center, I only experiment the issue when hovering on the list after search, not hovering on the items when they all appear without having searched.

**Comment by dirtydancing** [comment]
@hiperion85 I do not really have that many app menu icons, rather header bars, also e.g. with Gedit, and I have not noticed problems so far.

With Numix GTK theme, the issue for me arises right away when just hovering over the icons in control center.

**Comment by hiperion85** [comment]
@dirtydancing maybe it's because Numis theme applies highlighting effect when hovering over the icons in control center and Adwaita doesn't. The question is if the problem still persists whenever highlighting effect is applied.

**Comment by dirtydancing** [comment]
Maybe. But I have seen GTK themes that do hightlight in some way or the other when hovering, and that still have no issues here, e.g. Paper GTK theme (in contrast to e.g. Evopop GTK theme).

**Comment by hiperion85** [comment]
I have just tried Paper GTK theme and it causes the same jagged borders effect when hovering on the icons in the list on control center after search.

**Comment by dirtydancing** [comment]
I cannot reproduce that with Paper GTK theme and Arch/GNOME (3.18), all fine here.

![paper-gtk](https://cloud.githubusercontent.com/assets/7164227/10609736/4a292a82-7745-11e5-91f4-68aa3efaac67.png)

**Comment by hiperion85** [comment]
Ubuntu 14.04 with Gnome 3.10. Paper GTK theme.

![captura de pantalla de 2015-10-20 16 18 22](https://cloud.githubusercontent.com/assets/1215405/10609997/540c8854-7746-11e5-81e2-283c873d73a1.png)

**Comment by dirtydancing** [comment]
In contrast, fine here with Paper GTK theme:

![paper](https://cloud.githubusercontent.com/assets/7164227/10610180/044b914c-7747-11e5-8fa8-e56d7d0586ab.png)

**Comment by hiperion85** [comment]
That is because your Paper GTK theme is not highlighting the icon on hover (I've compared the two images orange color of the icon and its brighter on mine). Maybe we are using different versions of the theme (or the same theme is operating slightly different due to GTK version on our OS).

But I am sure that the problem will persist if the icons are highligthed.

**Comment by dirtydancing** [comment]
Well, on my end Paper GTK theme is not highlighting in the control center search when hoving over, but as I demonstrated above, it is highlighting on the main control center window, and as I have written, e.g. Evopop GTK theme is highlighting similarly, and there, in contrast to Paper GTK, this issue arises.

Screenshot with Evopop GTK, issue is present:

![evopop-gtk](https://cloud.githubusercontent.com/assets/7164227/10610489/52d546ae-7748-11e5-8fc2-7d08df6270f3.png)

So to me, this situation is not entirely clear. You are probably right and this is a question of the GTK theme version and the GTK+ version. It might also have to do with the style of hover highlighting.

**Comment by dirtydancing** [comment]
It might well be that this issue arises once the icon itself is hover highlighted in a lighter colour, just as you have suspected. The frame around the icon might be irrelevant. This might mean that those GTK themes that do not hover highlight the icon itself do not have this issue, whereas those GTK themes that do highlight the icon itself have this issue. Which in turn might mean that this is a general GTK+ issue.

In any event, by now I think it has become clear that this is not a Numix-Circle icon theme issue :-)

**Comment by Foggalong** [comment]
@satya164 ?

**Comment by bil-elmoussaoui** [comment]
A theme issue !

**Comment by satya164** [comment]
Seems to happen when the icon is highlighted. GTK themes can only specify if the icon has to be highlighted, but the image processing is done by GTK internally, so there is some issue with that.

**Comment by Foggalong** [comment]
Do the gtk themes this doesn't effect then not use highlighting?

**Comment by satya164** [comment]
It seems so, from the screenshots.

**Comment by Foggalong** [comment]
:+1:

**Comment by palob** [comment]
Maybe librsvg thing. Does it occur with PNG themes as well?
Is the ``size`` flag in the ``index.theme`` file (fixed, scalable) of any relevance?

**Comment by dirtydancing** [comment]
Did a quick check by replacing `preferences-desktop-wallpaper.svg` with `preferences-desktop-wallpaper.png`, and the same issue showed up with Numix GTK theme. So it does not seem to be .svg-related. Probably some kind of reproduction is needed here to be certain about this.

I am not sure how the size flag (fixed/scalable) could be of any relevance here. I did some checking by setting the size 48 from `fixed` to `scalable`, but nothing changed. Again, this was just a quick check.

**Comment by dirtydancing** [comment]
To visualise, I also get this issue with default Adwaita GTK theme with Arch/GNOME (3.18) for action icons, e.g. in Liferea Feed Reader. This happens with all GTK themes that hover highlight the icon colour itself. In contrast, again this is no problem with e.g. Paper GTK theme with only a box around the icon.

Screenshot with default Adwaita GTK theme in Liferea Feed Reader 1.10.16 with Arch/Gnome (3.18):

![liferea_adwaita-gtk](https://cloud.githubusercontent.com/assets/7164227/10709699/a2e760bc-7a38-11e5-9a01-3afdd99f3f3b.png)
