### ISSUE TITLE
Icon for SmartGit

### ISSUE THREAD

**Issue by fedelevin** [numixproject/numix-icon-theme-circle#2619]
A numix-icon-theme-circle for **SmartGit** is missing.

http://www.syntevo.com/smartgit/

smartgit-32.png ![smartgit-32](https://cloud.githubusercontent.com/assets/3971539/10616546/fc83f680-773b-11e5-831a-c1f0e69d21a4.png)
smartgit-48.png ![smartgit-48](https://cloud.githubusercontent.com/assets/3971539/10616544/fc7b5ad4-773b-11e5-9ded-ee40c79f5632.png)
smartgit-64.png ![smartgit-64](https://cloud.githubusercontent.com/assets/3971539/10616543/fc7ad8c0-773b-11e5-82d0-fac21740a5cb.png)
smartgit-128.png ![smartgit-128](https://cloud.githubusercontent.com/assets/3971539/10616545/fc7e1b20-773b-11e5-8270-82b4a5d21c12.png)
smartgit-256.png ![smartgit-256](https://cloud.githubusercontent.com/assets/3971539/10616547/fc8a285c-773b-11e5-84a0-567fa8775ddf.png)

The icon name says **"syntevo-smartgit.png"**
The desktop file name is **"syntevo-smartgit.desktop"**

I hope I'm not forgetting any data.
Thanks guys, your work it's amazing!

**Comment by fedelevin** [comment]
The icon name says "syntevo-smartgit.png"

**Comment by bil-elmoussaoui** [comment]
The icon is hardcoded, you need to add the desktop file name too!

**Comment by fedelevin** [comment]
@bil-elmoussaoui Now it's ok?

**Comment by bil-elmoussaoui** [comment]
Sorry, i meant the desktop file name; the one you find in `/usr/share/applications/` or `/$HOME/.local/share/applications/`
anyway, i'm using this application too, the desktop file name is `syntevo-smartgit.desktop`

**Comment by fedelevin** [comment]
@bil-elmoussaoui great, thanks!

**Comment by fedelevin** [comment]
@Foggalong The hardcode-fixer don't work for me with SmartGit :(

**Comment by bil-elmoussaoui** [comment]
You Should report that there ! With the needed informations

**Comment by Foggalong** [comment]
It's a case of reporting it there then (it's not a Numix product) and I'll add the fix :)
