### ISSUE TITLE
Is there any plans about source file types

### ISSUE THREAD

**Issue by andymost** [numixproject/numix-icon-theme-circle#2621]
Is there any plans about source file types like:
 - *.css
 - *.less
 - *.cpp
 - *.py
 - *.hs

**Comment by Foggalong** [comment]
All the different mimetypes are taken care of by our [base icon them](https://github.com/numixproject/numix-icon-theme) which Circle inherits :)

**Comment by palob** [comment]
All file types do have distinct Numix icon apart from ``less`` which I'm not sure is recognised by your system. It needs to be covered by the [shared-mime-info](http://freedesktop.org/wiki/Software/shared-mime-info/) package to be.

**Comment by Foggalong** [comment]
Am I remembering right that `*.less` is to do with CSS?

**Comment by palob** [comment]
Yep, it's a CSS prepocessor, like Sass.

**Comment by Foggalong** [comment]
I've done some searching and it looks like it just uses `text/css`
