### ISSUE TITLE
Icon for DupeGuru

### ISSUE THREAD

**Issue by acutbal** [numixproject/numix-icon-theme-circle#2622]
A numix-circle icon is missing for dupeGuru .

The icon line says "/usr/share/dupeguru_se/dgse_logo_128.png" and the original icon is attached
![dupeguru_se](https://cloud.githubusercontent.com/assets/2278584/10638608/1dfebcb6-780c-11e5-92a1-668afedd9150.png)

Thank you very much!!

**Comment by palob** [comment]
Hi, can you please add the name of the ``.desktop`` file?

**Comment by acutbal** [comment]
Hi!!

That's what I get when I drag and drop the desktop file to Gedit:

[Desktop Entry]
Name=dupeGuru
Comment=Find duplicate files.
Exec=dupeguru_se
Icon=/usr/share/dupeguru_se/dgse_logo_128.png
Terminal=false
Type=Application
Categories=Utility;


Thank you very much!!

**Comment by Foggalong** [comment]
@acutbal We also need the name of the file itself

**Comment by acutbal** [comment]
Ops... I'm sorry, excuse me... :smile: 

This is the name:  dupeguru_se.desktop

Thank you very much and best regards!!

**Comment by palob** [comment]
Something like this?
![dupeguru](https://cloud.githubusercontent.com/assets/7050624/10679266/cd5df968-7917-11e5-93e5-4d4c79a309d8.png)

**Comment by acutbal** [comment]
Hello!!

I like it very much, for me it's fine!! But I'm not a designer, just a fan
of numix's stuff, specially numix icon circle and numix light theme. The
last decision it's yours... 😀😀

Thank you very much and very best regards!!! 😀😀

Enviado desde mi Nexus 6

**Comment by Foggalong** [comment]
:+1:
