### ISSUE TITLE
Missing icon for IDLE

### ISSUE THREAD

**Issue by vedangmehta** [numixproject/numix-icon-theme-circle#2625]
The icon for IDLE is missing.
Do note that there're many versions of IDLE in software center with the same icon.
Icon attributes for different versions of IDLE are as follows :

IDLE using Python 3.5 : "/usr/share/pixmaps/python3.5.xpm", Desktop file name : "idle-python3.5.desktop"

IDLE using Python 3.4 : "/usr/share/pixmaps/python3.4.xpm", Desktop file name : "idle-python3.4.desktop"

IDLE using Python 2.7 : "/usr/share/pixmaps/python2.7.xpm", Desktop file name : "idle-python2.7.desktop"

IDLE : "/usr/share/pixmaps/idle.xpm", Desktop file name : "idle.desktop"

IDLE 3: "/usr/share/pixmaps/idle3.xpm", Desktop file name : "idle3.desktop"

I'm also uploading the screenshot.
![screenshot from 2015-10-23 01-49-34](https://cloud.githubusercontent.com/assets/8724529/10677507/82211c06-792a-11e5-9d61-1dd2418fc1ea.png)

**Comment by palob** [comment]
It's [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).
