### ISSUE TITLE
Icon missing for Browser

### ISSUE THREAD

**Issue by vedangmehta** [numixproject/numix-icon-theme-circle#2626]
Numix circle icon is missing for Ubuntu web browser.
I'm attaching a screenshot and the essential details.
Icon option says "/usr/share/webbrowser-app/webbrowser-app.png".
The desktop file name is "webbrowser-app.desktop".

![screenshot from 2015-10-23 02-17-12](https://cloud.githubusercontent.com/assets/8724529/10677878/9acbb534-792c-11e5-9a46-a6588ac15805.png)

**Comment by palob** [comment]
It's [harcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).

**Comment by Foggalong** [comment]
Not a good sign that Ubuntu are actively hardcoding their primary default app in Unity 8
