### ISSUE TITLE
Icon for GNOME Games

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2627]
The nex new GNOME app.
https://wiki.gnome.org/Apps/Games

Icon=gnome-games
![gnome-games](https://cloud.githubusercontent.com/assets/7050624/10679738/d3cd8d7e-791a-11e5-8c31-ff1d4017193f.png)

**Comment by palob** [comment]
Hmm, we already have got quite a few similar icons:
![game-icons](https://cloud.githubusercontent.com/assets/7050624/10679758/f63192de-791a-11e5-8e84-555ffff57d17.png)

**Comment by Foggalong** [comment]
Yeah, probably symlink to application-games since that symbol is directly based on the 360 controller

**Comment by MrTimscampi** [comment]
Sorry for the mess with my commits, guys, I messed up and had to clean my fork after pushing the commit.

There's only one of those commit in my pull request, now, but these references don't seem to go away, despite having removed the commits.
