### ISSUE TITLE
Icon for Nylas

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2630]
Nylas is a new open source mail client [More info](https://nylas.com/N1)
Desktop file name : `nylas.desktop`
Icon name : `Icon=nylas`
The default icon 
![icon](https://raw.githubusercontent.com/nylas/N1/master/build/resources/linux/icons/256.png)
[screenshot](https://cloud.githubusercontent.com/assets/7660997/10758434/9a6d3fee-7cb1-11e5-9248-2a9c535f507b.png)

**Comment by Foggalong** [comment]
Do you use GNOME on a tablet? :O

**Comment by bil-elmoussaoui** [comment]
@Foggalong nop! i tactile screen :( i don't how to disable it..

**Comment by Foggalong** [comment]
Oh cool! It should be possible surely?

**Comment by bil-elmoussaoui** [comment]
Don't know. The only thing that i can disable is the tactile keyboard(only in Gnome); i didn't find anything on the boot settings :/

**Comment by 2Cubed** [comment]
Would love to see a Nylas icon. :+1:

**Comment by rtud** [comment]
+1 :)

**Comment by marioguerriero** [comment]
+1

**Comment by palob** [comment]
Anybody got the icon in higher resolution?

**Comment by bil-elmoussaoui** [comment]
@palob  https://github.com/nylas/N1/tree/master/build/resources/linux/icons

**Comment by palob** [comment]
I've got this so far:
![nylas2](https://cloud.githubusercontent.com/assets/7050624/12066361/2b7351f0-afe7-11e5-9370-da081afdc1a1.png)

**Comment by bil-elmoussaoui** [comment]
Looks great for me :+1:

**Comment by palob** [comment]
Some alts:
![nylas4](https://cloud.githubusercontent.com/assets/7050624/12066932/bd10f73a-aff0-11e5-9e2a-d22632842907.png)
![nylas5](https://cloud.githubusercontent.com/assets/7050624/12066930/bd0b8a16-aff0-11e5-9571-476b7787effe.png)
![nylas6](https://cloud.githubusercontent.com/assets/7050624/12066931/bd0e7ea6-aff0-11e5-9801-b65481c255c5.png)

**Comment by Foggalong** [comment]
Alts are nice but the border width breaks the guildelines. I'm guessing that guessing that the symbol doesn't look too great when the border is the 30px circle though, so go with the original
