### ISSUE TITLE
Icon for Master PDF Editor 3

### ISSUE THREAD

**Issue by acutbal** [numixproject/numix-icon-theme-circle#2633]
Hello!!

A numix-circle icon is missing for Master PDF Editor 3.

The icon line says "masterpdfeditor3.png"
Desktop file name: masterpdfeditor3.desktop

That's what I get when I drag and drop the desktop file to Gedit:
[Desktop Entry]
Name=Master PDF Editor 3
Comment=Edit PDF files
Exec=/opt/master-pdf-editor-3/masterpdfeditor3 %f
Path=/opt/master-pdf-editor-3
Terminal=false
Icon=masterpdfeditor3.png
Type=Application
Categories=Office;Utility
MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;

The original icon is attached.
![captura de pantalla de 2015-10-30 17 25 12](https://cloud.githubusercontent.com/assets/2278584/10851450/710c38fe-7f2b-11e5-8839-bb6c520fb504.png)

Thank you very much!! :smile:

**Comment by charlesvdv** [comment]
Hi, 

The icon of master-pdf-editor is not missing. You just have to change the icon line with:
icon=master-pdf-editor and it will find the numix circle icon for master-pdf-editor :smile:

**Comment by acutbal** [comment]
Done, thank you very much!! :smile:
