### ISSUE TITLE
Icon for mupen64plus and mupen64plus-qt

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme-circle#2634]
mupen64plus is a Nintendo 64 emulator http://mupen64plus.org/
Desktop file name `mupen64plus.desktop`
Icon name `Icon=mupen64plus`
mupen64plus-qt is a QT GUI for mupen64plus https://github.com/dh4/mupen64plus-qt
Desktop file name `mupen64plus-qt.desktop`
Icon name `Icon=mupen64plus-qt`

Both stock icons are the same, one symlink to the other would suffice:

![mupen64plus](https://cloud.githubusercontent.com/assets/7532854/10870241/f3622a98-80ac-11e5-9614-1d095b4cfb77.png)

**Comment by palob** [comment]
We've got [this one](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/m64py.svg).

**Comment by sljunkie** [comment]
@palob nice, this will suffice as a symlink for both.

**Comment by palob** [comment]
We need all icons names so symlinks are alway better than renaming.
