### ISSUE TITLE
applications-system.svg metaphor

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2635]
Maybe it could do with a redesign?
The current one doesn't scream ``system`` that loudly.
![system](https://cloud.githubusercontent.com/assets/7050624/10872149/cb4bac06-80fb-11e5-8b4e-6392ba30383d.png)

**Comment by bil-elmoussaoui** [comment]
maybe a non circle icon?

**Comment by wa4557** [comment]
Used in ubuntu control center. So a circle icon is needed

**Comment by MrTimscampi** [comment]
Under Gnome 3.18, it is used in the Settings as "Details".
Brings up information on the system (Gnome version, memory, CPU, GPU, distribution), default applications and default actions for removable media.

**Comment by Foggalong** [comment]
^ this is why it's designed the way it is. A few different DEs & distros use it as a trigger for general system information
