### ISSUE TITLE
Icon for Visual-Studio-Code

### ISSUE THREAD

**Issue by Slothberry** [numixproject/numix-icon-theme-circle#2637]
There is no numix circle icon for the Linux version of Visual Studio Code as of yet.
I believe the icon to be "vso"

![vso](https://cloud.githubusercontent.com/assets/7146796/10903980/bf4e4f2a-820f-11e5-9bad-6ad49d97f43c.png)

**Comment by ChuckDaniels87** [comment]
Duplicated #2041, this icon is hardcoded.

**Comment by Foggalong** [comment]
This has the icon reported as `vso` though which [isn't one we have](https://github.com/numixproject/numix-icon-theme-circle/find/master)

**Comment by ChuckDaniels87** [comment]
Ops, sorry.

**Comment by Slothberry** [comment]
I wish I could finally contribute to this wonderful project myself, but things have been piling up and now it's literally the only icon of a program that I'm using that doesn't have a proper numix icon theme.

**Comment by ChuckDaniels87** [comment]
Is this only a symlink then?

**Comment by Foggalong** [comment]
@ChuckDaniels87 yeah
