### ISSUE TITLE
latexila icon bug

### ISSUE THREAD

**Issue by charlesvdv** [numixproject/numix-icon-theme-circle#2640]
Hello, 

On my computer, the latexila icon is the same icon as gedit. Normally with #1260, a latexila icon should exist. Does any one have an idea how to fix this ? 

Thanks.

ps : I've installed the numix-icon-theme-circle via the copr on my fedora machine.

**Comment by Foggalong** [comment]
Yeah, the copr package is running behind the git version which is why it's not showing up right. If you want the latest version (for now, until we can get a better copr setup) you'll have to use it straight from git :(

**Comment by charlesvdv** [comment]
Ok I will use git then :smile: Thanks a lot !

**Comment by Foggalong** [comment]
No problem! Any other questions feel free to ask :)
