### ISSUE TITLE
application-vnd.iccprofile.svg is a mimetype icon

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2644]
Does anybody know why it is in Circle?

**Comment by Foggalong** [comment]
[This thing](https://github.com/numixproject/numix-icon-theme-circle/issues/242)

**Comment by bil-elmoussaoui** [comment]
The same as #2367 and #2440, adding the mimetype to base will not affect the circular icon ;)

**Comment by palob** [comment]
OK, thanks :)
