### ISSUE TITLE
Icon for application/x-keepass2

### ISSUE THREAD

**Issue by MrTimscampi** [numixproject/numix-icon-theme-circle#2650]
Keepass2/KeepassX databases in the .kdbx format don't have a proper icon.

There are already icons for Keepass2 and KeepassX, those could be used for ideas.

As indicated in the issue's name, MIME type is application/x-keepass2.

**Comment by palob** [comment]
This would be an issue for the [base theme](https://github.com/numixproject/numix-icon-theme).
I've submitted a PR fixing it.
