### ISSUE TITLE
Zandronum

### ISSUE THREAD

**Issue by Bamminator** [numixproject/numix-icon-theme-circle#2654]
I have Zandronum and Doomseeker installed on my Elementary OS and they are displayed with their default icons. But however i have looked inside the the app icon list for numix-circle and i noticed that you have made special icons for them.
Is this a bug or do i have to configure something i haven't seen?
I installed the Numix theme through Elementary tweaks

I hope you can help me :)
Brian

**Comment by Foggalong** [comment]
Please add the details outlined in the readme :)
