### ISSUE TITLE
Can't get it from ppa in Ubuntu 15.10 

### ISSUE THREAD

**Issue by SalahAdDin** [numixproject/numix-icon-theme-circle#2655]
I put the ppa and update the list but i can get the packages:
![captura de pantalla de 2015-11-11 22-56-18](https://cloud.githubusercontent.com/assets/5034215/11110246/710aa21e-88c7-11e5-9737-60439082973e.png)

**Comment by bil-elmoussaoui** [comment]
```bash
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install  numix-icon-theme numix-icon-theme-circle	
```
The other packages you're trying to install `numix-icon-theme-bevel` and `numix-plank-theme` were not updated (yet maybe)

**Comment by SalahAdDin** [comment]
I have to donwload from launchpad.
