### ISSUE TITLE
Icon for Linphone

### ISSUE THREAD

**Issue by abrahamortiz** [numixproject/numix-icon-theme-circle#2676]
A numix-circle-icon for linphone is missing.

The icon line says "/usr/share/pixmaps/linphone/linphone.png" and the original icon is attached.

![selection_002](https://cloud.githubusercontent.com/assets/12741256/11165900/8b80f4ea-8ae3-11e5-9fdb-b63ce53d5eba.png)

**Comment by Foggalong** [comment]
Hardcoded duplicate of #977. See the readme for more info
