### ISSUE TITLE
Icon for intelliJ

### ISSUE THREAD

**Issue by marczykm** [numixproject/numix-icon-theme-circle#2679]
A numix circle icon for intelliJ development application.
The icon link says "/home/marcin/Aplikacje/idea-IC-143.382.35/bin/idea.png" and original icon is attached.
![zrzut ekranu z 2015-11-15 14-31-56](https://cloud.githubusercontent.com/assets/3109269/11168948/a704f1d6-8ba5-11e5-89ef-e1b872d95cf5.png)

**Comment by bil-elmoussaoui** [comment]
The icon already exists. You can fix that using hardcode-fixer as mentioned in Readme. Or you can modify the desktop file manually and change the icon name
