### ISSUE TITLE
Icon for FoxIt

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2685]
[FoxIt](https://www.foxitsoftware.com) is a pdf viewer 

- The launcher: `FoxitReader.desktop`
- Launcher Path: `/home/leco/.local/share/applications`
- (Hardcoded) icon name: `FoxitReader.png`

- Default icon:
![foxitreader](https://cloud.githubusercontent.com/assets/1277920/11214687/cd4d1960-8d29-11e5-9dd6-d8c5cc254878.png)

**Comment by Foggalong** [comment]
Duplicate of #2581
