### ISSUE TITLE
Symlink "whatsapp" -> "web-whatsapp"

### ISSUE THREAD

**Issue by mdemierre** [numixproject/numix-icon-theme-circle#27]
I don't know if this is a problem in Numix or in the packages but I found at least one package using the "whatsapp" icon name:
https://aur.archlinux.org/packages/whatsapp-web-desktop/

Moka has the symlink:
https://github.com/snwh/moka-icon-theme/blob/master/Moka/48x48/web/whatsapp.png

By the way, is there an effort on standardizing this kind of icon naming for apps that do not have an official GNU/Linux binary distributed?

**Comment by bil-elmoussaoui** [comment]
@mdemierre the issue should be reported here instead https://github.com/numixproject/numix-core. I've added the symlink on my latest commit https://github.com/numixproject/numix-core/commit/fdad31f7bdde80b10935b5e9eccf4e2a3d3d51dd; You have to wait until the next release to have the new symlink.

**Comment by mdemierre** [comment]
@bil-elmoussaoui Sorry I thought this was Linux packaging specific. Thanks for the quick update.
