### ISSUE TITLE
Icon for Atom Editor Beta

### ISSUE THREAD

**Issue by carloshfoliveira** [numixproject/numix-icon-theme-circle#2721]
There's an icon for the Atom Text Editor but none for the beta version. I suggest using the same one for the beta, as you already do with Firefox, both Beta, Developer Edition and Stable share the same icon.

**Comment by Foggalong** [comment]
We do actually have different icons for every branch of Firefox: [stable](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/firefox.svg), [beta](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/firefox-beta.svg), [aurora](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/firefox-aurora.svg), [nightly](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/firefox-trunk.svg), [developer](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/firefox-trunk.svg), and [unbranded](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/firefox-icon-unbranded.svg).

Also, can you please add the icon name from the .desktop file as shown in the README :)

**Comment by carloshfoliveira** [comment]
I found out that my FF desktop was still using the stable icon and then I
changed to the dev edition :) the icon name is atom-beta.

**Comment by Foggalong** [comment]
Thanks :+1:

**Comment by palob** [comment]
How about a pale variant of atom.svg for atom-beta.svg?
![atom-beta](https://cloud.githubusercontent.com/assets/7050624/11761475/6a28d4c4-a0c4-11e5-8238-5eae8d79bc57.png)

**Comment by ChuckDaniels87** [comment]
You could try with the colour palette of the [beta website](https://atom.io/beta). [Stable release site](https://atom.io/).

**Comment by palob** [comment]
Like this?
![atom-beta2b](https://cloud.githubusercontent.com/assets/7050624/11761611/97256d8e-a0c9-11e5-9011-098fbaf77aa5.png)

**Comment by carloshfoliveira** [comment]
I like it! I think that the science icon is quite an adaption of the official Atom Beta icon haha but, IMHO, this one looks better 


Enviado do meu smartphone Sony Xperia™

---- palob escreveu ----

**Comment by ChuckDaniels87** [comment]
Yeah, really nice. :+1:
