### ISSUE TITLE
Icon for DataGrip

### ISSUE THREAD

**Issue by marioguerriero** [numixproject/numix-icon-theme-circle#2722]
Name: 0xDBE
Description: New Intelligent IDE for DBAs and SQL Developers
Icon:
![Original Icon](https://pbs.twimg.com/profile_images/479525398502326272/J-YgEAmn.png)

https://www.jetbrains.com/dbe/

**Comment by Foggalong** [comment]
is 0xDBE that actual icon name?

**Comment by marioguerriero** [comment]
I think so

**Comment by marioguerriero** [comment]
The team recently released their first stable version and rebranded the software. It is not called DataGrip: https://www.jetbrains.com/datagrip/

The icon is now this:
![DataGrip](https://pbs.twimg.com/profile_images/677154323281797120/i78_A5Ym_400x400.png)

**Comment by ryanstull** [comment]
+1
