### ISSUE TITLE
Icon for Microsoft Access 2010

### ISSUE THREAD

**Issue by brunces** [numixproject/numix-icon-theme-circle#2724]
Hello, guys.

Could you please make a Circle icon for the following app?

Microsoft Access 2010

![ms-access](https://cloud.githubusercontent.com/assets/7181488/11611685/a3bcb2c6-9bc1-11e5-95c9-751e590a5bba.png)

I guess the name of the icon should be "ms-access.svg", just like you did with the other MS Office 2010 ones here https://github.com/numixproject/numix-icon-theme-circle/issues/628 .

Thank you very much for your attention. :)

brunces

**Comment by Foggalong** [comment]
Same was with LoL [here](https://github.com/numixproject/numix-icon-theme-circle/issues/1086) we only do WINE stuff if it's a popular request. Get 5 "+1"s and we'll switch it to a request.

**Comment by brunces** [comment]
No problem. I understand.

I tried and made one myself. Not as accurate or professional as the one you guys usually make, but...


[ms-access.zip](https://github.com/numixproject/numix-icon-theme-circle/files/53218/ms-access.zip)

Thanks anyway. Numix rocks! :)

**Comment by Foggalong** [comment]
It's not quite to the guidelines so I couldn't merge it straight off, but if you'd like to submit it for further feedback feel free to open a pull request :) in this context "wontfix" means "we won't fix, but don't mind if others do".
