### ISSUE TITLE
Issues with installing into ~/.local/share/icons

### ISSUE THREAD

**Issue by hhu94** [numixproject/numix-icon-theme-circle#2726]
I am trying to install numix-icon-theme-circle locally, and most things work fine except for some status bar icons (specifically InSync and fcitx). They are displayed as a question mark icon.

I have tried the following:

* Cloned the numix-icon-theme and numix-icon-theme-circle repositories and then moved all Numix* directories into ~/.local/share/icons.

* Installed the packages from ppa and then copied the Numix* directories from /usr/share/icons into ~/.local/share/icons, then uninstalled the packages.

Neither of these attempts were successful at fixing the status bar issue. Interestingly, cloning the repositories and copying the Numix* directories into /usr/share/icons did work properly.

I am not sure what is causing this, but it seems like there is something that requires the install to be in /usr/share/icons.

Edit: I am running Ubuntu 15.10, in case it matters.
[This](http://imgur.com/a/LUkCD) is the difference I'm experiencing.

**Comment by bil-elmoussaoui** [comment]
@wa4557 The symlinks that we create bettween Numix Circle and Numix Base shouldn't have this kind of side effects?

**Comment by wa4557** [comment]
If both are in ~/.local/share/icons it should work perfectly fine. @hhu94 Can you post the output of `ls ~/.local/share/icons` after you copied the themes to this folder?

**Comment by hhu94** [comment]
Here:
```
ls ~/.local/share/icons
hicolor  Numix  Numix-Circle  Numix-Circle-Light  Numix-Light
```
Also [here](https://github.com/numixproject/numix-icon-theme-circle/files/58845/tree.txt) is the output of `tree ~/.local/share/icons`.

**Comment by Foggalong** [comment]
Do you have the same Numix theme installed anywhere else?

**Comment by hhu94** [comment]
No, I made sure to only install it there.

**Comment by palob** [comment]
Is the second icon from the left something fctix-related?

**Comment by hhu94** [comment]
Yes, it is supposed to represent the current input language. It doesn't seem to be working properly either but I think that that's a separate issue.

**Comment by wa4557** [comment]
Hmm. Try moving NUmix to `~/.icons` instead of `~/.local/share/icons` (that's were Numix is installed in my case)

**Comment by hhu94** [comment]
@wa4557 doing this solved the issue. Somehow I was under the impression that `~/.icons` was deprecated in favor of `~/.local/share/icons`. It seems like that isn't the case.

**Comment by Foggalong** [comment]
It varies by Ubuntu flavour iirc
