### ISSUE TITLE
Icon for urxvt does not show correctly in task panel (RXVT-unicode)

### ISSUE THREAD

**Issue by whitephoenix0** [numixproject/numix-icon-theme-circle#2728]
http://i.imgur.com/cVDLFJ4.png
 As you can see, there is no icon for urxvt terminal. In the applications file, the icon shows up correctly however. I'm not sure if this is an issue on my installation or what. I'm using XFCE by the way.

**Comment by bil-elmoussaoui** [comment]
You can fix this issue using my script (StartupWMClassFixer)[https://github.com/bil-elmoussaoui/StartupWMClassFixer]. Please report your issue there with the informations needed to fix this (as mentioned in the readme.) This has nothing to do with Numix theme!

**Comment by whitephoenix0** [comment]
Looks like I actually just needed "rxvt-unicode-pixbuf" from aur, closing
