### ISSUE TITLE
Desktop background not displayed

### ISSUE THREAD

**Issue by ankitstarski** [numixproject/numix-icon-theme-circle#2729]
When you turn on desktop icons from `gnome-tweak-tool` and apply Numix theme, the Desktop background is overlayed by a whitish opaque background.

I'm using Fedora 23 running GNOME 3.18.1

**Comment by palob** [comment]
I suppose you're talking about the GTK theme?

**Comment by ankitstarski** [comment]
My bad, seems like I posted it on `numix-icon-theme-circle`
