### ISSUE TITLE
Game Urban Terror

### ISSUE THREAD

**Issue by mastaiza** [numixproject/numix-icon-theme-circle#2733]
![urbanterror_001](https://cloud.githubusercontent.com/assets/16268588/11762938/563d5b4c-a119-11e5-832a-0a2bc709548a.png)

**Comment by mastaiza** [comment]
You can make an icon of the game

**Comment by palob** [comment]
We need the information set out in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).
