### ISSUE TITLE
Repository not found in Fedora 

### ISSUE THREAD

**Issue by ChronoWaste** [numixproject/numix-icon-theme-circle#2737]
Using the console o fedy the repository not found :c

**Comment by bil-elmoussaoui** [comment]
There's a new copr repo for Numix : https://copr.fedoraproject.org/coprs/numix/numix/
You can enable it using `sudo dnf copr enable numix/numix`; And this was fixed in Fedy too: see this PR https://github.com/folkswithhats/fedy/pull/310
@Foggalong  can be closed
