### ISSUE TITLE
Icon for Zenmap

### ISSUE THREAD

**Issue by Stunkymonkey** [numixproject/numix-icon-theme-circle#2742]
Zenmap is installed on many computers. It would be nice to have an icon for it

Original Icon:
![Image of Zenmap] (http://www.macupdate.com/images/icons256/36710.png)

**Comment by palob** [comment]
Hi, please add the information asked for in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

**Comment by Foggalong** [comment]
Hardcoded, invalid, duplicate. Not very often those come along.
