### ISSUE TITLE
icon for dota 2 (steam)

### ISSUE THREAD

**Issue by dontspamm** [numixproject/numix-icon-theme-circle#2744]
Game: Dota 2
App ID 570 https://steamdb.info/app/570/
icon: [game-icon.zip](https://github.com/numixproject/numix-icon-theme-circle/files/67864/game-icon.zip)
icon path:steam/steam/steamapps/common/dota 2 beta/game/dota/resource
notes: icon is zipped because .bmp file cant be uploaded here

**Comment by bil-elmoussaoui** [comment]
Duplicate of #1074 #638. The icons is hardcoded, please look at the readme to see how to fix that.

**Comment by bil-elmoussaoui** [comment]
@Foggalong Forgot to close this one :P

**Comment by Foggalong** [comment]
:+1:
