### ISSUE TITLE
Icon for itch

### ISSUE THREAD

**Issue by herrflick** [numixproject/numix-icon-theme-circle#2745]
Hi, I'd love to have a Numix icon for the new Itch.io video games store app.

The icon line says "itch.png".

Cheers!
Carlos

![selection_052](https://cloud.githubusercontent.com/assets/16386424/11933391/9aabfbae-a7f3-11e5-84a3-d954b510a1c0.png)

**Comment by palob** [comment]
The icon is [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons), could you please tell us the name of the ``.desktop`` file?

**Comment by herrflick** [comment]
Sorry, I missed your commentary. It's "itch.desktop".
Thanks for your reply!

**Comment by palob** [comment]
Thanks :)
