### ISSUE TITLE
Units Converter

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2748]
I created a small application to convert between different units https://github.com/bil-elmoussaoui/UnitsConverter

The icon name 
`units-converter`

Default icon:  Still looking for an idea :P

**Comment by forivall** [comment]
I'm thinking of something like one of those [circular thermometers](https://duckduckgo.com/?q=circular+thermometer&iax=1&ia=images) or [speedometers](https://duckduckgo.com/?q=canadian+speedometer&iax=1&ia=images) with both Celcius and Fahrenheit / mph and km/h, and having the icon be two sets of notches on the outside & then something in the middle implying conversion, like the [typical arrows](https://duckduckgo.com/?q=convert&iax=1&ia=images)

**Comment by bil-elmoussaoui** [comment]
@forivall Good idea :+1: You can use `accessories-media-converter` as a base if you want to

**Comment by bil-elmoussaoui** [comment]
I'm closing this as i stopped working on the application!

**Comment by forivall** [comment]
Yeah, I tried to make something a few months ago, but it was crap.
