### ISSUE TITLE
Icon for gnome-twitch

### ISSUE THREAD

**Issue by anaturinbor** [numixproject/numix-icon-theme-circle#2749]
That video is not playing for me, sorry.

Original icon: 
![gnome-twitch](https://cloud.githubusercontent.com/assets/10692755/12012698/dd766a62-ad09-11e5-9d2c-89906aaf33ad.png)

Icon name: gnome-twitch

Description: GNOME Twitch is a GNOME 3 application for watching Twitch.tv (a popular live streaming video platform that primarily focuses on video gaming) on your desktop, without Flash or a web browser.

[Desktop Entry]
Version=0.0.1
Type=Application
Name=GNOME Twitch
Exec=/usr/bin/gnome-twitch
Icon=gnome-twitch
Name[en_AU]=com.gnome-twitch.app

**Comment by Foggalong** [comment]
Please add the details set out in the readme

**Comment by anaturinbor** [comment]
Sorry. I updated it the post based on other requests.

**Comment by Foggalong** [comment]
Thanks! :)

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by ChuckDaniels87** [comment]
I didn't know that awesome stuff existed.
