### ISSUE TITLE
Mint Software Manager "crippled icons"

### ISSUE THREAD

**Issue by zummuz** [numixproject/numix-icon-theme-circle#2750]
Hi.
For some reason there are only colored circles (means that icons were applied, but without images?) in Software Manager. Icons for these categories are also placed in kickoff and they work fine.

![screenshot from 2015-12-27 20 19 38](https://cloud.githubusercontent.com/assets/13698274/12011469/27c7c3f2-acdf-11e5-9b34-4564f61bfd3a.png)

The same behavior:
![screenshot from 2015-12-27 21 25 12](https://cloud.githubusercontent.com/assets/13698274/12011553/6700b8b8-ace3-11e5-986a-0db69f22f6c5.png)

Is that a known issue?
Linux Mint 17.3 cinnamon

**Comment by palob** [comment]
Never seen this anywhere else than the GitHub preview, no idea what's happening there. Is this a new issue or is it just now you started using Numix Circle?

Is the Mint Software Manager GTK, Qt or something else?

My uninformed guess is that those might be the icons which still have that unused clipping in their code.

**Comment by zummuz** [comment]
@palob 
>or is it just now you started using Numix Circle?

Yes, just started now.
>Is the Mint Software Manager GTK, Qt or something else?

Cinnamon is a desktop environment that is based on the GTK+ 3 toolkit.
So, I have installed libgtk-2.0-0 (2.24.23-0ubuntu1.3) and libgtk-3-0 (3.10.8~8+qiana)

**Comment by palob** [comment]
But are you sure the Software Manager (not a Cinnamin app) is GTK and uses librsvg for SVG rendering?

**Comment by palob** [comment]
Could you try whether ``sudo gtk-update-icon-cache -f /usr/share/icons/hicolor``, ``sudo gtk-update-icon-cache -f /usr/share/icons/Numix`` are of any help?

Maybe removing the icon thumbnail cache does something ``rm -R ~/.cache/thumbnails/*`` ``rm ~thumbnails/*``

**Comment by zummuz** [comment]
>Could you try whether sudo gtk-update-icon-cache -f /usr/share/icons/hicolor, sudo gtk-update-icon-cache -f /usr/share/icons/Numix are of any help?

No, nothing has changed.
>Maybe removing the icon thumbnail cache does something rm -R ~/.cache/thumbnails/* 
rm ~/.thumbnails/*

No, all the same.

**Comment by bil-elmoussaoui** [comment]
Mintinstall is a gtk application, you can check their source code in Github. But i've never seen that before, we had a lot of issues with MintInstall :(

**Comment by wa4557** [comment]
Is there any obvious difference between `applications-graphics` and e.g. `applications-games`?

**Comment by zummuz** [comment]
@wa4557 
Don't know:
`-rw-r--r-- 1 root root 9496 Dec 27 18:33 48x48/apps/applications-games.svg
lrwxrwxrwx 1 root root   24 Dec 27 18:33 48x48/apps/applications-graphics.svg -> accessories-painting.svg
-rw-r--r-- 1 root root 4363 Dec 27 18:33 48x48/apps/applications-internet.svg
lrwxrwxrwx 1 root root   10 Dec 27 18:33 48x48/apps/applications-office.svg -> docear.svg`

**Comment by zummuz** [comment]
@wa4557 
`-rw-r--r-- 1 root root 9496 Dec 27 18:33 48x48/apps/applications-games.svg`
`-rw-r--r-- 1 root root 4363 Dec 27 18:33 48x48/apps/applications-internet.svg`
`lrwxrwxrwx 1 root root   24 Dec 27 18:33 48x48/apps/applications-graphics.svg -> accessories-painting.svg`
`lrwxrwxrwx 1 root root   10 Dec 27 18:33 48x48/apps/applications-office.svg -> docear.svg`

**Comment by wa4557** [comment]
@zummuz: Could you try soemthing like `inkscape --vacuum-defs /path/to/accessories-paintings.svg`. Do everything @palob suggested above again. Change the icon theme to some other theme and back to Numix and see if something changed for `application-graphics`?

**Comment by palob** [comment]
Checked ``octave.svg`` and ``unetbootin.svg``. Both contain ``clipPath`` objects.

@zummuz 
[Here](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/unetbootin.svg?short_path=2fcbf1b#L7-L16) is the source code of ``unetbootin.svg``.

Could you please delete the lines 7 through 16 (as highlighted in the link above) and check if unetbootin shows up correct then?

**Comment by wa4557** [comment]
@palob The difference I see in these icons, is that the icons which work are "inkscape" svgs whereas the icons which don't have been treated with the svgcleaner-script. So a `inkscape --vacuum-defs` changes the icon back to a inkscape svg

**Comment by palob** [comment]
But there are working ones which have been treated with svgcleaner.
As far as I can see it's really just the ``clipPath`` stuff.

**Comment by zummuz** [comment]
@wa4557 
>@zummuz: Could you try soemthing like inkscape --vacuum-defs /path/to/accessories-paintings.svg. Then do everything @palob suggested above again; change the icon theme to some other theme and back to Numix and see if something changed for application-graphics?

It hasn't helped

@palob 
>Could you please open the icon in a text editor and delete lines 7 through 16 (as highlighted in the link above) and check if unetbootin looks fine then?

Looks fine:
![screenshot from 2015-12-28 15 48 12](https://cloud.githubusercontent.com/assets/13698274/12018951/0d011a68-ad7b-11e5-8c37-f64660f6b15e.png)

**Comment by wa4557** [comment]
@zummuz Cool, I guess @palob is right then

@palob Are there any icons that still need the `clipPath` stuff? Otherwise we should add an option to the svgcleaner script that removes those parts...

**Comment by zummuz** [comment]
Also some icons haven't been applied (firefox, for instance, applied only on installation page). And those which have been applied, after installation become empty with check mark (like unetbootin on the screenshot below) 
![screenshot from 2015-12-28 16 09 13](https://cloud.githubusercontent.com/assets/13698274/12019180/d7830d1c-ad7d-11e5-838f-5340a198371c.png)
Though that's not significant.

**Comment by bil-elmoussaoui** [comment]
I guess it's an issue with MintInstall..

**Comment by palob** [comment]
@wa4557 I don't think there is any icon which needs that. If any icon needed this it would show up broken in Qt DEs / image viewers.

**Comment by palob** [comment]
@bil-elmoussaoui Yeah, don't know where those non-Numix icons come from.
The Firefox icon is an outdated upstream icon revision, the VLC icon isn't the upstream icon either.

**Comment by palob** [comment]
in addition to ``clipPath`` stuff it looks like some icons have unused ``text`` objects in their code which ``inkscape --vacuum-defs`` and ``svgcleaner-cli`` can't aren't capable of removing.

**Comment by wa4557** [comment]
`scour` also does not remove them. We could manually remove them using `sed` or sth similar but not sure if this breaks something...

**Comment by palob** [comment]
Well, as with my previous cleanup PRs let's do it and see if something breaks.
It might be important to delete everything between each ``<clipPath...`` - ``</clipPath>`` instead of removing everyting between the first occurrence of ``<clipPath...`` and the last occurrence of ``</clipPath>`` in case there's something between different ``clipPath`` objects.

By the way, running the svglclean script on Numix Base saves about 45 MB currently.

**Comment by wa4557** [comment]
oO 45MB that's quite a bit...
Ok I'll try to think of a clever way to use `sed` or something similar...

**Comment by wa4557** [comment]
Harder then expected because `sed` is not powerful enough, so I had to settle down using `perl`

Anyways this does the trick: `find . -type f -iname "*.svg" -print0 | xargs -0 perl -i -pe 'BEGIN{undef $/;} s/<clipPath.*clipPath>//smg'`

I tried it and I cannot find any breakages

**Comment by palob** [comment]
That's great news. Are you going to open a PR? I'll help checking for breakage.

**Comment by wa4557** [comment]
Not opening a PR yet but you can check out this branch (`AdobeLightroom` clipping already removed) https://github.com/wa4557/numix-icon-theme-circle/tree/clipping

**Comment by wa4557** [comment]
@zummuz Could you try out the above mentioned branch as well and see if the breakage has gone away?

**Comment by wa4557** [comment]
`gnome-maps` was also still using clipping. No further breakage visible. I also removed leftover `text` tags (only 5 icons)

Altogether more than 10000 lines of code are removed by this "cleaning"

**Comment by zummuz** [comment]
@wa4557 
Yes, it works fine now:
![screenshot from 2015-12-30 23 06 47](https://cloud.githubusercontent.com/assets/13698274/12056727/d006ce2e-af4a-11e5-9d3d-2ca02d18a620.png)
Thanks a lot!

**Comment by bil-elmoussaoui** [comment]
@zummuz There's two missing icons, can you try to get the icons names and report them in Numix Circle? :+1:

**Comment by palob** [comment]
@wa4557 Haven't found any breakage so far :+1: . There's just the tiny issue that your current script leaves blank lines.

**Comment by wa4557** [comment]
I know. No easy way to fix that. There's even room for improvement since a new cleanup would remove now all the leftover IDs from the now removed clippings. What did you exactly use the other day?

**Comment by palob** [comment]
Just [this](https://github.com/numixproject/numix-tools/blob/master/numix-tools/svgclean) (you need to have ``svgcleaner`` installed).

**Comment by wa4557** [comment]
Cool. I ran that as well, now a `grep "clippath" *.svg` yields nothing

**Comment by wa4557** [comment]
Btw: Looking at the base theme there are even more icons that have this clipping... Especially the places icons seem to be full of them

**Comment by palob** [comment]
Thanks for reporting this @zummuz .

**Comment by zummuz** [comment]
@bil-elmoussaoui 
It looks like the icon for the Featured category is linked or someting - its never changed (`cs-default-applications.png`):
![](https://lh5.googleusercontent.com/-q6YArszVhE0/U--5JyX6sQI/AAAAAAAADXA/cxuf83HGgVM/w1280-h800/LM%2BSoftware%2BManager.png)
![](https://delightlylinux.files.wordpress.com/2014/06/usc01.png)
![](https://i.imgur.com/JsJOY7g.png)
And the name of the Accessories category icon is `applications-utilities.png`. Is it worth reporting?

**Comment by palob** [comment]
Btw, you can get a Numix Circle icon for Mint Software Center itself. It is [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).

**Comment by bil-elmoussaoui** [comment]
I still remember that the featured icon is hardcoded :( And yeah please report it so we can see if we can fix it :+1:

**Comment by zummuz** [comment]
@palob 
Yep, [thanks](https://github.com/Foggalong/hardcode-fixer/issues/215) :)
