### ISSUE TITLE
Icon for Fallout

### ISSUE THREAD

**Issue by kookerus** [numixproject/numix-icon-theme-circle#2753]
There's no icon for the original fallout. It's a wine app, so I don't know if I'm allowed to make a request for one. The original .ico file has 5 different images when converted, so I'll attach them all
![fallout-0](https://cloud.githubusercontent.com/assets/8160403/12046003/e4e1b256-ae7c-11e5-8616-73c86a8eeb78.png)
![fallout-1](https://cloud.githubusercontent.com/assets/8160403/12046000/e4dea53e-ae7c-11e5-8a82-63765ab8d022.png)
![fallout-2](https://cloud.githubusercontent.com/assets/8160403/12046001/e4dfbab4-ae7c-11e5-8ecb-c12d4db86be6.png)
![fallout-3](https://cloud.githubusercontent.com/assets/8160403/12046002/e4e1831c-ae7c-11e5-94cf-e1df2fee61c7.png)
![fallout-4](https://cloud.githubusercontent.com/assets/8160403/12046004/e4eec7d4-ae7c-11e5-856e-afcdf898c5fb.png)

My apologies this kind of request isn't allowed.

EDIT: edited to fit with the rules in the README.

**Comment by Foggalong** [comment]
Same was with LoL [here](https://github.com/numixproject/numix-icon-theme-circle/issues/1086) we only do WINE stuff if it's a popular request. Get 5 "+1"s and we'll switch it to a request.

**Comment by kookerus** [comment]
Okay, thanks for the info!

**Comment by KUPOinyourWINDOW** [comment]
+1

**Comment by Foggalong** [comment]
Please use GitHub reactions for your +1s, doing comments cloggs up the issue tracker. Both yours and this comment will be deleted in an hour.
