### ISSUE TITLE
Icon for SecureFX

### ISSUE THREAD

**Issue by kpod13** [numixproject/numix-icon-theme-circle#2762]
Hi all.

Happy new year and thank you very mutch for your work!

I created this issue, because this cool project doesn't contain icon for SecureFX (but contains for SecureCRT). 

Original icon was placed below.
![securefx_256x256](https://cloud.githubusercontent.com/assets/756949/12071966/d95672a6-b0d8-11e5-8ae3-e3456107ff5a.png)

**Comment by palob** [comment]
Hi, could you please add the ``Icon=...`` line from the respective ``.desktop`` file?

**Comment by kpod13** [comment]
HI, palob! Thank you for reply.

It is contain of /usr/share/applications/SecureFX.desktop
```
[Desktop Entry]
Name=SecureFX
Comment=SecureFX provides file transfer using SFTP, FTPSSL and FTP.
Exec=SecureFX
Icon=securefx
StartupNotify=true
Terminal=false
Type=Application
Categories=Network;
```

It works for SecureCRT (unity uses icon from current theme), but it does not work for SecureFX (because theme does not contain icon for SecureFX)

**Comment by Foggalong** [comment]
I close invalid issues if they're not updated after a few days. Thanks for adding the required details though

**Comment by kpod13** [comment]
I understood. That's ok.

Thank you for reopening issue, @Foggalong. I hope that this information is enough for work. Also, I am ready to help if you need additional information.

**Comment by Foggalong** [comment]
Yeah, this is enough information :+1:
