### ISSUE TITLE
im-jabber

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2763]
Is `im-jabber` used by any application? 
![screenshot from 2016-01-02 01-08-41](https://cloud.githubusercontent.com/assets/7660997/12072685/5fe02bb4-b0ed-11e5-9367-3d5ba850e04b.png)
The icon is symlinked to `jabber-im`. I think both are not used by any application.. The circle icon is used instead of base icon by Empathy

**Comment by Foggalong** [comment]
I think `im-jabber.svg` can be removed, but I'm not sure about `jabber-im.svg`. I'll sort thisnow :)

**Comment by bil-elmoussaoui** [comment]
I took a look at all the possible themes on the internet and i didn't find any applications using `jabber-im` :p but we can keep it ;)

**Comment by bil-elmoussaoui** [comment]
The right icon is used now :+1: 
![capture du 2016-01-19 11-58-08](https://cloud.githubusercontent.com/assets/7660997/12416823/f1cd2e28-bea3-11e5-8ae6-5afd8b33e48e.png)
