### ISSUE TITLE
Icon for guitarix

### ISSUE THREAD

**Issue by eduardomezencio** [numixproject/numix-icon-theme-circle#2766]
Icon missing for guitarix. Icon name is "gx_head". Here's the default icon
![gx_head](https://cloud.githubusercontent.com/assets/4137750/12083414/32d6823c-b28a-11e5-8687-620a7553a3bd.png)

**Comment by palob** [comment]
3 drafts, 1st one isn't really recognisable at small sizes, 2nd scales the best.
![gx_head](https://cloud.githubusercontent.com/assets/7050624/12431932/837ba422-bef8-11e5-89a2-f30ae20d9caa.png)
![gx_head2](https://cloud.githubusercontent.com/assets/7050624/12431934/83a158fc-bef8-11e5-8d49-94546e6cdb5c.png)
![gx_head3](https://cloud.githubusercontent.com/assets/7050624/12431933/837bde7e-bef8-11e5-89d6-6ff6ed36b547.png)

**Comment by Foggalong** [comment]
Number 2 is goodo :+!:
