### ISSUE TITLE
Icon for Gitter desktop

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-icon-theme-circle#2767]
I installed the Gitter desktop app from their website and found that there was no icon :worried: . And I also have the .desktop file.

**Comment by palob** [comment]
Could you please tell us the name of the ``.desktop`` file and the ``Ìcon=...`` line from inside?

**Comment by SuicSoft** [comment]
@palob The name of the ```.desktop``` file is ```gitter.desktop``` and the ```Icon=``` is ```/opt/Gitter/linux64/logo.png``` :worried:

**Comment by bil-elmoussaoui** [comment]
There's an icon for Gitter, just use Hardcode-fixer to change the icon name for you : https://github.com/Foggalong/hardcode-fixer

**Comment by SuicSoft** [comment]
@bil-elmoussaoui Thanks for the hard code fixer. Maybe ```numix-icon-theme-circle``` should add a ```CONTRIBUTING.md``` which says to use hardcode-fixer before creating an issue

**Comment by bil-elmoussaoui** [comment]
@SuicSoft https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons
