### ISSUE TITLE
[CHROME] Icon for ARC Welder

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-icon-theme-circle#2768]

**Comment by bil-elmoussaoui** [comment]
We need the icon name in the desktop file `$HOME/.local/share/applications/` and the default icon.

**Comment by SuicSoft** [comment]
@bil-elmoussaoui Here is the .desktop file
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=ARC Welder
Exec=/opt/google/chrome-unstable/google-chrome-unstable --user-data-dir=/home/suici/.config/google-chrome-unstable --profile-directory=Default --app-id=emfinbmielocnlhgmfkkmkngdoccbadn
Icon=chrome-emfinbmielocnlhgmfkkmkngdoccbadn-Default
StartupWMClass=crx_emfinbmielocnlhgmfkkmkngdoccbadn
```

**Comment by Foggalong** [comment]
@SuicSoft can you please add this information from the off in future? Icon requests are always appreciated but we can only act on them if we know what we're dealing with :)

**Comment by bil-elmoussaoui** [comment]
@SuicSoft + i didn't find this chrome extension, i think having the link of it in chrome store or the default icon would be better.

**Comment by Foggalong** [comment]
[It's here](https://chrome.google.com/webstore/detail/arc-welder/emfinbmielocnlhgmfkkmkngdoccbadn?utm_source=chrome-ntp-launcher)

**Comment by bil-elmoussaoui** [comment]
Can be symlinked to Android SDK or Android Studio? 
![screenshot from 2016-01-06 00-14-42](https://cloud.githubusercontent.com/assets/7660997/12130430/8156e36c-b40a-11e5-8a14-c97829ff6ab3.png)

**Comment by Foggalong** [comment]
Not really, it's a different type of software. The icon can certainly be similar though, maybe incorporating some of Chromes bright colours in there

**Comment by SuicSoft** [comment]
@bil-elmoussaoui Sorry for not replying , it was 4 am in my time zone. Anyways ARC Welder does not appear in the search results in the Chrome web store for some reason

**Comment by SuicSoft** [comment]
@Foggalong I checked for updates on my system and no updates are available . I have installed Numix Circle with the PPA

**Comment by Foggalong** [comment]
See here #2430
