### ISSUE TITLE
Icon for Android Studio

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-icon-theme-circle#2769]
It's already a circle, just thinking if this icon theme could have an icon.

**Comment by bil-elmoussaoui** [comment]
There's already an icon for Android studio, it's just hardcoded. Take a look at Hardcode-fixer issues

**Comment by SuicSoft** [comment]
@bil-elmoussaoui I ran the hard code fixer but there still isn't an icon

**Comment by bil-elmoussaoui** [comment]
@SuicSoft it's an issue with hardcode-fixer, not Numix! https://github.com/Foggalong/hardcode-fixer/issues/149 There's a fix as PR : https://github.com/Foggalong/hardcode-fixer/pull/213 if you can try it and see if everything works fine. But this can be closed :+1:

**Comment by SuicSoft** [comment]
@bil-elmoussaoui Thanks :smile:
