### ISSUE TITLE
HipChat icon

### ISSUE THREAD

**Issue by pericles** [numixproject/numix-icon-theme-circle#277]
First of all, thanks for the great work!

I noticed that there is no circle icon for hipchat, so I'd really appreciate if you guys could add one, below is some info about it.

desktop entry:
```
[Desktop Entry]
Name=HipChat
GenericName=Group chat and IM
Comment=Group chat and IM - built for teams
Exec=/opt/HipChat/bin/hipchat
Icon=hipchat.png
Terminal=0
Type=Application
Encoding=UTF-8
Categories=Network;InstantMessaging;
```

original icon: 
![hipchat-icon-100043057-medium](https://f.cloud.github.com/assets/213506/2184410/60e977a2-97bf-11e3-8f6a-ed0d910ad3da.png)

Thanks!

**Comment by Foggalong** [comment]
Moved to base :)
