### ISSUE TITLE
Inbox by Gmail

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-icon-theme-circle#2772]
Desktop File [```/home/suici/.local/share/applications/chrome-ajjmenfgmbpceneffopmikhahnkeebje-Default.desktop```]
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=App Launcher for Inbox by Gmail App
Exec=/opt/google/chrome-unstable/google-chrome-unstable --user-data-dir=/home/suici/.config/google-chrome-unstable --profile-directory=Default --app-id=ajjmenfgmbpceneffopmikhahnkeebje
Icon=chrome-ajjmenfgmbpceneffopmikhahnkeebje-Default
StartupWMClass=crx_ajjmenfgmbpceneffopmikhahnkeebje
```

**Comment by palob** [comment]
We've got this one. Is it a good fit?
![web-inbox](https://cloud.githubusercontent.com/assets/7050624/12154620/dcd374a6-b4c0-11e5-8d12-e2a74af62184.png)

It's already symlinked as ``chrome-pkclgpgponpjmpfokoepglboejdobkpl-Default``.

**Comment by Foggalong** [comment]
Yeah :)
