### ISSUE TITLE
Fcitx icon problem

### ISSUE THREAD

**Issue by myyerrol** [numixproject/numix-icon-theme-circle#2781]
![screenshot from 2016-01-09 22 46 34](https://cloud.githubusercontent.com/assets/4677346/12216607/f34f1316-b722-11e5-91b5-0b4c4955c2ec.png)
Why the icon of fcitx become painting.svg? And I like the previous icon(system default keyboard icon), How can I change it?

**Comment by palob** [comment]
Related to #2166.

**Comment by myyerrol** [comment]
Thank you! But how to change the current icon of fcitx to normal?
![screenshot from 2016-01-10 00 47 00](https://cloud.githubusercontent.com/assets/4677346/12217183/c381d482-b733-11e5-898e-a38e4b905464.png)
![screenshot from 2016-01-10 00 47 27](https://cloud.githubusercontent.com/assets/4677346/12217185/cb239676-b733-11e5-99c1-2d207a3e9d6d.png)

**Comment by palob** [comment]
We'll work out a better Nmix Circle match.
For using the "normal" icon rename ``/usr/share/icons/Numix-Circle/48x48/apps/fcitx.svg`` to for instance ``fcitx_.svg``.

**Comment by myyerrol** [comment]
![screenshot from 2016-01-10 01 58 58](https://cloud.githubusercontent.com/assets/4677346/12217505/c1b2e218-b73d-11e5-9d4f-64847035a540.png)
![screenshot from 2016-01-10 01 59 10](https://cloud.githubusercontent.com/assets/4677346/12217509/c7e04e3c-b73d-11e5-855f-6453ab9517b3.png)
Thanks a lot. But when I do what you said, the icon become a question mark. So excuse me, how to solve it ?

**Comment by palob** [comment]
``sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle``

**Comment by myyerrol** [comment]
Thank you very much! It solve my problem!!!
