### ISSUE TITLE
Icon for Nylas N1

### ISSUE THREAD

**Issue by gitgud-software** [numixproject/numix-icon-theme-circle#2788]
It's a pretty extensible mail client from Nylas, which currently mimes the OSX aesthetic. The default icon is already round, but undersized and certainly not flat. I hope to see an icon for this roll out soon, there's already a lot of buzz about it.
 
File: nylas.desktop
```
[Desktop Entry]
Name=Nylas N1
Comment=An extensible, open-source mail client built on the modern web.
GenericName=Nylas N1
Exec=/usr/share/nylas/nylas %U
Icon=nylas
Type=Application
StartupNotify=true
StartupWMClass=Nylas N1
Categories=GNOME;GTK;Utility;EmailClient;Development;
MimeType=text/plain;x-scheme-handler/mailto;x-scheme-handler/nylas;
```

**Comment by palob** [comment]
We've [already got it](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/nylas.svg).

You're not using the latest revision. Did you install from the PPA or copr repo?

**Comment by gitgud-software** [comment]
I'm using the PPA at the moment.

**Comment by bil-elmoussaoui** [comment]
@gitgud-software There's an issue with the launchpad ppa #2430

**Comment by gitgud-software** [comment]
Yeah it looks like that bug had something to do with it. I just re-added the PPA and upon updating the new package showed up.

**Comment by gitgud-software** [comment]
Duplicate Request
