### ISSUE TITLE
Icon for BYOND (Build Your Own Net Dream)

### ISSUE THREAD

**Issue by gitgud-software** [numixproject/numix-icon-theme-circle#2789]
This is a relatively popular game engine with a large community of users. The engine is built for the Windows platform with only CLI server hosting tools for Linux devices, however the game is very easy to run using WINE and Winetricks.

I've been using a custom byond.desktop for a while, since I haven't seen the app install an icon to the desktop successfully (at least, not on GNOME3). This may need some confirmation on another platform where desktop icons serve a more prominent role. Not that it would matter in particular: The current WineDB instructions call for the game to be installed in a 32-bit WINE environment for compatibility purposes.

Filename: byond.desktop
----------
```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=BYOND
Comment=Build Your Own Net Dream
Exec=bash /home/exampleuser/.byond/byond.sh
Icon=/home/exampleuser/.byond/byond.png
Terminal=false
Type=Application
Categories=Application;Games;
StartupNotify=true
```
BYOND Icon
------------
![byond](https://cloud.githubusercontent.com/assets/10673048/12310289/69a58df4-ba1d-11e5-937d-3c34c67afc6e.png)

**Comment by Foggalong** [comment]
Sorry, only just realised this is a WINE request. Same as with LoL [here](https://github.com/numixproject/numix-icon-theme-circle/issues/1086) we only do WINE stuff if it's a popular request. Get 5 "+1"s and we'll switch it to a request.
