### ISSUE TITLE
Icon for Autodesk Maya 2016

### ISSUE THREAD

**Issue by yattaah** [numixproject/numix-icon-theme-circle#2790]
Every 3D Artist will be happy about this :)

Icon: /usr/autodesk/maya/desktop/Maya.png
Desktop File Name: Autodesk-Maya2016.desktop

Thanks!

![autodesk-maya-2016](https://cloud.githubusercontent.com/assets/5113186/12323686/d5ef2240-babd-11e5-9d01-42d1c4b11d4a.png)

**Comment by Foggalong** [comment]
We have it, it's just hardcoded. Please report it [here](https://github.com/Foggalong/hardcode-fixer/issues) instead.

**Comment by bil-elmoussaoui** [comment]
@Foggalong i think that we need a symlink from`Maya2016` to  `maya` as for older versions?

**Comment by Foggalong** [comment]
I dunno, it could be they've changed their naming scheme and that isn't the case anymore?

**Comment by bil-elmoussaoui** [comment]
Just in case a theme will have a different icon for 2016 version & other versions
