### ISSUE TITLE
mate-panel-fish.svg linked to bluefish-alt.svg; bluefish-alt.svg does not exist

### ISSUE THREAD

**Issue by AndydeCleyre** [numixproject/numix-icon-theme-circle#2794]
Neither of these are icons I need, but the broken link trips up a script I use when `cp` can't stat `mate-panel-fish.svg`. Probably just point `mate-panel-fish.svg` to `bluefish.svg`, unless there's a better icon for the former or the former's no longer needed by anyone.

**Comment by Foggalong** [comment]
Ooo, good catch. I'll fix this now
