### ISSUE TITLE
Sizing issue for wingpanel icons

### ISSUE THREAD

**Issue by kwcooper** [numixproject/numix-icon-theme-circle#28]
This may just be me, and if so I'll investigate further, but the circle theme increases the size of my wing-panel indicator icons to a unnecessary size. 

![wingpanelnumixproblem](https://cloud.githubusercontent.com/assets/17441478/21468502/eb63e30c-c9e1-11e6-8a28-08d1b3ab734d.jpeg)

I'm on elementry os luna.

**Comment by Mibo5354** [comment]
Same for Loki 
![screenshot from 2016-12-26 09 20 28](https://cloud.githubusercontent.com/assets/16360349/21473620/ae6aae10-cb4c-11e6-8c63-98796a024909.png)

**Comment by ruppalsingh** [comment]
This can be solved by editing `/usr/share/icons/Numix-Circle/index.theme` or `/usr/share/icons/Numix-Circle-Light/index.theme` from `Inherits=numix` to `Inherits=elementary`.

**Comment by palob** [comment]
Can you please transfer this to https://github.com/numixproject/numix-icon-theme?
