### ISSUE TITLE
panel

### ISSUE THREAD

**Issue by mastaiza** [numixproject/numix-icon-theme-circle#2801]
when the light panel some icons are not visible
redshift , transmission , pidgin

**Comment by bil-elmoussaoui** [comment]
Can you post a screenshot?

**Comment by mastaiza** [comment]
![Uploading 20160124-023511.png…]()

![20160124-022540](https://cloud.githubusercontent.com/assets/16268588/12532658/ecf83678-c23a-11e5-95e0-de505e08eaae.png)

**Comment by wa4557** [comment]
Are you using Numix-Light, or the standard Numix icon theme? (You should use Numix-Light)

**Comment by mastaiza** [comment]
numix circle

**Comment by wa4557** [comment]
You should use Numix-Circle-Light then

**Comment by mastaiza** [comment]
icons transmission is still no . the rest came

**Comment by bil-elmoussaoui** [comment]
@mastaiza an other screenshot maybe?

**Comment by mastaiza** [comment]
![20160124-030319](https://cloud.githubusercontent.com/assets/16268588/12532815/e347787e-c23e-11e5-94a7-3331e567ef22.png)

**Comment by wa4557** [comment]
Maybe transmission has a hardcoded light icon?

**Comment by mastaiza** [comment]
don't know

**Comment by wa4557** [comment]
what's the transmission package installed on your system? For me `transmission-gtk` works...

**Comment by bil-elmoussaoui** [comment]
Works fine here too..

**Comment by bil-elmoussaoui** [comment]
@mastaiza Try restarting the application?

**Comment by mastaiza** [comment]
About it worked . Sorry for bothering

**Comment by bil-elmoussaoui** [comment]
Not a problem, You can close this;)
