### ISSUE TITLE
Icon for VeraCrypt

### ISSUE THREAD

**Issue by ZJaume** [numixproject/numix-icon-theme-circle#2803]
VeraCrypt is based on TrueCrypt(which has no longer support).
![captura de pantalla de 2016-01-24 17-42-51](https://cloud.githubusercontent.com/assets/11339330/12537533/ef72ee20-c2c1-11e5-9d75-3bef3d7dcc08.png)

**Comment by zsteinmetz** [comment]
There is a new icon.

![veracrypt128x128](https://cloud.githubusercontent.com/assets/10266826/12538671/a6d817bc-c2df-11e5-88af-848ead74a3f6.png)

I would suggest to use this as a basis.

**Comment by Foggalong** [comment]
Please add the details set out in the readme

**Comment by zsteinmetz** [comment]
The icon name is 'veracrypt'

**Comment by zsteinmetz** [comment]
I experimented a bit. What do you think?

![veracrypt](https://cloud.githubusercontent.com/assets/10266826/12560046/c3a4df74-c398-11e5-912e-d5a21ba5ed9e.png)

**Comment by Foggalong** [comment]
I like that! There are a few bits and bobs which will need tweaking to conform to the Numix guidelines but that's certainly a good starting point :+1:

**Comment by elmat0** [comment]
Just a heads-up. Veracrypt had a bit of a run in with another company that uses a very similar logo. Seems an honest mistake, though I'd imagine they will be re branding again soon.

**Comment by zsteinmetz** [comment]
Thanks for pointing this out @elmat0, so maybe we should wait a little longer for them to work things out.

I tried to design the icon according to the guidelines. I must have missed something. Sorry for that. Could you give me a hint on the bits and bobs that need tweaking?

**Comment by Foggalong** [comment]
The small artifacts between triangles can be rectified by slight overlapping of shapes :) other than that I'd have to see the SVG for sure - feel free to make a pull request!

**Comment by Foggalong** [comment]
@elmat0 Thanks for the information, definitely something to bare in mind
