### ISSUE TITLE
Icon for julia

### ISSUE THREAD

**Issue by zsteinmetz** [numixproject/numix-icon-theme-circle#2804]
What about adding an icon for the upcoming programming language julia?
Icon name is 'julia'

![julia](https://cloud.githubusercontent.com/assets/10266826/12538143/f04a64b2-c2d1-11e5-8dab-c59a5f764503.png)

**Comment by palob** [comment]
Is this icon used anywhere else than USC?
Doesn't this just install the CLI interface?

**Comment by zsteinmetz** [comment]
Well yes, its basically to start the CLI from the launcher. Actually the same as for R ..

**Comment by palob** [comment]
This would be a simple representation:
![julia](https://cloud.githubusercontent.com/assets/7050624/12538789/0c396220-c2e3-11e5-98e0-7d6be1043ce0.png)
![julia0](https://cloud.githubusercontent.com/assets/7050624/12538790/0c3af1c6-c2e3-11e5-99cd-b376600edbd7.png)

**Comment by zsteinmetz** [comment]
Nice one :+1:

**Comment by Foggalong** [comment]
3 :+1:

**Comment by palob** [comment]
The dark one? w or w/o contour?

**Comment by zsteinmetz** [comment]
I would opt for the light one w/o contours

**Comment by Foggalong** [comment]
Dark one w/o contours :+1:
