### ISSUE TITLE
Tray icons for Linux Mint Update Manager

### ISSUE THREAD

**Issue by fwahh** [numixproject/numix-icon-theme-circle#2806]
Hi! There seem to be no indicator icons for Mint's update manager.

![update_manager](https://cloud.githubusercontent.com/assets/16854594/12541232/67a69a8e-c314-11e5-8e55-9627495e0e6c.png)

**Comment by bil-elmoussaoui** [comment]
@fwahh Can you get the icon names? btw , this is a Numix base issue and not a circle one.

**Comment by bil-elmoussaoui** [comment]
+ the icons are hardcoded, [linuxmin/mintupdate/usr/lib/linuxmint/mintUpdate/icons/](https://github.com/linuxmint/mintupdate/tree/master/usr/lib/linuxmint/mintUpdate/icons). Report that here before reporting it to Numix Base [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray)
