### ISSUE TITLE
Missing keepassx-indicator and keepassx-locked icons

### ISSUE THREAD

**Issue by vysinsky** [numixproject/numix-icon-theme-circle#2807]
Ref https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/143

I am not sure if it is normal icon request so I don't follow README instructions. If I should fix it, let me know please.

**Comment by bil-elmoussaoui** [comment]
This should be requested [here](https://github.com/numixproject/numix-icon-theme)

**Comment by vysinsky** [comment]
Sorry I will close this one.
