### ISSUE TITLE
Icon for Solaar

### ISSUE THREAD

**Issue by aircave** [numixproject/numix-icon-theme-circle#2810]
Only for **numix-circle-light** and **numix-light**.
The system tray battery icon for Solaar is "missing" (icon that shows in system tray turns black instead of white).
The icon line says "solaar" but was not able to locate battery icon.

Project's website: https://github.com/pwr/Solaar

Issue: Solaar icon shows incorrectly in system tray area ONLY with numix-light and numix-circle-light. The icon works fine under numix-circle. 
I'm assuming this is an icon-related problem and not theme (Using Nimux-Cinnamon-2) problem. Otherwise please close this thread.
Issue Example: 
![screenshot from 2016-01-26 03 12 21](https://cloud.githubusercontent.com/assets/5119417/12576660/f5772042-c3da-11e5-9022-32696bd9a82d.png)
Appears normal only when using "numix-circle": 
![light-correct](https://cloud.githubusercontent.com/assets/5119417/12576985/276a3aa6-c3dd-11e5-9973-4cd0692a6e89.png)

Other info:
Name=Solaar
Comment=Logitech Unifying Receiver peripherals manager
Exec=solaar
Icon=solaar
Keywords=logitech;unifying;receiver;mouse;keyboard;
Categories=Utility;GTK;

**Comment by Foggalong** [comment]
Numix Light and Numix Circle Light are icon themes with black panel icons, designed to be used with white panels. You have a black panel so you should be using Numix or Numix Circle.
