### ISSUE TITLE
Icon for generic Mortal Kombat games

### ISSUE THREAD

**Issue by TamasBarta** [numixproject/numix-icon-theme-circle#2816]
Linux does not have any Mortal Kombat games released, but for those playing them on Wine, at least a generic Mortal Kombat icon would be awesome. No original icon can be attached, since I'm talking about a generic one, and I play Mortal Kombat Komplete Edition, which has a very crappy 32x32 Win95 style original icon. Desktop file name is also irrelevant, since when played on Wine, desktop file name varies.

**Comment by Foggalong** [comment]
Same was with LoL [here](https://github.com/numixproject/numix-icon-theme-circle/issues/1086) we only do WINE stuff if it's a popular request. Get 5 "+1"s and we'll switch it to a request.

**Comment by sagikazarmark** [comment]
:+1:
