### ISSUE TITLE
Icon for network printers

### ISSUE THREAD

**Issue by zsteinmetz** [numixproject/numix-icon-theme-circle#2817]
At the moment it looks like this in the printer panel

![printers](https://cloud.githubusercontent.com/assets/10266826/12695492/7a87ad38-c750-11e5-8794-fb4db8fdd64b.png)

Icon name is `i-network-printer`

**Comment by Foggalong** [comment]
That should probably be a devices icon rather than an app icon, so the request should [go here](https://github.com/numixproject/numix-icon-theme/issues)

**Comment by zsteinmetz** [comment]
I was thinking about that, too .. but isn't the right local printer icon in the circle-themed app icons as well?

**Comment by Foggalong** [comment]
It is, but I think that the latter has just picked it up incorrectly from an app icon
