### ISSUE TITLE
Icon for Brave Browser

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#2818]
https://github.com/brave

Icon=brave
![brave](https://cloud.githubusercontent.com/assets/7050624/12705179/744acac8-c86c-11e5-9902-fd9b31487111.png)

**Comment by palob** [comment]
![brave1](https://cloud.githubusercontent.com/assets/7050624/12705184/806a46bc-c86c-11e5-90d4-99b48ed465fd.png)
![brave1b](https://cloud.githubusercontent.com/assets/7050624/12705185/806f74c0-c86c-11e5-9983-81c265bfee0f.png)
![brave1p](https://cloud.githubusercontent.com/assets/7050624/12705186/808ee54e-c86c-11e5-8f59-0f2233942d5b.png)

Rounded shapes:
![brave2](https://cloud.githubusercontent.com/assets/7050624/12705188/8aa1b796-c86c-11e5-96f4-31b526e7cdf7.png)
![brave2b](https://cloud.githubusercontent.com/assets/7050624/12705189/8aa4fa32-c86c-11e5-846b-8e766b39df26.png)
![brave2p](https://cloud.githubusercontent.com/assets/7050624/12705190/8ac0d7c0-c86c-11e5-9a00-ab0c938a5e3a.png)

**Comment by palob** [comment]
@Foggalong Green light for any of the above?

**Comment by Foggalong** [comment]
2nd rounded :)

**Comment by palob** [comment]
This (24x26)
![brave2](https://cloud.githubusercontent.com/assets/7050624/12790018/a1f763ce-caa0-11e5-9974-e028c07ef4f4.png)
or a bit bigger (26x28)?
![brave0](https://cloud.githubusercontent.com/assets/7050624/12790027/ac646672-caa0-11e5-94de-552a684c5c41.png)

**Comment by Foggalong** [comment]
24x26 :+1:

**Comment by modelmat** [comment]
I'm not sure if this is the correct place to put this, but the yellow and orange does not have very good contrast on my system
![image](https://user-images.githubusercontent.com/25718989/55949377-ca929f80-5c95-11e9-9d7f-e0fd4ac51fd6.png)
It would be nice if the colours were slightly different.

**Comment by palob** [comment]
I for one find it quite stark even in the screenshot but we could darken the orange and tone down the yellow. Could you please open a new enhancement request?
