### ISSUE TITLE
Icon Request for DopeWars

### ISSUE THREAD

**Issue by bongochong** [numixproject/numix-icon-theme-circle#2839]
- DopeWars (http://dopewars.sourceforge.net/)
![dopewars](https://cloud.githubusercontent.com/assets/10101120/12800032/9d07d044-ca8f-11e5-9879-da9601a767be.png)

Icon=dopewars-weed.png
/usr/share/applications/dopewars.desktop

**Comment by palob** [comment]
2 ver simple drafts:

![dopewars0](https://cloud.githubusercontent.com/assets/7050624/12869119/2cae3ab6-cd16-11e5-89a3-29b53c1974a6.png)
![dopewars1](https://cloud.githubusercontent.com/assets/7050624/12869120/2cb28b20-cd16-11e5-9993-c6de2d72cbee.png)

**Comment by bongochong** [comment]
they both look fantastic! though i could see myself misidentifying the bottom (pill-shaped) one as the xfce settings editor if i was really tired, it's still perfect work right off the bat.

**Comment by Eleuin** [comment]
i guess you could say the first one looks rather... dope?

**Comment by bongochong** [comment]
ahhh yeh
