### ISSUE TITLE
Icon for DrRacket

### ISSUE THREAD

**Issue by mgbowe1** [numixproject/numix-icon-theme-circle#2842]
I would like to have an icon available for DrRacket.
The icon line says "/usr/share/racket/drracket-exe-icon.png"
Here is the default icon:
![screenshot from 2016-02-07 21-47-43](https://cloud.githubusercontent.com/assets/14890220/12877627/9a54b60c-cde4-11e5-9a82-92a76f9026ea.png)

**Comment by palob** [comment]
We've already [got it](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/drracket.svg) so this is for the hardcode-fixer.

@mgbowe1 Could you please look up the name of the ``.desktop`` file?

**Comment by mgbowe1** [comment]
Sorry, it appears I just missed it looking through the directory for it.
