### ISSUE TITLE
Icon for "Computer charging?"

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-icon-theme-circle#2860]
I've encountered an interesting situation when I plugged in an iPad to my laptop running Ubuntu 15.10 via USB the other day as it began charging and replacing the usually battery icon with a question mark.
Here are the screenshots:
![screenshot from 2016-02-13 11-37-38](https://cloud.githubusercontent.com/assets/6375934/13142283/cfe09774-d644-11e5-9564-ebb0cda7ec94.png)
![screenshot from 2016-02-13 11-35-04](https://cloud.githubusercontent.com/assets/6375934/13142294/dfd3a8b0-d644-11e5-8ba8-eb08c32169af.png)
Perhaps it might also be helpful to report that the question mark was replaced with a regular battery icon when iPad was fully charged, and that I don't have any icon theme without this problem.

**Comment by Foggalong** [comment]
This is a [base issue](https://github.com/numixproject/numix-icon-theme) please report it there.
