### ISSUE TITLE
Trash icon is not changing when trash is not empty

### ISSUE THREAD

**Issue by pwittchen** [numixproject/numix-icon-theme-circle#2865]
In previous versions of Numix Circle Theme trash icon were colored to red, when trash wasn't empty. Right now, it's gray all the time even if something is in the trash. I think that different color (e.g. red) or different icon for non-empty trash is useful for me as a system user. Can you bring previous behavior back or add similar behavior (different color or icon for non-empty trash)?

![screen-01](https://cloud.githubusercontent.com/assets/695319/13197171/f122ffba-d7e5-11e5-8e06-16a1b54f1805.png)
![screen-02](https://cloud.githubusercontent.com/assets/695319/13197172/f14087e2-d7e5-11e5-9cc2-f613b355050f.png)

**Comment by Foggalong** [comment]
This is an issue with the [base theme](https://github.com/numixproject/numix-icon-theme) not the app theme

**Comment by pwittchen** [comment]
Ok, I've created an issue for base theme.
