### ISSUE TITLE
Icon for RetroShare (F2F comunication app)

### ISSUE THREAD

**Issue by ZJaume** [numixproject/numix-icon-theme-circle#2871]
That's the logo
![retroshare06](https://cloud.githubusercontent.com/assets/11339330/13425949/9c8d3322-dfaa-11e5-8b1a-9af96a64c7b4.png)

**Comment by palob** [comment]
We've got [this one](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/retroshare.svg).

Could you please add the information set out in the readme? Without it we can't help you.

**Comment by ZJaume** [comment]
Oh sorry I didn't see that .svg icon on my /usr/share directory, i have compiled my retroshare app and it doesn't use the svg icon placed by numix. But I think this numix icon should be more similar to the original.
