### ISSUE TITLE
Problem with icons on desktop and file manager

### ISSUE THREAD

**Issue by spl0i7** [numixproject/numix-icon-theme-circle#2873]
I tried to apply this icon theme on xfce desktop but there seem to be some issue. When I select icon theme from settings it looks like
![selection](https://cloud.githubusercontent.com/assets/6875910/13452780/13ceff1c-e071-11e5-8991-38c05ea5eaf9.png)
file manager icon seems bit off and when I apply it , Icons on my desktop look like
![screenshot_2016-03-02_12-11-06](https://cloud.githubusercontent.com/assets/6875910/13452795/3ac55940-e071-11e5-954f-0035b709f2eb.png)
and it file manager it looks like
![screenshot from 2016-03-02 12-11-44](https://cloud.githubusercontent.com/assets/6875910/13452799/42b9d7e8-e071-11e5-95b4-f9b6ddd24466.png)
I am using Thunar as file manager here and Fedora 23 .

**Comment by palob** [comment]
In addition to Numix Circle need the [Numix base theme](https://github.com/numixproject/numix-icon-theme) :)
Apart fro that it looks like you don't have the fallback ``gnome-icon-theme`` installed.

**Comment by palob** [comment]
@spl0i7 Is it fixed after installing ``numix-icon-theme``?

**Comment by spl0i7** [comment]
@palob yes.
