### ISSUE TITLE
Firefox ESR symlink

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme-circle#2888]
Add a symlink for Firefox ESR.
`firefox.svg -> firefox-esr.svg`

**Comment by palob** [comment]
Would be a distinct design of any help (like less saturated colours since the ESR is less fresh).

**Comment by gregorydk** [comment]
Mozilla doesn't make a distinction, they use the same icon. As far as I'm concerned it may be a symlink to the Firefox icon.
