### ISSUE TITLE
Some icons seems to not show up / Ubu Unity

### ISSUE THREAD

**Issue by foxyantho** [numixproject/numix-icon-theme-circle#2899]
Hello,

Some icons seems to not show up like folders / some apps icons, etc...

However, inside `48x48/apps`, are all the needed SVG are here and readable.
( eg: `terminal.svg` / `default-folder.svg`, `application-x-gzip.svg` , etc )

Installing in both `~/.icons/` and `/usr/share/icons/` have the same effect.

Image preview : ![capture](https://cloud.githubusercontent.com/assets/7000625/13907530/935d8978-eef0-11e5-814b-57af150257a0.png)

OS : Ubuntu 14.04.4 / Unity 7.2

*Thanks for reading!*

**Comment by bil-elmoussaoui** [comment]
You need to install Numix-icon-theme (Base theme) that contains the folders and mimetypes icons too

**Comment by foxyantho** [comment]
@bil-elmoussaoui Thanks for the answer!

I know the Circle theme inherit the main Numix. I've already installed both before submitting this issue. The fact is I don't understand why some icons appear and some not :smile:

**Comment by Foggalong** [comment]
@bil-elmoussaoui I don't think it's that issue, since LibreOffice an terminal aren't showing either.

@foxyantho how are you installing the theme?

**Comment by foxyantho** [comment]
@Foggalong Hello,

I just downloaded a zip from the GitHub's pages `numixproject/icon-theme` and `numixproject/theme-circle` then extract base `Numix` and `Numix-Circle` folders in `~/.icons/` and finally use UnityTweakTool to select "Numix-Circle" theme.

Either copying in `~/.icons/` or `/usr/share/icons/` have the same effect.

However if I take a look inside "Numix-Circle/48x48/apps/" there are the files "file-manager.svg" and "libreoffice-main.svg" and both are readable ( chmod 664 ).

**Comment by Foggalong** [comment]
@foxyantho any luck with `~/.local/share/icons/`?

**Comment by foxyantho** [comment]
@Foggalong I've found the problem, it's all my fault, sorry! :smile: 

Gnome file-roller doesn't show symlink, so when I unzipped the archive : the symlinks weren't present and that's why some application icons didn't appear.  The archive need to be extract directly.

**Comment by Foggalong** [comment]
Ahh. glad the problem was sorted.
