### ISSUE TITLE
TexStudio Icon not distinguishable

### ISSUE THREAD

**Issue by abisthecodermal** [numixproject/numix-icon-theme-circle#29]
TeXStudio icon has a light background with white text, which is not so discernible.

![texiconissue](https://cloud.githubusercontent.com/assets/15901636/21600071/8517832a-d19c-11e6-99b3-ba032888a47e.png)
_The TeXStudio icon between InkScape and GIMP on a unity launcher_

May I suggest the below icon...

![texstudio](https://cloud.githubusercontent.com/assets/15901636/21600744/19ba08f4-d1a7-11e6-9771-e9a4c70e7592.png)

**Comment by palob** [comment]
Hi, can you please report this against https://github.com/numixproject/numix-core?
