### ISSUE TITLE
Gnome News

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme-circle#2902]
Gnome news is a new RSS reader application for Gnome 
The application is still not released yet (won't be released until 3.22 i guess)
Icon name : `Icon=gnome-news`
Default icon: 
![gnome-news](https://cloud.githubusercontent.com/assets/7660997/13970956/a0c4dab0-f08c-11e5-896d-35f4b5a6177d.png)
Maybe using Caffeine icon as a base one, and just use the orange color(RSS logo) instead of the current one?

**Comment by palob** [comment]
I'd rather use something else. What's the metaphor supposed to be here?

**Comment by bil-elmoussaoui** [comment]
No idea.. maybe drinking a coffee while reading the news

**Comment by palob** [comment]
Two drafts:
![gnome-news0](https://cloud.githubusercontent.com/assets/7050624/14756718/3f1c1ce2-08ec-11e6-8c45-244453a75a28.png)
![gnome-news2](https://cloud.githubusercontent.com/assets/7050624/14756719/3f227c18-08ec-11e6-9dad-cea90ccd644d.png)

:rage: Blimey! I managed to overwrite the best one.

**Comment by Foggalong** [comment]
I actually love the first one!

**Comment by ChuckDaniels87** [comment]
Both are really nice. :+1:
