### ISSUE TITLE
Gnome 3.20 changed the name of its icons

### ISSUE THREAD

**Issue by eduardomezencio** [numixproject/numix-icon-theme-circle#2910]
Here are the ones that I noticed:

Cheese - Icon=org.gnome.Cheese
Clocks - Icon=org.gnome.clocks (yes, clocks is lowercase for some reason)
Maps - Icon=org.gnome.Maps
Calendar - Icon=org.gnome.Calendar

Maybe there is more

**Comment by palob** [comment]
[Already fixed](https://github.com/numixproject/numix-icon-theme-circle/pull/2905/commits/a3874e1f23f671cb49f2d3371ab055b1f19972f7) unless you know of even more.

**Comment by eduardomezencio** [comment]
my bad, sorry

**Comment by palob** [comment]
No problem, a duplicate report is better than no report :)
