### ISSUE TITLE
FoxItReader Icon

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#2917]
Default .desktop

[Desktop Entry]
Name=Foxit Reader
Comment=View pdf documents
Keywords=pdf;octet-stream;
StartupNotify=true
Terminal=false
Type=Application
Categories=Application;Office;Viewer;X-Red-Hat-Base;
MimeType=application/pdf;application/octet-stream;
Icon=FoxitReader
Exec=/opt/foxitsoftware/foxitreader/FoxitReader.sh

My quick fix is [here](https://www.dropbox.com/s/z4onjx0efpsmrk7/FoxitReader.svg?dl=0)

**Comment by bil-elmoussaoui** [comment]
Duplicate of #2581 #2682

**Comment by palob** [comment]
Actually, this needs a symlink ``FoxitReader.svg``.

**Comment by alkaef** [comment]
@palob I put 'FoxitReader.svg' inside the circle icon `48/apps` folder but the icon stays the same. What's wrong?

**Comment by bil-elmoussaoui** [comment]
@alkaef you need to update the icon cache using `sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle/`
