### ISSUE TITLE
Missing calendar icon in Xenial

### ISSUE THREAD

**Issue by sargunster** [numixproject/numix-icon-theme-circle#2920]
The default calendar app does not have a Numix icon in Ubuntu 16.04 beta 2.

**Comment by Foggalong** [comment]
Please add the information set out in [the readme](https://github.com/numixproject/numix-icon-theme-circle/#icon-requests). We can't fix icons without the details listed there.

**Comment by palob** [comment]
I think it should have been fixed [here](https://github.com/numixproject/numix-icon-theme-circle/pull/2905/commits/a3874e1f23f671cb49f2d3371ab055b1f19972f7).
They're using GNOME Calendar 3.20.

Are you using the PPA version? It is a few months outdated.
