### ISSUE TITLE
gnome-books icon issue

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-icon-theme-circle#2925]
In Archlinux, in the org.gnome.Books.desktop file, the icon is set to "org.gnome.books" which results in the default icon. However, in order to get the Numix icon to show for it you have to set the value in the .desktop file to "gnome-books".

The issue is that when it is set to "org.gnome.books", only the default icon shows and not the Numix icons; however, if I change it to "gnome-books" it will show fine the Numix theme, but if I go back to the Adwaita theme it reverts to a missing icon.

Is there a way to link the "gnome-books" icon also to "org.gnome.books" so either way it will show the correct icon?

**Comment by Foggalong** [comment]
Yeah sure, I'll get that done now.

**Comment by brittyazel** [comment]
Sorry quick correction (my fault), it is actually "org.gnome.Books" with a capital "B" in Books. I didn't realize that would make a difference, sorry

**Comment by Foggalong** [comment]
Working now?

**Comment by brittyazel** [comment]
Yep, like a charm. Thanks man, I appreciate it

**Comment by Foggalong** [comment]
No problem, thanks for using the theme :)
