### ISSUE TITLE
Icon for PasswordSafe

### ISSUE THREAD

**Issue by rdlu** [numixproject/numix-icon-theme-circle#2929]
https://pwsafe.org/

A numix-circle icon is missing for one of the greatest password managers out there!

```
[Desktop Entry]
Encoding=UTF-8
Name=PasswordSafe

Comment=Manage passwords
Exec=pwsafe %f
Icon=/usr/share/icons/hicolor/48x48/apps/pwsafe.png
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;Database;Security;
```

![PasswordSafe Icon](https://pwsafe.org/images/pwsafe_logo.gif)

**Comment by palob** [comment]
We [have got](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/pwsafe.svg) the icon. It is [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons) though.
