### ISSUE TITLE
Gnome software icon

### ISSUE THREAD

**Issue by KoczurekK** [numixproject/numix-icon-theme-circle#2937]
Hello,

Gnome Software's icon doesn't fit numix circle theme at all although it's default app for managing applications in Ubuntu 16.04. Is there a chance for flat-circle version of that?

![gnome software](https://cloud.githubusercontent.com/assets/7727537/14258997/4639bd54-faa5-11e5-9e18-2d0b1c231872.png)

![gnome-software_org gnome software](https://cloud.githubusercontent.com/assets/7727537/14259135/c8a4e62e-faa5-11e5-8671-e948c05fdf2e.png)

**Comment by bil-elmoussaoui** [comment]
There's already a circle icon, the gnome software might be using a different icon name; Can you please check out the destkop file and copy it's content and paste it here? :+1:

**Comment by KoczurekK** [comment]
Yup. ^^

#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Software
Comment=Add, remove or update software on this computer
Icon=org.gnome.Software
Exec=gnome-software %U
Terminal=false
Type=Application
Categories=GNOME;GTK;System;PackageManager;
Keywords=Updates;Upgrade;Sources;Repositories;Preferences;Install;Uninstall;Program;Software;App;Store;
StartupNotify=true
MimeType=x-scheme-handler/appstream;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=gnome-software
X-GNOME-Bugzilla-Component=gnome-software
X-GNOME-UsesNotifications=true
DBusActivatable=true
X-Ubuntu-Gettext-Domain=gnome-software

**Comment by bil-elmoussaoui** [comment]
This was already fixed in #2905, you just need to download the latest version of Numix theme! (the ppa may not be updated to the latest version)

**Comment by KoczurekK** [comment]
I tought ppa contains newer packages and that pull request is 12 days old, so i assumed that is another bug. :\

Thanks!

**Comment by bil-elmoussaoui** [comment]
Yeah you can take a look at #2430, so can you close this one? :)

**Comment by palob** [comment]
The PPA was last updated Nov 2015.
