### ISSUE TITLE
Icon for Zenmap

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-icon-theme-circle#2938]
A icon for Zenmap is missing in Numix Circle.

The icon line in the `.desktop` file says `/usr/share/zenmap/pixmaps/zenmap.png`

![zenmap](https://cloud.githubusercontent.com/assets/13938848/14317979/634c6354-fc28-11e5-9486-3f2d2234742e.png)

**Comment by palob** [comment]
Please add the information [asked for](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

**Comment by palob** [comment]
We've got an icon but it is [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).
