### ISSUE TITLE
Icon for Slingscold

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#2947]
[Desktop Entry]
Name=Slingscold
Comment=Lanzador de aplicaciones
Exec=slingscold
Icon=/usr/share/icons/slingscold.png
Type=Application
Categories=GNOME;GTK;Utility;
StartupNotify=false

![2016-04-07 04 57 48](https://cloud.githubusercontent.com/assets/18265958/14338161/b081669e-fc85-11e5-8631-b676a7ce2015.png)

**Comment by palob** [comment]
We've got an icon but it is [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).
