### ISSUE TITLE
Icon for Oracle SQL Developer

### ISSUE THREAD

**Issue by BuZZ-dEE** [numixproject/numix-icon-theme-circle#2949]
The [logo](http://www.oracle.com/technetwork/developer-tools/sql-developer/sqldev-101614-2340766.jpg) from their [website](http://www.oracle.com/technetwork/developer-tools/sql-developer/overview/index.html).

![Oracle SQL Developer logo](http://www.oracle.com/technetwork/developer-tools/sql-developer/sqldev-101614-2340766.jpg)

**Comment by Foggalong** [comment]
Duplicate of  #43
