### ISSUE TITLE
Manager programs of the Mint Cinnamon

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#2950]
Icons of categories are displayed not correctly.
![virtualbox_linux mint cinnamon _08_04_2016_08_01_44](https://cloud.githubusercontent.com/assets/18265958/14374648/65e61cc6-fd69-11e5-9fea-91a400c6c30a.png)

**Comment by Foggalong** [comment]
Duplicate of  #2750
