### ISSUE TITLE
Icons tollbar for Thunderbird

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#2951]
It is possible to replace not getting icons for tollbar?
![virtualbox_linux mint cinnamon _08_04_2016_08_03_54](https://cloud.githubusercontent.com/assets/18265958/14374661/a23b14c4-fd69-11e5-9eff-2203a294676b.png)

**Comment by Foggalong** [comment]
This is a base theme icon rather than an app icon so please report it [here](https://github.com/numixproject/numix-icon-theme/issues) instead.
