### ISSUE TITLE
Tray Icon for ppa:jconti/recent-notifications

### ISSUE THREAD

**Issue by gustavodini** [numixproject/numix-icon-theme-circle#2952]
I would request the application icon"ppa:jconti/recent-notifications"(https://launchpad.net/~jconti/+archive/ubuntu/recent-notifications).

**Comment by Foggalong** [comment]
Please add the information set out in [the readme](https://github.com/numixproject/numix-icon-theme-circle/#icon-requests). We can't fix icons without the details listed there.
