### ISSUE TITLE
Bug Icon for MultiSystem

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#2955]
Today I installed MultiSystem. Also I have found out that there are no icons, but in a package they are.

multisystem.svg
multisystem-test-iso.svg
![2016-04-09 19 46 40](https://cloud.githubusercontent.com/assets/18265958/14404953/36a3edc2-fe94-11e5-9128-0fe9ce2a06e8.png)

The name of an icon in a label have changed and now it:

Icon=multisystem-liveusb
Icon=multisystem-vbox
![2016-04-09 19 45 20](https://cloud.githubusercontent.com/assets/18265958/14404955/3d0145f2-fe94-11e5-9d25-d55c7725cbd4.png)

**Comment by palob** [comment]
Hmm, I don't quite understand what's the issue here. 
Since you mentioned you use the PPA version, perhaps #2874 already fixed your icons?

**Comment by ElvisPresly** [comment]
Yes in that subject I see that you have corrected it. When the PPA package is updated? On my personal computer still ugly icons.
Thank You

**Comment by Foggalong** [comment]
PPA is broken at the moment, see #2430
