### ISSUE TITLE
Icon for Back in time

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#2956]
Icon=gtk-save   //for old version
Icon=document-save

![2016-04-10 11 36 10](https://cloud.githubusercontent.com/assets/18265958/14408923/d227fdea-ff18-11e5-9570-c71699029052.png)

**Comment by Foggalong** [comment]
We can't fix either of them because they use icon names used by action icons. Please report this to the upstream developer to get them to use a better icon name
