### ISSUE TITLE
Icon for brain workshop

### ISSUE THREAD

**Issue by k-kirill** [numixproject/numix-icon-theme-circle#2957]
A numix-circle icon is missing.

Brain Workshop is a free open-source version of the dual n-back brain training exercise: http://brainworkshop.sourceforge.net/

Icon name: `Icon=brainworkshop`

Default icon:
![brainworkshop](https://cloud.githubusercontent.com/assets/8539168/14413366/7d31fa14-ff88-11e5-8ab6-913428717811.png)

**Comment by palob** [comment]
Is that discernible as a brain?
![brainworkshop](https://cloud.githubusercontent.com/assets/7050624/14413651/cca6ceec-ff80-11e5-9d88-c038b288b779.png)

**Comment by Foggalong** [comment]
I'd say so yeah :)

**Comment by k-kirill** [comment]
Wow, it's just amazing how fast the issue has been fixed. Thanks a lot.
