### ISSUE TITLE
Icon for gtkdialog

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme-circle#2960]
Hi, sometimes at start of certain programs. For example when performing certain actions in the Multisystem program the ugly icon in Plank Dock appears. I have found her and she is called gtkdialog.png
Make please her. Thanks.
Icon=gtkdialog
![gtkdialog](https://cloud.githubusercontent.com/assets/18265958/14466603/8fde5642-00e8-11e6-858d-c113e8db8d84.png)
![2016-04-12 18 55 26](https://cloud.githubusercontent.com/assets/18265958/14466611/93f8bace-00e8-11e6-89e7-dfedb8750821.png)

**Comment by palob** [comment]
So there's an app icon for a dialog window? As in a grey box where you can choose ``OK``, ``Cancel`` or something?

**Comment by ElvisPresly** [comment]
I apologize, I badly speak English.
This icon appears in dock of the panel close up and looks ugly :)
Perhaps this program replaces dialog boxes, I didn't study it in more detail.
I will make a screenshot if it is required to you

**Comment by ElvisPresly** [comment]
![default](https://cloud.githubusercontent.com/assets/18265958/14485298/3708bf2e-0167-11e6-8bdd-4d1ef07fa7f2.png)
