### ISSUE TITLE
Icon for Franz

### ISSUE THREAD

**Issue by brncavalcante** [numixproject/numix-icon-theme-circle#2963]
Icon = Franz
![logofranz](https://cloud.githubusercontent.com/assets/18425086/14506630/25edba4a-0195-11e6-92fc-99bf55e396ea.png)
Thanks :)

**Comment by iliaskomp** [comment]
+1

**Comment by Foggalong** [comment]
Please use GitHub +1s to do this kind of thing, otherwise it's just clogging up the issues tracker. I'll be removing both this comment and yours by the end of the day.
