### ISSUE TITLE
Icon for Ubuntu Web Browser (Browser)

### ISSUE THREAD

**Issue by t9toqwerty** [numixproject/numix-icon-theme-circle#2966]
Icon for Ubuntu Web Browser (Browser) in Ubuntu 16.04 is missing.

**Comment by palob** [comment]
Please add the information set out in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).
This particular icon might be [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).

**Comment by t9toqwerty** [comment]
Here is the entry in desktop file.


[Desktop Entry]
Version=1.0
Name=Browser
GenericName=Web Browser
Comment=Browse the World Wide Web
Keywords=Internet;WWW;Browser;Web;Explorer
Type=Application
Icon=/usr/share/webbrowser-app/webbrowser-app.png
Exec=webbrowser-app %u
Terminal=false
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;
X-Ubuntu-Touch=true
X-Ubuntu-Gettext-Domain=webbrowser-app
X-Ubuntu-Single-Instance=true
X-Ubuntu-Default-Department-ID=web-browsers
X-Screenshot=/usr/share/webbrowser-app/screenshot.png
X-Ubuntu-Splash-Color=#FFFFFF
![selection_001](https://cloud.githubusercontent.com/assets/5053687/14572190/0224def4-036b-11e6-87fe-6b457f5a8d0b.png)

**Comment by palob** [comment]
That one's already covered by the [hardcode-fixer script](https://github.com/Foggalong/hardcode-fixer).

**Comment by t9toqwerty** [comment]
Got it.
