### ISSUE TITLE
Icon for Logout (Ubuntu Unity)

### ISSUE THREAD

**Issue by t9toqwerty** [numixproject/numix-icon-theme-circle#2967]
Icon for Logout , Shutdown & Reboot in Ubuntu 16.04 is missing. In 16.04 These three shortcuts are provided.

**Comment by palob** [comment]
Please add the information set out in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests)

**Comment by t9toqwerty** [comment]
[Desktop Entry]
Name=Logout
Comment=Log out of your account.
GenericName=Log Out
Exec=gnome-session-quit --logout
Terminal=false
Type=Application
Categories=Utility
Icon=/usr/share/unity/icons/logout_highlight.png
NotShowIn=GNOME-Flashback;
X-AppStream-Ignore=true
![logout](https://cloud.githubusercontent.com/assets/5053687/14572313/c861f304-036b-11e6-9510-4bebaeddb61d.png)

**Comment by palob** [comment]
Thanks, that's hardcoded unfortunately. If you tell us the name of the ``.desktop`` file we can add it to the [hardcode-fixer](https://github.com/Foggalong/hardcode-fixer).

Annoying to see that the Ubuntu folks still fail to abide by freedesktop standards.

**Comment by t9toqwerty** [comment]
The name of .desktop file is
logout.desktop
