### ISSUE TITLE
Icon for Shutdown (Ubuntu Unity) 

### ISSUE THREAD

**Issue by t9toqwerty** [numixproject/numix-icon-theme-circle#2968]
[Desktop Entry]
Name=Shutdown
Comment=Power off the computer
GenericName=Shut Down
Exec=gnome-session-quit --power-off
Terminal=false
Type=Application
Categories=Utility
Icon=/usr/share/unity/icons/shutdown_highlight.png
NotShowIn=GNOME-Flashback;
X-AppStream-Ignore=true
![shutdown](https://cloud.githubusercontent.com/assets/5053687/14572344/f6b5d9dc-036b-11e6-991f-11cac6515557.png)

**Comment by t9toqwerty** [comment]
The name of .desktop file is 
shutdown.desktop

**Comment by Foggalong** [comment]
I don't know about these icons. I mean, they're clearly not app icons they're action icons. At the same time, Canonical have given them .desktop files? Weird

**Comment by Foggalong** [comment]
Decided I'm gonna mark them as won't fix. While ever they're both hardcoded and weirdly setup it's going to be too much work to get our icons in there.

**Comment by leoheck** [comment]
They are used when you ask for reboot or shutdown or logout, but they also can be accessible by the unity as an app:

![selection_008](https://cloud.githubusercontent.com/assets/1277920/17530571/74eab83a-5e4e-11e6-8dee-43f72ec01b84.png)

![selection_007](https://cloud.githubusercontent.com/assets/1277920/17530521/447cba54-5e4e-11e6-9f84-224776e7ebbf.png)

**Comment by Foggalong** [comment]
^ see above comments for why this won't be fixed
