### ISSUE TITLE
Icon for Reboot (Ubuntu Unity)

### ISSUE THREAD

**Issue by t9toqwerty** [numixproject/numix-icon-theme-circle#2969]
[Desktop Entry]
Name=Reboot
Comment=Reboot the computer
GenericName=Reboot
Exec=gnome-session-quit --reboot
Terminal=false
Type=Application
Categories=Utility
Icon=/usr/share/unity/icons/restart_highlight.png
NotShowIn=GNOME-Flashback;
X-AppStream-Ignore=true
![reboot](https://cloud.githubusercontent.com/assets/5053687/14572368/1e387168-036c-11e6-9c21-f4c9efe40097.png)

**Comment by t9toqwerty** [comment]
The name of .desktop file is
reboot.desktop

**Comment by t9toqwerty** [comment]
@Foggalong  , It looks really ugly in Unity .You should do something to fix it.

**Comment by Foggalong** [comment]
Oh jees, I didn't realise they were showing up in the launcher too. That's possibly an Ubuntu bug so it might be worth reporting it upsteam to them. Report should outline:
* Icons shouldn't be hardcoded, so example would be `Icon=highlight_logout`
* Icons possibly shouldn't be in the launcher at all

@dirtydancing Any ideas about this?

**Comment by wa4557** [comment]
Unity sometimes has funny design choices, but showing shutdown reboot and suspend in the dash is probably the stupiest idea they ever had. 

@t9toqwerty:

If you want to remove them permanently from the dash copy `reboot.desktop` to `~/.local/share/applications/` and add `Hidden=true` to the `desktop` file. Then they are gone forever even if you update unity

**Comment by dirtydancing** [comment]
Agreed with what @wa4557 said. What a strange Ubuntu/Unity decision to include these in the dash.
