### ISSUE TITLE
Fix bad nvidia prime-indicator panel icon

### ISSUE THREAD

**Issue by alkaef** [numixproject/numix-icon-theme-circle#2979]
After installing prime-indicator the default icon shown on the panel will be like this:
![screenshot from 2016-04-17 09 03 02](https://cloud.githubusercontent.com/assets/13399275/14584666/bd1fdd92-047b-11e6-8064-5c0d8fac30a2.png)

Notice the numix circle icon is shown instead of the nvidia-panel icon which doesn't fit. 
To fix this copy `nvidia-panel.svg` on `/usr/share/icons/Numix-Light/16/status/` to `/usr/share/icons/Numix-Light/16/panel/`. Do the same on `Numix` icon folder if you are using a dark theme.

**Fixed icon preview**
![screenshot from 2016-04-17 09 06 50](https://cloud.githubusercontent.com/assets/13399275/14584685/3f27a36a-047c-11e6-92ca-1bd880c68878.png)

**Comment by Foggalong** [comment]
This is an issue with the [base theme](https://github.com/numixproject/numix-icon-theme), not with Circle, so please report it there
