### ISSUE TITLE
Icon for Tor is missing.

### ISSUE THREAD

**Issue by anicake** [numixproject/numix-icon-theme-circle#2983]
Contents of tor-browser-en.desktop

> [Desktop Entry]
> Version=1.0
> Type=Application
> Name=Tor-Browser (en-US)
> Exec=/usr/bin/tor-browser-en
> Icon=/usr/share/pixmaps/tor-browser-en.png
> Categories=Network;
> Comment=Tor Browser Bundle: Anonymous browsing using firefox and tor

![tor_browser_onion](https://cloud.githubusercontent.com/assets/922486/14588965/8f738852-04f4-11e6-803c-c78a64834356.png)

**Comment by palob** [comment]
It's [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).
