### ISSUE TITLE
Icon for Civilization V (Steam)

### ISSUE THREAD

**Issue by EloItsMee** [numixproject/numix-icon-theme-circle#2994]
Game: Sid Meier's Civilization V
AppID: 8930
Icon: ![civ_v_icon](https://cloud.githubusercontent.com/assets/18531904/14605850/95478f98-058b-11e6-9512-e64792f07406.png)

**Comment by Foggalong** [comment]
[We already have one!](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/steam_icon_8930.svg) See the readme section on hardcoded icons for more information
