### ISSUE TITLE
Discord canary icon only shows in usr/share/applications

### ISSUE THREAD

**Issue by Dizeeee** [numixproject/numix-icon-theme-circle#3]
Discords icon does not use Numix circle anywhere besides usr/share/applications

**Comment by palob** [comment]
Can you post the ``Icon=`` inside the launcher file and refile the issue against https://github.com/numixproject/circle-core?

**Comment by Dizeeee** [comment]
Here:
[Desktop Entry]
Name=Discord Canary
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/share/discord-canary/DiscordCanary
Icon=discord-canary
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;

**Comment by palob** [comment]
Thanks. You don't need to, it's already reported as https://github.com/numixproject/circle-core/issues/3121.
