### ISSUE TITLE
Icon for electronic wechat

### ISSUE THREAD

**Issue by Jamesxu182** [numixproject/numix-icon-theme-circle#30]
The icon for electronic wechat is missing. I found a circle icon from internet.

I install electronic wechat from AUR in Archlinux. The icon=electronic-wechat in .desktop file in /usr/share/applications directory. 

The original icon is:
![electronic-wechat](https://cloud.githubusercontent.com/assets/7959510/21827127/2f3e2120-d782-11e6-902b-e6c484fbf640.png)

The new circle icon I provide is:

![electronic-wechat](https://cloud.githubusercontent.com/assets/7959510/21827066/ec6e14f4-d781-11e6-9b07-2480951db6af.png)

**Comment by palob** [comment]
Hi, can you please submit your icon as PR against https://github.com/numixproject/numix-core?
