### ISSUE TITLE
Gnome Software Icon

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [numixproject/numix-icon-theme-circle#3002]
The Gnome Software Centre (named: "Software") included in the Ubuntu 16.04 series is missing a numix circle icon. With the buggy but promising mess being released tomorrow, I was wondering if there's an icon in the works?

**Comment by Foggalong** [comment]
[We already have one.](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gnome-software.svg) We need the icon line in the launcher though, or we can't make sure we have it connected up right.

**Comment by KUPOinyourWINDOW** [comment]
I think it's "gnome-software %U"
Is that helpful?

**Comment by KUPOinyourWINDOW** [comment]
How can I find out the icon line?

**Comment by Foggalong** [comment]
Check the README section on icon requests

**Comment by KUPOinyourWINDOW** [comment]
I'm not sure how to do that, sorry, I'm willing to help though if I can have more information.

**Comment by Foggalong** [comment]
[Here](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

**Comment by KUPOinyourWINDOW** [comment]
The icon is: "org.gnome.Software" and the app name is "Software"

The icon looks like this (please ignore the fire on the screen):
![screenshot 2016-04-21 01 33 00](https://cloud.githubusercontent.com/assets/7698035/14694517/05474d84-0761-11e6-97eb-121a2e99eb16.png)

**Comment by palob** [comment]
We've got a [symbolic link](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/org.gnome.Software.svg) for this. Looks like your Numix Circle installation isn't up to date.

**Comment by KUPOinyourWINDOW** [comment]
I've kept it updated via the numix ppa though so it should be up to date?

**Comment by palob** [comment]
No, due to what's discussed in #2430 the PPA is quite outdated unfortunately.

**Comment by KUPOinyourWINDOW** [comment]
Ah, thank you for the explanation. How can I grab an updated version of numix circle?

**Comment by Foggalong** [comment]
Downloading the source from GitHub, but hopefully that won't be nessisary for much longer :+1:
