### ISSUE TITLE
Icon for whatsie

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme-circle#3010]
An icon for whatsie is missing http://www.webupd8.org/2016/04/use-whatsapp-on-your-linux-desktop-with.html

`Icon=whatsie`

![whatsie](https://cloud.githubusercontent.com/assets/6475757/14753266/8068a624-08d4-11e6-9203-e13ce640fc3c.png)

**Comment by palob** [comment]
![whatsie-all](https://cloud.githubusercontent.com/assets/7050624/14904592/7fbe5da2-0da9-11e6-8354-29730c876241.png)
One of those or a symlink to the first one?
Prefer Nos. 2 and 3 as 0 and 1 don't scale as gracefully.

**Comment by wa4557** [comment]
not the first one, because you need to have `whatsapp-web` installed, whcih means dulicate icons. Don't really like the last one, so if not `whatsie0` I'd go for `whatsie2`

**Comment by Foggalong** [comment]
Whatsie2 or Whatsie3 would be nice :)
