### ISSUE TITLE
Missing icon for hplip's GUI

### ISSUE THREAD

**Issue by Avamander** [numixproject/numix-icon-theme-circle#3027]
Ubuntu 16.04 does not any more have USC, it has GNOME software centre (that also doesn't have an icon). It also has an unthemed system tray icon, how does one report that?
Screenshot of the entry:
![screenshot from 2016-04-27 23-55-14](https://cloud.githubusercontent.com/assets/5392141/14867902/91c648c4-0cd3-11e6-8e8f-de6bf2ed7282.png)

Just in case I added the entire .desktop file:

```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=HP Device Manager
GenericName=Printer Management Application
Comment=View device status, ink levels and perform maintenance.
Exec=hp-toolbox
Icon=/usr/share/hplip/data/images/128x128/hp_logo.png
Terminal=false
Categories=Application;Utility;
X-KDE-StartupNotify=false
StartupNotify=false
```

**Comment by palob** [comment]
The theme covers it however it is [hardoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons.

**Comment by Avamander** [comment]
@palob Sorry!

**Comment by palob** [comment]
You're welcome, better be safe and report than sorry!
