### ISSUE TITLE
Personal File Sharing

### ISSUE THREAD

**Issue by Avamander** [numixproject/numix-icon-theme-circle#3028]
```
[Desktop Entry]
Name=Personal File Sharing
Comment=Launch Personal File Sharing if enabled
Keywords=share;files;bluetooth;obex;http;network;copy;send;
AutostartCondition=GSETTINGS org.gnome.desktop.file-sharing enabled
Icon=folder-remote
Exec=/usr/lib/gnome-user-share/gnome-user-share-webdav
Terminal=false
Type=Application
Categories=
OnlyShowIn=GNOME;Unity;
NoDisplay=true
X-GNOME-Autostart-Delay=15
X-Ubuntu-Gettext-Domain=gnome-user-share
```

Not available from GNOME's store, turned up the icon size and made a screenshot of the desktop entry.
![screenshot from 2016-04-28 00-01-08](https://cloud.githubusercontent.com/assets/5392141/14868073/53c25710-0cd4-11e6-8b68-789648ffc56f.png)

**Comment by palob** [comment]
What you see is an icon from the [Numix base theme](https://github.com/numixproject/numix-icon-theme). With that icon name it is impossible to make it use a proper Numix Circle icon.

**Comment by Avamander** [comment]
Maybe the hardcoded icon script can be used to edit the desktop entry?

**Comment by palob** [comment]
It could indeed, feel free to open an issue or a pull request there.
Furthermore you can manually edit the ``.desktop`` file (and copy it over to ``~.local/share/application`` in order to prevent it from reverting back each time the app gets an update.

**Comment by Avamander** [comment]
What should I change the `Icon=<ICON>` to have a proper icon for it?

**Comment by palob** [comment]
The name of the Numix Circle icon you whish to see.
Actually, I don't think we've got a 1:1 visual representaion in Circle yet.
Perhaps ``Icon=shares`` is a good fit.

**Comment by Avamander** [comment]
It's not `Icon=shares` and it's times nicer. Thanks.
