### ISSUE TITLE
GNOME software

### ISSUE THREAD

**Issue by Avamander** [numixproject/numix-icon-theme-circle#3029]
Icon entry:
`Icon=org.gnome.Software`

Screenshot:
![screenshot from 2016-04-28 00-10-10](https://cloud.githubusercontent.com/assets/5392141/14868302/99309658-0cd5-11e6-9973-b82f6516a7aa.png)

**Comment by palob** [comment]
We've got that one. You aren't using the latest version of Numix Circle.

**Comment by Avamander** [comment]
I followed the instructions in readme.md in the root directory. Is that not the latest?

**Comment by palob** [comment]
Unfortunalty what you get through the PPA is a few months old due to #2430.
You need to install manually to get the latest and greatest.

**Comment by Avamander** [comment]
There is no prebuilt package then?

**Comment by palob** [comment]
No, alas there won't until the issue gets resolved. 
Manual installation isn't that big of a deal though.

Make sure you've got git installed, remove the PPA version and run:
```
git clone https://github.com/numixproject/numix-icon-theme-circle
cd numix*
sudo cp -R Numix* /usr/share/icons
```

**Comment by tkdberger** [comment]
I'm glad there's a way to get an up-to-date version at least. Seems a bit sketchy but it'll do for now.
