### ISSUE TITLE
CLion and PyCharm

### ISSUE THREAD

**Issue by Avamander** [numixproject/numix-icon-theme-circle#3030]
![screenshot from 2016-04-28 00-17-22](https://cloud.githubusercontent.com/assets/5392141/14868650/514713c4-0cd7-11e6-89fc-9ae7f8d9e3b2.png)

```
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm
Icon=/home/<INSTALLATION DIRECTORY>/bin/pycharm.png
Exec="/home/<INSTALLATION DIRECTORY>/bin/pycharm.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm
```
![screenshot from 2016-04-28 00-17-44](https://cloud.githubusercontent.com/assets/5392141/14868658/57e90304-0cd7-11e6-89ac-ff8aad699cee.png)

```
[Desktop Entry]
Version=1.0
Type=Application
Name=CLion
Icon=/home/<INSTALLATION DIRECTORY>/bin/clion.svg
Exec="/home/<INSTALLATION DIRECTORY>/bin/clion.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-clion
```

Issue to include these two in the dehardcoder script is also made as the script did not fix the icons if they even exist.

**Comment by palob** [comment]
The icons do exist, might be another hardcoded path.
