### ISSUE TITLE
Icon for Tresorit

### ISSUE THREAD

**Issue by lamka02sk** [numixproject/numix-icon-theme-circle#3038]
Please add icon for Tresorit. www.tresorit.com

**Comment by Foggalong** [comment]
Please add the information set out in [the readme](https://github.com/numixproject/numix-icon-theme-circle/#icon-requests). We can't fix icons without the details listed there.

**Comment by lamka02sk** [comment]
Sorry, I forget. Here are some informations:
The Icon Line -
`Icon=/home/*username*/.local/share/tresorit/tresorit.png`
The Original Icon -
![tresorit](https://cloud.githubusercontent.com/assets/8135372/14977656/10e75bf2-1116-11e6-8cfe-4249999cf149.png)

**Comment by Foggalong** [comment]
This is a hardcoded icon, so needs reporting to the hardcode fixer mentioned in the readme.
