### ISSUE TITLE
Icon for AfterShotPro2

### ISSUE THREAD

**Issue by mjs7231** [numixproject/numix-icon-theme-circle#3039]
This is their current icon:
<img src='http://a4.mzstatic.com/us/r30/Purple1/v4/6f/81/80/6f81807a-bbd1-2772-5e1e-8f82d20df245/icon256.png'/>

**Comment by Foggalong** [comment]
Please add the information set out in [the readme](https://github.com/numixproject/numix-icon-theme-circle/#icon-requests). We can't fix icons without the details listed there.
