### ISSUE TITLE
Icon for Ubuntu Software

### ISSUE THREAD

**Issue by Red-devilz** [numixproject/numix-icon-theme-circle#3053]
After the update to ubuntu 16.04, Numix icons themes have no icon for Ubuntu Software(which is different from Ubuntu Software center). Can an icon be added for the same?

**Comment by palob** [comment]
duplicate of #3029.

**Comment by sergioad** [comment]
also it is gnome software wich allready has icon in Numix, it only needs to be renamed to org.gnome.Software

**Comment by palob** [comment]
@sergioad Even the symlink is in the repo [already](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/org.gnome.Software.svg).
