### ISSUE TITLE
Icon for YouTube DL GUI

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-icon-theme-circle#3107]
A numix-circle-icon for YouTube DL GUI is missing.

Icon=/usr/share/pixmaps/youtube-dlg.png

![youtube-dlg](https://cloud.githubusercontent.com/assets/11943860/15169331/735ea970-1710-11e6-8fb1-aa130c60e423.png)

**Comment by palob** [comment]
We've got the icon. It's [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons) though.
