### ISSUE TITLE
Icon for Robocode

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-icon-theme-circle#3120]
A Numix-circle-icon for **Robocode** is missing.

The icon says "robocode" and original is attached.

![robocode](https://cloud.githubusercontent.com/assets/11943860/15201157/5c1bbe2e-17c4-11e6-8178-ce2dedce9e9d.png)

**Comment by palob** [comment]
One of those?
![robocode333](https://cloud.githubusercontent.com/assets/7050624/15264316/3aefc9b6-1972-11e6-9c13-bc2ca43ba415.png)
![robocode444](https://cloud.githubusercontent.com/assets/7050624/15264317/3af0b06a-1972-11e6-9c2e-1f3d2ea63977.png)

**Comment by Foggalong** [comment]
The second one :+1:
