### ISSUE TITLE
Icon for GNOME Calendar

### ISSUE THREAD

**Issue by bharadwaj-raju** [numixproject/numix-icon-theme-circle#3124]
As of GNOME 3.18, the Calendar app uses it's own icon:

![screenshot from 2016-05-13 12-58-04](https://cloud.githubusercontent.com/assets/15855081/15240928/6b62fcb6-190a-11e6-886d-ee6d555a1cdc.png)

~~Edit: So it's actually Evolution calendar. The `Icon=` line in the `.desktop` file says `evolution`.~~ It's `gnome-calendar` and it has no `.desktop` file.

**Comment by palob** [comment]
Please add the information, set out in the readme. Are you sure it isn't 3.20?

Probably duplicate, PPA problem.

**Comment by bharadwaj-raju** [comment]
@palob Updated. Also, I'm sure it's 3.18:

    $ gnome-shell --version
    GNOME Shell 3.18.4

**Comment by Foggalong** [comment]
[We already have that icon](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/evolution.svg). Have you installed the theme correctly?

**Comment by palob** [comment]
Hmm that icon above surely is the GNOME Calendar icon.

**Comment by bharadwaj-raju** [comment]
Sorry, not Evolution. Strange. There's no `.desktop` file for that. the executable, however, is `gnome-calendar`. But no `.desktop` in `/usr/share/applications`, `/usr/local/share/applications` and `~/.local/share/applications`.

**Comment by Foggalong** [comment]
[We have that too :/](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gnome-calendar.svg)

**Comment by bharadwaj-raju** [comment]
Even I have that in my Numix-Circle installation - `gnome-calendar.svg` symlinked to `office-calendar.svg`. But `gnome-calendar` doesn't pick that up, I think because it has no `.desktop` file.

**Comment by ChuckDaniels87** [comment]
Archlinux, Gnome 3.20. Gnome Calendar has the Numix's icon.

**Comment by bharadwaj-raju** [comment]
I suppose it should be added to the `hardcode-fixer`?

**Comment by ChuckDaniels87** [comment]
@bharadwaj-raju I'm not sure if you should add it. Could you give us some information of your system?

**Comment by bharadwaj-raju** [comment]
@ChuckDaniels87 Ubuntu 16.04, GNOME Shell 3.18.4

**Comment by bil-elmoussaoui** [comment]
Are you sure that you don't have this desktop file? `org.gnome.Calendar.desktop`

**Comment by bharadwaj-raju** [comment]
No, don't have that. Are there other places to check than `/usr/share/applications`, `/usr/local/share/applications` and `~/.local/share/applications`?

**Comment by bil-elmoussaoui** [comment]
This is the list of desktop files directories 
- `/usr/share/applications/`
- `/usr/share/applications/kde4/`
- `/usr/local/share/applications/`
- `/usr/local/share/applications/kde4/`
- `/home/${SUDO_USER:-$USER}/.local/share/applications/`
- `/home/${SUDO_USER:-$USER}/.local/share/applications/kde4/`

**Comment by ChuckDaniels87** [comment]
You can try `locate org.gnome.Calendar.desktop`. I've check a Ubuntu Gnome 16.04 installation and the files are present in:
```
/usr/share/app-install/desktop/gnome-calendar:org.gnome.Calendar.desktop
/usr/share/applications/org.gnome.Calendar.desktop
```

**Comment by bharadwaj-raju** [comment]
OK, checked again, it exists. (I should use case-insensitive `grep`...) And the `Icon=` line says `org.gnome.Calendar`. Should we have a symlink from `org.gnome.Calendar.svg` to `office-calendar.svg`?

**Comment by bil-elmoussaoui** [comment]
The symlink already exists, btw the ppa is not up to date see #2430

**Comment by bharadwaj-raju** [comment]
Oh. Closing. Since when is it like this? Now I'm just cloning the git repo.

**Comment by bil-elmoussaoui** [comment]
Few months..

**Comment by palob** [comment]
@bharadwaj-raju Ubuntu 16.04 has got a few GNOME 3.20 components. That's totally independent from the Shell version.

**Comment by bharadwaj-raju** [comment]
@palob Yes, you're right:

    $ gnome-calendar --version
    gnome-calendar: Version 3.20.1

**Comment by W-Floyd** [comment]
I encountered a form of this issue today, but only with Square icons. The python script simply does not create a 'org.gnome.Calendar' symlink for the square version. Seeing as I don't know Python, maybe someone else could have a look at it?

```
william@william-solus ~/Documents/git/Fork/numix-core $ ./gen.py -t square -p linux

Generating Linux theme...
Done!

william@william-solus ~/Documents/git/Fork/numix-core $ ./gen.py -t circle -p linux

Generating Linux theme...
Done!

william@william-solus ~/Documents/git/Fork/numix-core $ find ./numix-icon-theme-* | grep 'org.gnome.Calendar'
./numix-icon-theme-circle/Numix-Circle/48/apps/org.gnome.Calendar.svg
```

**Comment by bilelmoussaoui** [comment]
@W-Floyd The calendar icons are part of this https://github.com/numixproject/numix-core/issues/3481. The Square icon theme is not complete yet

**Comment by W-Floyd** [comment]
lol No wonder...
If I get some time, would this be okay to have a jab at?

**Comment by bilelmoussaoui** [comment]
Have fun doing that ;)

**Comment by W-Floyd** [comment]
Make no promises, tell no lies. Should get some of my other PRs in first though...

**Comment by W-Floyd** [comment]
@bil-elmoussaoui Before I get ahead of myself, what are the required options for use when exporting optimizes SVG files?

**Comment by bilelmoussaoui** [comment]
@palob Might give you a better answer than me about that ;)

**Comment by palob** [comment]
Just be sure the "CSS to XML conversion" option be not checked.

**Comment by W-Floyd** [comment]
Okay, will do.
