### ISSUE TITLE
Numix-Icon-Theme-Circle out of date

### ISSUE THREAD

**Issue by btd1337** [numixproject/numix-icon-theme-circle#3161]
The theme numix-icon-theme-Circle is **out of date** in the ppa:numix/ppa.

When will you update it?

We are not getting the updates that you have done :/

![numix ppa](https://cloud.githubusercontent.com/assets/11943860/15280470/15054924-1b07-11e6-9d04-6b3720df26e7.jpg)

**Comment by MichaelTiebesl** [comment]
@btd1337 See #2430 and #3029 to fix it temporarily...:)
