### ISSUE TITLE
Insync tray icon issue

### ISSUE THREAD

**Issue by thefirstofthe300** [numixproject/numix-icon-theme-circle#3171]
I am running Ubuntu Mate 16.04 and have just installed the Numix icon theme via the noobslab repo as I want automatic updates (I also bought the theme through the store to support you guys...great work going on here!).  I also installed Insync and set the icon theme to Numix Circle and the gtk theme to Numix.  My Insync icon is ugly and out of place.  Case in point:

![screenshot at 2016-05-20 16 10 59](https://cloud.githubusercontent.com/assets/3161330/15444449/aafe2a62-1ea5-11e6-91a9-9e50a1a6eeb0.png)

**Comment by bil-elmoussaoui** [comment]
1 - It's a Numix base issue
2 - We have a tray icon for insync but sadly it does not work at all (insync issue, not Numix one..)
3 - What's that cloud icon? :)

**Comment by thefirstofthe300** [comment]
I would love to use Owncloud, but right now, the Google Drive support just
isn't stable enough to use.
