### ISSUE TITLE
power icon is too big on elementary 0.4

### ISSUE THREAD

**Issue by ijustyce** [numixproject/numix-icon-theme-circle#3174]
![2016-05-22 16 39 36](https://cloud.githubusercontent.com/assets/6041166/15453138/e511413e-203b-11e6-86cc-24224a56faa1.png)

Here is my screenshot, power icon and notification is too big

**Comment by Foggalong** [comment]
* Do you mean the shutdown, not the power? That batter icon looks the right size to me.
* What release is elementary 0.4?
* This is a [base](https://github.com/numixproject/numix-icon-theme) issue, not a circle one.
