### ISSUE TITLE
No Yakkety Build

### ISSUE THREAD

**Issue by WTRXGamer** [numixproject/numix-icon-theme-circle#3176]
I have installed the GTK+ theme through the repositories, but when trying to install the app icon theme, the package cannot be found.

Here are the commands I have used:

`sudo add-apt-repository ppa:numix/ppa`
`sudo apt-get update`
`sudo apt-get install numix-icon-theme-circle`

To be clear, numix-icon-theme and numix-gtk-theme work fine, but the app icon package cannot be found.

**Comment by Foggalong** [comment]
Any ideas @PaoloRotolo?

**Comment by WTRXGamer** [comment]
Could someone show me the contents of the file numix-ubuntu-ppa-yakkety.list in /etc/apt/sources.list.d?

Here is what mine looks like:
`
deb http://ppa.launchpad.net/numix/ppa/ubuntu yakkety main
# deb-src http://ppa.launchpad.net/numix/ppa/ubuntu yakkety main
# deb-src http://ppa.launchpad.net/numix/ppa/ubuntu yakkety main
`

**Comment by Foggalong** [comment]
Oooh, you're on Yakkety. You should have mentioned that in your original post! As far as I know, we don't have Yakkety builds just yet.

**Comment by WTRXGamer** [comment]
I'm actually on Debian, should I just change it to an older build of ubuntu?

**Comment by PaoloRotolo** [comment]
I'll add Yakkety build ASAP.

**Comment by PaoloRotolo** [comment]
Just uploaded a Yakkety bulid. Can you please confirm it works now?

**Comment by WTRXGamer** [comment]
Sorry for the late response, but I can confirm that it works. Thank you!
