### ISSUE TITLE
Icon for Netease Cloud Music

### ISSUE THREAD

**Issue by YaoC** [numixproject/numix-icon-theme-circle#3179]
A Numix-circle-icon for **Netease Cloud Music** is missing.
Icon=netease-cloud-music
The icon says "netease-cloud-music" and original is attached.
![netease-cloud-music](http://svgur.com/i/64.svg)
[svg file](http://svgur.com/i/64.svg)

**Comment by palob** [comment]
[Fixed.](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/netease-cloud-music.svg)
