### ISSUE TITLE
Evolution email calendar event icon

### ISSUE THREAD

**Issue by SrAceves** [numixproject/numix-icon-theme-circle#3195]
For calendar events, the icon in the message body is HUGE -- very annoying:
![captura de pantalla de 2016-05-30 18-58-11](https://cloud.githubusercontent.com/assets/12215943/15659891/8319ed1a-2698-11e6-827f-b883347199fb.png)

**Comment by Foggalong** [comment]
This is a bug with [base](https://github.com/numixproject/numix-icon-theme), not Circle. Please open the icon there.

**Comment by SrAceves** [comment]
Done!
