### ISSUE TITLE
Icon for Ubuntu Software Center

### ISSUE THREAD

**Issue by praveenpuglia** [numixproject/numix-icon-theme-circle#3200]
A circular, better icon instead of this...
![image](https://cloud.githubusercontent.com/assets/313363/15736293/61ac5b38-28bc-11e6-962c-c542924737a9.png)

please. :)

P.S - Ubuntu 16.04.

**Comment by palob** [comment]
Please ad the information asked for in the [readme](https://github.com/numixproject/numix-icon-theme-circle#numix-circle).

How did you install the theme?
As far as I can see this should be fixed now even with the PPA version.

**Comment by praveenpuglia** [comment]
I installed it from the ppa. 

I am now finding that the software center itself isn't working. I'll get back with details as soon as this works.
