### ISSUE TITLE
icon for keepassx2

### ISSUE THREAD

**Issue by storrgie** [numixproject/numix-icon-theme-circle#3204]
![Imgur](http://i.imgur.com/yvcgCoL.jpg)

```
[agd@enoch ~]$ which keepassx2
/usr/bin/keepassx2
```

Maybe, naively, I'm thinking that it's due to the fact it's name is keepassx2 (because of the 2.x) release. I think you already have a keepassx icon.

I'm also using numix-square, but was unsure of how to register an issue against that project.

**Comment by palob** [comment]
Please add the information asked for in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

Can you check how it looks with Numix-Circle?
