### ISSUE TITLE
Icon for Discord

### ISSUE THREAD

**Issue by chelog** [numixproject/numix-icon-theme-circle#3205]
https://discordapp.com/ (just a reference)

Icon=discord-canary
Original is attached
![discord](https://cloud.githubusercontent.com/assets/8367507/15799788/b77dc654-2a70-11e6-972e-79dc64d17aac.png)

**Comment by palob** [comment]
duplicate of #3121

**Comment by chelog** [comment]
@palob woopsie, my bad, closing
