### ISSUE TITLE
Software Center ubuntu 16.04 icon

### ISSUE THREAD

**Issue by raknerak** [numixproject/numix-icon-theme-circle#3224]
Hi,

with ubuntu 16.04, ubuntu started to use gnome software center instead of ubuntu software center. 

Here is the icon:
![selection_012](https://cloud.githubusercontent.com/assets/7880734/16034331/de14e10c-3219-11e6-84e6-8ebd3b856f14.png)

.desktop file details:

/usr/share/applications$ cat org.gnome.Software.desktop
[Desktop Entry]
Name=Software
Comment=Add, remove or update software on this computer
Icon=org.gnome.Software
Exec=gnome-software %U
Terminal=false
Type=Application
Categories=GNOME;GTK;System;PackageManager;
Keywords=Updates;Upgrade;Sources;Repositories;Preferences;Install;Uninstall;Program;Software;App;Store;
StartupNotify=true
MimeType=x-scheme-handler/appstream;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=gnome-software
X-GNOME-Bugzilla-Component=gnome-software
X-GNOME-UsesNotifications=true
DBusActivatable=true
X-Ubuntu-Gettext-Domain=gnome-software

**Comment by palob** [comment]
We've go that one. Are you using the Numix Circle PPA?

Try ``sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle``.

**Comment by raknerak** [comment]
I made fresh install ubuntu 16.04. I installed numix circle PPA and then installed circle theme via apt-get. 

I already run "sudo gtk-update-icon-cache -f /usr/share/icons/Numix-Circle" but there is no change...

**Comment by palob** [comment]
@wa4557 Any idea what's wrong here?

**Comment by wa4557** [comment]
Yeah I figured it out. There's another `org.gnome.Software.desktop ` desktop file in /usr/share/ubuntu/applications/org.gnome.Software.desktop` with `Icon=ubuntusoftware` that overrides it. I guess a symlink from the old ubuntu software icon should fix the problem

**Comment by palob** [comment]
So which icon to link to? ``gnome-software`` or the Ubuntu Software Center icon?

**Comment by wa4557** [comment]
I would link to `softwarecenter.svg`
