### ISSUE TITLE
Icon not shown properly

### ISSUE THREAD

**Issue by walkerlala** [numixproject/numix-icon-theme-circle#3227]
I have install all the icon-theme but many icons for many file extension are not shown properly.
Actually, as far as I can see, only files end with .sql, .pyc, .pl, .sh have their icons, while files like .cpp, .java don't(just like some unknown file)

I have try to modify those "text-x-python.svg", "application-x-python.svg"  files(change another ones) but no effect. One exception is when I change the "application-x-perl.svg" file, the icons would change correspondingly.

Any problems that you guys can see ?
I always use Ubuntu-Tweak-Tool to change the icons theme. Is that proper ?

Thanks!.

**Comment by palob** [comment]
That's an issue for the [base theme](https://github.com/numixproject/numix-icon-theme). How did you install it?

Did you download the GitHub ZIP? For Ubuntu the easiest way to install it is to use the PPA.
In which place the icons aren't shown correctly? File manager window? Can you please post a screenshot?

Is ``sudo gtk-update-icon-cache -f /usr/share/icons/Numix`` of any avail?

**Comment by walkerlala** [comment]
I forget how I install it the first time( I guess I use the Github ZIP to install *Numix-uTouch* because I just successfully add the ppa with no warning), but I just install *Numix-Circle-Light* using the ppa.

The icons in the lancher and other places are fine, except the file manager windows( you can see in the screenshot I attach)

I just do `sudo gtk-update-icon-cache -f  /usr/share/icons/Numix-Circle-Light` and it work fine, telling me that cache file created successfullu), but the windows manager didn't change

I'm sorry I can't post a screencast directly here because Github tell me it cannot process that file(really weird), so I put it on my google drive. Sorry about that.
https://drive.google.com/open?id=0Bwi4SUSqm7wcd0hSSXJNeU9BdTA

**Comment by palob** [comment]
The GitHub ZIP download is often broken.

Which mimetype is shown in the file properties dialog for the incorrectly recognised files?

**Comment by walkerlala** [comment]
For the *.cpp* file, *text/x-c++src*
            *.h* ,  *text/x-chdr*
            *.java* , *text/x-java*
            *. py*, *text/x-python*
            *.pyc*, *application/x-python-bytecode*

**Comment by palob** [comment]
That's strange then. I take it you've added the PPA?

Could you please do try reinstalling it?
 ```
sudo apt-get remove numix-icon-theme
sudo rm -R /usr/share/Numix
sudo apt-get install numix-icon-theme
```
(Hope the names are correct, I'm not running Ubuntu)

**Comment by walkerlala** [comment]
I reinstalled `numix-icon-theme` and `numix-icon-theme-circle`, but it result the same. I would try to manually configure it (I think it may be some bug of the file manager in Ubuntu 14.04 LTS). Thank you anyway!

**Comment by palob** [comment]
@wa4557 Any idea what's wrong here?

**Comment by bil-elmoussaoui** [comment]
@walkerlala Can you try an other file manager?

**Comment by wa4557** [comment]
@walkerlala Are those icons by any chance on an external drive? If yes the mimetype icons won't work.

**Comment by palob** [comment]
The mimetype however is assigned correctly...

**Comment by wa4557** [comment]
It gets even weirder??
![untitled](https://cloud.githubusercontent.com/assets/6475757/16115250/2baf6ec0-33c6-11e6-90e7-a969ec01ac31.png)

**Comment by walkerlala** [comment]
@wa4557 The icons are on the same driver as the system. Actually all of the file system are on the same driver

@bil-elmoussaoui I would like to. I have **xfe** as an alternative file manager, but I am not able to make any icons show up there(i.e. I don't know how to configure the configuration of an alternative file manager other than **nautilus**). Any hints ?

Thanks!

**Comment by palob** [comment]
It doesn't show Numix icons out of the box?

**Comment by wa4557** [comment]
Yeah but that's not a Numix issue, happens for me with every icon theme

**Comment by walkerlala** [comment]
@palob Yes, when using **xfe**, it remain the same with or without Numix icons
Do you know any other file manager on Ubuntu? May trying more would make thing clearer

**Comment by wa4557** [comment]
For me it seems to be a Nemo thing. With nautilus everything works flawlessly...

**Comment by wa4557** [comment]
Figured it out. In nemo disable the: `Show text in icons` option. Then the correct mimetype shows up.

**Comment by walkerlala** [comment]
@wa4557 what Nemo? Can you please explain a little bit more ?

**Comment by palob** [comment]
@wa4557 Ah, yes. That's a feature Numix doesn't support anyway.

**Comment by walkerlala** [comment]
@wa4557 yes, you are correct. Thanks

**Comment by wa4557** [comment]
@walkerlala Closing then? That's obviously not a Numix issue
