### ISSUE TITLE
New 'game' label

### ISSUE THREAD

**Issue by Siilwyn** [numixproject/numix-icon-theme-circle#3240]
A lot of issues are requests for game icons, I think it would be reasonable to label these differently from 'normal' applications since there are so many of them.

What do you think? I'm open to helping sort through the existing issues.

**Comment by Foggalong** [comment]
I can't really see a benefit to giving them a different label. They're not tackled any differently from normal icon requests and they aren't the only type of request we have a lot of (webapps for example).
