### ISSUE TITLE
Ubuntu Software, Teamviewer & PIDA

### ISSUE THREAD

**Issue by mufeed20** [numixproject/numix-icon-theme-circle#3249]
Hi,
Ubuntu Software Center (same as GNOME Software but with different icon), Teamviewer 11 & PIDA don't have Numix-circle Icons. Please Add It. 
Thanks.

**Comment by palob** [comment]
Please add the information asked for in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

Ubuntu Software is fixed but the fix hasn't trickled down to the PPA yet.

Teamviewer most probably is [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).

**Comment by mufeed20** [comment]
Ok sorry.
