### ISSUE TITLE
Icon for mp3splt-gtk

### ISSUE THREAD

**Issue by icasdri** [numixproject/numix-icon-theme-circle#3260]
Missing icon for mp3splt-gtk from the mp3splt project (utility to split audio files without decoding).
[Link to Project Home](http://mp3splt.sourceforge.net/mp3splt_page/home.php). [Link to Project SourceForge](https://sourceforge.net/projects/mp3splt/).

```
Name=Mp3splt-gtk audio splitter
Icon=/usr/share/pixmaps/mp3splt-gtk_ico.svg
```
<img src="https://a.fsdn.com/allura/p/mp3splt/icon" />

This icon is **hardcoded**. I have [opened an issue upstream](https://sourceforge.net/p/mp3splt/bugs/202/) to hopefully fix this, targetting the icon line `Icon=mp3splt-gtk`.

**Comment by palob** [comment]
How about this? Maybe too CDish?

![mp3splt-gtk_ico](https://cloud.githubusercontent.com/assets/7050624/16424253/b342a274-3d5f-11e6-8fbc-a0a40d944cf7.png)

**Comment by Foggalong** [comment]
The symbol is fine, but it'd be nice if it could incorporate the colours from the original icon :)
