### ISSUE TITLE
Icon for Eclipse

### ISSUE THREAD

**Issue by LedZeck** [numixproject/numix-icon-theme-circle#3262]
A numix-circle for Eclipse IDE is missing.
The icon line says "/opt/eclipse/icon.xpm" and the original icon is attached
![eclipse256](https://cloud.githubusercontent.com/assets/7060310/16439391/3f89a574-3d8e-11e6-9460-2024461243d7.png)

**Comment by palob** [comment]
We've got the icon but it is [hardcoded](https://github.com/numixproject/numix-icon-theme-circle#hardcoded-icons).

You can fix it by copying the ``.desktop`` file to ``.local/share/applications`` and editing the icon line inside to ``Icon=eclipse`` or reporting it against the [hardcode-fixer script repo](https://github.com/Foggalong/hardcode-fixer).
