### ISSUE TITLE
VisualStudio Code uses wrong icon 

### ISSUE THREAD

**Issue by kassuro** [numixproject/numix-icon-theme-circle#3266]
I noticed today that VisualStudio Code uses by default the icon for the text editor instead it's own icon.
Reason for this is the code.svg symlink.
I don't know if there is a reason for using code.svg this way, since I don't know enough about how the icons are chosen or if that's a problem because of the binary naming from vs code. 
Just wanted to let you know and I'm sorry if this issue is unnecessary.

**Comment by ewgenius** [comment]
Also have this issue. May be it because of ```code.svg``` icon links ```text-editor.svg```
https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/code.svg

**Comment by palob** [comment]
Hi, see the discussion in #2964.
Maybe we can change that if we can be sure there is no editor using this icon name and no app using an action with an icon called ``code`` (if the latter was the case we should remove ``code.svg`` from Numix Circle altogether).

**Comment by kassuro** [comment]
I don't have any issues after changing the symlink of code.svg to one of the vs code icons. So on standard Xubuntu nothing else seems to use this.
