### ISSUE TITLE
Mendeley icon different for running indicator

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-icon-theme-circle#3271]
The Mendeley icon looks great in my list of installed applications, however once running the icon that is used is the ugly non-themed variant. Perhaps it is due to the running application having the name "Mendeleydesktop.x86_64". Any ideas on how to keep the proper icon while Mendeley is running?

**Comment by palob** [comment]
Perhaps the [StartupWMClassFixer](https://github.com/bil-elmoussaoui/StartupWMClassFixer) can help.
Reporting the issue upstream always is a way to go.

**Comment by brittyazel** [comment]
I submitted it upstream and they confirmed it is a known issue. Hopefully it will be fixed soon enough
