### ISSUE TITLE
Icon for Adobe Illustrator CS6

### ISSUE THREAD

**Issue by bytec0d3** [numixproject/numix-icon-theme-circle#3279]
A numix-circle icon for Adobe Illustrator CS6 is missing.
The original icon is attached.
![icon](https://cloud.githubusercontent.com/assets/1859476/16651360/b9a24ad0-4443-11e6-82ee-6fe0e633e6fd.png)

**Comment by palob** [comment]
Please add the information asked for in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

Am I assuming correctly you run this through Wine?

**Comment by bytec0d3** [comment]
Sorry, but I followed just the video [tutorial](https://plus.google.com/+NumixProjectOrg/posts/DkRmhFZuWez?pid=5968002803595175714&oid=115833527622591803679). What information missing?

And yes, i run Illustrator through wine.

**Comment by palob** [comment]
The icon name which is the most important information :)

**Comment by bytec0d3** [comment]
Oh, you are right, sorry!
From the .desktop generated by PlayOnLinux (Wine), the application name is "Adobe Illustrator CS6".

**Comment by bytec0d3** [comment]
Ok, I just found a solution.
There is already an icon for Adobe Illustrator in the Numix-circle theme, but it is named "Adobeillustrator" (with the lowercase i). To show the correct icon, just edit the .desktop and set Icon=Adobeillustrator

**Comment by palob** [comment]
Yeah, we could do a symlink nonetheless. However, iirc spaces in file names will at least cause warnings.

**Comment by Foggalong** [comment]
@palob WINE icons aren't themeable so there's no point in symlinking it. The warning an icon with spaces is should probably be an error - the icon cache isn't updated which means the theme isn't applied properly until restart.
