### ISSUE TITLE
Icon for YACreader

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme-circle#3288]
Homepage: http://www.yacreader.com/

.desktop files

```
[Desktop Entry]
Name=YACReader
GenericName=Yet Another Comic Reader
Comment=A comic reader with support for .cb*, .pdf and whole directories.
Exec=YACReader %f
Icon=/usr/share/yacreader/icon.png
Terminal=false
Type=Application
StartupNotify=true
Categories=Graphics;Viewer;
MimeType=application/x-cbz;application/x-cbr;application/x-cbt;application/x-cb7;application/x-pdf;application/x-zip;application/x-rar;application/x-7z;inode/directory;
Keywords=comic;viewer;pdf;reader;
X-Desktop-File-Install-Version=0.22
```
``` 
[Desktop Entry]
Name=YACReader Library
GenericName=Yet Another Comic Reader - Library
Comment=A comic library management application with server mode.
Exec=YACReaderLibrary %f
Icon=/usr/share/yacreader/iconLibrary.png
Terminal=false
Type=Application
StartupNotify=true
Categories=Graphics;Viewer;
MimeType=
Keywords=comic;library;server;
X-Desktop-File-Install-Version=0.22
[lmello@maxwell applications]$ cat YACReader.desktop 
[Desktop Entry]
Name=YACReader
GenericName=Yet Another Comic Reader
Comment=A comic reader with support for .cb*, .pdf and whole directories.
Exec=YACReader %f
Icon=/usr/share/yacreader/icon.png
Terminal=false
Type=Application
StartupNotify=true
Categories=Graphics;Viewer;
MimeType=application/x-cbz;application/x-cbr;application/x-cbt;application/x-cb7;application/x-pdf;application/x-zip;application/x-rar;application/x-7z;inode/directory;
Keywords=comic;viewer;pdf;reader;
X-Desktop-File-Install-Version=0.22
```

**Comment by palob** [comment]
Hi, can you please report the hardcoded icon paths [upstream](https://bitbucket.org/luisangelsm/yacreader)?

**Comment by sljunkie** [comment]
I'll try. It breaks freedesktop's convention I know. What I usually do fix this manually is create a symlink in /usr/share/pixmaps to the installed icons, ex:

```
tuxguitar.png -> /usr/share/tuxguitar/share/skins/Lavender/icon-96x96.png
```

And manually alter the .desktop file. So this doesn't break any icon theme.

**Comment by sljunkie** [comment]
@palob Ok I could file a bug report - https://bitbucket.org/luisangelsm/yacreader/issues/46/linux-hardcoded-icons-on-desktop-files

**Comment by sljunkie** [comment]
The developer said the .desktop files will be upgraded in 8.6

**Comment by palob** [comment]
Can you please show us the two original icons?

**Comment by sljunkie** [comment]
![icon](https://cloud.githubusercontent.com/assets/7532854/17110491/a32e6584-5273-11e6-857f-63b039546144.png)


![iconlibrary](https://cloud.githubusercontent.com/assets/7532854/17110454/6c50b2ec-5273-11e6-8595-5536907501a1.png)

**Comment by palob** [comment]
I've named the icons ``yacreader`` and ``yacreader-library``.
Please keep track of how the icons are renamed upstream.

**Comment by selmf** [comment]
Just FYI: Hardcoded paths are gone in the upcoming 9.0.0 release (we're currently at RC1). Default icons will be installed as "YACReader" and "YACReaderLibrary" (same name as the executables).

**Comment by palob** [comment]
Thanks, we'll do symlinks.
