### ISSUE TITLE
Blue circle with white arrow icons used in gtk apps are cut off/messed up

### ISSUE THREAD

**Issue by nstommel** [numixproject/numix-icon-theme-circle#3294]
So the GTK icons for the numix-icon-theme-circle or possibly numix-gtk-theme that contain white arrows on blue circles are messed up and look sloppy across multiple applications. Below are screenshots from Wireshark, ClamTK, and qpdfview showing the cut-off icons:

![screenshot from 2016-07-14 20-32-16](https://cloud.githubusercontent.com/assets/15708310/16860104/dcb7cce2-4a02-11e6-80d4-3f0e618ee9da.png)
![screenshot from 2016-07-14 20-35-11](https://cloud.githubusercontent.com/assets/15708310/16860109/eab0f5bc-4a02-11e6-9e7b-7e8c0446ae31.png)

Here you can see that sometimes the icons for the right and left arrows are fine, but others are cut off in an ugly fashion. Please fix this pronto, it's been a lingering issue for months. I actually cannot seem to find the particular broken image files representing these buttons either, but they only appear with this Numix theme/icon pack.

![screenshot from 2016-07-14 21-48-34](https://cloud.githubusercontent.com/assets/15708310/16861262/046a505c-4a0d-11e6-9302-6b27abefd79b.png)

![screenshot from 2016-07-14 20-32-16 copy](https://cloud.githubusercontent.com/assets/15708310/16860131/19804122-4a03-11e6-854e-cd562294440d.png)

**Comment by palob** [comment]
It's by design in fact. But I could check how it looks with a blue outline or the white circle part transformed into a line.

**Comment by nstommel** [comment]
The icons are not actually blurry, it's just that I had to crop the 1080p screenshot to small sections of my screen so the icons were apparent (so it looks kinda compressed and nasty, but that's not really the point here). I'm using the most current version of the Numix theme and numix-circle icon theme from the Numix ppa. The cut off arrow icons just look very inconsistent with the overall theme, to the point that they don't look 'by design' but rather appear to be broken. I love the Numix theme, but these arrow icons really need to be changed to match the overall aesthetic. It looks like a glitch, not a purposeful design choice. Thanks for your consideration, I hope this can be changed in the near future.

**Comment by palob** [comment]
What I had in mind for a quick solution doesn't cut the mustard so we'd probably have to redesign the icons to something like this:
![go-icons](https://cloud.githubusercontent.com/assets/7050624/16966620/a815a016-4e05-11e6-96d3-baa9277bb867.png)

**Comment by nstommel** [comment]
Yes, that would be perfect! That's exactly what I had in mind.

**Comment by nstommel** [comment]
So I've found all the names of the cut-off blue-circle-with-arrow icons in numix-icon-theme-master from the latest download zip archive off the Numix github page. I thought this would be helpful just for reference so all icons can be appropriately changed. Thanks!

All cut off 'first' icons:

numix-icon-theme-master/Numix/16/actions/stock_first.svg
numix-icon-theme-master/Numix/22/actions/stock_first.svg
numix-icon-theme-master/Numix/24/actions/stock_first.svg
numix-icon-theme-master/Numix/32/actions/stock_first.svg
numix-icon-theme-master/Numix/48/actions/stock_first.svg
numix-icon-theme-master/Numix/64/actions/stock_first.svg
numix-icon-theme-master/Numix/16/actions/go-first-rtl.svg
numix-icon-theme-master/Numix/22/actions/go-first-rtl.svg
numix-icon-theme-master/Numix/24/actions/go-first-rtl.svg
numix-icon-theme-master/Numix/32/actions/go-first-rtl.svg
numix-icon-theme-master/Numix/48/actions/go-first-rtl.svg
numix-icon-theme-master/Numix/64/actions/go-first-rtl.svg
numix-icon-theme-master/Numix/16/actions/go-first.svg
numix-icon-theme-master/Numix/22/actions/go-first.svg
numix-icon-theme-master/Numix/24/actions/go-first.svg
numix-icon-theme-master/Numix/32/actions/go-first.svg
numix-icon-theme-master/Numix/48/actions/go-first.svg
numix-icon-theme-master/Numix/64/actions/go-first.svg
numix-icon-theme-master/Numix/16/actions/gtk-goto-first-ltr.svg
numix-icon-theme-master/Numix/16/actions/gtk-goto-first-rtl.svg
numix-icon-theme-master/Numix/22/actions/gtk-goto-first-ltr.svg
numix-icon-theme-master/Numix/22/actions/gtk-goto-first-rtl.svg
numix-icon-theme-master/Numix/24/actions/gtk-goto-first-ltr.svg
numix-icon-theme-master/Numix/24/actions/gtk-goto-first-rtl.svg
numix-icon-theme-master/Numix/32/actions/gtk-goto-first-ltr.svg
numix-icon-theme-master/Numix/32/actions/gtk-goto-first-rtl.svg
numix-icon-theme-master/Numix/48/actions/gtk-goto-first-ltr.svg
numix-icon-theme-master/Numix/48/actions/gtk-goto-first-rtl.svg
numix-icon-theme-master/Numix/64/actions/gtk-goto-first-ltr.svg
numix-icon-theme-master/Numix/64/actions/gtk-goto-first-rtl.svg

All cut off 'last' icons:

numix-icon-theme-master/Numix/16/actions/stock_last.svg
numix-icon-theme-master/Numix/22/actions/stock_last.svg
numix-icon-theme-master/Numix/24/actions/stock_last.svg
numix-icon-theme-master/Numix/32/actions/stock_last.svg
numix-icon-theme-master/Numix/48/actions/stock_last.svg
numix-icon-theme-master/Numix/64/actions/stock_last.svg
numix-icon-theme-master/Numix/16/actions/go-last-rtl.svg
numix-icon-theme-master/Numix/22/actions/go-last-rtl.svg
numix-icon-theme-master/Numix/24/actions/go-last-rtl.svg
numix-icon-theme-master/Numix/32/actions/go-last-rtl.svg
numix-icon-theme-master/Numix/48/actions/go-last-rtl.svg
numix-icon-theme-master/Numix/64/actions/go-last-rtl.svg
numix-icon-theme-master/Numix/16/actions/go-last.svg
numix-icon-theme-master/Numix/22/actions/go-last.svg
numix-icon-theme-master/Numix/24/actions/go-last.svg
numix-icon-theme-master/Numix/32/actions/go-last.svg
numix-icon-theme-master/Numix/48/actions/go-last.svg
numix-icon-theme-master/Numix/64/actions/go-last.svg
numix-icon-theme-master/Numix/16/actions/gtk-goto-last-ltr.svg
numix-icon-theme-master/Numix/16/actions/gtk-goto-last-rtl.svg
numix-icon-theme-master/Numix/22/actions/gtk-goto-last-ltr.svg
numix-icon-theme-master/Numix/22/actions/gtk-goto-last-rtl.svg
numix-icon-theme-master/Numix/24/actions/gtk-goto-last-ltr.svg
numix-icon-theme-master/Numix/24/actions/gtk-goto-last-rtl.svg
numix-icon-theme-master/Numix/32/actions/gtk-goto-last-ltr.svg
numix-icon-theme-master/Numix/32/actions/gtk-goto-last-rtl.svg
numix-icon-theme-master/Numix/48/actions/gtk-goto-last-ltr.svg
numix-icon-theme-master/Numix/48/actions/gtk-goto-last-rtl.svg
numix-icon-theme-master/Numix/64/actions/gtk-goto-last-ltr.svg
numix-icon-theme-master/Numix/64/actions/gtk-goto-last-rtl.svg

All cut-off 'top' blue icons:

numix-icon-theme-master/Numix/16/actions/top.svg
numix-icon-theme-master/Numix/22/actions/top.svg
numix-icon-theme-master/Numix/24/actions/top.svg
numix-icon-theme-master/Numix/32/actions/top.svg
numix-icon-theme-master/Numix/48/actions/top.svg
numix-icon-theme-master/Numix/64/actions/top.svg
numix-icon-theme-master/Numix/16/actions/stock_top.svg
numix-icon-theme-master/Numix/22/actions/stock_top.svg
numix-icon-theme-master/Numix/24/actions/stock_top.svg
numix-icon-theme-master/Numix/32/actions/stock_top.svg
numix-icon-theme-master/Numix/48/actions/stock_top.svg
numix-icon-theme-master/Numix/64/actions/stock_top.svg
numix-icon-theme-master/Numix/16/actions/gtk-goto-top.svg
numix-icon-theme-master/Numix/22/actions/gtk-goto-top.svg
numix-icon-theme-master/Numix/24/actions/gtk-goto-top.svg
numix-icon-theme-master/Numix/32/actions/gtk-goto-top.svg
numix-icon-theme-master/Numix/48/actions/gtk-goto-top.svg
numix-icon-theme-master/Numix/64/actions/gtk-goto-top.svg
numix-icon-theme-master/Numix/16/actions/go-top.svg
numix-icon-theme-master/Numix/22/actions/go-top.svg
numix-icon-theme-master/Numix/24/actions/go-top.svg
numix-icon-theme-master/Numix/32/actions/go-top.svg
numix-icon-theme-master/Numix/48/actions/go-top.svg
numix-icon-theme-master/Numix/64/actions/go-top.svg

All cut-off 'bottom' blue icons:

numix-icon-theme-master/Numix/16/actions/bottom.svg
numix-icon-theme-master/Numix/22/actions/bottom.svg
numix-icon-theme-master/Numix/24/actions/bottom.svg
numix-icon-theme-master/Numix/32/actions/bottom.svg
numix-icon-theme-master/Numix/48/actions/bottom.svg
numix-icon-theme-master/Numix/64/actions/bottom.svg
numix-icon-theme-master/Numix/16/actions/stock_bottom.svg
numix-icon-theme-master/Numix/22/actions/stock_bottom.svg
numix-icon-theme-master/Numix/24/actions/stock_bottom.svg
numix-icon-theme-master/Numix/32/actions/stock_bottom.svg
numix-icon-theme-master/Numix/48/actions/stock_bottom.svg
numix-icon-theme-master/Numix/64/actions/stock_bottom.svg
numix-icon-theme-master/Numix/16/actions/gtk-goto-bottom.svg
numix-icon-theme-master/Numix/22/actions/gtk-goto-bottom.svg
numix-icon-theme-master/Numix/24/actions/gtk-goto-bottom.svg
numix-icon-theme-master/Numix/32/actions/gtk-goto-bottom.svg
numix-icon-theme-master/Numix/48/actions/gtk-goto-bottom.svg
numix-icon-theme-master/Numix/64/actions/gtk-goto-bottom.svg
numix-icon-theme-master/Numix/16/actions/go-bottom.svg
numix-icon-theme-master/Numix/22/actions/go-bottom.svg
numix-icon-theme-master/Numix/24/actions/go-bottom.svg
numix-icon-theme-master/Numix/32/actions/go-bottom.svg
numix-icon-theme-master/Numix/48/actions/go-bottom.svg
numix-icon-theme-master/Numix/64/actions/go-bottom.svg

All cut off 'jump' icons:

numix-icon-theme-master/Numix/16/actions/go-jump-rtl.svg
numix-icon-theme-master/Numix/22/actions/go-jump-rtl.svg
numix-icon-theme-master/Numix/24/actions/go-jump-rtl.svg
numix-icon-theme-master/Numix/32/actions/go-jump-rtl.svg
numix-icon-theme-master/Numix/48/actions/go-jump-rtl.svg
numix-icon-theme-master/Numix/64/actions/go-jump-rtl.svg
numix-icon-theme-master/Numix/16/actions/go-jump.svg
numix-icon-theme-master/Numix/22/actions/go-jump.svg
numix-icon-theme-master/Numix/24/actions/go-jump.svg
numix-icon-theme-master/Numix/32/actions/go-jump.svg
numix-icon-theme-master/Numix/48/actions/go-jump.svg
numix-icon-theme-master/Numix/64/actions/go-jump.svg
numix-icon-theme-master/Numix/16/actions/gtk-jump-to-ltr.svg
numix-icon-theme-master/Numix/16/actions/gtk-jump-to-rtl.svg
numix-icon-theme-master/Numix/22/actions/gtk-jump-to-ltr.svg
numix-icon-theme-master/Numix/22/actions/gtk-jump-to-rtl.svg
numix-icon-theme-master/Numix/24/actions/gtk-jump-to-ltr.svg
numix-icon-theme-master/Numix/24/actions/gtk-jump-to-rtl.svg
numix-icon-theme-master/Numix/32/actions/gtk-jump-to-ltr.svg
numix-icon-theme-master/Numix/32/actions/gtk-jump-to-rtl.svg
numix-icon-theme-master/Numix/48/actions/gtk-jump-to-ltr.svg
numix-icon-theme-master/Numix/48/actions/gtk-jump-to-rtl.svg
numix-icon-theme-master/Numix/64/actions/gtk-jump-to-ltr.svg
numix-icon-theme-master/Numix/64/actions/gtk-jump-to-rtl.svg


All cut-off 'start' icons:

/home/noctua/Downloads/numix-icon-theme-master/Numix/16/actions/start.svg
/home/noctua/Downloads/numix-icon-theme-master/Numix/22/actions/start.svg
/home/noctua/Downloads/numix-icon-theme-master/Numix/24/actions/start.svg
/home/noctua/Downloads/numix-icon-theme-master/Numix/32/actions/start.svg
/home/noctua/Downloads/numix-icon-theme-master/Numix/48/actions/start.svg
/home/noctua/Downloads/numix-icon-theme-master/Numix/64/actions/start.svg

All cut-off 'finish' icons:

numix-icon-theme-master/Numix/16/actions/finish.svg
numix-icon-theme-master/Numix/22/actions/finish.svg
numix-icon-theme-master/Numix/24/actions/finish.svg
numix-icon-theme-master/Numix/32/actions/finish.svg
numix-icon-theme-master/Numix/48/actions/finish.svg
numix-icon-theme-master/Numix/64/actions/finish.svg

**Comment by nstommel** [comment]
Most of the paths I specified are actually just shortcuts if you check, so really only a few .svg files need to be changed. I just made sure to include every reference to the cut-off icons. I think this change would fit MUCH better into the design aesthetic. I've tried many base themes and icon themes, but Numix has always had the nicest, most complete set of icons available! I think that changing these often overlooked icons to something like what you suggested would be fantastic.

**Comment by palob** [comment]
@Foggalong @wa4557 @ChuckDaniels87 @dirtydancing @bil-elmoussaoui 
What are thoughts on a redesign for the ``go-...`` icons as discussed [above](https://github.com/numixproject/numix-icon-theme-circle/issues/3294#issuecomment-233766249)?

**Comment by dirtydancing** [comment]
@palob I have to say that I do like the current design with the arrows of the same shape. In contrast, your suggestion above makes use of different arrow shapes, which to me looks somewhat inconsistent. At the same time, I see the issue here about the "cut-off" appearance. How about keeping the current shape, but using a somewhat darker blue instead of the current white-grey?

**Comment by nstommel** [comment]
Yeah, that would certainly work! The current white-gray is very hard to see against the white background in most applications.

**Comment by Foggalong** [comment]
Yeah, agreed with @dirtydancing. As much as a like both of your individual redesigns @palob, the arrows being inconsistent across them both is a deal breaker. The idea of the darker blue area might be worth playing about with though.

**Comment by Foggalong** [comment]
I have just realised that this has been reported in the wrong repo though. Please refile in the [base theme](https://github.com/numixproject/numix-icon-theme) as that's where these icons are located.
