### ISSUE TITLE
Blurry bluetooth icon

### ISSUE THREAD

**Issue by ruppalsingh** [numixproject/numix-icon-theme-circle#33]
Using Numix-Circle icon-theme on elementaryOS 0.4 Loki. The bluetooth icon on Plank is blurry, [like so](https://i.imgur.com/BFR1W7x.png). Plank is configured, by default, to show 48x48 icons.

**Comment by ruppalsingh** [comment]
This may need to go to numix-core. Please let me know if it is so. I will close this and create a new issue in the appropriate repo.

**Comment by palob** [comment]
Yeah, would be nice to have this in the core repo, thanks.

**Comment by bil-elmoussaoui** [comment]
@ruppalsingh Btw, this is not related to Numix at all, but to be sure can you try with an other icon theme (except the default one)? if it's still looking blurry please report a bug issue here https://github.com/bil-elmoussaoui/StartupWMClassFixer instead of Numix Core
