### ISSUE TITLE
Dolphin: text editor icon shown instead of text-plain mimetype icon

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme-circle#3312]
![mimetype](https://cloud.githubusercontent.com/assets/7050624/17086334/66b35314-51ef-11e6-95a2-ff6382c6290a.png)

We haven't got any icon named ``text-plain.svg`` in Circle.

However there's ``text.svg``.
Does anybody know if there's an app actually needing it?

**Comment by palob** [comment]
I can confirm that ``text.svg`` is the toxic icon here. Deleting it fixes the issue.

**Comment by Foggalong** [comment]
It was part of a big symlink push from years a few years ago so as long as it's covered in base it can probably be removed here.
