### ISSUE TITLE
Indicator Stickynotes icon missing

### ISSUE THREAD

**Issue by szekeres2016** [numixproject/numix-icon-theme-circle#3328]
Hi, I'd like to report a missing icon for "Indicator Stickynotes" its one of (in not) the best desktop sticky notes app. The desktop file name is: "**indicator-stickynotes.desktop**" with "**Icon=indicator-stickynotes**" line inside.
![indicator-stickynotes](https://cloud.githubusercontent.com/assets/20751590/17275684/a01f9420-5710-11e6-8d57-ff5b187357f7.png)

**Comment by palob** [comment]
Is this icon shown as tray indicator?

**Comment by palob** [comment]
Is there a dedicated tray icon or is it the same as the launcher/app icon?

**Comment by szekeres2016** [comment]
It looks the same. I checked the github page of the project [https://github.com/umangv/indicator-stickynotes](url) There is an "**indicator-stickynotes**" and an "**indicator-stickynotes-mono**" icon in the package. They look the same but the tray might use the mono icon, so I don't really know...

**Comment by szekeres2016** [comment]
Wow... you made an icon for it already? :D sweet!

**Comment by wa4557** [comment]
According to the source code, the tray icon is indeed `indicator-stickynotes-mono`. I'll add an icon in base soon

**Comment by bil-elmoussaoui** [comment]
@wa4557 Take a look at the `hicolor` folder too...they are using the same icon for the tray as for the application icon. Maybe someone should report that upstream?

**Comment by wa4557** [comment]
I think they are not: https://github.com/umangv/indicator-stickynotes/blob/master/indicator-stickynotes.py#L86
