### ISSUE TITLE
OMG! Chrome! Webapp icon broken

### ISSUE THREAD

**Issue by szekeres2016** [numixproject/numix-icon-theme-circle#3334]
I noticed that there is already a Numix circle icon for this Webapp named "chrome-aeellliejpiclijnghognjagifplmmij-Default.SVG" unfortunately that is linked to the wrong app: https://chrome.google.com/webstore/detail/omg-chrome/aeellliejpiclijnghognjagifplmmij. As you can see the icon links to the Browser extension instead of the actual Webapp here: https://chrome.google.com/webstore/detail/omg-chrome/igpknfbadalohcopbkaepbgblomnbdma. I suppose this is a simple matter of changing the icon name. Thank you for the great job guys, really love this project!

**Comment by Foggalong** [comment]
It's not linked to the wrong one, it just needs an additional link to the webapp :)
