### ISSUE TITLE
vmware small icons issue

### ISSUE THREAD

**Issue by raknerak** [numixproject/numix-icon-theme-circle#35]
vmware right bottom side small icons seem strange.

![selection_051](https://cloud.githubusercontent.com/assets/7880734/22822896/ca4ed792-ef9a-11e6-8faf-cea9892a83f3.png)

**Comment by palob** [comment]
Hi, can you please reopen this in this repo https://github.com/numixproject/numix-icon-theme and show how it looks like using another theme?

**Comment by raknerak** [comment]
I manually download and completely removed old one but no change. Again icons are broken,

**Comment by raknerak** [comment]
When I switch to paper icon theme, it seems fine. 
![selection_053](https://cloud.githubusercontent.com/assets/7880734/22845272/4640a0a0-effb-11e6-88c7-823d9c336564.png)
