### ISSUE TITLE
Visual Studio Code icon not showing properly

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [numixproject/numix-icon-theme-circle#37]
The `.deb` file downloaded from the official VSCode website installs a `.desktop` file with `icon=code`, but the numix icon has no `code.svg` instead having `vscode.svg`.

Could you guys fix this issue?

Maybe creating a symlink would fix the issue.

**Comment by palob** [comment]
Please see https://github.com/numixproject/numix-core/issues/2964.
