### ISSUE TITLE
[SOLVED] Harfbuzz

### ISSUE THREAD

**Issue by t0m5k1** [numixproject/numix-icon-theme-circle#39]
When will this project be updated to support harfbuzz 1.4.x ??
I dont use infality or any other patched freetype yet the icons default to adwaita, someone else logged an issue and was told to downgrade to fix I do not have version 1.3.x as well as all the packages that will also require downgrade.
I really like this icon pack but having to trawl the web to find required version to get this to work is proving to be a nightmare.

**Comment by palob** [comment]
Hmm, I fail to understand what's our connection to harfbuzz. Could you please elaborate?

**Comment by t0m5k1** [comment]
https://github.com/numixproject/numix-icon-theme-circle/issues/31
I have the same issue.
No worries though I think I fixed it after some testing in a VM.

**Comment by t0m5k1** [comment]
Please close
