### ISSUE TITLE
Plex icon Pixelated

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme-circle#4]
Thank you for replacing plex media server icon.. however, it seems to be pixelated. 

![screenshot from 2016-08-21 16-36-12](https://cloud.githubusercontent.com/assets/1277920/17839462/e56a48ea-67be-11e6-951c-f854f94f53e8.png)

**Comment by Foggalong** [comment]
For future reference, this isn't an issue with the Linux packaging so needs to go in the new [circle-core](https://github.com/numixproject/circle-core) repo which houses the design assets.
