### ISSUE TITLE
Lack of some icons

### ISSUE THREAD

**Issue by ferlahozseg** [numixproject/numix-icon-theme-circle#41]
Hello!

I'm using the numix icon circle theme inside an elementary OS Loki and I have seen some issues:
1) Improvements on the headset and speakers icon (now is like a network PCI icon or something similar...)
2) Lack of icons in the system settings menu: applications, elementary tweaks and parental control.
3) Lack of icons for Launcher and Cerbere (in the system-settings-menu/Tweaks menu)
4) better integration with the icons in the top panel (bluetooth, sound, wifi, battery and notification icons)

I hope you fix it soon.

**Comment by palob** [comment]
Hi, please attach screenshots or - even better - find the icon names.

**Comment by ferlahozseg** [comment]
FIrst of all, I have to say that I'm so happy with this icon theme! You're doing a great work!
Here you have four screenshots of these problems and I've added a little description in every one.

![captura de pantalla de 2017-03-23 20-40-38](https://cloud.githubusercontent.com/assets/17322506/24267660/5404c90c-100b-11e7-996f-a61780243eb3.png)

![captura de pantalla de 2017-03-23 20-40-54](https://cloud.githubusercontent.com/assets/17322506/24267665/58af3bd6-100b-11e7-9e0d-d1fd211d912f.png)

![captura de pantalla de 2017-03-23 20-50-12](https://cloud.githubusercontent.com/assets/17322506/24267673/61f1a724-100b-11e7-9fff-7b3c2b7d153a.png)

![captura de pantalla de 2017-03-23 20-50-20](https://cloud.githubusercontent.com/assets/17322506/24267680/67790ea8-100b-11e7-88a2-f33c9b0b08a2.png)

If you need more information do not hesitate to ask me.

**Comment by palob** [comment]
Hi, can you please repost this here: https://github.com/numixproject/numix-icon-theme?

Related with https://github.com/numixproject/numix-icon-theme/issues/437.
