### ISSUE TITLE
Nautilus icon unchanged on GNOME 3.22.3

### ISSUE THREAD

**Issue by rupek1995** [numixproject/numix-icon-theme-circle#42]
System: Fedora 25, Gnome 3.22.3

I installed the icon pack from the numix repo today, and everything seems fine except the nautilus icon - it stays unchanged.

![image](https://cloud.githubusercontent.com/assets/9074800/24277228/153d862e-103c-11e7-89f0-99b9747aa0ab.png)

![image](https://cloud.githubusercontent.com/assets/9074800/24277218/fea316e0-103b-11e7-92dd-87e474ad581d.png)

**Comment by rupek1995** [comment]
Wrong repo for issue, sorry.

**Comment by LinjingFcode** [comment]
I have the same issue, but how to solve?

**Comment by palob** [comment]
Where did you install it from? AFAIK Numix Circle is in the official Fedora repos.

Anyway, this has been fixed quite some time ago so the package is outdated.

**Comment by LinjingFcode** [comment]
I didn`t know it and i cloned it from github. I think it is necessary to note it in README.md file. Thanks for your reply!

**Comment by palob** [comment]
Which repo did you clone?

**Comment by LinjingFcode** [comment]
It seems that is this repo.

**Comment by palob** [comment]
It seems? Please check this. If you installed from this repo the cion should be displayed correctly. If not, please find out the icon name and open an issue against this repo https://github.com/numixproject/numix-core
