### ISSUE TITLE
Icon for Tilix (formerly Terminix)

### ISSUE THREAD

**Issue by dagrha** [numixproject/numix-icon-theme-circle#44]
A numix-circle icon is for [Tilix](https://github.com/gnunn1/tilix) is missing. The project used to be called Terminix and there was a numix-circle icon for Terminix, but the project changed names and consequently lost its numix-circle icon.

The Icon line says `Icon=com.gexperts.Tilix` and a screenshot of the current icon is attached.
![screenshot from 2017-03-25 08-28-38](https://cloud.githubusercontent.com/assets/6957654/24323038/24c170ac-1135-11e7-8327-e7a6421f6c16.png)

Thank you for the fantastic numix-circle theme, keep up the great work!

**Comment by groudie** [comment]
Is this project still active? I haven't been hearing anything from the original guy so created the icons. He use to be really active.

**Comment by dagrha** [comment]
I believe that, yes, it is still active. [The project](https://github.com/gnunn1/tilix) has over 1,100 stars, and latest commit was yesterday. The change from "Terminix" to "Tilix" happened just 6 days ago.

**Comment by groudie** [comment]
@dagrha That's good news. I just haven't been hearing about the project lately. They use to make a lot of waves in the Linux community. I hope they add the Tilix icon soon. I spoke with the guy in charge of the La Capitaine project. He said he'll make the necessary changes on Monday.

**Comment by palob** [comment]
We've [already got a symlink](https://github.com/numixproject/numix-core/commit/0af521f7c825c4fd9560f877b839aac769e1c9f0).

**Comment by dagrha** [comment]
Thanks for the reply, @palob. When do the changes typically get pushed to the PPA? I am still seeing the standard Tilix icon and can't wait for that numix goodness :-)

![pasted image at 2017_03_31 04_30 pm](https://cloud.githubusercontent.com/assets/6957654/24571589/66eb3e8c-162f-11e7-9706-b2b24a08e562.png)

Cheers.

**Comment by palob** [comment]
Thanks for your passion :)

@Foggalong who does the releases is food-poisoned but on the way up. Might take a few days.

In the meantime you can fix the issue by copying Tilix's ``.desktop`` file over to ``~/.local/share/applications`` and changing the icon line to ``Icon=terminix``

**Comment by dagrha** [comment]
thanks, palob :+1:. feel better, Foggalong :-/
