### ISSUE TITLE
Icon request: Otter Browser

### ISSUE THREAD

**Issue by m4sk1n** [numixproject/numix-icon-theme-circle#45]
A numix-circle icon is for [Otter Browser](https://github.com/OtterBrowser/otter-browser) is missing. The Icon line says Icon=otter-browser and a screenshot of the current icon is attached.
![przechwycenie obrazu ekranu_2017-03-26_14-33-32](https://cloud.githubusercontent.com/assets/21127288/24331277/3f01a41c-1231-11e7-9bda-22a3f32cdea2.png)
Thanks ;)

**Comment by palob** [comment]
We've [already got the icon](https://github.com/numixproject/numix-core/blob/master/icons/circle/48/otter-browser.svg). You must be using an outdated version of the theme.
