### ISSUE TITLE
Icon request: Typora

### ISSUE THREAD

**Issue by MayKiller** [numixproject/numix-icon-theme-circle#48]
A numix-circle icon is for [Typora](https://www.typora.io/) is missing.
The Icon line says Icon=typora and current icon is attached.
![typora](https://cloud.githubusercontent.com/assets/3736910/25470492/0edb0df8-2ae8-11e7-812b-0cf33c58e478.png)
Thanks.

**Comment by Foggalong** [comment]
Icon request [go here](https://github.com/numixproject/numix-core). Please check the readme for the required info first
