### ISSUE TITLE
Icon Request: TORCS

### ISSUE THREAD

**Issue by thenanobel** [numixproject/numix-icon-theme-circle#49]
A **Numix Circle** icon for **TORCS** is missing.
The icon line says "torcs" (Icon=torcs) and the original icon is attached.

![TORCS Icon](https://cloud.githubusercontent.com/assets/9353047/25488557/2b353612-2b89-11e7-88df-65e0d87347ee.png)

**Description:** TORCS is a 3D racing cars simulator game using OpenGL.
**Website:** [http://torcs.sourceforge.net/index.php](http://torcs.sourceforge.net/index.php)

**Comment by Foggalong** [comment]
Icon request [go here](https://github.com/numixproject/numix-core). Please check the readme for the required info first
