### ISSUE TITLE
Discord Canary icon is not present outside of the applications folder

### ISSUE THREAD

**Issue by Dizeeee** [numixproject/numix-icon-theme-circle#5]
Here is the launcher info:

[Desktop Entry]
Name=Discord Canary
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/share/discord-canary/DiscordCanary
Icon=discord-canary
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;

**Comment by palob** [comment]
duplicate of #3.

**Comment by palob** [comment]
@Dizee Fixed?
