### ISSUE TITLE
fcitx icons all lost in indicator tray

### ISSUE THREAD

**Issue by gehuangyi20** [numixproject/numix-icon-theme-circle#50]
I am using numix-circle as my icon theme. The fcitx icon in the system menu tray all lost. They all becomes the default keyboard. If I am using numix as my icon theme, the icons are there.

Screen shot for Numix-Circle
![1](https://cloud.githubusercontent.com/assets/3879058/25548847/8576ca2e-2c3c-11e7-98af-47cdd50218ea.png)

Screen shot for Numix
![2](https://cloud.githubusercontent.com/assets/3879058/25548927/ea8c7c1a-2c3c-11e7-873d-6a62ec511b23.png)

**Comment by palob** [comment]
Hi, can you please try to find out what the icon names are?
