### ISSUE TITLE
change folder colour

### ISSUE THREAD

**Issue by goshobul** [numixproject/numix-icon-theme-circle#51]
Got the theme from the AUR. By default it uses green icons for the folders. In the icon set folder I have all the colours. How do I make the icon theme to use the purple icons instead of the green ones ( too lazy to rename all purple icons to the name used by the green ones).

**Comment by palob** [comment]
Hi, please take a look at this https://github.com/numixproject/numix-folders.

The GUI doesn't work with Wayland and needs a fix, the script works nontheless via CLI anyway.
