### ISSUE TITLE
icon for dnfdragora

### ISSUE THREAD

**Issue by DarkEra** [numixproject/numix-icon-theme-circle#52]
A numix-circle icon for dnfdragora is missing.
The icon line says "dnfdragora" and the original icon is attached.
![screenshot_2017-05-14_16-59-38](https://cloud.githubusercontent.com/assets/6264656/26035076/eff3c05a-38c6-11e7-8048-c3fccf52351e.png)

**Comment by palob** [comment]
Hi, please open icon requests here https://github.com/numixproject/numix-core.
