### ISSUE TITLE
icon for dnfdragora Package Installer

### ISSUE THREAD

**Issue by DarkEra** [numixproject/numix-icon-theme-circle#53]
A numix-circle icon for dnfdragora Package Installer is missing.
The icon line says "dnfdragora" and the original icon is attached.
![screenshot_2017-05-14_17-06-28](https://cloud.githubusercontent.com/assets/6264656/26035140/b4a430e2-38c7-11e7-9aaa-53a46b11e1ad.png)

**Comment by palob** [comment]
Hi, please open icon requests here https://github.com/numixproject/numix-core.
