### ISSUE TITLE
icon for dnfdragora-updater

### ISSUE THREAD

**Issue by DarkEra** [numixproject/numix-icon-theme-circle#54]
A numix-circle icon for dnfdragora-updater is missing.
The icon line says "dnfdragora" and the original icon is attached.
![screenshot_2017-05-14_17-09-12](https://cloud.githubusercontent.com/assets/6264656/26035157/12d621a2-38c8-11e7-8f16-8569ba6f0308.png)

**Comment by palob** [comment]
Hi, please open icon requests here https://github.com/numixproject/numix-core.

**Comment by DarkEra** [comment]
Thanks for the heads up, i didn't know about it that it was changed. I only found the old way since your readme/documentation still points to the video on how to request icons.

**Comment by palob** [comment]
Thank you.
