### ISSUE TITLE
zotero icon doesn't look much like the original

### ISSUE THREAD

**Issue by R-Broadley** [numixproject/numix-icon-theme-circle#56]
Zoteros official icon is a grey diamond with a red Z, the current Numix circle icon is burgundy circle with a white Z. 

I have created a new icon in the numix circle style which is grey with a red Z. 
I currently have it in svg form, don't know if that is all thats needed. 

Let me know if your interested and i'll create a pull request.

**Comment by palob** [comment]
Sure, feel free to submit a pull request against https://github.com/numixproject/numix-core.
