### ISSUE TITLE
Use "Wire" icon for "wire-desktop"

### ISSUE THREAD

**Issue by thenanobel** [numixproject/numix-icon-theme-circle#57]
Last month the [Wire team announced that they have started maintaining a official repository for Debian based GNU/Linux systems](https://medium.com/@wireapp/a-step-forward-for-wire-for-linux-52f0538cac15). And the packages come from this repository use the name "wire-desktop" instead of "Wire". So, it uses the default icon instead of the one provided by the *Numix Circle Icon Theme*. This issue should be fixed.

Here goes the `/usr/share/applications/wire-desktop.desktop` file,

    [Desktop Entry]
    Name=wire-desktop
    Comment=Modern communication, full privacy.
    Exec="/opt/wire-desktop/wire-desktop"
    Terminal=false
    Type=Application
    Icon=wire-desktop
    Categories=Network

**Comment by palob** [comment]
Fixed. Please report icon requests here https://github.com/numixproject/numix-core.

**Comment by thenanobel** [comment]
I think, this was not an icon request. So, I reported it here. Anyway, I'll report any kind of requests there in the future and thanks for fixing this. 😊
