### ISSUE TITLE
Make Opera browser icon look more like its actual icon

### ISSUE THREAD

**Issue by dvorapa** [numixproject/numix-icon-theme-circle#59]
Since September 2015 Opera browser has got a slightly different logo. But in Numix it seems to me there was no change in Opera browser icon since then. Could you please make Opera browser icon look more like the official one?

**Comment by palob** [comment]
Hi, this has already been reported and here is an icon proposal:
https://github.com/numixproject/numix-core/pull/3749

**Comment by dvorapa** [comment]
Thank you, hope it will be resolved soon
