### ISSUE TITLE
Icon for ClassicMenu Indicator

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme-circle#593]
Hi, a Numix-Circle icon is missing for ClassicMenu Indicator.

Icon line: Icon=classicmenu-indicator-light

Icon: 
![classicmenu-indicator-light](https://cloud.githubusercontent.com/assets/7164227/2642741/07f416ae-bf0e-11e3-8169-90bb8c41a76d.png)

**Comment by Foggalong** [comment]
This should now be fixed :)
