### ISSUE TITLE
Downgrade on Fedora 26

### ISSUE THREAD

**Issue by flocomkoko** [numixproject/numix-icon-theme-circle#60]
When updating to Fedora 26 the numix-icon-theme-circle package downgrades from 
0.1.0-13.git5a11140.fc25 to 0.1.0-12.gitc3aefdb.fc26. This seems to be a simple packaging issue, since the 0.10.13 version is availible in the update repo for Fedora 25 but not in Fedora 26.

**Comment by Daniel-Krebs** [comment]
Stumbled upon this bug by Google and just wanted to inform you, that the people at Fedora/Redhat seem to be aware of it: https://bugzilla.redhat.com/show_bug.cgi?id=1469761

**Comment by Foggalong** [comment]
Thanks @Daniel-Krebs !
