### ISSUE TITLE
request for global folder-color

### ISSUE THREAD

**Issue by Armanmd** [numixproject/numix-icon-theme-circle#61]
`Hello`, is there an easy way to switch provided folders' color, ie from default orange to grey or whatever?

i mean is in **papirus-icon-theme** there is good feature (`global folder-color`) Can you make it ?

[screen shot](https://cloud.githubusercontent.com/assets/819186/23070195/f2546caa-f532-11e6-903f-7835be96edc7.png)

_*Can you make that*_

**Comment by Foggalong** [comment]
Hey @Armanmd! Thanks for getting in touch. Numix was in fact the first icon theme to allow folder colour changing through [Folder Color](http://foldercolor.tuxfamily.org/), or if you'd prefer we also have [our own program](https://github.com/numixproject/numix-folders) which allows you to do the same thing. Hope that helps!
