### ISSUE TITLE
Icon for lightdm-settings in Linux Mint 18.2

### ISSUE THREAD

**Issue by wibble99** [numixproject/numix-icon-theme-circle#62]
Linux Mint is using light-dm now and the .desktop file looks for the "lightdm-settings" icon. This can be fixed by the user to be "lightdm-gtk-greeter-settings" for which there is a Numix Circle icon, but an additional icon link with the name "lightdm-settings" pointing to "login.svg" would be a permanent fix. Issues also affects numix-icon-theme-square.

Not the most important issue by any means, but easy to fix.

**Comment by bil-elmoussaoui** [comment]
The same answer as in your other issue https://github.com/numixproject/numix-icon-theme-square/issues/13#issuecomment-325196218
