### ISSUE TITLE
Visual Studio Code Icon - Color Problems.

### ISSUE THREAD

**Issue by CosmoAbdon** [numixproject/numix-icon-theme-circle#64]
Hi, I think we got a issue on all vscode icons. (all versions of square and circle).
The Icon design is amazing, but I think your guys left a blue layer on the icon.

Image : https://imgur.com/a/JlLHW
In github : https://github.com/numixproject/numix-core/blob/master/icons/circle/48/visualstudiocode.svg

I'll wait for a reply and a fix.

Thx in advance.

[OFF]
This icon looks amazing, maybe inspire ur guys : https://stas.blog/wp-content/uploads/2017/04/vs-code-icon.png

**Comment by palob** [comment]
If you are referring to the blue background, I can tell you that's on purpose.

**Comment by CosmoAbdon** [comment]
For real ? Because this blue layer looks kinda strange and doesn't give any charm.

**Comment by Foggalong** [comment]
This repo isn't for issues relating to the icons themselves, just the Linux packaging. If you wish to rereport this please do so in Numix Core were we handle all the design work
