### ISSUE TITLE
Problem with NetBeans icon

### ISSUE THREAD

**Issue by atilacamurca** [numixproject/numix-icon-theme-circle#66]
![netbeans-icon](https://user-images.githubusercontent.com/508624/31017120-dc269b8a-a4fd-11e7-9f5e-e4e3c4c66d20.png)

As you can see in the picture there's a rendering problem with NetBeans icon.

```
Version: 2.0.3+17~201709261931~ubuntu14.04.1
APT-Sources: http://ppa.launchpad.net/numix/ppa/ubuntu/ trusty/main amd64 Packages
```

**Comment by Foggalong** [comment]
Please report this in the Numix Core repo where we actually manage the icons. This is just the packaging repo
