### ISSUE TITLE
Icon for Python IDLE

### ISSUE THREAD

**Issue by natanfelles** [numixproject/numix-icon-theme-circle#69]
https://screenshots.debian.net/package/idle

**Comment by natanfelles** [comment]
![new_python](https://user-images.githubusercontent.com/3011423/32196175-ee0b4d16-bda6-11e7-8704-434f7dd02bd3.gif)

![text-x-python](https://user-images.githubusercontent.com/3011423/32196198-fc489eec-bda6-11e7-8a06-a7e3c45340e8.png)

**Comment by palob** [comment]
Please report missing icons here https://github.com/numixproject/numix-core

The IDLE icon is hardcoded, please cf. the core README for assistance.

**Comment by natanfelles** [comment]
Thank you!
