### ISSUE TITLE
Request to tone down the Clipit icon

### ISSUE THREAD

**Issue by Organic-Marble** [numixproject/numix-icon-theme-circle#7]
Apparently in Ubuntu there's this new thing Clipit.  The functionality seems cool but the icon from numix-icon-theme-circle is a bright red and white that sits in my system tray and looks like something has gone wrong.  It sits about where a failed update warning sits and is muy distracting.  I have to shut down Clipit because I can't take the icon there.  

This is a sincere request from a user who loves your icons, to tone this one down so it does not look like my system is about to fail.
![2016-08-28-215227_2304x1024_scrot](https://cloud.githubusercontent.com/assets/20708885/18039556/dba9aee4-6d69-11e6-848f-05b8311eb828.png)

**Comment by palob** [comment]
The icon isn't supposed to be there. Can you aks the Clipit dev to use a seperate icon for the tray?

**Comment by Organic-Marble** [comment]
Thanks for the reply.  I traced the problem to a bad symbolic link in 
the Numix-Circle icon directory, so I'm thinking it's probably not the 
Clipit dev's problem.  But I am certainly not an expert on this stuff.

Anyway, I fixed it on my system like so.

cd /usr/share/icons/Numix-Circle/48/apps
sudo rm clipit-trayicon.svg
sudo ln -s /usr/share/app-install/icons/clipit-trayicon.svg 
clipit-trayicon.svg

and I got a nice clipboard / piece of paper icon instead of the glaring 
red warning light.

Thanks again for your great icons, I love them!

Bill

**Comment by Organic-Marble** [comment]
Looks like this now.

![2016-08-31-215109_2304x1024_scrot](https://cloud.githubusercontent.com/assets/20708885/18153791/5b76e918-6fc5-11e6-9ca2-33cf2a4c66db.png)

**Comment by palob** [comment]
Ah OK,we can remove ``clipit-trayicon`` from Circle then. Does Clipit come with a launcher? I fear it's got ``clipit-trayicon`` as its icon.

Can you open an issue against https://github.com/numixproject/numix-core so we can look after a Numixy design for the tray icon? It's just a matter of a symlink either.

**Comment by palob** [comment]
I've installed it, unfortunately the icon the launcher uses is ``clipit-trayicon``.

**Comment by Organic-Marble** [comment]
I fixed the symlink, and mine is OK now.  (see the last picture I posted).
