### ISSUE TITLE
Icon for Gnome Encfs Manager

### ISSUE THREAD

**Issue by lmpng** [numixproject/numix-icon-theme-circle#709]
Icon for Gnome Encfs Manager is missing.
The icon line says "gnome-encfs-manager" and the original icon is attached.

![gnome-encfs-manager](https://cloud.githubusercontent.com/assets/1295587/2938236/aabb6d4e-d8fc-11e3-9aad-9a2dc5b0c9ed.png)

Thank you very much!

**Comment by Foggalong** [comment]
Moved to base :)

**Comment by TamasBarta** [comment]
I still have the same issue that mfin had. I have the launcher icon shown in the Unity panel.

**Comment by Foggalong** [comment]
@TamasBarta do you know what icon name the panel uses?

**Comment by TamasBarta** [comment]
I found this in it's source code:

`src/trayicon.vala:87`
```vala
appindicator = new AppIndicator.Indicator(  "Gnome Encfs Manager",
                            "gnome-encfs-manager-panel",
                            IndicatorCategory.APPLICATION_STATUS);
```

So I believe it's `gnome-encfs-manager-panel`. I'm not sure though if that's the version which is currently packaged.
