### ISSUE TITLE
Icon for Tails Installer

### ISSUE THREAD

**Issue by kAoi97** [numixproject/numix-icon-theme-circle#72]
A numix-circle icon for Tails Installer is missing
The icon line says "tails-installer.svg" and the original icon is attached.
![captura de pantalla de 2017-11-29 08-44-44](https://user-images.githubusercontent.com/6687371/33378052-949f2a3e-d4e1-11e7-8051-04b03b64f888.png)

**Comment by Foggalong** [comment]
Check the readme for the right repo
