### ISSUE TITLE
How to change Private Internet Access (PIA) icon?

### ISSUE THREAD

**Issue by javery86** [numixproject/numix-icon-theme-circle#73]
Where would I find the file that needs to be edited in order to have it point to the Numix Circle pia-manager.svg icon?

**Comment by javery86** [comment]
Update: I figured it out.

The file is located at /home/user name/.local/share/applications/pia_manager.desktop

Just change this...

Icon=/home/joe/.pia_manager/pia_tray_files/img/icon_512x512.png

to this...

Icon=pia-manager

**Comment by palob** [comment]
Good to hear you could fix the issue. For future reference please post any non-packaging issues concerning our app icons here https://github.com/numixproject/numix-core.
