### ISSUE TITLE
Folder icons are white "blanks" instead of yellow folders

### ISSUE THREAD

**Issue by perryraskin** [numixproject/numix-icon-theme-circle#76]
I had to reinstall my Ubuntu VM, and I am trying to get my theme combo back. I am trying to apply Numix-Circle for icons, and for some reason, everything works besides for folder icons. They are just blank icons, or "white pieces of paper" to resemble a blank icon. Any ideas? I'm positive I installed everything correctly, and I am using Unity Tweak Tool.
![screen shot 2017-12-27 at 1 19 15 pm](https://user-images.githubusercontent.com/17967465/34389603-944a9c3e-eb08-11e7-8d74-56e404e717eb.png)

**Comment by bil-elmoussaoui** [comment]
Can we get a screenshot with just Numix base theme?

**Comment by perryraskin** [comment]
It must have been something with my Parallels VM or something. I re-did the entire thing in VirtualBox and it works ok now.
