### ISSUE TITLE
The christmas commit causes "gtk-update-icon-cache: The generated cache was invalid"

### ISSUE THREAD

**Issue by marcvangend** [numixproject/numix-icon-theme-circle#77]
I'm using Arch Linux and have Numix Circle installed from the AUR. Today I wanted to re-install the icon theme to pull in any available updates. For some reason the install process returns `gtk-update-icon-cache: The generated cache was invalid.` twice.
In an attempt to figure out the source of the problem, I edited the PKGBUILD file to specify a different commit hash. It turns out that only the latest commit (1e063b7, "The christmas commit") causes this error. The one before, 919feb3, generates the cache file correctly. I suspect that the cause of the problem is `numix-icon-theme-circle/Numix-Circle/48/apps/924C_StarCraft II.0.svg` which contains a space in the name.

**Comment by bil-elmoussaoui** [comment]
We fixed this few days ago https://github.com/numixproject/numix-core/pull/4065. A new release will come by the end of this month. We are a bit busy with finals. We have also added a test case to avoid having this issue in the future

**Comment by marcvangend** [comment]
Ah, in that case, I apologize for the noise. I didn't realize that this was coming from Numix core. Thanks for the quick reply.
