### ISSUE TITLE
Numix circle uses python icon for WICD in tray

### ISSUE THREAD

**Issue by TomJansen** [numixproject/numix-icon-theme-circle#79]
Hello and thank you for this great icon pack.

I however have a problem with one icon. 
For WICD, Numix circle uses the python icon in the tray on XFCE. The normal Numix icon pack does not have this problem. In their issue tracker, they "symlinked the wifi icons" see here: https://github.com/numixproject/numix-icon-theme/issues/246.

Thank you!

BTW, I am on Xubuntu. I removed gnome network-manager because it gave me connection errors.

**Comment by palob** [comment]
Can you please show a screenshot?

**Comment by TomJansen** [comment]
Here you go. The circle python image is wicd.


![screenshot_2018-01-21_15-41-37](https://user-images.githubusercontent.com/2716208/35195313-ec43e7ca-fec1-11e7-943e-d60d54cc4995.png)

**Comment by palob** [comment]
No that makes no sense at all. It is the idle icon and app icons aren't supposed to show up in the tray anyway. It is probably because we have got a symlink called ``idle`` which I think we should remove from our app icon theme because it is too generic.
The wicd guys however should rename their icon as well to say ``wicd-idle``.

**Comment by TomJansen** [comment]
Thanks, I just renamed one icon from gnome network-manager from the original numix icon pack to idle.svg and put that into numix-circle

**Comment by palob** [comment]
How does the icon look without Numix Circle applied?

**Comment by TomJansen** [comment]
With Adwaita icon theme applied (so original icon):
![wicd](https://user-images.githubusercontent.com/2716208/35220363-5f1f7e3a-ff76-11e7-92d5-d0c070c7a7e2.png)

**Comment by TomJansen** [comment]
You have several of these icons for WICD. Here are all of them. These are extracted from `/usr/share/wicd/icons/hicolor/22x22/status/`
[wicd status icons.tar.gz](https://github.com/numixproject/numix-icon-theme-circle/files/1651862/wicd.status.icons.tar.gz)
