### ISSUE TITLE
Error running gtk-update-icon-cache

### ISSUE THREAD

**Issue by yeahimfreaky** [numixproject/numix-icon-theme-circle#81]
Hi,
I'm using the latest Numix-Circle icons in XFCE, and everything appears to be working fine. However, I'm getting an error with `gtk-update-icon-cache`:

```
$ gtk-update-icon-cache ~/.icons/Numix-Circle
gtk-update-icon-cache: The generated cache was invalid.
```

This command works successfully with the Numix icon set, so I think it's specific to this Circle set.

**Comment by palob** [comment]
This is due to Wine icon names which contain spaces. Should be fixed in future releases.

**Comment by Foggalong** [comment]
Will close when a release with a fix has gone out :)

**Comment by ryukinix** [comment]
This happens with me in Arch Linux as well.

**Comment by Foggalong** [comment]
Should be fixed in the latest version :+1:
