### ISSUE TITLE
Icon for Mattermost

### ISSUE THREAD

**Issue by mholecy** [numixproject/numix-icon-theme-circle#82]
A numix-circle icon for mattermost application is missing.
Icon line says "mattermost-desktop" and original icon is attached.
![screenshot from 2018-02-06 16-43-30](https://user-images.githubusercontent.com/6795825/35868501-f3bbc2be-0b5c-11e8-903a-6369810a6e0b.png)

**Comment by Foggalong** [comment]
Please read the readme
