### ISSUE TITLE
Toolbar bluetooth icon is green instead of monochromatic

### ISSUE THREAD

**Issue by korg91** [numixproject/numix-icon-theme-circle#83]
After last update via ppa, on Ubuntu 16.04 with Unity the bluetooth icon in the toolbar is green rather than monochromatic. This happens only with Numix-circle and Numix-circle-light icon themes, not with Numix nor Numix-light.
![numix_bt_icon](https://user-images.githubusercontent.com/3729408/36076521-0ccbf5b6-0f55-11e8-956f-a6fe57746370.png)

**Comment by palob** [comment]
Are you using Blueman or some stuff?

**Comment by palob** [comment]
Please read the readme and reopen the issue here https://github.com/numixproject/numix-icon-theme

**Comment by korg91** [comment]
@palob [Done](https://github.com/numixproject/numix-icon-theme/issues/1288), thanks.

On a side note, could you please point out where the readme says that such issues should be reported on the numix-icon-theme repo? On the readme for _this_ repo, it says:

> The tracker for this repo is only for issues relating to the Linux packaging.

But how can I know if this is an issue with the Linux packaging?
