### ISSUE TITLE
TeamViewer icon replace in tray on app icon.

### ISSUE THREAD

**Issue by Faust30000** [numixproject/numix-icon-theme-circle#85]
The problem with the icon of the program is TeamViewer. A standard icon (not a Numix) of the program is displayed in the system tray. And in the list of installed icons for the tray.
Linux Mint Cinnamon 18.3

**Comment by palob** [comment]
Hi, please reopen this in the appropriate tracker and attach a screenshot.
https://github.com/numixproject/numix-icon-theme
