### ISSUE TITLE
BTSync GUI Menu-Icon Broken

### ISSUE THREAD

**Issue by MrDroid** [numixproject/numix-icon-theme-circle#850]
In numix-icon-theme-circle_0.2+201406030301~500~ubuntu14.04.1_all.deb the panel icon for btsync-gui-gtk broken. It shows the application icon rather than a grey icon.

http://i.imgur.com/ZjDmB77.png

Downgrading to numix-icon-theme-circle_0.2+201405292020~495~ubuntu14.04.1_all.deb fixed it for me.

http://i.imgur.com/UlisbBS.png

**Comment by Foggalong** [comment]
I've just realised that this request has 44px status icons. I've never come across those before :O

**Comment by Foggalong** [comment]
Moving the status part of this request to the base theme :)
