### ISSUE TITLE
Settings menu icon doesn't follow typical design patterns

### ISSUE THREAD

**Issue by jacobcantele** [numixproject/numix-icon-theme-circle#86]
I believe Numix-Circle is inappropriately using the hamburger button. Shouldn't the typical design pattern be a gear icon?

For example, this looks really wrong:

![screenshot from 2018-03-23 16-58-47](https://user-images.githubusercontent.com/10467486/37855139-c59b9e7c-2ebb-11e8-8a64-3141f85be29a.png)

**Comment by palob** [comment]
can you please reopen this here https://github.com/numixproject/numix-icon-theme?
