### ISSUE TITLE
Missing package for Debian 9 (stretch)?

### ISSUE THREAD

**Issue by qwang07** [numixproject/numix-icon-theme-circle#87]
I can install `numix-icon-theme` through `sudo apt install numix-icon-theme` but not `numix-icon-theme-circle`. Also, `sudo add-apt-repository pps:numix/ppa` cannot be processed, because the public key cannot be verified in Debian 9.

**Comment by totietje** [comment]
@qwang07 I'm also having this issue, have you found another way of installing?

**Comment by GLolol** [comment]
No official package for Numix-Circle has ever existed in Debian and Ubuntu; there is only a pending package (my own) so far that can hopefully be uploaded soon (https://bugs.debian.org/863383)

I have unofficial .deb's at https://packages.overdrivenetworks.com/rfs/numix-icon-theme-circle_18-02-16-1/numix-icon-theme-circle_18-02-16-1_all.deb if you want to install that way. These are built off the [tentative packaging](https://github.com/utopia-repository/numix-icon-theme-circle/tree/debian/sid) that targets Debian unstable.

**Comment by qwang07** [comment]
@GLolol Cool, I tried and it works for me. Thanks a lot.

**Comment by totietje** [comment]
Thanks, worked for me too :D

**Comment by Foggalong** [comment]
Glad this was resolved, will keep an eye on that Debian package to see if they have any questions :)
