### ISSUE TITLE
A few icons missing in gnome 18.10

### ISSUE THREAD

**Issue by ddnexus** [numixproject/numix-icon-theme-circle#88]
Updating to 18.10 leaves gnome-tweaks and dconf-editor naked :). It's probably a naming problem.

**Comment by palob** [comment]
Please check if you've got the latest version installed. If yes please report the missing icon names  here https://github.com/numixproject/numix-core

**Comment by ddnexus** [comment]
I am not sure to understand. Maybe I didn't explain it correctly.
The 2 icons are present and working with the last version IF you use 17.10. But if you use 18.04 the icons are not applied to the same application (maybe because the application changed its name or something?).
Is that a problem that has to be reported at the link you provided?

**Comment by palob** [comment]
I'm talking about the latest version of our theme which I think has got the needed files. You're right, the icons were renamed upstream.

**Comment by ddnexus** [comment]
Ok, so should I use the link you suggested or this issue is enough?

**Comment by palob** [comment]
If the issue persists please rereport the with the needed icon names in the Core repo so we don't lose track.
