### ISSUE TITLE
OCZ SSD GURU renamed upstream to OCZ SSD Utility

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-icon-theme-circle#9]
Like the title says, OCZ's SSD GURU program has been renamed and rebranded upstream as OCZ SSD Utility.

In the .desktop file, the icon being requested is now "ocz-ssd-utility"

I believe we had a fancy icon for OCZ SSD GURU, can we switch that over to the new branding?

**Comment by Foggalong** [comment]
Following a repo reorganisation this repo is just for issues with the Linux packaging. For issues with the icons, please file a request [here](https://github.com/numixproject/circle-core/issues).
