### ISSUE TITLE
Indicator icon for Copy client.

### ISSUE THREAD

**Issue by wraithbb** [numixproject/numix-icon-theme-circle#905]
Hi,

Right now CopyAgent, a client for http://copy.com/ cloud service is using default application icon from Numix Circle theme which location is /usr/share/icons/Numix-Circle/48x48/apps/copy.svg. The icon is quite nice, but it is used also for indicator icon. 

This is a request for 24x24 monochrome copy indicator icon - similar to dropbox.

**Comment by Foggalong** [comment]
Moved to base :)
