### ISSUE TITLE
Invalid GTK Icon Cache [$15]

### ISSUE THREAD

**Issue by cldx** [numixproject/numix-icon-theme-circle#915]
We believe this is triggered in the same way than in this bug:

https://github.com/moka-project/moka-icon-theme/issues/94

Uncertain if we will approach the same solution.

**Comment by emariz** [comment]
Just for the record, these are the icons which currently generate the issue

	$ find /usr/share/icons/Numix-Circle/ -type f -name "* *"
	/usr/share/icons/Numix-Circle/48x48/apps/56B4_Battle.net Launcher.0.svg
	/usr/share/icons/Numix-Circle/48x48/apps/5C12_World of Warcraft Launcher.0.svg
	/usr/share/icons/Numix-Circle/48x48/apps/Yahoo Mail-mail.yahoo.com.svg

	$ find /usr/share/icons/Numix-Circle/ -type l -name "* *"
	/usr/share/icons/Numix-Circle/48x48/apps/Google News-news.google.com.svg
	/usr/share/icons/Numix-Circle/48x48/apps/Amazon Cloud Reader-read.amazon.com.svg
	/usr/share/icons/Numix-Circle/48x48/apps/Google Calendar-google.com.svg
	/usr/share/icons/Numix-Circle/48x48/apps/Angry Birds-chrome.angrybirds.com.svg
	/usr/share/icons/Numix-Circle/48x48/apps/Google docs-docs.google.com.svg


Because I do not use those applications, I simply replaced the spaces with underscores in their file names and the GTK Icon Cache built without problems.

	su -c 'gtk-update-icon-cache /usr/share/icons/Numix-Circle'
	gtk-update-icon-cache: Cache file created successfully.


Granted, this only shows the issue and leaves it unsolved, but other users might want to identify such icons and rename (or delete) them to generate a valid icon cache.

**Comment by ChuckDaniels87** [comment]
From [GTK documentation](https://developer.gnome.org/icon-theme-spec/):

>Hence, theme names are case sensitive, and are limited to ASCII characters. Theme names may also not contain comma or space. 

It seems that there is no direct solution to this, unless code is changed upstream or the icons are removed. Maybe a workaround can be done in the packaging changing names before _gtk-update-icon-theme_ is executed and restoring them after that, at least in AUR can be done.

**Comment by snwh** [comment]
Correct. It can't be fixed. (Regardless of the bounty placed on it.)

**Comment by ChuckDaniels87** [comment]
@Foggalong maybe you could use this bounty on other issues as Calibre one.

**Comment by Foggalong** [comment]
@ChuckDaniels87 good thinking, I'll do that :) Thanks for your input on this @snwh it's much appreciated.

**Comment by Foggalong** [comment]
[Wrote a bit in the wiki](https://github.com/numixproject/numix-wiki/wiki/Unthemed-Icons#invalid-icon-names) to cover it. Just have to work it into the main readme now and delete the relevant icons :)

**Comment by ChuckDaniels87** [comment]
Nice :+1:
