### ISSUE TITLE
Gajim support

### ISSUE THREAD

**Issue by manuel-uberti** [numixproject/numix-icon-theme-circle#92]
Hi,

first of all thank for this awesome icon theme.

I see there is a `gajim.svg` file in `/usr/share/icons/Numix-Circle/48/apps`, but I always seem to get the default Gajim icon.

I am running Ubuntu 18.04 with GNOME Shell 3.28.1. I get the default Gajim icon both in the top bar and in the dash (I am using Dash to Dock extension). I installed the icons using your PPA.

Is there something I am missing?

If you need more info to debug the problem, or more tests on my side, feel free to ask.

**Comment by palob** [comment]
Hi, can you please look for Gajim's ``.desktop`` launcher file and report the ``Icon=...`` line from inside in our icon repository?

**Comment by manuel-uberti** [comment]
Sure, done [here](https://github.com/numixproject/numix-core/issues/4354).

Thank you
