### ISSUE TITLE
Monochrome icons in Cinnamon menu. [$10]

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme-circle#928]
Some applications are using monochrome icons in Cinnamon menu:

Google Chrome.

![Google Chrome](http://i.imgur.com/6GJdIzA.png)

Vlc, Handbrake.

![Vlc Handbrake](http://i.imgur.com/3Kpw0O0.png)

Also on cinnamon panel tooltips:

![Google Chrome Tooltips](http://i.imgur.com/9JgfdTL.png)

![Vlc tooltips](http://i.imgur.com/LO3ASWm.png)

**Comment by Foggalong** [comment]
We've moved the status icons to base so this should now be fixed :D
