### ISSUE TITLE
Debian Install Impossible

### ISSUE THREAD

**Issue by aGnamZer0** [numixproject/numix-icon-theme-circle#93]
Hello,

I installed the Basic Numix Icon Theme on Debian without any problem with the command-line : "sudo apt install numix-icon-theme".

However, when I want to do the same with Numix Incon Theme Circle by using "sudo apt install numix-icon-theme-circle", it displays the following error : "E: Impossible de trouver le paquet numix-icon-theme-circle".

Can you please fix this bug ?

Thank your for your reply

Best Regards,

aGnamZer0

**Comment by palob** [comment]
Hmm, I thought we were in the Debian repos but that appears not to be the case https://packages.debian.org/search?searchon=names&keywords=numix

The bottom line is you won't be able to install Numix Circle from the official Debian repos.
You can download and install it manually* or use the PPA (which unfortunately doesn't update at the moment). See https://github.com/numixproject/numix-core/issues/3891 for reference.

*Download the archive from here https://github.com/numixproject/numix-icon-theme-circle/releases, unzip and move the folders ``Numix-Circle`` and ``Numix-Circle-Light`` to ``~/.local/share/icons`` or ``~/.icons``.

**Comment by aGnamZer0** [comment]
Very well, thank you for your quick reply. I'll do like that for the moment.

Best regards,

aGnamZer0

2018-06-02 23:14 GMT+02:00 Vincent Bermel <notifications@github.com>:

**Comment by jlu5** [comment]
There is a pending package for numix-circle in Debian unstable right now; hopefully it will be available soon. https://ftp-master.debian.org/new/numix-icon-theme-circle_18-04-04-1.html

**Comment by jlu5** [comment]
Numix Circle is now available in Debian! (testing & unstable) https://packages.debian.org/sid/numix-icon-theme-circle :)

I'll try to push the newest release (18.08.29) in the next couple days.
