### ISSUE TITLE
Icon for FreeCad and FreeCad filetype

### ISSUE THREAD

**Issue by michiwend** [numixproject/numix-icon-theme-circle#939]
![freecad](https://cloud.githubusercontent.com/assets/411392/3329074/4a9c8a16-f7c3-11e3-9ce0-3eead83b4660.png)

[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=FreeCAD
Comment=A general purpose 3D CAD modeler
GenericName=CAD Application
Exec=/usr/bin/freecad %F
Path=/opt/freecad/lib
Terminal=false
Type=Application
Icon=/opt/freecad/data/freecad.xpm
Categories=Application;Science;Math;Education;
StartupNotify=true
MimeType=application/x-extension-fcstd;
X-Desktop-File-Install-Version=0.22

Filetype icon:
![freecad-doc](https://cloud.githubusercontent.com/assets/411392/3329078/51b004a4-f7c3-11e3-98eb-4501c1221bf2.png)

**Comment by Foggalong** [comment]
Can you report the mimetype to the numix-icon-theme repo, then it can be fixed there :)

**Comment by palob** [comment]
Wondering whether ``model.svg`` would be an appropriate design to symlink the mimetype against.
