### ISSUE TITLE
icon for Football Manager 2014 (Steam)

### ISSUE THREAD

**Issue by MarcoGuimaraes** [numixproject/numix-icon-theme-circle#947]
Game : Football Manager 2014
AppID : 231670

![steam_icon_231670](https://cloud.githubusercontent.com/assets/2810684/3353241/6088678c-fa7a-11e3-9084-c4be965f54ce.png)

**Comment by Foggalong** [comment]
Fixed in 70a025e90499e9e1dd9d59e5c7e8a295f0a273cc
