### ISSUE TITLE
Icons for launcher_bfb seems to be the only three png icons left

### ISSUE THREAD

**Issue by dvorapa** [numixproject/numix-icon-theme-circle#95]
These should be converted to svg finally.

**Comment by palob** [comment]
AFAIK those are needed for Unity's dash icon and do not work as SVGs.

**Comment by Foggalong** [comment]
Yeah they're there as PNG because Unity 7 requires that format for the bfb. The last release of Unity 7 is supported until April 2021 so it doesn't really make sense to remove them from the theme until then because them being there isn't hurting anything else.
