### ISSUE TITLE
Update PhpStorm Icon

### ISSUE THREAD

**Issue by renemaas** [numixproject/numix-icon-theme-circle#967]
Old Version:
![auswahl_001](https://cloud.githubusercontent.com/assets/1160054/3562311/b8a0b6e4-09e9-11e4-91c6-d535901058a8.png)

New Version:
![bildschirmfoto vom 2014-07-12 19 33 02](https://cloud.githubusercontent.com/assets/1160054/3562333/9bc8939c-09ea-11e4-8fc9-6c8f2bd2521a.png)
Download: http://wikisend.com/download/306716/phpstorm-custom2.svg

**Comment by palob** [comment]
Just a reminder, the contributed icon hasn't been merged yet.
