### ISSUE TITLE
Status icons not working correctly

### ISSUE THREAD

**Issue by safar** [numixproject/numix-icon-theme-circle#973]
Is it possible to mix status icons from Ubuntu-mono-dark with app icons from numix-icon-circle theme?

When I apply numix-icon-circle status icons change to shown below:
![status_circle](https://cloud.githubusercontent.com/assets/2071358/3586528/4baed59e-0c31-11e4-8369-c4c92e5a3227.png)

As you can see from the image, icons for keyboard layout (greyed out) and mail notification is wrong. Also this mail icon doesn't change to blue when mail is received. 

I was wondering is it possible to get icons for status area from Ubuntu-mono-dark instead? So it looks like this:
![status_mono](https://cloud.githubusercontent.com/assets/2071358/3586545/77ffbf46-0c31-11e4-8db0-3fb7942944de.png)

Result should be this:

![result](https://cloud.githubusercontent.com/assets/2071358/3586550/82a54f2e-0c31-11e4-8400-0979df61544c.png)

The question is: is there a way to apply different icon sets for application and status icons? In a way that would be persistent through updates of numix icons set.

**Comment by Foggalong** [comment]
See [this comment](https://github.com/numixproject/numix-icon-theme-circle/issues/1380#issuecomment-75759844) and replace `elementary` with `ubuntu-mono-dark` :)
