### ISSUE TITLE
Visual Studio Code is showing wrong icon

### ISSUE THREAD

**Issue by AbelVM** [numixproject/numix-icon-theme-circle#98]
While the right icon is available in the repo at https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/visualstudiocode.svg, Ubuntu is displaying the text editor one. You can see the duplicate in the dock:
![image](https://user-images.githubusercontent.com/9017165/44627741-618f2f00-a933-11e8-9493-b32ec02614d6.png)

And the icon in the activities:
![image](https://user-images.githubusercontent.com/9017165/44627761-98654500-a933-11e8-8a49-cb1a3675ba4e.png)

**Comment by palob** [comment]
No, this is Visual Studio Code calling their icon ``code`` instead of something meaningful like ``vscode``.

**Comment by AbelVM** [comment]
:thinking: 

And is there any way to fix this from my side? Do I need to wait for un update of Numix? 

I'm tired of opening Gedit when I need VS Code, and the other way around :disappointed:

**Comment by palob** [comment]
Find the ``.desktop`` file in ``/usr/share/applications/``, copy it to ``~/.local/share/applications/``, open it in an editor an edit the icon line so it reads ``Icon=vscode``.

**Comment by palob** [comment]
You can copy the modified launcher and call it like whatever you like.
In the original one you need to add ``NoDisplay=true`` so as not to get 2 icons.

**Comment by sagarpanchal** [comment]
> Find the `.desktop` file in `/usr/share/applications/`, copy it to `~/.local/share/applications/`, open it in an editor an edit the icon line so it reads `Icon=vscode`.

I do that after every update of vscode. LOL

**Comment by palob** [comment]
As I said, copy the launcher and add the line ``NoDisplay=true`` in the original one and your icon will survive the updates.
