### ISSUE TITLE
Rating icon issue - rhythmbox

### ISSUE THREAD

**Issue by cdorin93** [numixproject/numix-icon-theme-circle#99]
Not sure if this issue is related to this icon theme or not, but can someone tell me if the rating (stars) is shown nicely in rhythmbox if numix-icon-theme-circle is used?  

On my pc:
![image](https://user-images.githubusercontent.com/28493662/44910970-a260bc80-ad14-11e8-8180-d58070a15cd5.png)

The song that was rated is the one with the "i" sign

**Comment by palob** [comment]
Does this happen with only the base theme (Numix) applied?

**Comment by cdorin93** [comment]
I just realised that I was using the  numix-icons-circle provided by the Solus team. The github version works perfectly fine. Will open a bug report and request an update on their forum :).
